### ISSUE TITLE
Balance not displayed correctly when using nodes in private tangle

### ISSUE THREAD

**Issue by kuhlmannmarkus** [iotaledger/trinity-wallet#1004]
### Bug description
Trinity Android Wallet doesnt show balance when using a private tangle, even though the actual value transmitting transaction is recognized. Also manual sync and snapshot transition do not solve the issue. As disussed on discord with Umair Sarfraz @laumair, this might happen due to quorum queries to mainnet nodes.

### Environment Specs
Nexus 5x, LineageOS 15.1

- Manufacturer: LG
- Model: Nexus 5X, bullhead
- OS version: lineageos 15.1
- Trinity version: 0.6.0

### Steps To Reproduce
1. Add node that resides in private tangle
2. Refresh balance
3. NOT NECCESSARY BUT TRIED: Snapshot transition, manual sync

### Expected behaviour
Correct balance should be shown.

### Actual behaviour
Balance is always 0.

**Comment by laumair** [comment]
@kuhlmannmarkus Thanks for reporting this. Manual sync or Snapshot transition won't work.

Basically, you're seeing a zero balance because the node you add is from devnet, while quorum is using nodes from mainnet. We need to fix it by detecting if the custom node is from devnet or mainnet and perhaps disabling quorum in such a case.

**Comment by rajivshah3** [comment]
Would an alternative solution be to allow devnet nodes to be selected for quorum? We could fix this with https://github.com/iotaledger/trinity-wallet/issues/967

**Comment by laumair** [comment]
@rajivshah3 Yeah I think that's a good option. However, we'll also need to provide a default list of devnet nodes to the users. Otherwise, quorum can't execute.

**Comment by kuhlmannmarkus** [comment]
Just to be clear here: I'm not using a public devnet node. I'm using a node from my private tangle. These nodes do not have neighbors outside of my network.

**Comment by cvarley100** [comment]
@kuhlmannmarkus If you wish to use Trinity with a private tangle, please follow these steps (step 4 in particular): https://docs.iota.org/docs/trinity/0.1/how-to-guides/connect-to-a-custom-node
