### ISSUE TITLE
WebSocket Signature support 

### ISSUE THREAD

**Issue by Noc2** [iotaledger/trinity-wallet#1005]
### Description
WebSocket support similar to https://medium.com/getscatter/the-blockchain-isnt-just-for-web-applications-silly-rabbit-926a4ea5ccd1 to allow (d)apps to send/sign IOTA transactions without getting directly access to the seed.

### Motivation
To make it easier for all kinds of applications to integrate IOTA. In this case your seed can become your identity. It’s also very interesting together with applications that use masked authenticated messaging. 

### Requirements
Be able to send IOTA transactions inside apps without access to the seed itself (see https://github.com/GetScatter/scatter-js)

### Am I planning to do it myself with a PR?
Currently, I’m not planning to do it myself.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
