### ISSUE TITLE
SyntaxError when parsing JSON

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#1009]
## Error in Trinity Mobile

**SyntaxError** in **[native code]:0**
JSON Parse error: Unrecognized token '<'

[View on Bugsnag](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5ad06524d607e6001a8d95f5?event_id=5c53f018003565f377880000&i=gh&m=ci)

## Stacktrace

    [native code] parse
    node_modules/promise/setimmediate/core.js:37:14 tryCallOne
    node_modules/promise/setimmediate/core.js:123:25 
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:152:6 _callTimer
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:200:17 _callImmediatesPass
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:464:11 callImmediates
    [native code] callImmediates
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:320:11 spyOrToggle
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:11 
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:8 spyOrToggle
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:17 spyOrToggle
    [native code] value
    [native code] value

[View full stacktrace](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5ad06524d607e6001a8d95f5?event_id=5c53f018003565f377880000&i=gh&m=ci)

*Created by Rajiv Shah via Bugsnag*

**Comment by rajivshah3** [comment]
This is probably coming from places where we attempt to decode JSON without using a `try-catch` block, such as the one below: 
https://github.com/iotaledger/trinity-wallet/blob/ec3728166f6fdbebdbe3bc3c5364d20a7519fb5c/src/shared/actions/marketData.js#L103

**Comment by cvarley100** [comment]
Still present in 1.0.0

**Comment by rajivshah3** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**SyntaxError** in **&#91;native code&#93;:0**](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5ad06524d607e6001a8d95f5?event_id=5d2ca5c1004aa0797d5d0000&i=gh&m=fx)
