### ISSUE TITLE
Improve code test coverage for shared

### ISSUE THREAD

**Issue by laumair** [iotaledger/trinity-wallet#1013]
### Description
Add missing test coverage for `shared` directory.

### Requirements
Complete test coverage for:

- [Redux actions](https://github.com/iotaledger/trinity-wallet/tree/feature/realm/src/shared/actions)
- [IOTA utils](https://github.com/iotaledger/trinity-wallet/tree/feature/realm/src/shared/libs/iota)
- [General purpose utils](https://github.com/iotaledger/trinity-wallet/blob/feature/realm/src/shared/libs/utils.js)
- [State selectors](https://github.com/iotaledger/trinity-wallet/tree/feature/realm/src/shared/selectors)
- [Reducers](https://github.com/iotaledger/trinity-wallet/tree/feature/realm/src/shared/reducers)
- [Realm](https://github.com/iotaledger/trinity-wallet/tree/feature/realm/src/shared/storage)

### Am I planning to do it myself with a PR?
Yes.

**Comment by cvarley100** [comment]
@laumair Do you have a status update here?

**Comment by cvarley100** [comment]
No plans to increase test coverage in light of V2 development
