### ISSUE TITLE
NFC for quickly sending IOTAs between peers.

### ISSUE THREAD

**Issue by janimator0** [iotaledger/trinity-wallet#1035]
### Description
Adding NFC to Trinity to allow Visa like tapping between smart phones when sending and receiving. 

### Requirements
Usage for sending IOTA: Sender inputs the amount he wants to send. Sender and Receiver tap phones which transfers Receivers receiving address to Sender and pops up a sending confirmation on Senders device seamlessly. Sender confirms transaction and IOTAs are are now in process of being sent.

Usage for receiving: Receiver specifies amount of IOTAs he desires in trinity wallet. Receiver and Sender tap devices which transfers receiving address to sender. Sender receives confirmation to send funds also an additional password check. Once confirmed the IOTAs are now being sent over the tangle.

### Motivation
It's too difficult to continuously transfer IOTAs between friends.This will provide a quick solution till a more comprehensive one is created. This can also help with adoption as it will be easier for none tech savvy users to transfer IOTAs. Also it resembles Visa type tap payments.

### Am I planning to do it myself with a PR?
No.

**Comment by webkracht** [comment]
NFC also could be used as alternative for Amazon Go shopping.

When products have NFC tags customers can pay and deactivate the NFC tag with Trinity. After a successful payment the product can be taken out of the store without triggering the alarm.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.

**Comment by Cryptec** [comment]
is this still on a Radar? would love to see NFC here.

**Comment by cvarley100** [comment]
@Cryptec Yeah we will look at it for the new wallet sooner or later.
