### ISSUE TITLE
Trinity may report unspent addresses as spent when reattaching a transaction

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#1036]
### Bug description
When reattaching a pending transaction, Trinity may sometimes show an error message such as "Could not broadcast transfer: One or more of the addresses have already been spent from". It will then show a more detailed message in the error log and provide the addresses that are supposedly spent. Upon searching on [thetangle.org](thetangle.org), the reported addresses are not actually spent from. 

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: iPhone 6S
- OS version: iOS 12.1

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity). 

- Trinity version: Built from https://github.com/iotaledger/trinity-wallet/pull/421/commits/fa3d312f34438b626814c0b18ec432988170d609

### Steps To Reproduce
This seems to happen in isolated cases

1. Send a value transaction from an unspent address
2. Press "Retry" to manually reattach the transaction

### Expected behaviour
The transaction should reattach

### Actual behaviour
Trinity says that the input address is spent, when it is actually not

### Errors
"Could not broadcast transfer: One or more of the addresses have already been spent from"

**Comment by KiwiCat123** [comment]
This bug sometimes occurred when there was a network issue before the transaction got broadcasted. Trinity reported an error but it showed this transaction in the history and after pressing Retry it said that it was already spent from that address.
Maybe this helps.

**Comment by rajivshah3** [comment]
Aha, that might be the cause. In the instance I saw (and another instance reported on Discord) there was also a network issue.

**Comment by laumair** [comment]
Should be fixed with https://github.com/iotaledger/trinity-wallet/pull/1046
