### ISSUE TITLE
auto-lock not disabled while data migration

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1040]
### Bug description
Trinity doesn't prevent the auto-lock on the data migration page after the update. Data migration could take a few minutes so the iPhone locks itself before the migration is finished.

### Environment Specs
- Model: iPhone 6
- OS version: iOS 12.1.1

- Trinity version: Trinity mobile 0.6.1 (41)

### Expected behaviour
The phone shouldn't auto-lock during the data migration as it is on the loading screen after a new seed got added

### Actual behaviour
Auto-lock is not disabled by Trinity and the phones locks itself before the migration is finished

**Comment by KiwiCat123** [comment]
maybe there should also be a warning to not minimize or close this app during data migration

**Comment by cvarley100** [comment]
@KiwiCat123 Auto-lock is not enabled on the migration screen

**Comment by cvarley100** [comment]
Do not close message added in #1146

**Comment by rajivshah3** [comment]
@cvarley100 I think @KiwiCat123 may have been referring to the OS auto-lock. We can use `react-native-keep-awake` here

**Comment by cvarley100** [comment]
I see, thanks, I'll add that to the PR.
