### ISSUE TITLE
seed name can not be changed

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1044]
### Bug description
It is not possible to change the name of a seed in the settings. "Save" button in "Edit account name settings" does nothing after editing the name.

### Environment Specs
- Model: iPhone 6
- OS version: iOS 12.1.1

- Trinity version: mobile 0.6.1 (41)

### Expected behaviour
account name should be changed and trinity should go back to "account management" page

### Actual behaviour
"Save" button does nothing

**Comment by laumair** [comment]
@KiwiCat123 Thanks for reporting the bug. Fixed in https://github.com/iotaledger/trinity-wallet/pull/1045

**Comment by rajivshah3** [comment]
@laumair can this be closed?

**Comment by KiwiCat123** [comment]
it's fixed in (42)
