### ISSUE TITLE
Currency/timeframe on balance page reset after app restart

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1049]
### Bug description
After trinity gets completely closed and restarted the setting for the graph on balance page gets reset back to USD and 24h. 

### Environment Specs
What device are you running Trinity on?

- Model: iPhone 6 and iPhone 8
- OS version: iOS 12.1.1

- Trinity version: mobile 0.6.1 (42)

### Steps To Reproduce
1. changed settings for the graph (for example to EUR 7d)
2. closing the app completely with app switcher
3. reopen the app

### Expected behaviour
settings should still be EUR 7d

### Actual behaviour
setting is reset to USD 24h

**Comment by rajivshah3** [comment]
@laumair do we store the chart state and data in Realm or AsyncStorage?

**Comment by laumair** [comment]
@rajivshah3 No. I don't think we need to store chart data in Realm. However, we should store [currency](https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/reducers/marketData.js#L7) & [timeframe](https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/reducers/marketData.js#L11).

**Comment by rajivshah3** [comment]
> However, we should store [currency](https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/reducers/marketData.js#L7) & [timeframe](https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/reducers/marketData.js#L11).

So they're currently being stored in AsyncStorage? Hmm. I was expecting this to be an issue with a Realm schema but I guess it's something else

**Comment by laumair** [comment]
> So they're currently being stored in AsyncStorage?

Yes, [martketData reducer](https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/reducers/marketData.js) persists in AsyncStorage. I don't think it should. 


I'll work on this and will move `timeframe` & `currency` to realm storage.

**Comment by KiwiCat123** [comment]
This bug exists on the latest Desktop alpha 0.5.0 as well.

**Comment by Vid201** [comment]
This bug exists on the latest mobile version 1.2.3 and on the latest desktop version 1.2.1 as well.

**Comment by rajivshah3** [comment]
@Vid201 would you mind opening a new issue? There have been a lot of changes since this issue was opened
