### ISSUE TITLE
Trinity freezes when seed has big history

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1050]
### Bug description
Trinity starts freezing after a few seconds when using a seed with many addresses and a big history. And after some time using it the freezes longer and Trinity becomes unusable. The phone starts heating up a lot at when sending iota.

### Environment Specs

- Model: iPhone 8, iPhone 6
- OS version: iOS 12.1.1

- Trinity version: 0.6.1 (42)

### Expected behaviour
trinity shouldn't freeze all the time as in 0.6.0

### Actual behaviour
starts freezing after a few seconds, gets unusable after some time
sending iota fails most of the time there

**Comment by rajivshah3** [comment]
> sending iota fails most of the time there

Could you give some more information about this?

**Comment by KiwiCat123** [comment]
@rajivshah3 I couldn't see the error again while sending because Trinity always freezes before I could send with this seed

**Comment by laumair** [comment]
Can't seem to reproduce. 

@KiwiCat123 How many addresses (roughly) do you have in wallet? 

> sending iota fails most of the time there

At which point does it fail? `Syncing Account` ?

**Comment by KiwiCat123** [comment]
@laumair I'm using 3 seeds. One has more than 300 and another one about 150 addresses I think. The history for those 2 seeds is big and I'm using my own node with local snapshots disabled. The app seems to freeze fast after changing between those seeds.
It's not possible to send transactions anymore because the app becomes unusable before I could.
It mostly failed at `Syncing Account` and sometimes at `Preparing Inputs` as it didn't freeze before.

I could pm you one seed if that would help.

**Comment by rajivshah3** [comment]
Are you tapping anything while the transaction is sending? I noticed an issue where the UI will completely freeze if you press buttons (e.g. to navigate to another tab)

**Comment by KiwiCat123** [comment]
@rajivshah3 I think this issue you mean already existed in the versions before.
I can't even make a transaction on 0.6.1 because it already freezes before now.

**Comment by KiwiCat123** [comment]
The new 0.5.0 desktop alpha seems to be slower too with my seeds with big history. Especially showing a bundle takes a little.

**Comment by cvarley100** [comment]
Closed via #1293
