### ISSUE TITLE
Mobile: "Bolt" icon on "Root Warning" screen is cut and low quality

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#1130]
### Bug description
When we have rooted device, that warning screen comes out on initial screen. The icon needs replacement to better quality and not to be cut.
Small thing but hurts my OCD. :D

### Environment Specs
Samgung Galaxy S9+ Android 9.0 Pie

- Trinity version: 
0.6.2 (49)

![screenshot_20190222-181924_trinity](https://user-images.githubusercontent.com/35224101/53260546-0667aa80-36d2-11e9-9f1f-5c0c316ca564.jpg)

**Comment by rajivshah3** [comment]
@cvarley100 is this an issue with how the icons are generated? That icon is supposed to look like this:


![image](https://user-images.githubusercontent.com/19519564/53281354-f614f700-36f4-11e9-83d8-69ea839f7c1d.png)
https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/icons/icons/attention.svg

**Comment by cvarley100** [comment]
Yes. I have tried to fix it to no avail - worth further investigation.

**Comment by rajivshah3** [comment]
Is this the only icon that's affected?

**Comment by UmbahaSpodPaha** [comment]
I believe yes
