### ISSUE TITLE
Mobile: Black cursor blends with the background

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#1131]
### Bug description
Black cursor blends with the background. I remember that I already submitted that bug somewhere and I was said that It will be repaired in next version but it's still not repaired.

### Environment Specs
Samgung Galaxy S9+ Android 9.0 Pie

- Trinity version: 
0.6.2 (49)

![screenshot_20190222-180138_trinity](https://user-images.githubusercontent.com/35224101/53260690-665e5100-36d2-11e9-8153-820d219e065f.jpg)

**Comment by cvarley100** [comment]
This is an issue with the current version of React Native. See: https://github.com/facebook/react-native/issues/22762

Will hopefully be fixed in a future version.

**Comment by cvarley100** [comment]
Closing until we hear an update from facebook/react-native#22762
