### ISSUE TITLE
Mobile: When we're typing SeedVault password, text that was on top of the screen blends with statusbar

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#1132]
### Bug description
When we're typing SeedVault password, text that was on top of the screen jumps up and blends with statusbar which looks horrible.

Sorry for the photo quality. It took it with an actual potato.
(screenshot restriction on that screen)

### Environment Specs
Samgung Galaxy S9+ Android 9.0 Pie

- Trinity version: 
0.6.2 (49)

![photo0002](https://user-images.githubusercontent.com/35224101/53260881-f3a1a580-36d2-11e9-871d-8a157a078f69.jpg)
![photo0003](https://user-images.githubusercontent.com/35224101/53260882-f3a1a580-36d2-11e9-8fd1-221103a8ca69.jpg)

**Comment by cvarley100** [comment]
@UmbahaSpodPaha I'm going to mark this as won't fix for the time being. Unfortunately, the nature of the way we have chosen to use StatusBar means that this cannot be fixed without a pretty hacky solution. I'd rather keep the code clean I think.

**Comment by rajivshah3** [comment]
Could we get the height of the status bar and then add that to the padding of the text so it would move down a bit?

**Comment by cvarley100** [comment]
The way `android:windowSoftInputMode="adjustPan"` works will mean that has no effect, the padding will be pushed up.

**Comment by rajivshah3** [comment]
Ah, I see
