### ISSUE TITLE
snapshot transition always shows 0i

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1134]
### Bug description
The snapshot transition always shows 0i as detected balance although my seed doesn't have many used addresses and has an address with iotas on it. I clicked about 20 times on `No` as it showed me 0i as balance. The same happened on another seed too.

### Environment Specs

- OS version: macOS 10.14.3

- Trinity version: 0.5.0-RC1

### Steps To Reproduce
1. start snapshot transition
2. click on No as it shows 0i as balance

### Expected behaviour
should show the correct balance after clicking `No` for a few times.

### Actual behaviour
always shows 0i

**Comment by rajivshah3** [comment]
@KiwiCat123 sorry for the delayed response. Are you using a Ledger?

**Comment by KiwiCat123** [comment]
> @KiwiCat123 sorry for the delayed response. Are you using a Ledger?

No, I don't.

**Comment by rajivshah3** [comment]
Is there anything in the transaction history, and does a balance show on the main screen?

**Comment by KiwiCat123** [comment]
Yes, there are transactions in the history and it shows the correct balance on main screen.

I've tested this with different seeds on different computers and it never worked.

**Comment by rajivshah3** [comment]
Is this reproducible in 0.4.6?
