### ISSUE TITLE
Add push notifications (local) for incoming transactions on Mobile

### ISSUE THREAD

**Issue by mgrassotti** [iotaledger/trinity-wallet#1169]
### Description
Notify the user about new incoming transactions with a push notification (local)

### Motivation
Eliminate the need of opening the app or checking the account status repeatedly, for incoming transactions

### Requirements
- A local push notification is sent when the wallet is receiving a new transaction.

### Open Questions (optional)
Push notifications may be dependent on background processes 
cc @rajivshah3 @cvarley100 

### Am I planning to do it myself with a PR?
Unfortunately not, I never used React before.

**Comment by rajivshah3** [comment]
Great suggestion! Unfortunately this is dependent on background processes (#128, I'll continue work on that once higher-priority tasks are done) so that we can sync the wallet while it's not open.

**Comment by thomazchamberlain** [comment]
Hi @rajivshah3 It's true that you would need background tasks in order to implement this feature. However, you wouldn't need anything like react-native-background-task or react-native-background-fetch to do it. The library you would use for receiving push notifications is react-native-firebase and it includes the class RNFirebaseBackgroundMessage which you then register in App.js.
For example create a file named bgMessaging.js
```
import type { RemoteMessage } from 'react-native-firebase';

export default async (message: RemoteMessage) => {
    //do something like display the notification etc
    return Promise.resolve();
}
```
Then in App.js just import bgMessaging and then register `RNFirebaseBackgroundMessage` as a headless task that returns bgMessaging.
```
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);
```
That's all of the background work required receiving push notifications.

I would absolutely love to help iota and you out with this task. Would you consider allowing me to contribute a PR?

**Comment by rajivshah3** [comment]
Interesting. Would we have to send the notifications from a server if we used Firebase messaging though?

**Comment by thomazchamberlain** [comment]
I didn't see that part of the issue and just got excited when I saw push notifications, oops my bad. Now I'm clearer on the task I don't believe `RNFirebaseBackgroundMessage` should be used that way. I made an assumption that it wasn't just a local notification. Does this mean the plan is to have the device constantly poll for a notification to display?

**Comment by rajivshah3** [comment]
Yeah, we'd prefer if there wasn't a central server responsible for the notifications (in the spirit of decentralization 😃 )

> Does this mean the plan is to have the device constantly poll for a notification to display?

Right. We'll have to think about an interval that would be reasonably frequent but wouldn't kill the user's battery

**Comment by thomazchamberlain** [comment]
A project for Qubic maybe 😀 
I didn't realise there wasn't a service gateway serving the App (tangle not included). Very interesting challenge indeed. Assuming Qubic's eventual success I will be excited to see what can be done. 

Is there any other immediate need for any dev work on Trinity from the community?

**Comment by rajivshah3** [comment]
> I didn't realise there wasn't a service gateway serving the App

Yeah, everything is Tangle-based except for the default node list which comes from a server (we have a hardcoded list as a fallback).

> Is there any other immediate need for any dev work on Trinity from the community?

I'll check with the team, but most of the stuff we're working on/planning to work on is in the issues on GitHub. Let me know if you'd like to work on one of them and if you need any guidance! We'd be happy to help

**Comment by thomazchamberlain** [comment]
Sweet, I'll just head to the issues 👍. I'm pretty new to the opensource side of things so I wasn't sure how I should go about asking to work on something. Thanks a lot.

Last thought I want to share before I forget it later as I've just realised it. Once Qubic is functionality ready to run microservices, there's going to be an amazing opportunity to build some next-generation infrastructure on the tangle+qubic for just your general App related PaaS and SaaS. Like Instant messaging, push, auth etc. So it makes sense that the first step is an app gateway service for Trinity. 😄

**Comment by cvarley100** [comment]
@thomazchamberlain Echoing Rajiv's point - really do feel free to pick up any of the issues we have here. If you submit a PR we'll work with you to get it merged 💪

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
