### ISSUE TITLE
AppImage terminates immediately on Ubuntu

### ISSUE THREAD

**Issue by mmsbrggr** [iotaledger/trinity-wallet#1170]
### Bug description
AppImage does not open at all. When run in terminal it immediately exits with now error messages and no logs.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Lenovo Thinkpad
- Model: E540
- OS version: Ubuntu 18.10

- Trinity version: 0.4.6 (also in 0.4.5, 0.4.4, 0.4.3, 0.4.2 and 0.5.0-RC1)

### Steps To Reproduce
1. Run `./trinity-desktop-0.4.6.AppImage`
2. Observe that application immediately terminates with no error or logs 

### Expected behaviour
The application should open.

### Actual behaviour
The application terminates.

**Comment by rajivshah3** [comment]
Seems like an issue we were running into on mobile was also affecting certain versions of Ubuntu. This should be fixed in #1174
