### ISSUE TITLE
Can't login with Password and google authentificator.

### ISSUE THREAD

**Issue by kriss-t** [iotaledger/trinity-wallet#1195]
The issue tracker is only for reporting bugs or asking for feature requests.
If you need technical assistance for using Trinity Wallet, please consult the Trinity [documentation](https://docs.iota.works/trinity) and [knowledge base](https://iotaledger.atlassian.net/wiki/spaces/trinity/overview). For further assistance, please visit the #help channel on [Discord](https://discord.gg/7Gu2mG5).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).

### Bug description
A general description of the bug.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: 
- Model: 
- OS version:

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 

### Steps To Reproduce
1.
2.
3.

### Expected behaviour
What should happen.

### Actual behaviour
What really happened.

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

**Note**
The feature request will probably be integrated faster if you do a pull request for it.
If you want to discuss the feature before you actually write the code you are welcome to do it by first submitting an issue.

### Description
Briefly describe the feature you want.

### Motivation
Explain why this feature is needed.

### Requirements
Create a list of what you want this feature request to fulfill.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
Yes/No.

**Comment by rajivshah3** [comment]
@kriss-t can you please fill out the template? We need more information in order to investigate your issue

**Comment by rajivshah3** [comment]
@kriss-t is this still occurring?

**Comment by kriss-t** [comment]
Hi Rajiv.....I still have problems..😞
Last time when I login with no problem was maybe in december or January...
Now I try to ad dmore iot to my wallet ..I alreayd have a lot of them...but
can't login...it jsut freeze and do nothing....
I update the wallet to newer version and then it say wrong password...but
is not wrong becasue I didn't change it..is still my old one...
I don't find my seed so I need help to fix this login problem and then to
be abel to generate another seed..
Thanks in advance!

**Comment by rajivshah3** [comment]
@kriss-t please fill out the issue template, it's hard for us to help you without this information

**Comment by cvarley100** [comment]
We have since removed 2FA

**Comment by kriss-t** [comment]
Hi Charlie,
You removed the authentificator but still can't login ...
See attched error when use my password

[image: image.png]

How can I fix this?

**Comment by cvarley100** [comment]
You need to fill out the issue template in your first post.

**Comment by kriss-t** [comment]
Hi can you send me please issue template or link from that?
I didn.t find any template attached in any email.
Thanks!

**Comment by cvarley100** [comment]
It is automatically added to your original post. Just edit that.
