### ISSUE TITLE
Don't convert messages that contain only Trytes

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#1217]
I would like to propose a change to how messages are handled. 

Current Behavior: When I enter a message into the message field, it is converted to Trytes, whether the content already is in Tryte format or not. 

Proposed Behavior: Check if message is not A-Z9 before converting to Trytes, leave the messages untouched that already are Trytes. 

Why is this important? I think this would be very handy for people developing apps on the Tangle. It would allow you to publish transactions that the app couldn't able to publish, it would allow you to send test messages, etc.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2. Feel free to open a PR.
