### ISSUE TITLE
Mobile: Account name autofilled from SeedVault stays in the account name field

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#1228]
### Bug description
When we had finished first setup of the wallet and try to import new SeedVault file BUT cancel the importing, the account name from seedvault will stay forever in the Account Name field. (**see -> steps to reproduce**)

### Environment Specs
- Manufacturer: Samsung Galaxy S9+
- OS version: Android 9

- Trinity version: 
v 0.6.2 (52)

### Steps To Reproduce
1. Go into Settings -> Account management -> Add new account -> Use existing seed
2. Click on "Import SeedVault"
3. Select SeedVault file to import, enter the password and click "Okay"
4. **Do not click "Done"**  - instead of this, click "Back"
5. Click "Use existing seed" again and you will see that the account name from previously chosen seed is still there **EVEN AFTER FULL RESTART of the app.**

### Expected behaviour
Account name on "Use existing seed" should be cleared on exit even if we didn't finished the process.

### Am I planning to do it myself with a PR?
No, I don't know how to ;)

**Comment by cvarley100** [comment]
Closing due to related issue #1413
