### ISSUE TITLE
Check that file selected in SeedVault Import is really a Seedvault File

### ISSUE THREAD

**Issue by CrashTD** [iotaledger/trinity-wallet#1245]
### Bug description
Noticed lately that people misinterpret what the SeedVault import is for and drop normal .txt files on it and then are confused why it ask for a password.

### Steps To Reproduce
1. Create .txt file with seed (or random characters)
2. Select as SeedVault while creating account

### Expected behaviour

Trinity should show error "Not a SeedVault File".

### Actual behaviour
Trinity accepts the wrong file and ask for a non-existing password.

### Am I planning to do it myself with a PR?
No.

**Comment by rajivshah3** [comment]
I'll check if this happens on mobile as well
