### ISSUE TITLE
Desktop: Missing translation string

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#1306]
### Bug description
Missing translation strings (see photo at the bottom):
- "Ledger device access cancelled"
- "Cannot perform the action without Ledger device access."

### Trinity version:
Latest version as of today - FEB 14.
Desktop + ledger account

### Steps To Reproduce
1. Refresh ledger account history **without ledger connected** 
2. Warning box will show up on the screen (saying that ledger needs to be connected)
3. Close this warning window
4. You will see untranslated error-box

### Expected behaviour
Please add these strings for translators (on crowdin).
@rajivshah3 

### Errors
![20190412_142312](https://user-images.githubusercontent.com/35224101/56099377-4ac23a80-5f0c-11e9-96aa-6031aa9e2b0f.jpg)

**Comment by rihardsgravis** [comment]
Seem to be added now:
https://github.com/iotaledger/trinity-wallet/blob/3aba852c0686ae9ea99bdb17b4acd686a95d0d2c/src/shared/locales/en/translation.json#L812
https://github.com/iotaledger/trinity-wallet/blob/3aba852c0686ae9ea99bdb17b4acd686a95d0d2c/src/shared/locales/en/translation.json#L813
