### ISSUE TITLE
unlocking with fingerprint is possible although it is disabled in settings

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1342]
### Bug description
After the app was closed for some time and the password screen is there again it is possible to tap on the fingerprint icon next to the password field and there it is possible to unlock Trinity with the fingerprint sensor although it is disabled in the security settings.

### Environment Specs

- Model: iPhone 8, iPhone 6
- OS version: iOS 12.1.1

- Trinity version: 0.6.2 (54)

### Steps To Reproduce
1. minimize Trinity and wait until it locks
2. tap the fingerprint icon next to the password field
3. unlock it with fingerprint

### Expected behaviour
it shouldn't be possible to unlock Trinity with the fingerprint, the fingerprint icon shouldn't be possible

### Actual behaviour
Unlocking it is possible, the fingerprint icon is visible

![IMG_4400](https://user-images.githubusercontent.com/21984138/56317258-91a66f00-615c-11e9-8c81-ee898b28fa1a.PNG)
![IMG_4401](https://user-images.githubusercontent.com/21984138/56317259-91a66f00-615c-11e9-81d2-f8d1eb378182.PNG)

**Comment by cvarley100** [comment]
@KiwiCat123 Can you share a screenshot of your biometric settings?

**Comment by KiwiCat123** [comment]
@cvarley100 
![IMG_4415](https://user-images.githubusercontent.com/21984138/56426460-af88e680-62b8-11e9-936b-b414c59bbc8b.PNG)
