### ISSUE TITLE
Error in migration

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#1344]
## Error in Trinity Mobile

**Error** in **/Users/vagrant/git/src/shared/storage/index.js:801**
Migration is required due to the following errors:
- Property 'AccountInfoDuringSetup.completed' has been added.

[View on Bugsnag](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5cb63496c566b0001916feed?event_id=5cb738d00037f49e6c130000&i=gh&m=ci)

## Stacktrace

    /Users/vagrant/git/src/shared/storage/index.js:801 - 

[View full stacktrace](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5cb63496c566b0001916feed?event_id=5cb738d00037f49e6c130000&i=gh&m=ci)

*Created by Rajiv Shah via Bugsnag*

**Comment by rajivshah3** [comment]
Possibly related to #1315

**Comment by cvarley100** [comment]
Closing due to age.
