### ISSUE TITLE
Incorrect? Already spent from address error

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#1386]
### Bug description
- Trinity reports unspent address as spent when re-attaching transaction.
- Trinity attempts to "retry" this transaction forever, even after confirmation.

### Possibly related issue
#1036 

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Samsung
- Model: Galaxy S8+
- OS version: Android 9

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.6.2 (55)

### Steps To Reproduce
1. get network error when generating receiving address but still receive address
2. send funds to generated address from same account
3. Error

### Expected behavior
The wallet should not tell the user that an unspent address is already spent

### Actual behavior
Trinity tells users that the sending address has already been sent from, yet broadcasts the transaction in question (possibly unsafe)

### Errors
![1](https://i.imgur.com/w3LzWAH.png)
![2](https://i.imgur.com/Ca9ftBc.png)
![3](https://i.imgur.com/bwGZ9u8.png)
![4](https://i.imgur.com/vZyvwRA.png)
![5](https://i.imgur.com/RPUZ3X2.png)

**Comment by sloganking** [comment]
Still ongoing in Trinity V 0.7.0 (59)

**Comment by laumair** [comment]
@SleepingFox88 I cannot seem to reproduce this issue. 

What notification did you see after you retried the failed transaction for the first time in history?

**Comment by sloganking** [comment]
Has this issue been fixed? 

I see #1607 marked this issue as a duplicate and is now closed.
Also #1644 marked this issue as closed and has been merged.

I updated mobile trinity to v0.7.2(67) and after an initial "Address already spend from" error message, the problem seems to be fixed for me.
