### ISSUE TITLE
"Node out of sync" error on all nodes

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#1421]
### Bug description
Users have reported periods where they receive "Node out of sync" on every node that they attempt to connect to. I can't reproduce this issue on-demand, but I've seen it occur a few times.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: MacBook Pro
- OS version: macOS Mojave 10.14.5 Beta (18F118d)

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: Desktop v0.5.0-RC2

### Steps To Reproduce
Unknown

### Expected behaviour
Error should only be given when node is actually out of sync

### Actual behaviour
Nodes are reported as out of sync even when they are in sync

**Comment by rajivshah3** [comment]
Fixed in #1436

**Comment by PlanetaOTC** [comment]
Hello,

Today, I installed Trinity 0.5.2 in my Mac High Sierra and created a wallet with my Ledger Nano X. All went well, but after some minutes of inactivity and when reconnecting Ledger and unlocking Trinity, I'm not able to connect to any node, all give the same error "out of sync".

I deleted the entire Trinity and all folders involved and re-installed. Same problem.

Ideas?

Thanks
