### ISSUE TITLE
Cannot read property 'meta' of undefined

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#1422]
## Error in Trinity Desktop

**TypeError** in **/index.html**
Cannot read property 'meta' of undefined

[View on Bugsnag](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5c8f662c1823c1001a6d1e86?event_id=5cc5ec1e0038d8cf4df30000&i=gh&m=ci)

## Stacktrace

    src/ui/views/onboarding/seedStore/Ledger.js:187 - Function.e [as mapToProps]

[View full stacktrace](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5c8f662c1823c1001a6d1e86?event_id=5cc5ec1e0038d8cf4df30000&i=gh&m=ci)

*Created by Rajiv Shah via Bugsnag*

**Comment by cvarley100** [comment]
Closing due to age and stack trace returning 404
