### ISSUE TITLE
Mobile: Crash when double clicking on Log In

### ISSUE THREAD

**Issue by Hissi88** [iotaledger/trinity-wallet#1458]
### Bug description
The app crashes when you type in the **correct** password and then double click on Log In

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Samsung
- Model: S6
- OS version: Android 7.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v 0.7.0 (59 & 61)

### Steps To Reproduce
1. Type correct password
2. Double click on Log In

### Expected behaviour
App should start normally

### Actual behaviour
Crash

**Comment by cvarley100** [comment]
@Hissi88 Tried to repro this a few times on Pixel 3 but no luck

**Comment by Hissi88** [comment]
Hi @cvarley100.
I just tried it again with 1.0.0 (79) and couldn't reproduce it either. So it seems to be fixed somewhere in beteen then and can be closed. Good job ;)

Or did you tried it with the reported version?

**Comment by cvarley100** [comment]
I only tried in 1.0.0. Thanks @Hissi88, will close.
