### ISSUE TITLE
Mobile-won’t allow me to type 

### ISSUE THREAD

**Issue by Hillgoth5** [iotaledger/trinity-wallet#1465]
The issue tracker is only for reporting bugs or asking for feature requests.
If you need technical assistance for using Trinity Wallet, please consult the Trinity [documentation](https://docs.iota.works/trinity) and [knowledge base](https://iotaledger.atlassian.net/wiki/spaces/trinity/overview). For further assistance, please visit the #help channel on [Discord](https://discord.gg/7Gu2mG5).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).

### Bug description
A general description of the bug.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: 
- Model: 
- OS version:

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 

### Steps To Reproduce
1.
2.
3.

### Expected behaviour
What should happen.

### Actual behaviour
What really happened.

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

**Comment by Hillgoth5** [comment]
When I attempt to type my trinity password nothing was appearing. I deleted both apps and reinstalled, now when I attempt to enter my 81 seed again the wallet is not accepting any of the keystrokes.

**Comment by rajivshah3** [comment]
@Hillgoth5 please fill out the template. It asks important information that we need in order to investigate your issue
