### ISSUE TITLE
Won’t accept 

### ISSUE THREAD

**Issue by Hillgoth5** [iotaledger/trinity-wallet#1466]
### Bug description
Anything I attempt to type as as my password or seed does not appear. It’s as if my keyboard is inactive. 

### Environment Specs
What device are you running Trinity on?

- Manufacturer: IPhone 
- Model: XR
- OS version: 12.2

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 7.0

### Steps To Reproduce
1. Attempted login to trinity, no response
2. Deleted apps (both test and wallet) and reinstalled 
3. Accepts yes/no however now will not accept my seed either 

### Expected behaviour
Type should be filled in when entered

**Comment by rajivshah3** [comment]
Can you send a screen recording of what it looks like when you try to enter a seed? Please do not use your real seed in the screen recording

**Comment by Hillgoth5** [comment]
![ACC43D4F-B753-4011-853C-3F5944BBEF5B](https://user-images.githubusercontent.com/50252962/57172555-38d70780-6de7-11e9-9999-918b3c7260a9.png)
Unfortunately nothing appears when I type

**Comment by rajivshah3** [comment]
Do you hear the iOS keyboard sound when you type (double check to make sure your phone isn't on silent)? Do the keys pop up like this when you press them?

![image](https://user-images.githubusercontent.com/19519564/57172578-ffef6080-6def-11e9-886f-c3d83108a30f.png)

**Comment by Hillgoth5** [comment]
I do have the clicking and the keys do pop

**Comment by Hillgoth5** [comment]
![0875B954-2438-4CCD-B601-46B567180051](https://user-images.githubusercontent.com/50252962/57172605-e77b4800-6de7-11e9-8423-c31c2a9d7a8f.png)

**Comment by rajivshah3** [comment]
IOTA seeds must only use capital letters and the number 9, so it's not accepting the lowercase characters. However we should make this a bit more user-friendly

**Comment by Hillgoth5** [comment]
I did forget about the caps, I really appreciate your help...it is working. Thank you so much for the help.

**Comment by cvarley100** [comment]
We will look at ways to make this more clear to the user.
