### ISSUE TITLE
Desktop: Using Max amount switch raises error

### ISSUE THREAD

**Issue by Vale11** [iotaledger/trinity-wallet#1476]
### Bug description
The issue appears when using the switch button "max" to withdraw maximum amount from trinity wallet. If enter the same amount manually it goes thought. Happening on every node.

### Environment Specs
Trinity v .0.4.0

- Manufacturer: Apple macbook pro
- Model: Macbook pro 2016
- OS version: High Sierra 10.13.6

### Steps To Reproduce
1. Install trinity wallet 
2. Try to sent max amount iota from the wallet using "max" switch button.

### Expected behaviour
Max amount should be withdrawn

### Actual behaviour
Throwing an error

**Comment by rihardsgravis** [comment]
@Vale11 Could you, please, describe what error is thrown when clicking the Max switch button? Also - can this be reproduced on latest Trinity version `0.4.6`?

**Comment by cvarley100** [comment]
@Vale11 Please try this again on 0.5.0 and share the error message.

**Comment by Vale11** [comment]
Yeah, it seems like this issue was fixed. I'm not able to reproduce it on 0.4.6 and 0.5.0.

Thank you
