### ISSUE TITLE
Trinity RPC API to wallet management

### ISSUE THREAD

**Issue by mrbianchi** [iotaledger/trinity-wallet#1480]

**Comment by mrbianchi** [comment]
I was thinking something like Electrum Wallet rpc

**Comment by mrbianchi** [comment]
http://docs.electrum.org/en/latest/merchant.html#jsonrpc-interface

**Comment by cvarley100** [comment]
@mrbianchi Could you give some scenarios in how this might be used?

**Comment by cvarley100** [comment]
Related to #991, #1480

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
