### ISSUE TITLE
Windows7: v0.5.0 does not start

### ISSUE THREAD

**Issue by thucar** [iotaledger/trinity-wallet#1498]
### Bug description
After upgrading to v0.5.0 the wallet does not start. I see three Trinity.exe processes in my task manager.

### Environment Specs
- Model: PC
- OS version: Win7 x64
- Trinity version: v0.5.0

### Steps To Reproduce
1. Upgrade/install v0.5.0
2. Click the Trinity icon

### Expected behaviour
Trinity wallet should open

### Actual behaviour
Trinity wallet does not open but three Trinity.exe processes appear in task manager.

**Comment by cvarley100** [comment]
Hi @thucar. Windows 7 is not currently supported in version 0.5.0. The new Realm database introduced in 0.5.0 does not support Windows 7. We are working on a fix and a new build will be ready soon.
