### ISSUE TITLE
Tray app does not show correct fiat value

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#1501]
### Bug description
Trinity does not show the correct fiat value of the user's balance in the tray app. It shows $0 instead.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: MacBook Pro
- OS version: macOS 10.14.5 Beta (18F118d)

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v0.5.0

### Steps To Reproduce
1. Set up an account in Trinity
2. Deposit enough so that it has a balance with a fiat equivalent greater than $0.01
3. Open the tray app

### Expected behaviour
The tray app should show the correct fiat value

### Actual behaviour
The tray app always shows $0.00

### Errors
N/A

**Comment by weidtn** [comment]
I'm on 0.5.1 on Linux and still have "$ 0.00". Also the values under the chart are all zero.

EDIT: same on android
