### ISSUE TITLE
TypeError: null is not an object (evaluating 't.settings.versions.version')

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#1514]
## Error in Trinity Mobile

**TypeError** in **MainActivity**
null is not an object (evaluating 't.settings.versions.version')

[View on Bugsnag](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5ccc49a6ea1b70001aa3a227?event_id=5cd94afb0039ed0401320000&i=gh&m=ci)

## Stacktrace

    src/ui/routes/entry.js:84 - getInitialScreen
    src/ui/routes/entry.js:74 - 

[View full stacktrace](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5ccc49a6ea1b70001aa3a227?event_id=5cd94afb0039ed0401320000&i=gh&m=ci)

*Created by Rajiv Shah via Bugsnag*

**Comment by rajivshah3** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **MainActivity**](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5ccc49a6ea1b70001aa3a227?event_id=5d1bd7570047c41342280000&i=gh&m=fx)

**Comment by cvarley100** [comment]
Closing due to lack of incidence in v1.0.0
