### ISSUE TITLE
0.5.0 doesn't work with ssh x-forwarding

### ISSUE THREAD

**Issue by KnockKnockNe0** [iotaledger/trinity-wallet#1527]
When i do
`$ ssh -XY foo@remote `
and run trinity-desktop-0.5.0.AppImage in the remote shell,
i get no response at all, no error, no electron GUI, nothing.
(It does work locally on the remote machine, though)

Not critical, just wondering :-)

**Comment by cvarley100** [comment]
Trinity cannot currently be run in the shell alone. Perhaps something for the future.

**Comment by KnockKnockNe0** [comment]
> Trinity cannot currently be run in the shell alone. Perhaps something for the future.

I know, i was not suggesting a shell-text-only version.

You can start any GUI APP locally in an X-Terminal.
And with ssh X-Forwarding the APP would run on a remote machine, while the GUI is forwarded to the local machine.
(e.g. if remote CPU is faster, maybe headless, different Linux Distro that works, local doesn't)

Please re-open?

**Comment by cvarley100** [comment]
Ok, in what scenario would you like to do this @KnockKnockNe0?

**Comment by KnockKnockNe0** [comment]
Ok, Scenario:

I got this computer A, it is slow, trinity doesn't run.
Then i got another computer B, it is fast, trinity runs.
A is the main machine, it has a monitor/display connected.
B runs headless (no monitor, renderslave)
A and B are connected via GbE LAN.
I connect from A to B via ssh to run apps.

(Yes there is VNC too, i know. That's how i run trinity right now)
