### ISSUE TITLE
Can’t change currency - iPhone 7

### ISSUE THREAD

**Issue by ATimesThree** [iotaledger/trinity-wallet#1537]
The issue tracker is only for reporting bugs. If you need technical assistance for using Trinity Wallet, please consult the Trinity [documentation](https://docs.iota.works/trinity) and [knowledge base](https://iotaledger.atlassian.net/wiki/spaces/trinity/overview). For further assistance, please visit the #help channel on [Discord](https://discord.gg/7Gu2mG5).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).

### Bug description
Can’t change currency on Trinity Mobile. Stuck on screen with not being able to chose the drop down menu and have the spinning wheel loading the whole time.

### Environment Specs
Trinity Mobile - Iphone 7

- Manufacturer: Apple
- Model: Iphone 7
- OS version: 12.2

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version:0.7.0

### Steps To Reproduce
1.
2.
3.

### Expected behaviour
What should happen.
Being able to change currency 

### Actual behaviour
What really happened.
Not able to change currency and stuck with spinning wheel.
 
### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

**Comment by rajivshah3** [comment]
It looks like our exchange rate endpoint crashed, possibly due to an issue at Heroku. It should be working now. Thanks for reporting!
