### ISSUE TITLE
Appimage ask every time for Desktop Integration. Even after selecting No last time.

### ISSUE THREAD

**Issue by CrashTD** [iotaledger/trinity-wallet#1540]
### Bug description
At every launch i get the window with title "Install" and "would you like to integrate trinity with your system?". Even after i selected "No" the last time.

![desktopintegration](https://user-images.githubusercontent.com/45145914/57861766-7f6d2e80-77f7-11e9-87a3-b66df4500424.png)

That seems to be a feature of electron.

### Environment Specs
Linux (4.19.36-1-MANJARO)
Trinity 0.5.0

**Comment by rajivshah3** [comment]
Did this start appearing in a certain release?

**Comment by CrashTD** [comment]
No, was the same with 0.4.6. sorry, should have added that info. Not sure about earlier versions.

**Comment by rajivshah3** [comment]
Ok, will look into this

**Comment by rajivshah3** [comment]
You can try this: https://github.com/electron-userland/electron-builder/issues/1962#issuecomment-454486453

It seems like a bug with `electron-builder` or `AppImage`

**Comment by CrashTD** [comment]
bingo. that fixed it. creating a empty file `$HOME/.local/share/appimagekit/no_desktopintegration`

thanks!
