### ISSUE TITLE
Windows 10: v0.5.0 does not start.

### ISSUE THREAD

**Issue by PresenceNumerique** [iotaledger/trinity-wallet#1542]
### Bug description
Trinity wallet does not start.

### Environment Specs
- OS version: Windows 10

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version:0.5.0

### Steps To Reproduce
1.Install/upgrade
2.Double Click trinity shortcut

### Expected behaviour
Wallet should launch

### Actual behaviour
Nothing happens but 3 processes can be seen in task manager

**Comment by t00k** [comment]
Hey Presence!
What version did you have before updating to 0.5.0?
Some people have had issues going from older versions and directly to 0.5.0, the solution has been to install 0.4.6, and then go to 0.5.0 from there.

Might be worth a try!

**Comment by PresenceNumerique** [comment]
Hello there,
I upgraded from 0.4.0 from what i remember.

I uninstalled 0.5.0 and installed it again and got same result: wallet not launching.

I will try installing 0.4.6 then.

**Comment by PresenceNumerique** [comment]
Ok, i tried it:
Installed v0.4.6 : everything is working.
Upgraded to v0.5.0: Wallet won't launch.

**Comment by t00k** [comment]
This seems to be a problem with the Credentials Manager. I just helped a guy on Discord with this exact same issue.

My short guide to fix it will follow below. Make sure to have your seeds backed up or remember the index for your Ledger.

> Start with going to Control Panel and Manage programs or whatever it is called. You want to uninstall Trinity from inside there. Since you cannot access the wallet we have to reset it by deleting appdata. On Windows 7 (for me) you can browse into %APPDATA% .. Just open My documents or similar and write %APPDATA% and enter..
> 
> First, delete C:\Users\YourUserName\AppData\Roaming\Trinity .. Then browse to C:\Users\YourUserName\AppData\Local\Programs\trinity-desktop and delete that trinity-desktop folder as well.
> 
> Next, go into Control panel -> User accounts .. On windows 7 there is in the left row something called Credentials manager .. Go into this and delete everything that starts with Trinity wallet/ .. This will make sure that you have absolutely nothing doing with Trinity on your computer. If you want to, restart your computer and then try installing Trinity 0.5.0 again, this time it should be entirely fresh.
> 
> Cannot promise that this method will work for you but have worked for others with similar issues.
> Where Credentials manager and Trinity had some "collision"
> 
> When I uninstalled Trinity the Local\Programs\trinity-desktop dissapeared but I had to manually delete the one inside %appdata%

I hope this will help you in your case. Will monitor this thread with your answer as well.

**Comment by PresenceNumerique** [comment]
I tried this and result is unfortunately identical: wallet does not launch.

**Comment by t00k** [comment]
That's too bad! :(

Will keep my eyes open in the Discord and hope that the devs find the cause of it.

**Comment by rajivshah3** [comment]
Can you post a list (screenshot works too) of the files in `C:\Users\username\AppData\Roaming\Trinity`?

**Comment by PresenceNumerique** [comment]
Sure, here you go:
![image](https://user-images.githubusercontent.com/46331204/57987663-d9ceef00-7a84-11e9-850c-b88cdcba087a.png)

**Comment by iarcho** [comment]
upgraded from version 0.3 to 0.5 on windows 10 and when i start wallet the logo shows then it dissapear and nothing is shown anymore

**Comment by cvarley100** [comment]
@iarcho It is recommended in the release notes that you first upgrade to 0.4.6 before upgrading to 0.5.0.
