### ISSUE TITLE
 Trinity Desktop 0.5.0 fails to open on Linux Mint 18.2 

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/trinity-wallet#1543]
### Bug description
Trinity Desktop 0.5.0 does not open on Linux Mint 18.2.

**Comment by rihardsgravis** [comment]
Linux Mint 18.2 requires an upgrade to libstdc++6 (this version is required by Electron).
It is advised to [update Linux Mint to version 19.1](https://community.linuxmint.com/tutorial/view/2) or update just the libstdc++6 version:
``` 
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6
```

**Comment by FatBirdie** [comment]
That did open the GUI but its all black inside the window.
