### ISSUE TITLE
N.write is not a function

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#1556]
## Error in Trinity Desktop

**TypeError** in **/index.html**
N.write is not a function

[View on Bugsnag](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5cde8c5c3c107400195ffef3?event_id=5ce13dde0039f048e01c0000&i=gh&m=ci)

## Stacktrace

    webpack/bootstrap:11 - Function.acceptTerms

[View full stacktrace](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5cde8c5c3c107400195ffef3?event_id=5ce13dde0039f048e01c0000&i=gh&m=ci)

*Created by Rajiv Shah via Bugsnag*

**Comment by rihardsgravis** [comment]
The error is `Realm.write is not a function` which was caused by faulty Realm initialisation. Is _fixed_ in `0.5.1` in #1549 by showing the Realm initialisation fatal error instead.
