### ISSUE TITLE
Trinity Desktop fails to open on Linux Mint

### ISSUE THREAD

**Issue by FatBirdie** [iotaledger/trinity-wallet#1582]
### Bug description
Linux AppImage will not start GUI, but starts 5 processes called 'trinity-desktop'

### Environment Specs
Desktop, Linux Mint

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version:
0.5.0

### Steps To Reproduce
1. Start
2. Nothing

**Comment by rihardsgravis** [comment]
@FatBirdie  what version of Linux Mint? Possible duplicate of #1543

**Comment by FatBirdie** [comment]
Works well with 0.4.0, but I've just re-installed my system with latest build of Linux mint, and now it seems to work fine for some reason. Sorry for taking up everyones time.
