### ISSUE TITLE
Node problem

### ISSUE THREAD

**Issue by FatBirdie** [iotaledger/trinity-wallet#1583]
### Bug description
Getting red error message box when starting Trinity:
Node error: The node returned an error while fetching your account information. If your problem persists, try changing node or disabling your system proxy in Trinity settings.

After this, menu options Trinity -> Error log and Trinity -> Settings -> *all* seem to be out of order. No matter what is clicked, nothing happens.

### Environment Specs
Desktop, Linux mint (not same computer as previous bug-report- to avoid confusion)

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version:
0.5.0

**Comment by rajivshah3** [comment]
@FatBirdie are you able to log in? What about using the Settings button in the bottom left?

**Comment by FatBirdie** [comment]
No, no login. There is no settings button. Attaching screenshot.

**Comment by FatBirdie** [comment]
![Screenshot from 2019-05-22 23-08-12](https://user-images.githubusercontent.com/40865389/58209182-cfac2b00-7ce6-11e9-9b1d-625895f1e9d0.png)

**Comment by FatBirdie** [comment]
Linux mint 19 on this computer by the way.

**Comment by rajivshah3** [comment]
Have you run a version of Trinity before 0.4.6?

**Comment by FatBirdie** [comment]
Works well with 0.4.0, but I've just re-installed my system with latest build of Linux mint, and now it seems to work fine for some reason. Sorry for taking up everyones time.

**Comment by cvarley100** [comment]
Not at all @FatBirdie, thanks for taking the time to submit the report!
