### ISSUE TITLE
Trinity does not work correctly on Windows when username has special characters

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#1594]
### Bug description
We're seeing error reports where Realm initialization is failing with an error similar to one of the following:  
```
Unable to open a realm at path 'C:\Users\username\AppData\Roaming\Trinity\trinity.realm.management': make_dir() failed: No such file or directory Path:.
```
```
Unable to open a realm at path 'C:\Users\username\AppData\Roaming\Trinity\trinity.realm.management': make_dir() failed: Illegal byte sequence Path:.
``` 

This may be related to a bug in Realm where paths with special characters are not supported (https://github.com/realm/realm-js/issues/2319)

### Environment Specs
What device are you running Trinity on?

- Manufacturer: N/A
- Model: N/A
- OS version: Windows

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v0.5.0 and later

### Steps To Reproduce
1. Create a user account with special characters in the username (Chinese, Korean, Cyrillic, and accented Latin characters are known to cause this issue)
2. Attempt to open the latest version of Trinity

### Expected behaviour
The app should open and function correctly

### Actual behaviour
The app might not function correctly

**Comment by rajivshah3** [comment]
A possible workaround may be to create another user account (without special characters in the username) for using Trinity

**Comment by rihardsgravis** [comment]
We should try to store Realm database in another, not user related path (e.g. the application path) for the Realm db.

**Comment by tolotos-rgu** [comment]
I have the same behavior. My Win10 username is "first name""blank""last name" the first name conains a German Umlaut (ü)

**Comment by suefkem** [comment]
Same issue here. Win10 Pro (1803), had the issue with trinity wallet after the last update. Username: Firstname(Whitespace)Lastname(with german Umlaut)

-  uninstalled it and deleted files located in appdata/roaming, downloaded and tried to install fresh -> same error. 
app from testflight/ios does somehow always reset and forces me to completly set up everything from scratch after I colse the app.

**Comment by rajivshah3** [comment]
> app from testflight/ios does somehow always reset and forces me to completly set up everything from scratch after I colse the app.

That's odd 🤔 would you mind creating another issue for that?

**Comment by suefkem** [comment]
> > app from testflight/ios does somehow always reset and forces me to completly set up everything from scratch after I colse the app.
> 
> That's odd 🤔 would you mind creating another issue for that?

No problem. Gonna do that now. Feel free to delete this to keep it clean in here
