### ISSUE TITLE
Triniy Failed TX

### ISSUE THREAD

**Issue by FatBirdie** [iotaledger/trinity-wallet#1596]
### Bug description
Been playing around with the new release of Trinity today and I've signed seveal transactions, moving IOTA from one ledeger to another. All of the sudden when signing a transaction I get an error message saying "Something went wrong while sending your transfer. Please try again." 
The message kept appearing and I restarted Trinity, where I then was met with an message  "missing security dependencies" and Trinity asks me to install dependencies to my system. I was very confused because I've been using Trinity uninterrupted up until then and the inconsistency makes me paranoid since I've not run an update or anything like it (but perhaps this is normal that Trinity asks users to install new things out of nowhere?).
I downloaded Trinity again, and first run it does not ask me to install any dependencies. Second time I start Trinity it does again. I clean the whole account from the settings menu and initialize my Ledger again. No message about dependencies appear and I try to re-create the transaction which failed before, and it fails once again. This time Trinity does not ask me to install dependencies even after restarting the software.
Checking the log from the menu, it says "Invalid TX" followed by several "Timeout" (and a "Node not synced" although this might have something to do with me trying to change Node after it failed).

Everything about the transaction was smooth up until the error. Ledger does not complain, all addresses seems correct etc. Not sure whats up now.

### Environment Specs
Linux Mint 19

- Trinity version:
0.5.1

### Errors
Can't copy the error log from Trinity. Can only select one line at a time. Perhaps this is something to fix also.

**Comment by FatBirdie** [comment]
Continued trying to send and with small amount it worked fine. I then increased the amount tenfold and again got the "transaction failed" error, and in the error log I see "Invalid bundle".

**Comment by FatBirdie** [comment]
Furthermore I've not been asked by Trinity to install any dependencies again, nor have I followed the steps Trinity asked me to follow as I found it strange. Even stranger that I'm no longer asked to install the packages anymore. Clarity?

**Comment by rajivshah3** [comment]
The dependency thing is definitely odd. The “invalid bundle” issue is likely because the Ledger device only supports a limited number of input transactions

**Comment by FatBirdie** [comment]
Ledger device only supports a limited number of input transactions?

**Comment by FatBirdie** [comment]
Do you mean, it can not collect funds from several addresses and make a transaction of it? So then what, all my funds are locked on the Ledger and I can not move them?

**Comment by FatBirdie** [comment]
Any dev for Trinity and Ledger care to comment?

**Comment by FatBirdie** [comment]
So strange, left the computer running with a transaction failing repeatedly. Came back now a while later, and now its gone through and is done. I'm properly confused.

**Comment by rajivshah3** [comment]
> So then what, all my funds are locked on the Ledger and I can not move them?

You can move your funds, you just might need to do it in more than one transaction

> Came back now a while later, and now its gone through and is done

That's weird 🤔

**Comment by FatBirdie** [comment]
Last transaction made generated errors, but I let it be and a few hours later something happened as it appeared on thetangel.org as "Bundle". Its been more than 3 days not, and its still "Pending". I've tried "Retry" many times in Trinity, but it makes no difference to the pending state.
I know the tangle used to have long times for transactions before, but I though this was not a problem any more although I guess I'm wrong? If the transaction is seen on thetange.org, then its just a matter of time before it goes through at least? Or am I misunderstanding something here?

**Comment by FatBirdie** [comment]
Trying to "retry" the "Promoting" transaction in Trinity, but keep getting "Invalid Bundle provided" in the error log and red error box with message "Could not promote transaction. Something went wrong while promoting your transaction. Please try again". Also, sometimes the "Retry" button completely hangs it seems, the icon on the button just keeps spinning without any end. No errors and no stop. How do I get the transaction to release if Trinity/Tangel/Ledger can't handle it? It was a pretty large transaction, so this isn't very fun to stare at not knowing what the hell is up. **Are there no devs that can comment?** Something is clearly not right with the operation of Trinity and Ledger X.

**Comment by FatBirdie** [comment]
Been running and quitting Trinity all day trying to get this to work. All of the sudden, now I get the "missing security dependencies" again, from out of nowhere! I've been doing the exact same thing every single time I've started the wallet, trying to retry sending the transaction and checking the log, yet now all of the sudden for some reason it wants me to install things to my system. Seriously, what is going on?
![Screenshot from 2019-05-27 20-32-09](https://user-images.githubusercontent.com/40865389/58435021-ce9c4480-80be-11e9-8892-c6dff2d50597.png)

**Comment by rajivshah3** [comment]
Hey, sorry for not replying. Did this ever happen to you in previous versions?

**Comment by FatBirdie** [comment]
No, it has not. But why would Trinity tell me to do this now, when I've started the software probably 20 times already today only doing the same thing every time? It makes no sense what so ever to me. Either I need it, and Trinity should tell me right away first time, or I don't and it should never bother me with it.

**Comment by rajivshah3** [comment]
> But why would Trinity tell me to do this now

I don't know, that's why I asked if this happened in previous versions. It's evidently a bug and I'm trying to isolate where it may have come from

**Comment by FatBirdie** [comment]
Okay, let me know if you need any information to aid in the bug search although that bug is more strange than anything I'm much more concerned with why my transaction as the retry button keeps spinning, and I'm getting all these strange errors sporadically.

**Comment by rajivshah3** [comment]
Can you check if there is a process called `gnome-keyring` (or similar) running?

**Comment by FatBirdie** [comment]
Yes, gnome-keyring-daemon is running

**Comment by rajivshah3** [comment]
Hmm, that's definitely odd if Trinity's not seeing that it's running. Have you installed or updated anything recently?

**Comment by FatBirdie** [comment]
Between downloading latest Trinity, having all the transaction issues and getting the message to install libsecret (which I now have)- No. No updates to the system.

**Comment by rajivshah3** [comment]
> which I now have

Did you not have it before?

**Comment by FatBirdie** [comment]
Before I was on 0.4.something, and no. No such message then.

**Comment by rajivshah3** [comment]
Can you paste the command that you used to install `libsecret` here?

**Comment by FatBirdie** [comment]
Just as Trinity asked me to: sudo apt-get install libsecret-1-dev

**Comment by rajivshah3** [comment]
Can you paste the output of `apt list --installed | grep libsecret` ?

**Comment by FatBirdie** [comment]
libsecret-1-0/bionic,now 0.18.6-1 amd64 [installed]
libsecret-1-dev/bionic,now 0.18.6-1 amd64 [installed]
libsecret-common/bionic,bionic,now 0.18.6-1 all [installed]

**Comment by rajivshah3** [comment]
Hmm, that seems normal. This is likely the same issue as #1630. Regarding the transaction that wouldn't confirm, would you happen to still have the bundle hash or transaction hash available through something like your browser history?

**Comment by FatBirdie** [comment]
Retry button for the "pending" transaction hsa been spinning non stop now for 10+ hours. This cant be normal?

**Comment by FatBirdie** [comment]
Yes, here is the bundle hash:
IYBGKYF9LKWWGFLVCRJRQADTNPXRCFYYSTDJWYXTZFVYTLFETDIPHCSXADJAVAGAXWCPLELTIKKNKIIJ9

**Comment by FatBirdie** [comment]
Regarding #1630 and resetting the wallet. I think this was wheat I did before.
I tried first downloading Trinity again, and it did not show the libsecret message the first time I started it, but the second time it did, where I then reset the wallet and were not prompted again about installing libsecret until I posted the screenshot here.

**Comment by rg80** [comment]
Hi, same problem here with latest trinity for OSX V10.14.5 and Nano X with latest firmware. I'm trying to transfer some IOTAs between accounts on the same wallet but It always fails with "Invalid Bundle".
Please tell me if I can help with some test. :)

![Schermata 2019-05-28 alle 21 30 12](https://user-images.githubusercontent.com/51135324/58506547-e68fc900-818f-11e9-98a4-6a5e6bacce8a.png)

**Comment by rajivshah3** [comment]
@rg80 please see https://github.com/iotaledger/trinity-wallet/issues/1596#issuecomment-495419664

**Comment by rajivshah3** [comment]
@FatBirdie can you please switch to remote PoW in settings and enable auto-promotion? Then click "retry" again

**Comment by FatBirdie** [comment]
@rajivshah3 Yes, changed to a node which would accept remote PoW, and enabled auto-promotion. Saw a quick green upper right box  "auto-promotion ....."-something, as it was successful, followed by a red box with an error message. In the error log I now have:  Transaction is inconsistent. Reason: tails are not solid (missing a referenced tx): 

Do you need the TX?

**Comment by rajivshah3** [comment]
Is it the same as the bundle hash you gave before?

**Comment by FatBirdie** [comment]
Wait. I tried retrying it again, and it went successfully!

**Comment by FatBirdie** [comment]
No, not the same hash as before.

**Comment by rajivshah3** [comment]
Ok, so that one is still pending?

**Comment by FatBirdie** [comment]
No, the second time now I pressed "Retry" after the first one produced the error, it went through almost immediately. The transaction has now been completed.

**Comment by FatBirdie** [comment]
Thanks for the help by the way.
Just let me know if there is anything I can check or do to help in regards to this particular issue.

**Comment by rajivshah3** [comment]
> The transaction has now been completed.

Great!

I think this issue can be closed since the tx eventually confirmed (the errors it was giving aren't exactly related to Trinity--some are related to Ledger or IRI). The issue with missing security dependencies is being tracked in #1630

**Comment by FatBirdie** [comment]
Okay, should whoever is handling the development of the Ledger software for IOTA be notified about it perhaps?

Thanks again!
