### ISSUE TITLE
Transaction history empty

### ISSUE THREAD

**Issue by ratiodep** [iotaledger/trinity-wallet#1604]
### Bug description
Transaction history stays empty with several seeds, even after Reattaching/Manual synchronising with different nodes.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Dell 
- Model: Precision M7720
- OS version: Win 7 64 Bit

- Trinity version: 0.51

### Steps To Reproduce
1. Open Trinity

### Expected behaviour
Transaction history displayed entirely.

### Actual behaviour
Transaction history stays empty.

**Comment by christopher-wilke** [comment]
Same thing happened to me. Balance shows correct value.

**Comment by jdesopo** [comment]
I'm experiencing the same problem on IOS V 0.7.2 (61). 

Settings>Account management>View addresses shows what looks like a valid history.

Balance (last 4 items in the top area) and History only show 0i transactions with wrong dates.

Total seed balance is good.  This problem exists for ALL seeds stored in Trinity.

![image](https://user-images.githubusercontent.com/51210514/58655185-658b1b80-82ce-11e9-8e70-7232f071ddb3.png)
![image](https://user-images.githubusercontent.com/51210514/58655220-7c317280-82ce-11e9-89ff-de860a02aa54.png)
![image](https://user-images.githubusercontent.com/51210514/58655697-87d16900-82cf-11e9-9447-43f5c1f2a343.png)

**Comment by cvarley100** [comment]
@ratiodep @h3dgyy @jdesopo Did you guys add old, existing seeds to Trinity?

**Comment by christopher-wilke** [comment]
@cvarley100 No I am using the Ledger Nano S for quite a long time now. I am still facing the same issue.

**Comment by cvarley100** [comment]
So, without resetting Trinity or removing the account, the history disappeared?

**Comment by christopher-wilke** [comment]
@cvarley100 Yes. Balance at the top shows the correct amount so I believe it's just the history?

**Comment by jdesopo** [comment]
Yes and at one time Trinity showed the history, and after an update (can’t remember which one), the history was gone.  This happened, I believe, around the first week in May - perhaps May 3rd or 4th, for me - but I may be off by a few days.

**Comment by christopher-wilke** [comment]
Any updates on this?

**Comment by cvarley100** [comment]
@h3dgyy You will likely need to connect to a node that still has your history to get it back

**Comment by christopher-wilke** [comment]
@cvarley100 How do I know which node I can use? I tried permanent nodes but none of them worked.
