### ISSUE TITLE
Biometric auth fails after reopening Trinity

### ISSUE THREAD

**Issue by ratiodep** [iotaledger/trinity-wallet#1621]
### Bug description
Biometric auth fails after reopening Trinity

![Screenshot_20190524_225830_com iota trinity](https://user-images.githubusercontent.com/50994219/58366513-c46a2280-7ed3-11e9-9da4-5aaac1212020.jpg)

### Environment Specs

- Manufacturer: Huawei 
- Model: P20 pro
- OS version: Android 9

- Trinity version: 0.71

### Steps To Reproduce
1. Open Trinity, log in with password
2. Close Trinity 
3. Reopen after a few minutes

Doesn't happen every time.

### Expected behaviour
Biometric auth should be possible

### Actual behaviour
Biometric auth fails directly without touching the fingerprint sensor of the phone

**Comment by rajivshah3** [comment]
I think I've seen this on iOS a few times but it's hard to reproduce reliably

**Comment by ratiodep** [comment]
Yes. Only had it twice yet, then never again.

**Comment by cvarley100** [comment]
@ratiodep Anything in the error log?
