### ISSUE TITLE
Create Error message when no internet connection

### ISSUE THREAD

**Issue by ratiodep** [iotaledger/trinity-wallet#1622]
### Description

Let the user know if there is no internet connection. 

![inet](https://user-images.githubusercontent.com/50994219/58369809-0e68fd80-7f00-11e9-976c-c56668b0f2e7.png)

### Motivation
Error message "node error (...)" could be misleading if in reality the cause is the non-existent Internet connection.

**Comment by cvarley100** [comment]
@ratiodep Trinity displays a blanket error if there is no internet connection.
