### ISSUE TITLE
 Fatal error launching Trinity desktop wallet v0.5.1. Linux/Ubuntu

### ISSUE THREAD

**Issue by Nick2567** [iotaledger/trinity-wallet#1625]
### Bug description
I was prompted to update Trinity from v0.4.6. The update completed and a message said "Trinity will now restart" but the message did not disappear so I restarted Trinity manually. Upon launching Trinity-desktop-0.5.1. a fatal error message displays. I still have access to Trinity, Edit, Help menus.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Dell
- Model: Inspiron
- OS version: Linux Ubuntu 16.04

What build of Trinity are you running? 

- Trinity version: Trinity-desktop-0.5.1.AppImage

### Steps To Reproduce
1. Double click on Trinity-desktop-0.5.1.AppImage
2. Results in error message indicated below.

### Expected behaviour
Wallet should launch normally as in v0.4.6.

### Actual behaviour
Launching wallet results in fatal error as described below.

### Errors
Error launching wallet.
There was a fatal error launching the wallet.
Failed to load Electron preload script
{"error":"Uncaught ReferenceError: setImmediate is not defined"}

**Comment by rajivshah3** [comment]
Was there a stacktrace in the error message, or did it only say `Uncaught ReferenceError: setImmediate is not defined`?

**Comment by Nick2567** [comment]
The first time I launched 0.5.1 there was a more detailed error message but now I just see the image below. I have access to the menu for Trinity --> Error Log but nothing appears.

![image](https://user-images.githubusercontent.com/32357455/58430429-452a4980-80a1-11e9-85cb-159ad0a2e8e0.png)

**Comment by rajivshah3** [comment]
Hmm. Do you remember anything from the detailed message?

**Comment by Nick2567** [comment]
No, unfortunately not. After restarting the wallet again I though it would either run without error or the same error message would appear.

Do you think I should download v0.4.6 again or download v0.5.1 and restore from seed vault?

**Comment by Nick2567** [comment]
Launched Trinity 0.5.1. (error message above still displaying)
Went to Trinity --> Check for Updates. A new Trinity version is available. Clicked Yes to update.
![image](https://user-images.githubusercontent.com/32357455/58752092-d08c4c00-84a0-11e9-987f-924eb910aa42.png)
Update completed but Trinity did not restart. Message stayed on screen.
![image](https://user-images.githubusercontent.com/32357455/58752102-fa457300-84a0-11e9-966b-4e3a746203c7.png)
Restarted manually. When launching 0.5.2. I now just see a blank white screen with the menus at the top.
![image](https://user-images.githubusercontent.com/32357455/58752113-3547a680-84a1-11e9-8b35-e8a43aa98080.png)

**Comment by Nick2567** [comment]
Removed AppImage and downloaded 0.5.2 again, same issue.
I have now downloaded 0.4.6 again and this is working fine, as before.
