### ISSUE TITLE
Error message when checking for updates without internet connection

### ISSUE THREAD

**Issue by ratiodep** [iotaledger/trinity-wallet#1626]
This issue has already been submitted with #282 but happens now again (maybe never fixed in Win 7?)

![bug_nointernet](https://user-images.githubusercontent.com/50994219/58399622-0b355500-8059-11e9-885b-def3a6ec9b16.png)

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Dell
- Model: Precision 7720
- OS version: Win 7 64 bit

- Trinity version: 0.51

### Steps To Reproduce
1. Cut internet connection
2. Start Trinity 
3. Start manual update

**Comment by rihardsgravis** [comment]
Closed in #1705
