### ISSUE TITLE
Fatal error: bad allocation

### ISSUE THREAD

**Issue by Noki** [iotaledger/trinity-wallet#1636]
### Bug description

The wallet crashed and now there is no way to start it again. There are no UI elements that allow any interaction.

### Environment Specs
What device are you running Trinity on?

- OS version: Windows 10

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: Trinity Desktop v0.5.1

### Expected behaviour

Automatically reset the wallet and restore the wallet from a backup file containing the seeds that were previously added.

### Actual behaviour

Unusable wallet that requires a reinstall / manual deletion of files.

### Errors

Starting up it shows the following screen. I can't even reset the wallet from there. The Trinity log folder is empty.

![image](https://user-images.githubusercontent.com/198902/58491202-e0d5bb80-816e-11e9-8873-f6e63900214b.png)

**Comment by rajivshah3** [comment]
Can you try restarting your computer? It looks like it failed to allocate memory.

**Comment by Noki** [comment]
@rajivshah3 that was the first thing i tried. The error was still present after restarting. I than deleted the Trinity folder in %appdata% and setup the wallet from scratch.

**Comment by rajivshah3** [comment]
So it worked after you deleted the `%appdata%` folder?

**Comment by Noki** [comment]
Yes. But that way I had to manually add all seeds again which is quite annoying and happend quite often over the last couple of weeks. The trinity wallet seems to have a lot of issues once you add multiple seeds with a couple of thousend active addresses... :-(

**Comment by rajivshah3** [comment]
Did you happen to see the size of the `AppData\Trinity` folder? We're investigating issues where the size of the database is unusually large. I wonder if this was related

**Comment by Noki** [comment]
@rajivshah3 the size was indeed very large. The trinity.realm was 2.03 GB in size, which is about one of windows memory limits.

**Comment by Noki** [comment]
![image](https://user-images.githubusercontent.com/198902/58622232-70907c80-82cb-11e9-8777-bc607f483fc5.png)

DB has grown back to almost 2 GB in less than one day. How do I optain the encryption key so I can have a look why it grows so fast?

**Comment by rajivshah3** [comment]
On Windows I think you can get it from Credentials Manager. If it doesn't let you see the key for that, you can use something like https://www.nirsoft.net/utils/credentials_file_view.html (I've never used this though so I'm not sure if it's safe). Then you would convert the decryption key into a 128-character hex key which you can put into [Realm Studio](https://realm.io/products/realm-studio/) to view the database data.

Regarding the reason it grows so fast, we're seeing objects being created multiple times. We're planning to fix this in #1609 . We're also looking into database compaction so that the database does not grow so quickly

**Comment by Noki** [comment]
@rajivshah3 I had a look and did not want to try it. So I guess I'm waiting for a fix for this because it grew to more than 2 GB and crashed again.

![image](https://user-images.githubusercontent.com/198902/58719179-4de78c00-83cf-11e9-8edb-a9b6577a58d6.png)

Currently Trinity is totally unusable for me.

**Comment by Noki** [comment]
Yay! Crashes with a white screen now...

![image](https://user-images.githubusercontent.com/198902/60355423-9d20dc80-99ce-11e9-9312-dd47ea412c8b.png)

**Comment by rajivshah3** [comment]
@Noki sorry for the delay in fixing this issue. For now, I think you may need to reset Trinity by deleting the `AppData\Trinity` folder. We're working on a fix to reduce database size in #1608

**Comment by cvarley100** [comment]
Closing to due age. Please reopen if you are still facing this issue after following @rajivshah3's steps.

**Comment by rajivshah3** [comment]
This issue was fixed in #1608 which was released in RC1 (release candidate)
