### ISSUE TITLE
Rebroadcast Error Loop

### ISSUE THREAD

**Issue by laumair** [iotaledger/trinity-wallet#1640]
### Bug description
Auto-retrying of failed transactions can get into an infinite loop if there is a problem with stored trytes. 

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: 
- OS version: 10.14.6 Beta 

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: Develop `b77b8145834fda432d4699f145cd2cccd656b401`

### Steps To Reproduce
1. Make a transaction with corrupt trytes (Make sure the trytes are signed)
2. Observe polling of components

### Expected behaviour
Trinity should stop auto-retrying of failed transactions after a limit (e.g., 5)

### Actual behaviour
Trinity gets in an infinite loop and continuously tries to broadcast transactions

### Errors
N/A

**Comment by rajivshah3** [comment]
Is this related to #1538 and #1386?

**Comment by laumair** [comment]
I think those two issues are related to UI components not updating properly but thanks for mentioning them here. I will also check these two issues.
