### ISSUE TITLE
Testflight Trinity App (0.70) removes data after closing app

### ISSUE THREAD

**Issue by suefkem** [iotaledger/trinity-wallet#1647]
### Bug description
A general description of the bug.

When using the app from testflight on iOS it did reset all my data after closing the app. happened 3 times. (Have to import seedvault again, enter all passwords and create account)
__
aswell does not show any currency information (just the graph without any digets to see how it stands)

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: iPhone 8
- OS version: 12.3.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).
- Trinity version: 0.70

### Steps To Reproduce
1. delete app, download again

**Comment by rajivshah3** [comment]
Can you try setting up your accounts, then go to General > iPhone Storage > Trinity to see how much storage Trinity is using?

**Comment by suefkem** [comment]
Hey, 
did set it up again and it says 46MB. 
Shall I go ahead and install the 12.3.1 iOS? I mean.. its a long time ago that an apple update actually helped fixing stuff but you will never know until you try :D
BR

**Comment by rajivshah3** [comment]
That might help, I'm not entirely sure. It definitely couldn't hurt to update though

**Comment by suefkem** [comment]
upgrading to ios 12.3.1 alone did not help but upgrading to trinity 0.71 at least lets me sign in straight agin. 
however the app just closes while signing in.

**Comment by cvarley100** [comment]
@suefkem Try deleting Trinity and setting up on 0.7.2 and let us know how it goes.

**Comment by suefkem** [comment]
Hey that seems to work.
