### ISSUE TITLE
Chrome OS Linux beta support

### ISSUE THREAD

**Issue by jurjendevries** [iotaledger/trinity-wallet#1665]
### Description
Trinity support for Chrome OS Linux beta. See https://support.google.com/chromebook/answer/9145439 for more information about Chrome OS Linux Beta.
Currently it gives an error "Cannot connect to secret service api"

### Motivation
A lot of people have a Chromebook with Chrome OS. Chrome OS can run extensions such as Metamask. Since it haves linux support it can run a lot of other apps too, but some won't work out of the box such as Trinity.

### Requirements
Run Trinity with all its features

### Am I planning to do it myself with a PR?
no. I don't have the skills. I am more a tester and supporter, knowledge sharing, meetup organizer and so in an open source environment.

![Screenshot 2019-05-30 at 20 06 01](https://user-images.githubusercontent.com/355488/58653653-78c1d980-8316-11e9-9f08-b1e156017697.png)

**Comment by cvarley100** [comment]
Related #1221

**Comment by LaPingvino** [comment]
Pay attention that my ChromeOS Linux is Arm64, not Intel/AMD, so it doesn't run simple binaries if they are not compiled for the correct architecture.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
