### ISSUE TITLE
Biometric auth fails upon sending transaction

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#1666]
### Bug description
When attempting to send a transaction, Trinity's bio-metric field will not initialize properly and fail.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Samsung
- Model: Galaxy S8+
- OS version: 9.0.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.7.2 (67)

### Steps To Reproduce
1. attempt to send transaction
2. be unable to send transaction due to bio-metric being messed up

### Other Notes
The issue fixed itself upon exiting the app, and unlocking and re-entering the app again.

### Expected behavior
Biometric prompt should take a fingerprint and send transaction.

### Actual behavior
Biometric field displayed and error and would not attempt to read and finger prints.

### Errors
![bioFail](https://i.imgur.com/oc0JZh0.png)

**Comment by sloganking** [comment]
Possibly related issues:

#1621
#1667

**Comment by cvarley100** [comment]
@SleepingFox88 Anything in the error log?

**Comment by cvarley100** [comment]
@SleepingFox88 Are you still experiencing this issue?

**Comment by sloganking** [comment]
I have not had this issue in a while. Closing it is fine for now
