### ISSUE TITLE
Fatal error: the username or passphrase you entered is not correct.

### ISSUE THREAD

**Issue by Meemaw** [iotaledger/trinity-wallet#1677]
### Bug description
I Get a fatal error screen after opening Trinity: "The username or passphrase you entered is not correct."

This happens even though I did not enter anything as this is the first screen that I get.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: Mabook Pro, 13 inch, 2017
- OS version: macOS Mojave 10.14.5

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: trinity-desktop-0.5.2.dmg

### Steps To Reproduce
1. Open Trinity

### Errors
<img width="1287" alt="Screenshot 2019-06-01 at 08 37 13" src="https://user-images.githubusercontent.com/8524109/58744879-de15e780-8448-11e9-94fd-04a21e4f2fb3.png">

**Comment by rihardsgravis** [comment]
@Meemaw  The wallet cannot access macOS Keychain, which is due to a macOS update bug.
Can you try the following - open opening `Keychain Access`.app. Right-click on the login keychain and try locking it and then unlocking it again. The try to open Trinity again.

**Comment by rajivshah3** [comment]
> due to a macOS update bug

@rihardsgravis does this mean the issue occurs with a certain version of macOS or the issue stems from a Trinity update on macOS?

**Comment by rihardsgravis** [comment]
> @rihardsgravis does this mean the issue occurs with a certain version of macOS or the issue stems from a Trinity update on macOS?

macOS update

**Comment by cvarley100** [comment]
Closing due to age.
