### ISSUE TITLE
Application started after update to 0.6 with black Screen. Rollback to 0.5.2 with Error: Provided schema version 2 is less than last set version 4.  

### ISSUE THREAD

**Issue by azarea** [iotaledger/trinity-wallet#1679]
### Bug description
Application started after update to 0.6 with black Screen. Rollback to 0.5.2 with Error: Provided schema version 2 is less than last set version 4.  

### Environment Specs
Windows 10 newest Release

### Steps To Reproduce
1. Update 0.5.2 to 0.6
2. Start new 0.6
3. Downgrade to 0.5.2

**Comment by rihardsgravis** [comment]
Fixed in #1679
