### ISSUE TITLE
opening settings circumvents password field if loading first seed fails

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1682]
### Bug description
If Trinity fails to load the seed at `Load seed for the first time` screen with `Node error` it shows the password screen which doesn't make sense to me to enter the password here. When I go to the setting end close them on `X` it doesn't ask for the password again and loads the seed again.
![tr2](https://user-images.githubusercontent.com/21984138/58766064-b161ed00-857a-11e9-8cc7-a4e34f2ee0c4.PNG)

### Environment Specs

- OS version: Windows 10 1809
- Trinity version: 0.6.0-RC1

### Steps To Reproduce
1. set up first seed
2. `Node error` at `Loading seed for the first time`
3. open setting
4. close settings

### Expected behaviour
It should return to the password screen.
OR there should be no pw screen at all when the first seed fails to load.

### Actual behaviour
Password prompt doesn't show up again although there was no password entered.

**Comment by rajivshah3** [comment]
Does it successfully load the seed even though the password wasn’t entered?

**Comment by KiwiCat123** [comment]
@rajivshah3  Yes, it does.

**Comment by rihardsgravis** [comment]
Fixed in #1688
