### ISSUE TITLE
closing settings at All Done! screen directly starts to load seed

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1684]
### Bug description
If I go to settings at `All Done!` screen after i set up the first seed and close the settings again Trinity starts to load the seed although I never clicked on the `Open your wallet button`.

### Environment Specs

- OS version: Windows 10 1809
- Trinity version: 0.6.0-RC1

### Steps To Reproduce
1. set up first seed
2. at `All Done!` screen open settings
3. close settings

### Expected behaviour
it should return to the `All Done!` screen and just start loading the seed after the user clicked `Open your wallet`

### Actual behaviour
it automatically starts loading the seed after clicking on `X` in settings

**Comment by rihardsgravis** [comment]
Reason for this issue is the same as for #1682

**Comment by rihardsgravis** [comment]
Closed in #1688
