### ISSUE TITLE
enter key doesn't add custom node

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1685]
### Bug description
In `Node settings` at `Add custom nodes` after entering the node address in the field it's not possible anymore to add the node with the enter key. I always have to click the `Add custom node` button which is little annoying and takes time when someone adds a few custom nodes.

### Environment Specs

- OS version: Windows 10 1809

- Trinity version: 0.6.0-RC1

### Steps To Reproduce
1. go to settings -> `Node` -> `Add custom nodes`
2. enter a nodes address
3. press Enter

### Expected behaviour
the node should be added to the list

### Actual behaviour
noting happens. It can only be added with the `Add custom node button`

**Comment by rihardsgravis** [comment]
Fixed in #1691
