### ISSUE TITLE
Key input scroll for currency and language selection

### ISSUE THREAD

**Issue by jojoCoWorker** [iotaledger/trinity-wallet#1693]
### Description
Currencies list and language list could be selected quickly if they where alphabetically sorted and we could scroll directly to the letter we press on the keyboard.

### Motivation
Lists are longer and longer...
![image](https://user-images.githubusercontent.com/33653820/58839538-7804ac80-8662-11e9-98f2-72bfc8ad282d.png)
languages order is weird, sometimes the left word is alphabetically sorted, sometimes the right one is...
![image](https://user-images.githubusercontent.com/33653820/58840236-1c87ee00-8665-11e9-8a16-58d5ca7abd31.png)

### Requirements
I'd like to seamlessly be able to select a language and a currency.

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment]
The language order is sorted alphabetically by [ISO 639-1 code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). In your screenshot, it is sorted in the following order:

```
ee
fa
fi
fr
he
hi
hr
hu
```

**Comment by jojoCoWorker** [comment]
Ok I see your point but :

1. In the case we can't have direct shortcut while pressing first letter on keyboard, a "human eye" has to read the lines, when it comes to ee it reads "E"for "Eesti keel", then for Persian it reads an "unknown character", "fa" never appears, then it sees an "S" for Suomi, nor "fi" for "Finnish" whereas it's looking for alphabet letter before "F" if it's looking for French for example... I would suggest to write the ISO 639-1 code in front of the language like :
> ee - Eesti keel - Estonian
> fa - ..... - Persian
> fi - Suomi - Finnish
> fr - Français - French
> he - .... - Hebrew
> hi - ... - Hindi
> hr - Hrvatski - Croatian
> hu - Magyar - Hungarian

2. If we could have keyboard shortcuts, that would be a good thing even if it's not something of the utmost importance ! I think the above advice to show/write the language would stay usefull.

Thank you for your answer Rajiv !

**Comment by rajivshah3** [comment]
> I think the above advice to show/write the language would stay usefull.

Yep, I agree. I use that a lot so that I don't need to search through long menus. I'll ask the community and team for their opinions on how we should map key presses to menu selections

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
