### ISSUE TITLE
Fatal error; found old data

### ISSUE THREAD

**Issue by yotardis** [iotaledger/trinity-wallet#1718]
The issue tracker is only for reporting bugs. If you need technical assistance for using Trinity Wallet, please consult the Trinity [documentation](https://docs.iota.works/trinity) and [knowledge base](https://iotaledger.atlassian.net/wiki/spaces/trinity/overview). For further assistance, please visit the #help channel on [Discord](https://discord.gg/7Gu2mG5).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).

### Bug description
A general description of the bug.

### Environment Specs
What device are you running Trinity on?

- Manufacturer:
- Model:
- OS version:

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version:

### Steps To Reproduce
1.
2.
3.

### Expected behaviour
What should happen.

### Actual behaviour
What really happened.

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

**Comment by cvarley100** [comment]
Simply delete your Trinity app data folder and try again.
