### ISSUE TITLE
Mobile* can't data migrate - also system crash on node change

### ISSUE THREAD

**Issue by Qaviz** [iotaledger/trinity-wallet#1729]
Updating to Mobile version (0.7.2 68), after logging in to my account the system attempts the data migration process but quickly fails with the error message *something went wrong please try again*. I then try to change nodes to see if this helps, but I get the node error message *error changing node please try again*. 

I then reset the app and tried to change nodes from the login screen, however the app crashes immediately upon pushing the change node button on the login screen. 
Essentially I cannot data migrate, cannot switch nodes on the data migration screen and cannot switch nodes on the login screen, locking me out of the app completely. 

- My discord handle is Qaviz, if you need to reach me

**Comment by Johnrb99** [comment]
I am having exactly the same issue. Should I open a new issue

**Comment by cvarley100** [comment]
@Qaviz @Johnrb99 It is likely that you had a particularly old version installed before. A lot of core changes have been made since then. Please could you delete the app on iPhone/clear data on Android and set up again.

**Comment by t00k** [comment]
![Screenshot_2019-06-07-15-43-17-408_com iota trinity](https://user-images.githubusercontent.com/49842330/59723350-a79ce280-9226-11e9-9768-4fccc8fbb8ba.png)
@cvarley100 Don't know if this has been taken into account with the migration issues? Have seen this error (localhost) twice on mobile and now there are a lot of Mac users being unable to migrate. Something similar on Mac?
