### ISSUE TITLE
Ledger connect problem

### ISSUE THREAD

**Issue by maximus925** [iotaledger/trinity-wallet#1737]
I'd like to create new Ledger account
On the first step program showing connected ledger but in second step when he wont to open IOTA application I pushing two buttons then I see information
Cannot connect to Ledger
I tested in another computer and is this same.
Wallet Ethereum working fine
![error 1](https://user-images.githubusercontent.com/51532759/59159588-f5e21100-8ac3-11e9-90eb-5794cf4ff210.png)
![error](https://user-images.githubusercontent.com/51532759/59159592-fc708880-8ac3-11e9-8e47-8bca960053f4.png)

**Comment by rajivshah3** [comment]
@maximus925 please use the template here: https://github.com/iotaledger/trinity-wallet/issues/new?labels=T+-+Bug&template=bug_report.md&title=. It will ask you for information that we need in order to reproduce the issue

**Comment by larthee** [comment]
I am having exactly the same issue, Trinity in Win 7 64bit does NOT recognize the connected ledger Nano S device, even so visible in Ledger Live and IITA app opened on ledger device. What can I do?
![no connection to Ledger nano S](https://user-images.githubusercontent.com/51678212/59388217-7d04e280-8d6b-11e9-8350-1ceff997da9d.PNG)

**Comment by larthee** [comment]
adding info: Using Ledger Nano S latest IOTA APP version 0.4.2

**Comment by cvarley100** [comment]
@larthee You must close Ledger Live

**Comment by larthee** [comment]
Thanks @cvarley100 - but it did not work before I opened Ledger Live - Legder live I only opened to verify if the Ledger Nano S is connected to the PC and working properly in another application than trinity. I even installed the latest Trinity again on a PC with I did set back (Basically blank WIn 7 System), but still same error? Any other idea?

**Comment by t00k** [comment]
Hey @maximus925 
These issues are usually when the warning havent been accepted on the Ledger itself. Or with Ledger Live and some other app conflicting, please try the steps below.

> If you see the warning for a split second but don't have the chance to confirm it on the Ledger, some program (like Trinity, Ledger Live, Browser) is running and accessing the ledger device, which should not be the case! Close everything and try again! If the message still disappears, you can try the following to be absolutely sure that nothing is interacting with the Ledger:
> 
> 

> - Plug the NanoS into a USB charger, for example for your phone, it can be anything that is not a computer
> 
> > 
> 
> - Enter your PIN and then start the IOTA application. You now see “WARNING!”
> 
> > 
> 
> - Scroll down. To do so press the right button 5 times until you see “for more info.” and two horizontal lines where the buttons are.
> 
> > 
> 
> - Click both buttons on the NanoS at the same time to show “IOTA”
> 
> > 
 
 So first make sure that you do not have Ledger Live och Trinity running when plugging in the Ledger. Then make sure to accept the warning on the Ledger itself. Otherwise try the steps provided.

**Comment by larthee** [comment]
@cvarley100 - now I updated my PC to WIN 10 and installed the latest trinity 0.6.0  -what can I say - still same error - I do NOT have any other app open and trinity still does show same error - how could I fix it? Appreciate your advice step by step... Thanks.
![trinity 0 6 0 auf WIN10](https://user-images.githubusercontent.com/51678212/59569146-bdbf6d00-9085-11e9-9da2-e9d406cf34c3.jpg)

**Comment by larthee** [comment]
Don's ask me why, but finally it worked on WIN 10 and funds are shown again. So this ticket could be closed. Thanks fro the advice so far.

**Comment by cvarley100** [comment]
Thanks for letting us know @larthee

**Comment by dthoeni** [comment]
I've had the same problem when sending funds. Running Trinity as administrator resolved the issue.
