### ISSUE TITLE
Trinity Desktop v0.6.0-RC2 wants quorum despite deactivation

### ISSUE THREAD

**Issue by no8ody** [iotaledger/trinity-wallet#1739]
### Bug description
In the trial version v0.6.0-RC2, Trinity wants to perform a quorum despite deactivating quorum.

### Environment Specs
Trinity is running on a windows 10 64bit

What build of Trinity are you running? Please provide the full version (you can find it in Settings 
v0.6.0-RC2

### Steps To Reproduce
1. Deactivate automatic node management
2. Deactivate remote node list
3. Deactivate quorum
4. Set own primary node

### Expected behaviour
If you want to interact with the node, Trinity tells you that a quorum is not possible and you should deactivate it (although already deactivated)

### Actual behaviour
If the quorum is deactivated, no corresponding error message should appear and no quorum should be performed.

### Errors
![quorum](https://user-images.githubusercontent.com/44928989/59198274-9eab7180-8b93-11e9-9410-65d7c84005e0.JPG)

**Comment by laumair** [comment]
@no8ody Thanks for reporting the issue. I'll try to reproduce the issue.

**Comment by laumair** [comment]
Reopening the issue as it still sometimes happen (on mobile) while sending transaction.

**Comment by cvarley100** [comment]
Fixed in 1.0.0
