### ISSUE TITLE
Can't change PoW setting to remote if on a node that does not support it

### ISSUE THREAD

**Issue by Noki** [iotaledger/trinity-wallet#1750]
### Bug description

Can't change PoW setting to remote if on a node that does not support it

![image](https://user-images.githubusercontent.com/198902/59268032-150baa80-8c4c-11e9-97a6-49aa0f9fbd5c.png)

### Environment Specs

- OS version: Windows 10
- Trinity version: 0.6.0-RC2

### Steps To Reproduce

Go to the advanced settings when connected to a node that does not support PoW and try to change the PoW setting to remote.

### Expected behaviour

Changing the setting is allowed and automatically forces the use of a node that supports PoW.

### Actual behaviour

The setting can't be changed unless you manually change the node first.

**Comment by cvarley100** [comment]
Hi @Noki, this is intended behaviour. We have plans to add remote PoW specific node selection however. See #1890

**Comment by cvarley100** [comment]
This will be fixed in 1.1.0.
