### ISSUE TITLE
I2P Integration

### ISSUE THREAD

**Issue by ghbjklhv** [iotaledger/trinity-wallet#1769]
**Goal**: I2P Integration into the IOTA Network
**Description**: Let's consider how to integrate and use I2P, possibly leveraging the work upstream.
**Why?**: IP anonymity is a huge issue. Users should feel safe that they are not giving away their location.

**Related Links/Projects**:
https://github.com/monero-project/kovri
https://www.wikipedia.org/wiki/I2P
https://github.com/Anoncoin/anoncoin

_______________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75435714-feature-i2p-integration)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75435714)](https://www.bountysource.com/issues/75435714-feature-i2p-integration)

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
