### ISSUE TITLE
Install the app on Kubuntu

### ISSUE THREAD

**Issue by Rude-Boy** [iotaledger/trinity-wallet#1784]
### Bug description
When opening the AppImage I am asked if I would ilke to integrate trinity-desktop-0.6.0.AppImage with my system. (see Dialog below)
But if i click "yes", no menu or icons have been added.

### Environment Specs

- OS version: Linux Kubuntu 19.04
- Trinity version: 0.6.0:

### Steps To Reproduce
1. open _trinity-desktop-0.6.0.AppImage_

### Expected behaviour
menu and icons are created

### Actual behaviour
menu and icons are not created

### Errors
Install - KDialog
Would you like to intefrate trinity-desktop-0.6.0.AppImage with your system?

This will add it to your applications menu and install icons.
If you don't do this you can still launch the application by double-clicking on the AppImage.

**Comment by rajivshah3** [comment]
Have you already installed [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher)?

**Comment by Rude-Boy** [comment]
Yeah, it works with AppImageLauncher. Thank you
