### ISSUE TITLE
Cannot progress past "Let's add a name" screen during seed import

### ISSUE THREAD

**Issue by p4ch1nk0** [iotaledger/trinity-wallet#1786]
### Bug description
Cannot progress past "Let's add a name" screen during seed import

### Environment Specs

- KDE Neon 5.16
- Trinity version: trinity-desktop-0.6.0.AppImage

### Steps To Reproduce
1. previously used trinity-desktop-0.4.6.AppImage
2. execute trinity-desktop-0.6.0.AppImage
3. select English (International) and click on Continue
4. select No, I have one
5. input a seed or import a seedvault file and click on Continue
6. enter an account name and click on Continue

### Expected behaviour
The wizard should accept the account name and progress to the next step when the user clicks on Continue

### Actual behaviour
Clicking on Continue does not progress to the next step

### Errors
![trinity screenshot](https://user-images.githubusercontent.com/8879587/59556979-a2783300-8f9b-11e9-8d55-76a5ed649b09.png)

**Comment by p4ch1nk0** [comment]
deleting Trinity from home/myusername/.config and relaunching allows me to manually type a seed and give it an account name, but it rejects the seedvault file password as invalid.

**Comment by rihardsgravis** [comment]
@p4ch1nk0 do I understand it correctly that you cannot import your seedvault file because it says Incorrect key for the seedvault file?
Could you try to open the seedvault file in a password manager like [Keepass](https://keepass.info/help/v2/setup.html#mono) to make sure you enter the correct password for the file?

**Comment by cvarley100** [comment]
@p4ch1nk0 Closing this one until further info is provided.
