### ISSUE TITLE
i dont see autopromotion working.

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#1788]
### Bug description
auto promote doesnt work 

### Environment Specs
What device are you running Trinity on?

pc , 
win 10
0.6.0

proof of work local

### Steps To Reproduce
1.  send tx to your own wallet
2. wait for hour
3. nothing happend 

### Expected behaviour
reattachements or promotions

### Actual behaviour
nothing

**Comment by rajivshah3** [comment]
Do you see anything in the error log?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/48189056/59570401-d59fec80-9097-11e9-90fb-932c37cfa692.png)

**Comment by rajivshah3** [comment]
“Too Many Requests” means you were rate limited and should change nodes. We plan to do that automatically in the future, see #1176

**Comment by ghost** [comment]
the problem is i dont see any reattachments.. on tangleexplorer.

is there a way to see api calls to node? somehow?.
when i manualy retry i can see reattachements.

i'm mostly worried about new users having their tx pending .. and don't understand it's probably some auto promote issue that does not always work propperly.

**Comment by laumair** [comment]
@wonkytonky2 What happens if you manually retry? Do you see reattachments or promotions then?

**Comment by ghost** [comment]
yes manualy i see reattachements happening if promotion fails on tangle explorer. 
 everyting works fine  if i do it manually

**Comment by laumair** [comment]
@wonkytonky2 Should be fixed with https://github.com/iotaledger/trinity-wallet/pull/1779.

**Comment by ghost** [comment]
cool thanks. i'll keep on testing with new release and update here

**Comment by laumair** [comment]
@wonkytonky2 Did you get a chance to test on the latest version?

**Comment by ghost** [comment]
not realy because network works pretty good now .  it's not pending anymore. i'll update issue when network gets slower  and i have to do auto promote

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/48189056/60091108-2375be00-9744-11e9-88fb-ffbbe9970c92.png)
same problem with latest desktop version. 
i dont see activity  for autopromotion. 
https://thetangle.org/bundle/IXYUTRJIJX9FXDLQXSKULDGYJNRKOCSYK9NKXJGZOXARETFIIFRQWJPMA9WCSUZ9ZGRCJDKQRK9KFYZQB

![image](https://user-images.githubusercontent.com/48189056/60091188-4ef8a880-9744-11e9-8703-40d4336ea4e5.png)
i turned  down everything and choose 1 node which seems ok .. 
still no reattach

**Comment by ghost** [comment]
did see reattachement. just had to wait a lot longer   got some error messages in error log  meanwhile (which came from promoting ) which is another issue
