### ISSUE TITLE
My Trinity Wallet balance is 0 after reset on my PC

### ISSUE THREAD

**Issue by awadhi3** [iotaledger/trinity-wallet#1790]
Hello there. 

I really need some help here. Recently i logged in to my trinity wallet on my MAC to send some IOTA, but i got error messages like your ledger wallet is not linked , or "missmatch". so i went ahead and downloaded the application on my PC and reset using my seed. I logged via my seed and now my balance is 0 ! im very worried guys, had good chunck of IOTA in my app .. kindly help me out.

**Comment by rajivshah3** [comment]
Hi, please see the #help channel in [Discord](https://discord.gg/fNGZXvh) for support
