### ISSUE TITLE
[Proposal] Node settings page

### ISSUE THREAD

**Issue by viossat** [iotaledger/trinity-wallet#1799]
### Description
This is a proposal to improve the UX of the new (0.6.0) node screen.
- Unhealthy nodes are shown with a warning icon.
- Nodes from the remote list are shown grayed out (not removable) but disappear from the list if the option is disabled.
- Quorum is made from the primary node and N-1 secondary nodes (N=quorum size).

![node-screen](https://user-images.githubusercontent.com/3019820/59626158-772c4a00-913b-11e9-9e75-761aa29b190c.png)

### Motivation
The first time I saw the new (0.6.0) node screen, I didn't find it understandable for regular users.
In my case, I wanted to connect my wallet to https://nodes.thetangle.org :
1. I clicked *Add custom nodes* and put the URL of the node
2. I clicked *Add Custom Node* and got an error "Duplicated node: The custom node is already listed.", I clicked *Back*
3. *"Oh, there is an enabled "Use remote node list" switch, my node is probably in that not visible remote list, let's disable that option first"*
4. I disable "Automatic node management" to be able to access the switch of that option, but I couldn't disable the remote node list: "No custom nodes: You must add at least one custom node before disabling the remote node list"
5. I asked for help on Discord, I had to disable "Primary node autoswitching" to get the remote node list displayed, where I could select the node

### Open Questions
- When "Automatic node management" is enabled, should the others options be hidden or just grayed out?
- Should multiple primary nodes be allowed?
- As Trinity requires HTTPS, should the "https://" be displayed? (especially on mobile where the width is limited)
- An *Options* button/menu may be required on mobile instead of the "Remove" and "Set primary" buttons

### Am I planning to do it myself with a PR?
No, sorry.

**Comment by cvarley100** [comment]
@viossat As we have a working system and other priorities, we may need to leave this one for V2. I'll update you if prioritisation changes.

**Comment by cvarley100** [comment]
#890 #891 #893 #895 closed issues are of relevance here

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
