### ISSUE TITLE
Desktop wallet launches with blank screen

### ISSUE THREAD

**Issue by DevTore** [iotaledger/trinity-wallet#1815]
### Bug description
No graphic on the screen after launching app

### Hardware Spec
MacBook Pro

### Expected behaviour
1. White Trinity/ IOTA logo appears and disappears on a dark blue background
2. login window etc is displayed

### Actual behaviour
1. White Trinity/ IOTA logo appears and disappears on a dark blue background
2. Display continues to show dark blue background only (no login window, etc.)

### Errors

![image](https://user-images.githubusercontent.com/42974518/59706199-f8ccb800-91cd-11e9-9eed-61a539275ffa.png)

<img width="1436" alt="Screen Shot 2019-06-18 at 1 34 47 PM" src="https://user-images.githubusercontent.com/42974518/59706336-46492500-91ce-11e9-852d-8e1ae1a95170.png">

**Comment by t00k** [comment]
If you updated from a really old version, try downloading 0.4.6 (find it on releases for this github) and run it, then update from 0.4.6 to the latest version. Make sure to have your seeds backed up.

**Comment by laumair** [comment]
@DevTore Did you update the wallet from a previous version?

**Comment by DevTore** [comment]
I downloaded the latest version and replaced the old version. After opening the new version, there was just a dark blue screen after the iota symbol had disappeared. I tried different things, such as
- clicking the “check for newest version” in the drop down menu, but received the message that I already have the latest version
- Downloading the newest version (from the IOTA Trinity download page as well as directly from Github) and replacing, with the same result
- restarting computer and repeating steps above, with the same result

Since the Trinity app only shows dark blue, there is nowhere to enter the seed.

**Comment by laumair** [comment]
@DevTore Do you (by any chance) remember the older version number of the application you were using?

**Comment by DevTore** [comment]
Unfortunately, I do not know the older version number of the application.
However, I followed @t00k advise to download and install v04.6. When I ran it, my MIOTA balance also displayed correctly.
Subsequently, I used the scroll down menu "Look for updates" and let the application automatically update to the latest version, which worked.
BUT, when entering my password, a 'Data migration' screen appeared, with the message:
"Something went wrong - There was a problem migrating your data. Please try again"
AND the following message: 
"Due to performance and storage limitations, Trinity is using a new database for storing settings and account data. Please wait while Trinity automatically migrates your existing data."
Two option buttons are displayed underneath: 'Change Node' and 'Retry'
When clicking the 'Retry' button, the "Something went wrong..." message appeared again.

**Comment by laumair** [comment]
@DevTore Thank you for the detailed information. I will investigate and fix it.

**Comment by DevTore** [comment]
Thank you @laumair and @t00k for trying to solve the issue. Unfortunately, there is yet another PROBLEM:
1) I installed the newest Trinity Wallet version for mac (v0.6.2), which is now showing the password input field
2) However, when typing in my password, I now receive the error message "Unrecognizable password"
3) 2 days ago, I followed @t00k advise to download v0.4.6, which showed my correct MIOTA balance. Therefore, I today again tried to install v0.4.6, but now this version also gave me the error message "Unrecognizable password"
4) I then from the app upgraded to the latest version, which also produced the error message when entering my password
