### ISSUE TITLE
Trinity makes use of unmaintained iota.lib.js

### ISSUE THREAD

**Issue by sachushaji** [iotaledger/trinity-wallet#1816]
### Description
The trinity wallet extensively makes use of iota.lib.js which is unmaintained currently.

### Motivation
The @iota/core is the latest version so in order to get the latest features, iota.lib.js should be replaced.

### Requirements
- The libs which are used to interact with iota mainnet should be ported to the latest iota library.
- Main changes would be here /src/shared/libs/*

### Open Questions
Are there any reasons why @iota/core is not been used instead at present?

### Am I planning to do it myself with a PR?
No

**Comment by laumair** [comment]
@sachushaji Thank you reporting this. 

We do know about the usage of [older](https://github.com/iotaledger/iota.js/tree/develop) version of [iota.js](https://github.com/iotaledger/iota.js). Plan is to move to the latest version in near future. 

Btw, we do use [@iota/core](https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/libs/iota/extendedApi.js#L8) but haven't fully updated it's usage across all areas in the application.

**Comment by sachushaji** [comment]
Closing as trinity is deprecated
