### ISSUE TITLE
Does not work on Ubuntu

### ISSUE THREAD

**Issue by pmatulis** [iotaledger/trinity-wallet#1846]
The wallet (at least `v.0.6.0`) does not work on Ubuntu 16.04 LTS (amd64). The application simply does not open.

**Comment by rajivshah3** [comment]
@pmatulis can you try the latest build that was just released?

**Comment by pmatulis** [comment]
@rajivshah3 Tried it. No change. If I provide an strace output will that leak private information?

**Comment by rajivshah3** [comment]
@pmatulis it shouldn’t, but could you check it and redact it appropriately just to make sure?

**Comment by pmatulis** [comment]
@rajivshah3 Heh, well it's many pages long.

**Comment by rajivshah3** [comment]
Could you post the first few lines?

**Comment by pmatulis** [comment]
Sure. Shall I remove ~/.config/Trinity first? It gets created on first "run".

**Comment by cvarley100** [comment]
Can you try with v1.0.0 after removing your config folder @pmatulis ? And have you enabled run as executable on the app image?

**Comment by pmatulis** [comment]
@cvarley100 Yes, v.1.0.0 opens on my Ubuntu 18.04 system. However, I'm stuck at step "Choose your  Ledger account index", which seems to be related to issue #589.

**Comment by rajivshah3** [comment]
Is the issue still occurring after you set up the udev rules?

**Comment by pmatulis** [comment]
After trying a few times I was able to access my coins. I'm currently trying to send a small amount to an exchange. The transaction has stayed in a pending state overnight. I guess I'll open a separate issue for that.

**Comment by cvarley100** [comment]
@pmatulis That one's just a networking issue. Find the transaction in your history, click on it, and hit retry. Also make sure `autopromotion` is turned on in your advanced settings.

Glad you were able to access the wallet.
