### ISSUE TITLE
Theme gets reset to Default after opening Trinity again

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1857]
### Bug description
After Trinity gets fully closed and opened again the theme I set got reset to `Default`. In my example I set the theme to`Ionic` before.

### Environment Specs
- OS version: MacOS 10.14.5

- Trinity version: 0.6.2

### Steps To Reproduce
1. set a different them in the settings
2. fully close Trinity and open it again

### Expected behaviour
The same theme as before the restart should be set.

### Actual behaviour
Theme is set to `Default` again.

**Comment by rajivshah3** [comment]
I can't seem to reproduce this on Trinity Desktop v0.6.2 on macOS 10.14.6 Beta (18G48f)

**Comment by KiwiCat123** [comment]
@rajivshah3 it happened only on that new 0.6.2 animations version

**Comment by rajivshah3** [comment]
Ooh ok, I'll try that one

**Comment by rajivshah3** [comment]
Yep, I can reproduce it on that build

**Comment by rihardsgravis** [comment]
Fixed in 29ce68642
