### ISSUE TITLE
Address reuse possible with pending tx following wallet reset

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#1858]
### Bug description
https://thetangle.org/address/BNWATFGSEYMBXPAETS9ECDIJLOJTOZRXLSTIC9OPBDKRTZZGODOEBOEXUWVGTADTIUECTIEMXRSJECKT9
![image](https://user-images.githubusercontent.com/48189056/59953502-ac5cd300-9480-11e9-8a24-90c94a7ed82a.png)

![image](https://user-images.githubusercontent.com/48189056/59953536-d4e4cd00-9480-11e9-88a3-84e70e78cb74.png)

my tx was pending . i tried to reattach a few times but didnt seem to work
so i tried to "reset" the wallet trough tools same problem still
so i removed  trinity completely  and added seed again.
then i could create a new tx althoug the old pending one was still there 

### Environment Specs
What device are you running Trinity on?

win 10 in vmware 
trinity 0.6.1

### Steps To Reproduce
on request i can give seed in private message . so ppl don't start spamming it 

### Expected behaviour
no  reuse of  address

### Actual behaviour
reuse of address

### Errors
no log anymore

**Comment by Thoralf-M** [comment]
Do you know what node you were connected to?

**Comment by ghost** [comment]
nope  it did have node connection issues at the time though i swictched trough a few

**Comment by laumair** [comment]
@wonkytonky2 Was the (pending) transaction in your wallet when you made an attempt to send transaction after resetting your wallet?

**Comment by ghost** [comment]
yes, that was what worries me

**Comment by laumair** [comment]
@wonkytonky2 Can you please share the state of the wallet with me on [Discord](https://discordapp.com/invite/fNGZXvh)?

**Comment by cvarley100** [comment]
Unable to reproduce.
