### ISSUE TITLE
Trinity stalls forever before any screen appears

### ISSUE THREAD

**Issue by yotardis** [iotaledger/trinity-wallet#1860]
### Bug description
Launching trinity after install. Stays stuck forever without displaying anything. Well, I didn't wait "forever" since I have a life but 30 mn without any trinity screen should be enough to be worried ^^

### Environment Specs
Windows 7 Pro 64 bit

What build of Trinity are you running? Please provide the full version (you can find it in Settings 
. First saw this with 0.6.1, didn't report at the time hoping next build would fix this, but it's still the same with 0.6.2, last working build for me was 0.5.2

### Steps To Reproduce
1. well, launch trinity. That's it :)

### Expected behaviour
see login screen, or any other screen with info at the very least

### Actual behaviour
nothing

### Errors
since there's nothing appearing, I'm not sure what I can attach. I can give you the processes listed on launch and staying there, not sure that helps…
![Image 003](https://user-images.githubusercontent.com/42700319/59960966-e5249880-94d0-11e9-9973-f1810d61d12f.png)

**Comment by rajivshah3** [comment]
Can you post a screenshot of the list of files in this folder? `C:\Users\your-username\AppData\Roaming\Trinity`

**Comment by yotardis** [comment]
here you go : 
![Image 001](https://user-images.githubusercontent.com/42700319/60438490-127bef80-9c11-11e9-8daf-f04c4d48f830.png)

. lockfile appears only during launch
. blob_storage folder is "updated" (well, modified date at least is updated) at each launch, but without content apart from some empty alphanumeric subfolder

**Comment by rihardsgravis** [comment]
@yotardis could you, please, check that you download Windows 7 release and not Windows 10?
At https://github.com/iotaledger/trinity-wallet/releases/tag/desktop-1.0.0 Windows 7 release installation file is named `trinity-desktop-*win7-1.0.0.exe`

**Comment by bnmko** [comment]
I had the same issue. Installing trinity-desktop-*win7-1.0.0.exe over the existing one (not a clean install) has solved the problem for me. 

The initial version I installed was trinity-desktop-win7-0.5.1.exe. After that trinity made one or two updates without a problem. The issue also appeared after an update but I didn't notice which version it was.

**Comment by cvarley100** [comment]
@yotardis Closing for now. Let us know if Rihards' suggestion does not fix the issue.

**Comment by yotardis** [comment]
great,  since you apparently threw windows 7 out of the window after 1.4, I'm now stuck with an "upgrade" that stalls my wallet, I guess I'll have to install a mobile one to get out of this mess...

**Comment by cvarley100** [comment]
@yotardis We took the reasonable decision to discontinue support for Windows 7 when Microsoft did. It is not a good idea to run a cryptocurrency wallet on an OS that will have no security updates.
