### ISSUE TITLE
Not able to restore Ledger index over 999

### ISSUE THREAD

**Issue by t00k** [iotaledger/trinity-wallet#1875]
### Bug description
When trying to restore from a Ledger index higher than 999, Trinity automatically changes the index to 999.

### Environment Specs
Windows 10,
Trinity desktop 0.6.2

### Steps To Reproduce
1. Add new account
2. Restore an existing Ledger account
3. Input anything with 4 digits, like 5555

### Expected behaviour
Trinity should accept the index above 999.

### Actual behaviour
Trinity automatically changes the index back to 999.

**Comment by rajivshah3** [comment]
@rihardsgravis it looks like [this change](https://github.com/iotaledger/trinity-wallet/commit/949fc05ecddb8603f444afab77279d318ab048e7#diff-3e6e1c0c0f3439f897418a4e463888e7R65) caused this issue

**Comment by rajivshah3** [comment]
@t00k for a workaround, I think versions before 0.6.0 should allow any value. You could try moving funds to a new account on a lower index using one of those versions
