### ISSUE TITLE
Price quoting in Trinity  is the wrong way around.

### ISSUE THREAD

**Issue by IOTASwiss** [iotaledger/trinity-wallet#1885]
In the pricing section on the Trinity Desktop it says BTC/iota but the price is in Satoshis. So as it is displayed  right now BTC is the base currency and Iota is the quoting currency but it’s quoted in Satoshis. So if we want to continue to price it in sats (which I guess we all want since its the most common form) it should read Iota/btc. Same goes for eth and USD.  For example: USD/IOTA means how many iotas do I need to get 1$ (answer:2.44) but we want the other way around 1 IOTA is worth 0.41$ that’s whhy it should read IOTA/USD

**Comment by rajivshah3** [comment]
If anyone wants to work on this issue, the only things that needs to be changed are these lines:

https://github.com/iotaledger/trinity-wallet/blob/03fe134a868210b75f67121263f8b8dfb36a5d90/src/desktop/src/ui/components/Chart.js#L81

https://github.com/iotaledger/trinity-wallet/blob/03fe134a868210b75f67121263f8b8dfb36a5d90/src/desktop/__tests__/ui/components/chart.test.jsx#L41
