### ISSUE TITLE
Trinity laggy on win7

### ISSUE THREAD

**Issue by DeathDragonAW** [iotaledger/trinity-wallet#1888]
### Bug description
Trinity is always running very laggy for me since version 0.6, had a look on my RAM usage and it is jumping in the range of about 150M to 2G.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Me
- Model: Mainboard X79A-GD45 Plus, CPU Xeon E5-1620V2, RAM 16GB G.Skill RipJawsZ DDR3-1866 DIMM CL8 Quad Kit 
- OS version: Win7 Pro 64Bit up to date

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v0.6.2 BETA

P.S.: I talked to a discord-mod about this and he said he also had this problem while he has been using trinity on win7 with seeds that have a large number of transactions (100+) which also applies on me
![Unbenannt2](https://user-images.githubusercontent.com/52355057/60386836-d1fa6580-9a9a-11e9-9878-6da62598f595.png)

**Comment by t00k** [comment]
I, (the mod he talked to) also had this issue on Windows 7, but only with seeds that contained a lot of history, + 100 transactions. After resetting wallet and importing without history the issue dissapeared. Maybe some memory leak, or updating when it shouldnt in the background?

**Comment by rajivshah3** [comment]
> Maybe some memory leak, or updating when it shouldnt in the background?

That could be the case. Another possible cause might be that it's rendering all of the transactions in the history window - even ones that aren't visible to the user (until they scroll up/down)

**Comment by f-ben** [comment]
I myself had the same problem on Windows 10 too. After deleting trinity, deleting appdata\trinity, reinstalling and setting up my account (with the same seed) everything works fine again.

**Comment by laumair** [comment]
@rajivshah3 I think this could be related to the duplicate objects in realm. 

https://github.com/iotaledger/trinity-wallet/pull/1609

**Comment by DeathDragonAW** [comment]
No change after update to 1.0.0

**Comment by DeathDragonAW** [comment]
> I myself had the same problem on Windows 10 too. After deleting trinity, deleting appdata\trinity, reinstalling and setting up my account (with the same seed) everything works fine again.

Already did this twice in the meantime.

**Comment by cvarley100** [comment]
@DeathDragonAW If you delete your Trinity folder in app data and set up fresh can you let us know if you still experience lag?

**Comment by DeathDragonAW** [comment]
![Unbenannt](https://user-images.githubusercontent.com/52355057/61330395-c68b9600-a81f-11e9-88da-6d51ee06f363.png)
recieved this error today with v1.0.0

**Comment by cvarley100** [comment]
We are no longer continuing to support Windows 7 as of today.

See: https://support.microsoft.com/en-gb/help/4057281/windows-7-support-will-end-on-january-14-2020
