### ISSUE TITLE
Not able to enable auto-promotion when using autonodemanagement, gets error about Remote PoW.

### ISSUE THREAD

**Issue by t00k** [iotaledger/trinity-wallet#1889]
### Bug description
I am not able to use auto-promotion when using automatic node management. When I try to slide the auto-promotion to Enable, it gives me an error about Remote PoW not supported on the nodes. Either the button mapping is wrong, or some other bug.

### Environment Specs
What device are you running Trinity on?

- OS version: Windows 10
- Trinity version: 0.6.2

### Steps To Reproduce
1. Change node settings to automatic.
2. Go to advanced settings
3. Try to enable auto-promotion

### Expected behaviour
Trinity should enable auto-promotion.

### Actual behaviour
Gets an error about "Remote Proof of Work is unavailable".

![remotepow](https://user-images.githubusercontent.com/49842330/60401059-67b9f180-9b7c-11e9-8fc5-df1e3f3d091e.png)

* Thanks to Sergey-Q for finding it!

**Comment by rajivshah3** [comment]
Related to #1750 . We might be able to fix this by implementing #1890 so that a node that supports PoW will be used for attachToTangle calls, but the original node will still be used for everything else.

**Comment by cvarley100** [comment]
@t00k This is because under auto-node management we select nodes.iota.org by default and this cluster does not allow remote PoW. We will be adding remote PoW specific node selection however. See #1890.
