### ISSUE TITLE
Add possibility to use a specific node for PoW

### ISSUE THREAD

**Issue by muXxer** [iotaledger/trinity-wallet#1890]
### Description
It would be a nice feature, if you could choose a specific node for all remote "attachToTangle" calls.  

### Motivation
This way you could use a smaller node like Raspberry Pi 4 for the quorum, and the heavy PoW could be done by a stronger server, or an external service like powsrv or thetangle.buisness.  

### Requirements 
Add a setting for specific PoW node.  

### Am I planning to do it myself with a PR?
No

**Comment by cvarley100** [comment]
@laumair Relevant monkey patch for iota.lib.js: https://github.com/iotaledger/curl-remote

**Comment by rajivshah3** [comment]
[This line](https://github.com/iotaledger/curl-remote/blob/313990b946fbb6a7e96998611b6ea9f10625f401/index.js#L3) may need to be removed so that the packager doesn't try to look for `node-fetch`. I think we can safely assume that `fetch` is defined in both RN and Electron

**Comment by muXxer** [comment]
I think it is easier to just use another IOTA API object with another address for the remote pow [here](https://github.com/iotaledger/trinity-wallet/blob/7e7d092b41d9b7c6dce6db014f3fb7b523efed20/src/shared/libs/iota/extendedApi.js#L515)

**Comment by alexsporn** [comment]
Or let the nodesConfigurationFactory return only the configured remote pow node when `useOnlyPowNodes` is `true`, that way it will get passed to attachToTangleAsync correctly during a transfer
