### ISSUE TITLE
Problem with IOTA Balance in Trinity

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#1898]
Hi,

i updated the Trinity Wallet and i didn't see my Balance.
I have restored my "account" and put the seed + ledger.

via a Snapshot i would like to restore my balance, but i didn't found anything..

Can someone help me please?

**Comment by rajivshah3** [comment]
Hi, have you tried asking on the #help channel in Discord?

**Comment by ghost** [comment]
Hi,
where i can find this chat?
Can you please send me an url?

**Comment by Thoralf-M** [comment]
https://discord.iota.org/
if you are on the server https://discordapp.com/channels/397872799483428865/398499876935303186
