### ISSUE TITLE
promtion Error: Transaction is inconsistent. Reason: tails are not solid (missing a referenced tx): AESMZXXM9ENPEEFBCNJCFMPLFK9BDIREFOVSLCDXRAREKAZKBVAYJGRONSTSEEBAIEPRJKNEIUYJ99999

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#1900]
### Bug description

Error: Transaction is inconsistent. Reason: tails are not solid (missing a referenced tx): AESMZXXM9ENPEEFBCNJCFMPLFK9BDIREFOVSLCDXRAREKAZKBVAYJGRONSTSEEBAIEPRJKNEIUYJ99999
i get this kind of errror message everyt time i try to promote.
once enough time has passed it does a reattch  
eventually the tx get confirmed but this error message in promotions is realy confusing 

seems to be related to promotion.  
### Environment Specs
What device are you running Trinity on?
win 10 
1.0 latest version

### Steps To Reproduce

create a tx (0 value is fine )   try to promote it

### Expected behaviour
not always getting an error 

### Actual behaviour
always getting an error

### Errors
Error: Transaction is inconsistent. Reason: tails are not solid (missing a referenced tx): AESMZXXM9ENPEEFBCNJCFMPLFK9BDIREFOVSLCDXRAREKAZKBVAYJGRONSTSEEBAIEPRJKNEIUYJ99999

**Comment by rajivshah3** [comment]
@laumair is this an IRI issue?

**Comment by ghost** [comment]
look like it i get the same issue trough https://thetangle.org when i use promote
i should open issue on iri github? or can you reference it there?

**Comment by cvarley100** [comment]
@GalRogozinski You able to take a look at this one?

**Comment by GalRogozinski** [comment]
@laumair can it be because of quorum?

**Comment by jakubcech** [comment]
Can we transfer the issue if it's indeed an IRI issue?

**Comment by GalRogozinski** [comment]
not yet, but maybe later

**Comment by GalRogozinski** [comment]
@cvarley100 
@laumair 

I just tried to reproduce the bug but I couldn't :-(
If you guys want my help we can do one of two things:
1. Try to set a meeting where we reproduce it together
2. Go over the promotion code in trinity together

**Comment by laumair** [comment]
@GalRogozinski 

No, it cannot be because of quorum. Quorum is only run on `getBalances` and `wereAddressesSpentFrom`. Rest of the endpoints are consumed from a single node. 

The frequency of this error occurring has decreased quite a lot now. I cannot seem to reproduce this. Perhaps it is because of the new IRI [release](https://github.com/iotaledger/iri/releases/tag/v1.8.0-RELEASE)?

**Comment by ghost** [comment]
i still get error logs :  Transaction is inconsistent. Reason: tails are not solid (missing a referenced tx): BOGWGPUBQWMGJDBFTPGJJMBRRSVAAWHUYIJCBUB9EZPV9ODHWSFDWQZVWDGPHTHSNBZPHBBFIUOJA9999
 Transaction is inconsistent. Reason: tails are not solid (missing a referenced tx): BOGWGPUBQWMGJDBFTPGJJMBRRSVAAWHUYIJCBUB9EZPV9ODHWSFDWQZVWDGPHTHSNBZPHBBFIUOJA9999
 Transaction is inconsistent. Reason: tails are not solid (missing a referenced tx): BOGWGPUBQWMGJDBFTPGJJMBRRSVAAWHUYIJCBUB9EZPV9ODHWSFDWQZVWDGPHTHSNBZPHBBFIUOJA9999
 Transaction is inconsistent. Reason: tails are not solid (missing a referenced tx): BOGWGPUBQWMGJDBFTPGJJMBRRSVAAWHUYIJCBUB9EZPV9ODHWSFDWQZVWDGPHTHSNBZPHBBFIUOJA9999
 Transaction is inconsistent. Reason: tails are not solid (missing a referenced tx): BOGWGPUBQWMGJDBFTPGJJMBRRSVAAWHUYIJCBUB9EZPV9ODHWSFDWQZVWDGPHTHSNBZPHBBFIUOJA9999


but the promotion did work. since new  iri

**Comment by laumair** [comment]
@wonkytonky2 Are these error logs new?

**Comment by laumair** [comment]
@GalRogozinski May I ask how you tried to reproduce the issue? Trinity promotion/reattachment is similar to [this](https://github.com/iotaledger/tangle-tools/blob/master/promoter/promoter/promoter.js) implementation.

**Comment by ghost** [comment]
yes these logs are new

![image](https://user-images.githubusercontent.com/48189056/61530272-e4c1e380-aa23-11e9-9133-8a4d797de5b6.png)

**Comment by rajivshah3** [comment]
I saw similar errors on thetangle.org yesterday or the day before

**Comment by GalRogozinski** [comment]
@laumair 
I initiated a transfer on trinity using the default configs (because no others were given in the description) several times, and attempted a promotion with the UI before confirmation

@wonkytonky2 
Do you see those errors consistently, often, sometimes, or rarely?

**Comment by GalRogozinski** [comment]
After conversing with @laumair we now have a theory that the problem relates to using a load balancer.
A transaction can be solid in one node but not solid in the others.

**Comment by cvarley100** [comment]
Resolved for the most part in #2486.
