### ISSUE TITLE
Trinity minimizes when using finger print to confirm a transaction 

### ISSUE THREAD

**Issue by ratiodep** [iotaledger/trinity-wallet#1901]
Trinity 1.0
Huawei P20 Pro 
Android 8.1

When I try to confirm a transaction with the finger print authentication Trinity minimizes  instead of confirming the transaction.

Tried it several times

**Comment by ratiodep** [comment]
Worked again after I closed Trinity completely and started again.

Could be a Huawei behavior, energy saving or so...

**Comment by cvarley100** [comment]
@ratiodep Did you have low power mode active when you experienced this?

**Comment by cvarley100** [comment]
Cannot reproduce.
