### ISSUE TITLE
Receive QR-Code not showing iOS

### ISSUE THREAD

**Issue by brunnerm4x** [iotaledger/trinity-wallet#1909]
After generating a receive Address, the trinity app does not show the QR-Code (just a black square). 
Device: iPhone 5s, iOS 12.3.1
Trinity Release Version

I have seen this behavior in trinity before, but I thought it would be because of wrong configuration after many updates in beta. 
I have now deleted the app completely, restarted the device and after that reinstalled current version of trinity; also created new account/seed and set up everything from zero. Still it does not show the QR-Code (address generation works fine, it does show a new address). 
Maybe some sort of scaling issue because of small screen of old iPhone?

**Comment by KiwiCat123** [comment]
I can confirm this on 1.0.0(79)
![IMG_0001](https://user-images.githubusercontent.com/21984138/60587935-feadc600-9d95-11e9-8fc8-d30206ba2930.PNG)

**Comment by rajivshah3** [comment]
@KiwiCat123 which device are you using?

**Comment by rajivshah3** [comment]
I can't reproduce this on an iPhone 6S, iOS 13 (17A5508m)

**Comment by KiwiCat123** [comment]
@rajivshah3 only had this on my iPhone 5S iOS 12.2

**Comment by cvarley100** [comment]
Cannot reproduce.
