### ISSUE TITLE
Automatic node management resets quorum size to 4

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#1915]
### Bug description
I changed the quorum size to `2` for example. The default size should be `3`. When I disable and enable quorum the size gets reset to 3 as expected but when I enable `Automatic node management` again is got reset to 4 instead of 3.

### Environment Specs
- OS version: iOS 12.1.1
- Trinity version: 1.0.0 (79)

### Steps To Reproduce
1. change quorum size
2. enable `Automatic node management`

### Expected behaviour
Quorum size should be changed to 3.

### Actual behaviour
gets changed to 4

**Comment by rihardsgravis** [comment]
Fixed in #1891
