### ISSUE TITLE
Ledger nano receiving address not show

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#1923]
### Bug description
After hitting receive in Trinity desktop, the address is shown for a few frames before the wallet stops displaying the address. Ledger nano X does not indicate that addresses are being generated while trinity is generating a new address.

### Environment Specs

- OS version: Win10
- HW Wallet: Ledger nano X
- Ledger firmware version: 1.2.4-1
- Ledger IOTA app version: 0.5.3

- Trinity version: Desktop 1.0.0

### Steps To Reproduce
1. connect and unlock Ledger nano
2. ask trinity to generate receiving address for ledger account.
3. Trinity does not give user receiving address

### Expected behavior
Trinity should give user receiving address

### Actual behavior
Trinity does not give user receiving address

### Errors
https://streamable.com/8c0vo

**Comment by cvarley100** [comment]
@SleepingFox88 Is there anything you can think of about your specific situation that might be causing these issues? It seems that this is not a widespread issue.

**Comment by cvarley100** [comment]
Closing to a single issue as they are likely all related
