### ISSUE TITLE
Ledger Nano not recognized as connected

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#1924]
### Bug description
Trinity does not realize that Ledger Nano is connected and unlocked. This caused Ledger Nano accounts to not be able to send or receive

### Environment Specs

- OS version: Win10
- HW Wallet: Ledger nano X
- Ledger firmware version: 1.2.4-1
- Ledger IOTA app version: 0.5.3

- Trinity version: Desktop 1.0.0

### Steps To Reproduce
1. connect and unlock Ledger HW wallet
2. attempt to generate receiving address of Ledger account.
3. Trinity will not detect the Ledger as connected and not allow the generation and displaying of the account's receiving address.

### Expected behavior
Trinity should display Ledger accounts Receiving address.

### Actual behavior
Trinity does not display Ledger accounts Receiving address.

### Errors
https://i.imgur.com/ug0C4gO.png

**Comment by sloganking** [comment]
This issue is probably related to #1925

**Comment by cvarley100** [comment]
Closing to a single issue as they are likely all related
