### ISSUE TITLE
Allow multiple account creation per seed

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#1926]
### Description
Keep the Trinity wallet's ability to handle multiple seeds, but allow users to create multiple accounts per seed. This will maintain backwards compatibility with how seeds and accounts are handled currently, while simplifying the account creation process for the user.

This feature request aims to supersede #790 by achieving the same benefits while also allowing for backwards compatibility with how multiple seeds can currently be stored in Trinity.

### Motivation
Most wallets add accounts so that one user is to able to better allocate their funds towards different goals. Seeing this, it makes no sense to require the creation and storage of a new seed every time the user wants to create a new account.

Ultimately this change will:
- Make account creation much more user friendly
- Make account creation a much faster task
- Lower the amount of seeds that users need to keep up with
- Maintain backwards compatibility with how Trinity currently allows the storage of multiple seeds

2:00 [Example of Trinity account creation now](https://streamable.com/q1vu9)
0:09 [Example of how fast and simple it could be](https://streamable.com/2spvd)

### Requirements
- The current process undergone [after pressing "add new account"](https://i.imgur.com/a0OoMYw.png)  will be replaced with a screen that prompts the user to enter a name for their new account.
- After entering a name and confirming they want to continue, the accounts seed will be generated from combining the master seed with the new account's index. Similarly to how account creation is already done on the Ledger Nano S. 
- The index generation should he handled automatically by trinity and users should not have to remember indexes to recover their accounts.
- The user will then be re-directed to the Trinity home page where their new account will show up as an option to receive and send funds from.
- A separate "add new seed" option will still be available somewhere in the wallet.
-  If a seed has multiple accounts, accounts may be presented as children of their seed. These could be displayed in an orientation [similar to bullet points](https://i.imgur.com/Oeqdjju.png) or similarly to how Trinity already displays options as grouped [under a title in Trinity settings](https://i.imgur.com/0GHwpry.png)

### Open Questions
- Due to snapshots and the inability for Trinity to ask nodes for a full transaction history, account recovery from one seed may acquire additional complexity from this change when compared to other cryptocurrencies. How to go about that is still open for debate. It might be sufficient to have users remember / save the largest account index they ever generated and store that with the associated seed.

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
This will likely be a core feature in V2 planning.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
