### ISSUE TITLE
Ledger Nano X Bluetooth Support

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/trinity-wallet#1932]
### Description
Trinity Desktop currently supports Ledger Nano X via USB. We need to add support for both desktop and mobile via bluetooth.

Relevant deps: 
https://github.com/LedgerHQ/ledgerjs/tree/master/packages/react-native-hw-transport-ble
https://github.com/LedgerHQ/ledgerjs/tree/master/packages/hw-transport-node-ble

### Motivation
Many users have Nano Xs.

cc @TylerHann

**Comment by rajivshah3** [comment]
Android support requires a new version of JavaScriptCore which will be added in #2012

**Comment by alexsporn** [comment]
any updates on this?

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.

**Comment by ilbertt** [comment]
any updates?
