### ISSUE TITLE
Add tooltip to certain settings to explain what they do

### ISSUE THREAD

**Issue by t00k** [iotaledger/trinity-wallet#1933]
### Description
A lot of the settings in Trinity can be somewhat techie, and hard to understand for grandmas on crack. So having a tooltip (?) explaining what the functions are could be a great improvement. 

### Motivation
There are a lot of questions on Discord on what certain stuff means, mostly around the node management. Having a tooltip around the different settings and explaining them in easy-to-understand terms will help people understand what it does.

### Requirements
Make it easier for grandmas on crack to understand what certain settings does.

### Am I planning to do it myself with a PR?
No

![tooltip](https://user-images.githubusercontent.com/49842330/60680363-511cde80-9e8b-11e9-8b56-533d264be6d7.png)

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
