### ISSUE TITLE
Getting "Trinity is performing another function. Please wait and try again" error message while trying to change account name.

### ISSUE THREAD

**Issue by aayush** [iotaledger/trinity-wallet#1938]
### Bug description
Getting "Trinity is performing another function. Please wait and try again" error message while trying to 
- change account name.
- add new seed

### Environment Specs
Android 7.0

- Manufacturer:
- Model:
- OS version:

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version:
v 1.0.0(79)

### Steps To Reproduce
1. Log in to trinity 
2. Go to settings->account management -> edit account name
3. You will see that error message

i tried killing that app and logging in several times 
still seeing same error.
![Screenshot_20190704-132714](https://user-images.githubusercontent.com/181183/60688606-1c009400-9e6b-11e9-85ed-a23a2663a423.png)

### Expected behaviour
Should be able to change account name

### Actual behaviour
Shows error message as described above

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

**Comment by rajivshah3** [comment]
Have you tried waiting a few minutes and then seeing if you're able to change the account name?

**Comment by aayush** [comment]
I tried waiting 5 to 10 min.. Didn't work... I killed the app after that,
logged in,  and just after logging in I tried to rename again. Still I got
that error.

AxP

**Comment by cvarley100** [comment]
It is likely that the nodes you are connected to are taking a long time to complete network requests. If you try disabling/reducing quorum it should help alleviate the issue.
