### ISSUE TITLE
Nano S app is not recognized as open

### ISSUE THREAD

**Issue by Digimon-pl** [iotaledger/trinity-wallet#1950]
### Bug description
Installed Trinity 1.0.0 and Iota App on Ledger Nano S. Yesterday 4.07 worked fine for the first time. The balance was not 0, was waiting for incoming transaction from Binance.
After Trinity closure and reopening no possibility to connect. 

If the Iota app is not open - Trinity recognizes it and asks to open the Iota App
If the Iota app is open - Trinity still cannot connect
What is more, the error log shows some "transactions" with closed Wallet and mentions "0 balance" (printscreen)
![Zrzut ekranu 2019-07-5 o 12 06 33](https://user-images.githubusercontent.com/52566801/60715571-9a1d7300-9f1d-11e9-8fa8-4fe9bbc800c8.png)

Messages : impossible to connect, try another server or disable Proxy. 
Tried different servers, disabled Proxy, reinstalled both Trinity and Iota App. 
Nothing helps

### Environment Specs
OS version: Mac OS Mojave 10.14.5

HW Wallet: Ledger nano S

Ledger firmware version: 1.5.5 MCU 1.7

Ledger IOTA app version: 0.4.2

Trinity version: Desktop 1.0.0

### Steps reproduced
Tried different servers
Disabled proxy
Reinstalled the Trinity Desktop
Reinstalled Iota App in Nano S

### Expected behaviour
Trinity should connect via Ledger Nano S

### Actual behaviour
Trinity should connect via Ledger Nano S

### Errors
Printscreen
![Zrzut ekranu 2019-07-5 o 11 48 17](https://user-images.githubusercontent.com/52566801/60715125-9ccb9880-9f1c-11e9-891b-7e15babfc4ee.png)

**Comment by rihardsgravis** [comment]
`App has not been initialized by user` error means, you have not accepted the IOTA app warning on the Ledger device. Please, follow this tutorial to do that https://trinity.iota.org/help/ledger/

**Comment by Digimon-pl** [comment]
Thanks it helped :) Somehow arrived to quickly accept the terms. Arcade game ON ;)
