### ISSUE TITLE
Cannot create Ledger account

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#1952]
### Bug description
Cannot create Ledger based account because Trinity does not recognize Ledger as connected.

### Environment Specs

- OS version: Win10
- Trinity version: Desktop 1.0.0
- Ledger: nano S

### Steps To Reproduce
1. Attempt to create new account
2. Get asked to generate or restore an existing seed instead of prompted to create new Ledger account, because Trinity does not recognize Ledger was connected.

### Expected behavior
Trinity should detect Ledger is connected

### Actual behavior
Trinity does not detect that Ledger is connected

### Errors
https://i.imgur.com/QmkoyjV.png
https://i.imgur.com/nH3pTsf.png

### Additional Notes
- Nantucket#7676 originally reported this issue on discord and I (sleepingfox) created this card with their permission. For further inquiries about the issue, please message Nantucket#7676 on the IOTA discord.

- A workaround has been found. To get your Ledger working with Trinity, connect, unlock, and open the IOTA app on the ledger BEFORE starting Trinity desktop

**Comment by sloganking** [comment]
#1925 and #1924 can use the same workaround. It is highly likely that these issues are related.

**Comment by cvarley100** [comment]
Closing to a single issue as they are likely all related
