### ISSUE TITLE
iOS 1.0.0 crashes on startup when installing over 0.7.3

### ISSUE THREAD

**Issue by Andersmholmgren** [iotaledger/trinity-wallet#1953]
### Bug description
I have been using the beta version of the client via TestFlight.
I installed the new version via app store
When I try to open it, the splash screen displays for ~20s before it exits. The crash logs indicate it was killed by the OS for taking too long

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: IPhone XS Max (MT502X/A)
- OS version: 12.3.1

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 1.0.0

### Steps To Reproduce
1. install version version 0.7.3 via test flight
2. install latest version (1.0.0) via app store
3. start app

### Expected behaviour
It should not crash on startup ;-)

### Actual behaviour
It did crash on startup ;-)

### Errors
[iotaWallet-2019-07-06-103649.ips.txt](https://github.com/iotaledger/trinity-wallet/files/3364264/iotaWallet-2019-07-06-103649.ips.txt)

**Comment by rajivshah3** [comment]
> Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace SPRINGBOARD, Code 0x8badf00d
Termination Description: SPRINGBOARD, scene-create watchdog transgression: com.iota.trinity exhausted real (wall clock) time allowance of 19.56 seconds | ProcessVisibility: Foreground | ProcessState: Running | WatchdogEvent: scene-create | WatchdogVisibility: Foreground | WatchdogCPUStatistics: ( | "Elapsed total CPU time (seconds): 11.260 (user 11.260, system 0.000), 9% CPU", | "Elapsed application CPU time (seconds): 1.410, 1% CPU" | )
Triggered by Thread:  0


From what I see online, it looks like `0x8badf00d` means the app is taking too long to launch. It’s hard to tell what’s causing it to take so long though 🤔  I’ll desymbolicate the report when I have some time.

**Comment by cvarley100** [comment]
@Andersmholmgren Can you try deleting and reinstalling and see if the issue resolves?

**Comment by Andersmholmgren** [comment]
I’ve tried offloading the app and reinstalling but was trying to avoid
deleting the app data. Admittedly the app data is the most likely cause I
guess

**Comment by Andersmholmgren** [comment]
I ended up deleting the app + data and reinstalling. This did fix it so it must've been gagging on the old data
