### ISSUE TITLE
Trinity continually prompts Ledger nano after transaction denial

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#1957]
### Bug description
Upon hitting Deny on your ledger nano to deny sending a transaction, Trinity just prompts the ledger with the transaction details again and gets stuck in a loop.

### Environment Specs
- OS version: Win10
- HW Wallet: Ledger nano X
- Ledger firmware version: 1.2.4-1
- Ledger IOTA app version: 0.5.3
- Trinity version: Desktop 1.0.0

### Steps To Reproduce
1. start to send a transaction on Ledger nano based account
2. hit deny on Ledger to cancel transaction
3. Get stuck being prompted to confirm or deny the transaction indefinably

### Expected behavior
Trinity should return to home screen after transaction was denied

### Actual behavior
Trinity continually tries to prompt the user to accept the transaction

### Errors
https://i.imgur.com/LsRYJTa.png

**Comment by cvarley100** [comment]
Closing due to relation to #1925
