### ISSUE TITLE
Dark theme needs refinement

### ISSUE THREAD

**Issue by MatthewScheuerman** [iotaledger/trinity-wallet#1959]
### Bug description
The borders of input fields on dark theme are very bright and aren't using the values from the theme javascript. Instead of using opacity, the app displays white borders. It should be #666666 but displays as white instead

### Environment Specs
What device are you running Trinity on?
Android Moto Z3 64gb. I will unfortunately be unable to recreate this until tomorrow when I'll be checking it on a Moto Z4. 

- Manufacturer: Motorola 
- Model: Z3
- OS version: Android 9 Pie

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version:

Current Version
1.0.0

### Steps To Reproduce
1. Switch to dark theme

### Expected behaviour
Using code from the theme: rgba(255, 255, 255, 0.4)"
Should display as gray/grey against black background. 

### Actual behaviour
Displays as white

Note: I will also check this against the Linux version soon. Consider using values without alpha.

**Comment by MatthewScheuerman** [comment]
![iota-inputs](https://user-images.githubusercontent.com/30085206/60772865-151f8e80-a0c2-11e9-889d-c0d798bdffc8.png)

Viewing on linux (Linux Mint 19 Tara x86_64 )
Borders don't seem to change on inputs but do change on button hover, and inputs from amount and search field don't match in background color.

**Comment by MatthewScheuerman** [comment]
Using a Moto Z4, the colors on inputs and especially on this screen seem too bright for a theme that is supposed to be in "dark" mode. 
![Screenshot_20190708-081843](https://user-images.githubusercontent.com/30085206/60813589-ae4db400-a159-11e9-8eed-0c129ec84d34.png)

**Comment by MatthewScheuerman** [comment]
@cvarley100 @rihardsgravis  I ran the dark theme through a json to SCSS converter after converting it to json, here are the changes I'd recommend (I can do a pull request if you'd like), but I can't verify them. Unfortunately I couldn't get Trinity to compile on my Linux machine. 

` "dark-chart_color": "rgb(204, 204, 204)",
    "dark-box_bg": "rgb(23, 23, 23)", 
    "dark-box_alt": "rgb(48, 48, 48)", 
    "dark-box_body": "rgb(227, 227, 227)",
    "dark-bar_bg": "rgb(0, 0, 0)", 
    "dark-bar_hover": "rgb(37, 37, 37)", 
    "dark-bar_alt": "rgb(56, 56, 56)", 
    "dark-bar_color": "rgb(227, 227, 227)",
    "dark-label_color": "rgb(227, 227, 227)",
    "dark-label_hover": "rgb(242, 242, 242)",
    "dark-input-bg": "rgb(0, 0, 0)",
    "dark-input-border": "rgba(227, 227, 227, 0.4)",
    "dark-input-alt": "rgb(114, 114, 114)",
    "dark-input-hover": "rgba(227, 227, 227, 0.5)",
    "dark-input-color": "rgb(30, 30, 30)",
    "dark-negative_color": "rgb(172, 69, 69)", 
    "dark-negative_hover": "rgb(146, 57, 57)", 
    "dark-negative_body": "rgb(255, 255, 255)",
    "dark-positive_color": "rgb(85, 160, 91)", 
    "dark-positive_hover": "rgb(31, 126, 74)", 
    "dark-positive_body": "rgb(255, 255, 255)",
    "dark_color": "rgb(38, 38, 38)", 
    "dark_hover": "rgb(30, 30, 30)", 
    "dark_body": "rgb(242, 242, 242)",
    "dark-secondary_color": "rgb(242, 242, 242)", 
    "dark-secondary_hover": "rgb(51, 51, 51)", 
    "dark-secondary_body": "rgb(0, 0, 0)",
    "dark-primary_color": "rgb(242, 242, 242)",
    "dark-primary_border": "rgba(255, 255, 255, 0)",
    "dark-primary_hover": "rgb(51, 51, 51)",
    "dark-primary_body": "rgb(0, 0, 0)",
    "dark-body_bg": "rgb(0, 0, 0)",
    "dark-body_color": "rgb(242, 242, 242)", 
    "dark-body_alt": "rgba(255, 255, 255, 0.15)",
    "dark-body_alt-change": "rgba(227, 227, 227, 0.15)",
    "dark-wave-dark-primary": "rgba(255, 255, 255, 0.15)", 
    "dark-wave_secondary": "rgba(255, 255, 255, 0.15)",
    "dark-animations-1": "rgb(163,163,163)",
    "dark-animations-2": "rgb(94,94,94)"`

Hopefully this is a step in the right direction

**Comment by MatthewScheuerman** [comment]
Note: I also checked the values for text on-light and on-dark against AAA compliancy for contrast and everything checked out ok.

**Comment by rajivshah3** [comment]
> Unfortunately I couldn't get Trinity to compile on my Linux machine

Do you want some help? You can post any issues you're running into in this thread or on Discord and we'd be happy to help

**Comment by MatthewScheuerman** [comment]
> > Unfortunately I couldn't get Trinity to compile on my Linux machine
> 
> Do you want some help? You can post any issues you're running into in this thread or on Discord and we'd be happy to help

Would love to. This week is pretty booked at the moment but I'll try to again soon.

**Comment by MatthewScheuerman** [comment]
Log I got after running 
`npm run deps:desktop`

`0 info it worked if it ends with ok
1 verbose cli [ '/home/username/.nvm/versions/node/v10.15.3/bin/node',
1 verbose cli   '/home/username/.nvm/versions/node/v10.15.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deps:desktop' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'predeps:desktop', 'deps:desktop', 'postdeps:desktop' ]
5 info lifecycle trinity-wallet@0.0.0~predeps:desktop: trinity-wallet@0.0.0
6 info lifecycle trinity-wallet@0.0.0~deps:desktop: trinity-wallet@0.0.0
7 verbose lifecycle trinity-wallet@0.0.0~deps:desktop: unsafe-perm in lifecycle true
8 verbose lifecycle trinity-wallet@0.0.0~deps:desktop: PATH: /home/username/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/username/dev/trinity-wallet/node_modules/.bin:/home/username/.nvm/versions/node/v10.15.3/bin:/home/username/gems/bin:/home/username/gems/bin:/home/username/go/bin:/usr/local/go/bin:/home/username/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
9 verbose lifecycle trinity-wallet@0.0.0~deps:desktop: CWD: /home/username/dev/trinity-wallet
10 silly lifecycle trinity-wallet@0.0.0~deps:desktop: Args: [ '-c', 'cd src/desktop && npm install && cd ../..' ]
11 silly lifecycle trinity-wallet@0.0.0~deps:desktop: Returned: code: 1  signal: null
12 info lifecycle trinity-wallet@0.0.0~deps:desktop: Failed to exec deps:desktop script
13 verbose stack Error: trinity-wallet@0.0.0 deps:desktop: `cd src/desktop && npm install && cd ../..`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/username/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/username/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid trinity-wallet@0.0.0
15 verbose cwd /home/username/dev/trinity-wallet
16 verbose Linux 4.15.0-54-generic
17 verbose argv "/home/username/.nvm/versions/node/v10.15.3/bin/node" "/home/username/.nvm/versions/node/v10.15.3/bin/npm" "run" "deps:desktop"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error trinity-wallet@0.0.0 deps:desktop: `cd src/desktop && npm install && cd ../..`
22 error Exit status 1
23 error Failed at the trinity-wallet@0.0.0 deps:desktop script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
username@minty-ThinkPad-`

**Comment by MatthewScheuerman** [comment]
Here's screenshots of what I have now. There's a lot of re-used and opinionated color variables that get re-used in the code so this is as far as I could take it. I checked the "average" text color for contrast AAA compliancy and it meets AAA with 7.34:1. However, this can change depending upon font weight and size.  

Please let me know if further updates are needed before making a pull request. Thanks
![dark-account-creation](https://user-images.githubusercontent.com/30085206/61098886-294aef00-a426-11e9-8604-7e7d6770bb55.png)
![dark-history-state](https://user-images.githubusercontent.com/30085206/61098887-294aef00-a426-11e9-89af-b3e63de64366.png)
![dark-input1](https://user-images.githubusercontent.com/30085206/61098888-294aef00-a426-11e9-8547-3bdf57c33d18.png)
![dark-input2](https://user-images.githubusercontent.com/30085206/61098889-29e38580-a426-11e9-8ac9-0aaa760bb026.png)
![dark-pow](https://user-images.githubusercontent.com/30085206/61098890-29e38580-a426-11e9-9c68-42cd73b5d116.png)
![dark-recieved-hash](https://user-images.githubusercontent.com/30085206/61098891-29e38580-a426-11e9-8a32-5ee0584f301e.png)
![dark-recieving](https://user-images.githubusercontent.com/30085206/61098892-29e38580-a426-11e9-90ee-c60f3cbb27ef.png)
![dark-sendconfirm](https://user-images.githubusercontent.com/30085206/61098893-29e38580-a426-11e9-8a00-842da73f694b.png)
![dark-showing_errorstate](https://user-images.githubusercontent.com/30085206/61098894-29e38580-a426-11e9-99a0-2b0e2cbd8021.png)
![dark-success](https://user-images.githubusercontent.com/30085206/61098895-29e38580-a426-11e9-8292-fba6ad37aa56.png)

**Comment by MatthewScheuerman** [comment]
If I inverse 2 values it improves the look of the "secondary-button" (close) but it does tend to make other boxes look different. However, this might be better for mobile

![dark-inverse](https://user-images.githubusercontent.com/30085206/61099624-8fd10c80-a428-11e9-8644-6cf6878c9562.png)
