### ISSUE TITLE
transaction is pending

### ISSUE THREAD

**Issue by navidslh2** [iotaledger/trinity-wallet#1960]
hi.i send iota with trinnity app but It is  25 days that my transaction is pending.

**Comment by Thoralf-M** [comment]
Do you have auto-promotion enabled or did you click on the `retry` button a few times? You could also enable remote PoW if your device isn't very fast

**Comment by rajivshah3** [comment]
Please keep Trinity open in order for auto-promotion to work. We currently cannot promote transactions while Trinity is in the background or closed
