### ISSUE TITLE
Trinity desktop wallet doesn't work on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by Twincaret** [iotaledger/trinity-wallet#1962]
I'm just tried to use desktop version IOTA wallet for linux (Ubuntu 18.04.2 LTS), but it not responding, and error logs are empty . And yes, I'm already have install libsecret-1-dev
![Screenshot from 2019-07-06 00-31-22](https://user-images.githubusercontent.com/39728089/60820054-576fcb00-a1a9-11e9-957d-9b86fb19ba3d.png)
![Screenshot from 2019-07-06 00-31-32](https://user-images.githubusercontent.com/39728089/60820055-58086180-a1a9-11e9-9269-d8a2226b3e2a.png)
![Screenshot from 2019-07-06 00-45-04](https://user-images.githubusercontent.com/39728089/60820057-58086180-a1a9-11e9-8d20-fd32665cde0e.png)

**Comment by rajivshah3** [comment]
Have you been able to use a previous version of Trinity or is 1.0.0 the only one you've tried?

**Comment by Twincaret** [comment]
Before I'm have created wallet in android version and it's works fine. But for linux it's only 1.0.0 version I have tried to start

**Comment by cvarley100** [comment]
Possibly related #1846

**Comment by cvarley100** [comment]
Cannot reproduce.
