### ISSUE TITLE
Easy export of transaction metadata

### ISSUE THREAD

**Issue by l3wi** [iotaledger/trinity-wallet#1963]
# Description
The ability to copy metadata about a transaction, or multiple, to the clipboard. 

At present I have to manually copy most of the information about past transactions: amount of tokens, date and time, message. It would be very useful if a copy button could be added to provide a basically formatted transaction receipt.

### Motivation
Its really annoying to manually type things when looking back over your history.

### Requirements
- Small Icon in the transaction view section
- When clicked all basic transaction information is copied to clipboard
  - Date & Time
  - Amount of tokens (in 'i')
  - Destination Address
  - Remainder Address
  - Bundle Hash

### Am I planning to do it myself with a PR?
No 😅

**Comment by webkracht** [comment]
Could there be an export to CSV as well?

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.

Related #2294
