### ISSUE TITLE
Ability to change MWM in settings

### ISSUE THREAD

**Issue by jnpsbck** [iotaledger/trinity-wallet#1964]
### Description
A developer mode where you could for example change mwm from 14 to something lower would be great.

### Motivation
Using trinity on the dev net or on a private tangle.
### Requirements
- being able to change mwm from 14 to something else in the advanced settings or as part of a developer mode.

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
