### ISSUE TITLE
save/load custom node settings via a qr code

### ISSUE THREAD

**Issue by jnpsbck** [iotaledger/trinity-wallet#1965]
### Description
For development purposes it would be great to be able to load and save custom node settings (primary node, mwm, quorum on/off, etc.)

### Motivation
It would be nice to be able to change node settings and advanced settings by scanning a qr code. This way it's easier to come back to my previous settings after a wallet reset when I want users to use a private tangle.

### Requirements
- add export to save node settings and export them as a qr code.
- add import to scan qr code and wallet is set up according to saved configuration.

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
@jnpsbck We will be working on more comprehensive dev support fairly soon. In light of that there would be no real point adding this so I will close for now.
