### ISSUE TITLE
Zero fiat balance on Mac tray app

### ISSUE THREAD

**Issue by mgrassotti** [iotaledger/trinity-wallet#1967]
### Bug description
A general description of the bug.

### Environment Specs
Desktop

- Manufacturer: Apple
- Model: Mac Book Pro 2014
- OS version: Mac OS Mojave 10.14.5

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v1.0.0

### Steps To Reproduce
I just dowloaded the latest update, then:
1. Open Trinity
2. Enter the password
3. Open the minified window from the icon on the OS topbar

### Expected behaviour
See both IOTA amount and fiat amount (EUR in my case)

### Actual behaviour
Seeing the correct IOTA total amount and € 0.00

I think a similar issue was already open in the past but, I am sorry, I cannot find it nor could solve updating or restarting the app

**Comment by rajivshah3** [comment]
https://github.com/iotaledger/trinity-wallet/pull/1511 should have fixed this but I guess the issue came back 🤔
