### ISSUE TITLE
Trinity performance with private tangle

### ISSUE THREAD

**Issue by jnpsbck** [iotaledger/trinity-wallet#1968]
### Bug description
When using Trinity Mobile with a private tangle at some point transactions don't get confirmed any more, even after multiple attempts to promote and reattach.

### Environment Specs

- Manufacturer: Xiaomi
- Model: A2
- OS version: Android 9

- Trinity version: v1.0.0(79)

### Steps To Reproduce
1. Set up a private tangle (https://docs.iota.org/docs/compass/0.1/how-to-guides/create-an-iota-network), I tried with different mwm values and COO tick times, most often mwm=9 tick=15 sec.
2. Set all node settings to off
3. Add private tangle node as primary node
4. Set auto promotion to on.
5. Send transactions until a transaction doesn't get confirmed.

### Expected behaviour
Transaction gets confirmed eventually.

### Actual behaviour
Transaction never gets confirmed, even after promotion, reattachment etc.

### Errors
https://github.com/iotaledger/trinity-wallet/issues/1900

![Screenshot_2019-06-29-18-05-29-085_com iota trinity](https://user-images.githubusercontent.com/1451625/60837728-3028f600-a1c9-11e9-922f-a08e21c2b4cc.png)
![Screenshot_2019-07-01-20-37-48-049_com iota trinity](https://user-images.githubusercontent.com/1451625/60837737-34551380-a1c9-11e9-8d3f-dcd98e95c5aa.png)
![Screenshot_2019-07-03-09-53-27-302_com iota trinity](https://user-images.githubusercontent.com/1451625/60837744-37e89a80-a1c9-11e9-9a9d-061bdc110f39.png)

**Comment by rajivshah3** [comment]
I'm not sure if this has to do with private tangles. The error in the error log has been seen with other users as well
