### ISSUE TITLE
Quorum multiple APIs for token value

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#1969]
### Description
This feature request proposes Trinity use multiple price APIs for token price data and quorum the result.

### Motivation
Multiple times in Trinity's history, Trinity has suddenly showed the value of IOTA tokens as $0.00 because Trinity could no longer talk to the API it was using for price data. This was only fixed when the connected API resumed responding or the Trinity developers updated the Trinity application to handle API changes. 

 This change will:
- Make obtaining price data more reliable
- Allow Trinity to provide more accurate and trustworthy price data

### Requirements
- have trinity store a list of multiple APIs which can provide the price of IOTA
- When in need of price data, have Trinity ask all (or a minimum amount) of it's price APIs for pricing data
- Obtain the median value from all price data given by Trinity's contacted APIs
- Asses whether price data is trust-able by assessing whether 2/3 of contacted APIs price data is within a set variation from the median (say 5%). 
- Display trust-able pricing data

### Open Questions
- Each known API may require the storing of how to retrieve price data from it, as different APIs may have different methods of communicating.

### Am I planning to do it myself with a PR?
No.

**Comment by sloganking** [comment]
This might be a good goal for V2

**Comment by rihardsgravis** [comment]
Updated in #2319 by querying an IOTA Foundation deployed API with multiple fallback endpoints
