### ISSUE TITLE
Desktop fails silently when drag-dropping a seed less than 81 chars

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/trinity-wallet#1974]
### Bug description

When dragging and dropping a seed with < 81 chars, nothing happens and no error message is displayed.

### Environment Specs

- OS version: Only checked Win 10

What build of Trinity are you running? 

- Trinity version: 1.0.0

### Steps To Reproduce
1. Drag and drop a seed with < 81 chars on seed entry
2. Nothing happens, no error message.

### Expected behaviour
An error message should be displayed.

### Actual behaviour
Nothing happens.

**Comment by sloganking** [comment]
For clarification, by drag-dropping a seed, do you mean a seedVault?

**Comment by cvarley100** [comment]
@SleepingFox88 I mean explicitly dropping the text
