### ISSUE TITLE
IOTA Newsfeed

### ISSUE THREAD

**Issue by jnpsbck** [iotaledger/trinity-wallet#2003]
### Description
It would be great to have an IOTA news feed that shows all the IOTA announcements, new blog posts; later also retweets and news about IOTA ecosystem projects.

### Motivation
Hard to keep track of all things IOTA for many people, especially if they don't follow discord / twitter.

### Requirements
1.) start with only regular IF announcements + new IF blog posts. 
2.) notifications about announcements (adjustable in settings)

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
