### ISSUE TITLE
Purchase IOTA from inside Trinity

### ISSUE THREAD

**Issue by f-ben** [iotaledger/trinity-wallet#2004]
### Description
Users should be able to purchase IOTA from inside the wallet.

### Motivation
Make exchanges unnecessary, make it easier for new users, and so on.

### Requirements
Purchase IOTA from inside the wallet
Optional: Sell/Trade IOTA from inside the wallet

### Open Questions (optional)
Which exchange to use (without the user noticing)

### Am I planning to do it myself with a PR?
No

**Comment by r4ched** [comment]
i hope this will be add to the wallet cause it will allow users to really own there coins it doesn't make the exchanges unnecessary, but it offers the user an easy and safe way to trade iota

**Comment by rihardsgravis** [comment]
Added with #2364
