### ISSUE TITLE
Balance check widget.

### ISSUE THREAD

**Issue by MR1991** [iotaledger/trinity-wallet#2005]
### Description
Allow creation of a widget on phone background that constantly shows your current balance 

### Motivation
Avoids logging in frequently.

### Requirements
2 block widget.
 Allow changeable currency, allow changeable address.
Constantly stay linked to newest address

**Comment by f-ben** [comment]
would love to have a widget too
for security it should be necessary for the user to login to trinity when placing the widget on the homescreen

**Comment by MR1991** [comment]
Well its just a view on an address so no real security needed? Only maybe to approve the link between trinity and the widget for keeping track of current addresses.

**Comment by cvarley100** [comment]
Duplicate of #2006
