### ISSUE TITLE
Add address to watch without seed

### ISSUE THREAD

**Issue by Shobba** [iotaledger/trinity-wallet#2006]
### Description
I'd like to add addresses without entering the seed in order to keep an eye on the balance (sending tx of course won't be possible)

### Motivation
I have my main wallet on a Ledger where I don't have access to the seed (obviously). But I'd like to see my balance in Trinity anyway.

### Requirements
Add "watch only" accounts for addresses (maybe it should be possible to add multiple addresses to one account manually because Trinity cannot know all the addresses of that seed).

### Am I planning to do it myself with a PR?
Probably not

**Comment by f-ben** [comment]
I like the idea but thats not really a feature I expect from a wallet. Personally I´d prefer a 3rd party solution

**Comment by Shobba** [comment]
3rd party solution would mean a different app or website, so two apps to check my iota accounts/balances. I'd prefer having everything in one place :) Accounts with small amounts that I can send whenever I want to, and accounts which my main stash.
(But as soon as Trinity on iOS works with the Ledger Nano X I'm happy :P)

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.

**Comment by cvarley100** [comment]
#2005 is a duplicate

**Comment by Shobba** [comment]
@cvarley100 I don't think this is a duplicate of #2005 .
#2005 is about a widget on your phone's homescreen that shows your balance (also of accounts/addresses with seed).
I suggested that it should be possible to add addresses/combine addresses to an account without entering the seed and only displaying the balance in the app.

I hope it's clearer now :)

**Comment by cvarley100** [comment]
My bad. Thanks.
