### ISSUE TITLE
Transaction Message Enhancement

### ISSUE THREAD

**Issue by bluepanther99** [iotaledger/trinity-wallet#2007]
### Description
It would be good if Trinity mobile has built-in integration to our mobile phone location or system information and on-request can insert the information into the transaction message(encrypted or not). Maybe like insert attachment button next to Message (insert gps location, or some information about your mobile phone)

### Motivation
I think this would be a small step for m2m economy

### Open Questions (optional)
Is this already been done or planned to do?

### Am I planning to do it myself with a PR?
No.

**Comment by webkracht** [comment]
[https://github.com/iotaledger/trinity-wallet/issues/2018](url) might be slightly related

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
