### ISSUE TITLE
Address book for Trinnity - feature request

### ISSUE THREAD

**Issue by Qaviz** [iotaledger/trinity-wallet#2009]
### Description
It would be great to see an address book for trinnity where you can add your friends and common addresses you send to, like a 'contacts page'.

To avoid the address re-use issue, you could implement a feature where if one of your friends adds a new address to send to (as they have spent from that address) your address book is automatically updated with their new address once they have opted for it.

### Motivation
To allow for a much more simplified sending and receiving feature, that doesn't allow prior communication in order to do it. (copy past address and then send to your friend in a message)

### Requirements
-Add names to an address book for you to keep on trinity
-These names have an address for you to send to (their wallet), which is updated automatically if they generate a new address in their wallet

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
