### ISSUE TITLE
Trinity Mobile/Desktop flexible resolutions for GNU/Linux Mobilephones (Librem 5, Pinephone) or Samsung DeX

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/trinity-wallet#2010]
### Description
To switch to the mobile UI when the resolutions lowers and have the full UI when the mobile device is connected to a screen.
_Example of Librem 5 connected to a screen_
![](https://cdn.discordapp.com/attachments/407883421369761792/570241540258267136/phonescreenkeyboardmouse-2.png)

_Samsung has this function too (Samsung DEX with Galaxy phones dock)_
![](https://cdn.vox-cdn.com/thumbor/A1id7a8_yLkJEPW5GuJSOiUJDs8=/0x0:2040x1360/920x613/filters:focal(857x517:1183x843):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/54558833/akrales_170425__1644_0006.0.jpg)

### Motivation
Mobile phones (that support pure GNU/Linux OS, or Samsung Galaxy phones) can be used as phones or desktop as shown in the pictures above.

I will personally own a Librem 5 (https://puri.sm/products/librem-5/). This device is running a PureOS image based on Debian GNU/Linux.
I downloaded their qemu image and started it (instructions: https://developer.puri.sm/Librem5/Development_Environment/Boards/qemu.html)
Trinity starts and seems to be working, but of course the resolution of the wallet looks somehow fixed:
![](https://cdn.discordapp.com/attachments/407883421369761792/570240717390086229/unknown.png)

![](https://cdn.discordapp.com/attachments/407883421369761792/570240890665435136/unknown.png)

### Requirements
The wallet might run on, let's say "flexible" resolutions, or even better adapt from the desktop UI to the mobile UI as soon as the wallet window is resized.

### Am I planning to do it myself with a PR?
No

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
