### ISSUE TITLE
Option to create account which can move funds automatically to another account

### ISSUE THREAD

**Issue by webkracht** [iotaledger/trinity-wallet#2011]
### Description
When creating a new account in Trinity an option is offered to move funds automatically to another selected account .  

### Motivation
A seed which can move it's funds automatically can be used safely in machines or in websites as there will be no funds to steal

### Open Questions (optional)
Would it be possible to create the transaction the moment funds are detected?

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
