### ISSUE TITLE
Trigger a request in Trinity to send encrypted data along with payment using deeplink

### ISSUE THREAD

**Issue by webkracht** [iotaledger/trinity-wallet#2018]
### Description
Send along with your payment, encrypted data to the receiver. The request for encrypted data should be triggered by a deeplink parameter so that the payment can only be finalized when request is followed up by sender. In Trinity these data/text snippets can be created so the right snippet can be selected upon payment.

### Motivation
It is imaginable that with a payment you want to send data along with your payment. 
E.g. when you scan a QR code related to your cart content in a webshop. You can send to the receiver, along with your payment, the delivery address where the goods have to be delivered. This would simplify checkout procedures in webshops as you don't have to create a profile before finalizing the order. 

### Requirements
- section in Trinity to create data/text snippets
- new deeplink parameter which can trigger the sending of an encrypted data snippet

### Am I planning to do it myself with a PR?
No.

**Comment by webkracht** [comment]
[https://github.com/iotaledger/trinity-wallet/issues/2007](url) might be slightly related.

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
