### ISSUE TITLE
An API call to trinity service without opening it via some form of POST method request but within the context of the phone

### ISSUE THREAD

**Issue by agentpx** [iotaledger/trinity-wallet#2019]
### Description
I wish there's an API that we can call and the call would be routed to Trinity's (provided it's installed on user's phone) Internal processing/API so that Trinity don't need to open but can accept payment request posting.

### Motivation
To make our app more intuitive and avoid the hassle of opening another app just to make paymet. Sort of like an in-app purchase.  

### Requirements
Payment posting, balance checking

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
