### ISSUE TITLE
Email Alias for Sending/Receiving IOTAS

### ISSUE THREAD

**Issue by healthycrypto** [iotaledger/trinity-wallet#2020]
### Description
Creating an email alias, like me@iota.org, to send and receive IOTAS. Every wallet will include an email address that you must sign up for and then instead of a long address to send IOTAS, you instead just use the email alias that your wallet links (behind the scenes) to your REAL iota address.

### Motivation
One of the biggest problems with IOTA is that it requires a new address every time you send or receive IOTAS. This can be a problem as it is difficult to raise money because you can't just setup a single address and advertise that to send you IOTAS. However, if an alias was setup behind the scenes it would solve that problem. 

It would also be easier for YOU to remember your IOTA address. Instead of having to memorize a long line of number/letters as an address, you can just tell people to send you IOTAS via the trinity wallet to: me@iota.org or whatever you chose. Everyone remembers their email address. How many people remember their blockchain address?

### Requirements
Trinity could then be used in addition to sending/receiving IOTAs to send and receive text messages (SMS), emails, and an address book could be integrated into Trinity to create an All in one solution. It could become a social media app to chat with friends and send/receive IOTAS from them as well.

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
