### ISSUE TITLE
Trinity Node Check not working since IRI 1.8.0

### ISSUE THREAD

**Issue by Wire-xx** [iotaledger/trinity-wallet#2036]
Unfortunately the "Node Check" on https://trinity.iota.org/nodes isn't working anymore since IRI 1.8.0.

I tried checking several different nodes with Firefox, Chrome and Edge and nothing works.
The Error message is

`An error occurred with this application. NO_STATUS_CODE_FROM_LAMBDA`

or sometimes

`Unhandled promise rejection SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"`

I already posted this in discord twice but nobody cared.

**Comment by rihardsgravis** [comment]
Thank you for the report! The issues is fixed now.
