### ISSUE TITLE
Cannot find variable Intl 

### ISSUE THREAD

**Issue by laumair** [iotaledger/trinity-wallet#2037]
### Bug description

Completing onboarding leads to a crash because of a missing variable

### Environment Specs

- Manufacturer: Android Studio
- Model: Emulator

- Trinity version: 924f9b6b69380c2351efdc3f3e8a63d0566532cc

### Steps To Reproduce
1. Complete onboarding
2. Observe loading screen
3. Once loading finished, the application will crash

### Expected behaviour
The application should not crash after loading

### Actual behaviour
The application crashed after loading

### Errors

<img width="330" alt="Screenshot 2019-07-16 at 2 13 48 am" src="https://user-images.githubusercontent.com/20437468/61249957-f0857f80-a76f-11e9-995b-f0e94b18f501.png">

**Comment by rajivshah3** [comment]
This was probably introduced by https://github.com/iotaledger/trinity-wallet/commit/1d7ba3a2fcb25dab32ab7a06c94404a252cdda83. We may need to polyfill `Intl` until #2012 is merged

**Comment by laumair** [comment]
> This was probably introduced by 1d7ba3a

Correct.
