### ISSUE TITLE
Language code standardization

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#2039]
### Description
In the codebase, we should use a certain standard for language codes, such as [BCP-47](). For compatibility with other libraries, we should use functions to convert to another standard if necessary.

### Motivation
As we add support for more languages, functions like this become harder to maintain:
https://github.com/iotaledger/trinity-wallet/blob/49030f57871164b6dca3507fed34d8f0fb44ee64/src/shared/libs/i18n.js#L119-L150

`moment` and `Intl` also use different standards and converting between our language codes (which do not follow a particular standard) and the ones that other libraries support can become a hassle.

### Requirements

- Use BCP-47 or another standard
- Use functions to convert to other standards if necessary

### Am I planning to do it myself with a PR?
Yes

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
