### ISSUE TITLE
Client-side tip reissuance during PoW

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/trinity-wallet#205]
### Problem

- Weaker devices can suffer from the length of time it takes them to complete Proof of Work. 
- By the time a bundle is broadcast, its transactions may already be quite deep, and risk being considered as lazy tips by tipsel. 

### Solution

- To avoid increasing alpha, we can issue a new tip at each point Proof of Work is completed for a transaction in the bundle.

### Considerations

- Do we issue a new branch for each transaction in the bundle?

**Comment by paulhandy** [comment]
I would also suggest to modify the proof of work scheme to be interrupted at a user-configurable time to replace the branch transaction hash with a newer one.

**Comment by Thoralf-M** [comment]
Not possible anymore with the bundle validation changes here <https://github.com/iotaledger/iri/releases/tag/v1.8.5-RELEASE>
