### ISSUE TITLE
Support for socks5 proxy in Advanced settings

### ISSUE THREAD

**Issue by sreeraj-krishnan** [iotaledger/trinity-wallet#2082]
### Description
I'm looking for socks5 support for trinity

### Motivation
Tails OS is a OS for privacy. It uses tor network to run any apps on it. Its booted from usb and we can always carry with us. It has support for bitcoin wallet.
Similarly I was trying to make trinity work on tails OS, however it was not able to connect to any nodes, because I believe trinity does not support socks5.

But in case it supports socks5, could you try to make it work on  tails OS ?

### Requirements

Need socks5 support for Trinity wallet which is configurable.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
No

**Comment by thomazchamberlain** [comment]
Hi @cvarley100 I have some time available to work on this. May I take on this task?

**Comment by cvarley100** [comment]
Hi @thomazchamberlain, yes please do. It would make most sense to go alongside the proxy settings here in Advanced Settings https://github.com/iotaledger/trinity-wallet/blob/6726c23b1c9cb95ba00a1dd02944c13d8695205d/src/desktop/src/ui/views/settings/Advanced.js#L292 
Let us know if you need any help!

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
