### ISSUE TITLE
IOTA Public key (.gpg file) missing

### ISSUE THREAD

**Issue by Andrewskiz** [iotaledger/trinity-wallet#2115]
Hey, I created an issue here about the .gpg file missing under the Trinity Wallet release assets here: https://github.com/iotaledger/trinity-wallet/issues/2093

The issue was closed, and while the links to How to verify authenticity of your Trinity download were fixed, there is still no sign of the iota.foundation.subkey.trinity.public.gpg referenced under Linux > Verify the code signature. The trinity-desktop-1.0.0.AppImage.asc file is there, but there is no .gpg file anywhere to be seen. 

Therefore, step 2: Import the Trinity GPG key is not possible. Sorry to recreate this issue, but it seems not to be fixed unless I am missing something obvious.

**Comment by rajivshah3** [comment]
Looks like the `gpg` file was never included in the artifacts to be uploaded when we run the pipeline to build the app. I'll look into adding it

**Comment by rajivshah3** [comment]
Sorry for the delay on this. I'll hopefully have this resolved soon

**Comment by andrewmakarskiy** [comment]
How long does SOON take?

**Comment by cvarley100** [comment]
@andrewmakarskiy Builds will be signed with a new key from the next release onwards. So look out for the public key in the release artefacts for 1.2.0.

**Comment by RainerB** [comment]
@cvarley100 @andrewmakarskiy looking at [trinity-wallet desktop-1.2.0](https://github.com/iotaledger/trinity-wallet/releases/tag/desktop-1.2.0) it seems the gpg pubkey is still missing.

**Comment by rajivshah3** [comment]
Sorry for the delay in resolving this. We're updating the instructions so that you can retrieve the key from a public keyserver (https://github.com/iotaledger/documentation/pull/595)
