### ISSUE TITLE
Send IOTA amount in chosen units: dollars, pounds etc and show CDN or USD 

### ISSUE THREAD

**Issue by hpssjellis** [iotaledger/trinity-wallet#2159]
Feature Requests

### Description
1. In the send amount text box it already does a conversion to the specified units, but for dollars does not state if it is CDN (Canadian) or USD (US Dollars). Request adding  $ USD or $ CDN

2. Allow a method to enter IOTA in the chosen units (Dollars, Pounds etc). Either with an extra text box or some entry method such as the number sign (Not the dollar symbol since that might not work for other default currencies.). If your default units are USD then type #5.02 The text box converts that to IOTA (today about 21 Mi) and again shows the value as $5.02 USD

3. Give users choice if they want to display the currency.

4. Give users choice on number of decimal points to display. (Presently any entry below 15,000 IOTA shows up as $0.00, but 15,000 IOTA actually has a dollar conversion 15,000 IOTA ~= $0.00357 CDN)

### Motivation
1. Anything that makes IOTA less confusing is a good idea
2. Really important to send the correct amount of IOTA. USD are fairly different than CDN
3. Presently the Trinity wallet does show the conversion to your default units but you have to make several attempts until you get the correct dollar value. Ability to enter the dollar value would be useful.
4. Some people might not like viewing the conversions
5. Control of decimal points for conversions would be useful

### Am I planning to do it myself with a PR?
No, but would like to know where approximately in the code this information is programmed.

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
