### ISSUE TITLE
Mobile: Missing icon / weird gap on alert boxes

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#2193]
### Bug description
There is missing "✓" icon of alertboxes in newest 1.1.0 version of Trinity Mobile and it looks a little bit weird. Without that icon, there is this not good looking gap.

Samsung Galaxy S10
Android 9
Trinity Mobile 1.1.0

### Expected behaviour
To have it good-looking = fix the icon or align the text to left without the gap.

![20190903_001722](https://user-images.githubusercontent.com/35224101/64134700-e3385900-cde0-11e9-8e4e-6f2639f11452.jpg)

![20190903_001805](https://user-images.githubusercontent.com/35224101/64134701-e3385900-cde0-11e9-8fc8-d89ff7793eaf.jpg)

**Comment by rajivshah3** [comment]
We've seen this issue in development for a while, but it has never shown up in a release. I'll investigate, maybe #2161 will fix it
