### ISSUE TITLE
node menu display bug

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/trinity-wallet#2194]
### Bug description
Nodelist from `Autoselect primary node` is shown behind the Proof of work node part, if that's disabled

### Environment Specs
- OS version: Win 10
- Trinity version: 1.1.0-RC1

### Steps To Reproduce
1. Disable `Autoselect primary node` and `Autoselect proof of work node`
2. Change the primary node
![trinitynodeslist](https://user-images.githubusercontent.com/46689931/64359006-c7fb6280-d007-11e9-811a-dc4738863934.png)

**Comment by rihardsgravis** [comment]
Fixed in #2364
