### ISSUE TITLE
Can't delete custom node

### ISSUE THREAD

**Issue by Hissi88** [iotaledger/trinity-wallet#2195]
### Bug description
I can't delete a custom node.
Clicking the X doenst work.

![grafik](https://user-images.githubusercontent.com/45494848/64472684-86cb9580-d162-11e9-981f-d553387f9d05.png)

### Environment Specs
What device are you running Trinity on?

- Windows 7

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: V1.1.0-RC1

### Steps To Reproduce
1. Add a custom node
2. Try to delete it again
3.

### Expected behaviour
Should be deleted

### Actual behaviour
Does not

### Errors
none

**Comment by rajivshah3** [comment]
Fixed in #2209
