### ISSUE TITLE
Too few nodes in the node list

### ISSUE THREAD

**Issue by Hissi88** [iotaledger/trinity-wallet#2196]
### Bug description
Too few nodes in the node list. I did a reset two times, but always same issue.

![grafik](https://user-images.githubusercontent.com/45494848/64472738-4e788700-d163-11e9-844d-0d96cffe70f9.png)

### Environment Specs
What device are you running Trinity on?

- Windows 7

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: V1.1.0-RC1

### Steps To Reproduce
1. See screenshot
2.
3.

### Errors
None

**Comment by rajivshah3** [comment]
Fixed in #2209
