### ISSUE TITLE
Trinity Desktop v1.0.0 for linux not working

### ISSUE THREAD

**Issue by userneu3** [iotaledger/trinity-wallet#2227]
Trinity Desktop v1.0.0 for linux not working on updated (x)ubuntu 16.04.LTS 64bit.
I made it executable manually or by "sudo chmod" - its not working. At one try  it asked if I wanted to install it permanently, I tried all posibilites (yes no), and I see it in the programm menue, but can't start it. No window opens.
Neither start by terminal is working.
Thanks for your ideas

**Comment by feikede** [comment]
Same for me. Doesn't work. No windows, just some processes and a folder in $HOME/.config. v.1.1RC1 works.

**Comment by userneu3** [comment]
@feikede 
well, the developers seem to be very indifferent to our problems... 2 days and no reaction.
I myself I could run trinity successfully in my Ubuntu 18.4. system.
At least this is working.

**Comment by cvarley100** [comment]
1.1RC works, right? In which case just wait for 1.1.0's release.

**Comment by userneu3** [comment]
"Trinity Desktop v1.1.0-RC1"
there are warnings to use 1.1.0-RC1:

> Test release warning
> This is an early release candidate version of the desktop wallet. It is to be used for testing purposes only, with very small amounts of tokens.

https://github.com/iotaledger/trinity-wallet/releases

**Comment by cvarley100** [comment]
Indeed. That is a release candidate version. When deemed stable, release candidate versions are released in full. So, 1.1.0 will be promoted shortly to full release.

**Comment by userneu3** [comment]
thank you
