### ISSUE TITLE
iota Trinity wallet Seedvault issue "Unrecognised SeedVault Key"

### ISSUE THREAD

**Issue by captPython** [iotaledger/trinity-wallet#2233]
### Bug description
Hi Firends,
I have recently used trinity-desktop-1.0.0.AppImage wallet and generated vault seeds. Eveerythings works well I had kept a encrypted seeds and noted down the password But now when I am trying to login again using the same seedVault and using the password to decrypt it then it is throwing an error as shown in Screenshot.

### Environment Specs
Ubuntu 18

- Manufacturer:
- Model:
- OS version:

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: trinity-desktop-1.0.0

### Steps To Reproduce
1. Generated SeedVault
2. Logout and again tried to login
3.

### Expected behaviour
It should decrypt the key and should have asked for Wallet password

### Actual behaviour
Thrown an error "Unrecognised SeedVault Key"

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

![image](https://user-images.githubusercontent.com/10431310/65319458-4b4ab580-dbbd-11e9-86bd-f8792ed9508b.png)

**Comment by cvarley100** [comment]
Hi @captPython. This error suggests the password you entered is not correct. Perhaps you wrote it down incorrectly, or used a different password? Let me know if either of those could be the case.

Also, did you just leave a review on Google? We'd appreciate it if you let us try resolve this issue with you before leaving a negative review.

**Comment by captPython** [comment]
@cvarley100 thanks for your comment.. Seems seeds file were Corrupted.. 

Never mind.. I was able to recover another copy of it .. I had already changed or deleted that review .. Thanks for your help again
