### ISSUE TITLE
Allow copying IOTA amount and time received/sent/in wallet from the app

### ISSUE THREAD

**Issue by SuperFluffy** [iotaledger/trinity-wallet#2294]
### Description

Allow copying specific IOTA amounts you have received or sent or own from within the trinity wallet. This also applies to the specific time you have made a transaction. Places include `Balance` and `History`.

### Motivation

Sometimes you write down the exact amount of tokens you received, for example in a Google Doc or a Spreadsheet (for tax purposes, the relevant authorities want to have a list of your token movements, so this way you can provide an easy overview other than the transaction hash). Or you want to tell a person “I received x amount of IOTA from you.”. Or you want to send the exact amount of tokens you received back to somebody or forward it to somebody else.

### Requirements

App places:

+ Balance
+ History

Feature:

+ Copy total balance
+ Copy amount received/sent in a transaction
+ Copy timestamp of the transaction

### Am I planning to do it myself with a PR?

No.

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
