### ISSUE TITLE
Save options not possible

### ISSUE THREAD

**Issue by vinox2016** [iotaledger/trinity-wallet#2295]
### Bug description

Cannot save settings in options. If I press "save", nothing happens. But the color animation of the button works.

Had node management on manual, wanted to set it back to automatic node management.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Dell
- Model: Precision M7720
- OS version: Windows 7 64  bit

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 1.10

### Steps To Reproduce
1. Go to options
2. Set node mgmt to manual
3. Save
4. Set node mgmt back to auto
5. Try to save

**Comment by cvarley100** [comment]
@vinox2016 `Auto node management` just represents the default settings, you need to change the individual settings before you save.
