### ISSUE TITLE
Feat: Ledger (nano s / X) rescue / import function (24 word seed import)

### ISSUE THREAD

**Issue by Jx77on** [iotaledger/trinity-wallet#2310]
Feature request: 
Create a possibility to import the ledger nano s or X 24 words seed to get independent from Ledger Hardware if needed.

Cause: 
To get access to the IOTA seed in case of Ledger software tools, Hardware or so on won't be available in future
or you lost your ledger hardware and need access to your funds before the new ordered ledger will arrive.

Source of an generator is available, but online is a big risk, but it is usable offline too.
IOTA isn't supported directly at the moment: https://github.com/iancoleman/bip39
May there could be lead off a lot to keep the effort as low as possible.
Thanks!

**Comment by cvarley100** [comment]
@Jx77on This tool currently exists for obtaining a seed from your mnemonic: https://github.com/muXxer/recover-iota-seed-from-ledger-mnemonics

We currently do not have plans to add such a feature to Trinity.
