### ISSUE TITLE
(Mobile) Sliders invisible on dark theme.

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#2316]
### Bug description
Black slider is almost invisible on dark theme and it almost seems that these tiles are broke because of the way that slider blends in with background.

### Environment Specs
- Manufacturer: Samsung
- Model: Galaxy S10
- OS version: Android 9
- Trinity version: 1.1.0 (85)

### Steps To Reproduce
1. Change Trinity Mobile theme to Dark
2. Make slides up and down on tx history page
3. Observe slider on the right

### Expected behaviour
Make slider gray or something more visible on dark theme.

![20191102_111745](https://user-images.githubusercontent.com/35224101/68069595-769af580-fd62-11e9-9d67-159d2c8b21ce.jpg)

![20191102_043541](https://user-images.githubusercontent.com/35224101/68069582-2fad0000-fd62-11e9-984c-0a1def4877f8.jpg)

**Comment by cvarley100** [comment]
Minor issue. Won't fix.
