### ISSUE TITLE
Login button not working on Android 10

### ISSUE THREAD

**Issue by doxmare** [iotaledger/trinity-wallet#2317]
### Bug description
In the welcome screen from Trinity on Android 10 the login button does not do anything at all (no wrong password notification or anything else)

### Environment Specs
What device are you running Trinity on?

Manufacturer: Google
Model: Pixel 2 XL
OS version: Android 10

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

Trinity version: v1.1 (can't open settings due to the bug)

### Steps To Reproduce
Open Trinity and try to login

### Expected behaviour
Login button should log you in or give an error

### Actual behaviour
Nothing happens

### Video
https://streamable.com/ugz77

**Comment by rajivshah3** [comment]
@Doxmare please provide all information requested in the template such as manufacturer and model, as these are necessary for us to investigate the issue properly

**Comment by doxmare** [comment]
Done

**Comment by cvarley100** [comment]
@Doxmare Did this start happening out of the blue? Did you restore your OS from back-up or update from a much older version?

**Comment by doxmare** [comment]
@cvarley100 Out of the blue, but I didn't open the app for a few months at least

**Comment by cvarley100** [comment]
@Doxmare It is likely this is interference from old keychain entries. Please reset the wallet and set up again with your seed backups.
