### ISSUE TITLE
Can't open app after installing it first time

### ISSUE THREAD

**Issue by skipokylas** [iotaledger/trinity-wallet#2348]
### Bug description
A general description of the bug.

### Environment Specs
What device are you running Trinity on?

- OS version: macOS Mojave 10.14.6

- Trinity version: last on Sunday, November 17

### Steps To Reproduce
1. Install app from site
2. open first time
<img width="1276" alt="Screenshot 2019-11-17 at 10 55 19 PM" src="https://user-images.githubusercontent.com/29805382/69013951-0dd09180-098e-11ea-9010-375d21b11523.png">

**Comment by rajivshah3** [comment]
@skipokylas after some investigation this seems related to the macOS keychain (https://github.com/desktop/desktop/issues/3625). Can you please try the following and let me know if it solves the issue?

1. Quit Trinity
2. Open Keychain Access (`/Applications/Utilities/Keychain Access`)
3. Right-click the `login` keychain and lock it:
![image](https://user-images.githubusercontent.com/19519564/69092957-82054680-0a1b-11ea-88c6-2fc22809207c.png)
4. Right-click it again and unlock it
5. Open Trinity

**Comment by rajivshah3** [comment]
This issue has been linked to an error in Bugsnag
[**Error** in **/index.html**](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5ce6a1f1dfbdf60019b3a725?event_id=5dd2d08a00531fced0940000&i=gh&m=li)

**Comment by rajivshah3** [comment]
Hi @skipokylas , did the above steps solve the issue for you?

**Comment by skipokylas** [comment]
Hi @rajivshah3 , Yes, it solved the problem.
Thank you.

**Comment by skipokylas** [comment]
Hi @rajivshah3, similar problem
<img width="1230" alt="Screenshot 2020-01-29 at 3 14 08 PM" src="https://user-images.githubusercontent.com/29805382/73359701-202e4c00-42aa-11ea-99e6-d4de4154cf31.png">

**Comment by rajivshah3** [comment]
This seems like a slightly different issue. We're going to update Realm soon and see if that solves the problem

**Comment by traminal** [comment]
@rajivshah3 Hi, I followed the info above yet I still can't fix my Trinity wallet problem. Is there any other method to fix this? 

thanks,
Tram

**Comment by MOTA22** [comment]
Hi I am having this issue also! Can anyone help please?
![Screen Shot 2021-02-20 at 21 05 12](https://user-images.githubusercontent.com/73853700/108608549-8909ca00-73bf-11eb-8523-c0dbc6b02c03.png)
