### ISSUE TITLE
IFTTT Connector for Trinity V2

### ISSUE THREAD

**Issue by Jamiehix** [iotaledger/trinity-wallet#2375]
### Description
A connector so that IFTTT (If This Then That) can interact with Trinity V2. 

Some existing projects that may be possible to collaborate with: https://github.com/iota-community/ifttt

https://github.com/0570dev/iota/tree/master/software/arduino/iota-ifttt

https://ecosystem.iota.org/projects/iota-integration-gateway

### Motivation
IFTTT can provide a lot of usability cases that even casual users can benefit from, if Trinity were able to interact. In particular connecting to IoT devices. Some examples: https://ifttt.com/monzo

### Requirements
A connector so that various functionalities of Trinity V2 can be utilised by IFTTT

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
Marking as V2 and closing. We will reconsider feature and enhancement suggestions for the next version of the wallet.
