### ISSUE TITLE
Trying to send funds from ledger - confirmation not showing up

### ISSUE THREAD

**Issue by FritzPeterAlbrecht** [iotaledger/trinity-wallet#2386]
I'm trying to send funds with my ledger. Trinity stops working at the point where I have to confirm the tx on my ledger. Confirmation on the ledger not showing up! Also something is popping up on my desktop and directly disappears without a chance to read whats going on.

This is happening the first time. Can't touch my funds.

**Comment by cvarley100** [comment]
@FritzPeterAlbrecht How did you resolve this?

**Comment by FritzPeterAlbrecht** [comment]
It was caused by spreaded funds on the ledger. Four addresses had balances, as I learned the Ledger can just handle to addresses in one tx due to memory limitations. So in Trinity just go to your account, click settings and then click adresses!

**Comment by FritzPeterAlbrecht** [comment]
https://medium.com/@hbmy289/how-to-access-iota-funds-spread-over-too-many-inputs-on-ledger-nano-s-74708548fa6e

**Comment by cvarley100** [comment]
@FritzPeterAlbrecht Ah brilliant, glad you sorted the issue. We need to add this information to Trinity so it's easier to find.
