### ISSUE TITLE
Apple Pay and Android Pay for buying IOTAs with Moonpay

### ISSUE THREAD

**Issue by GuidAnce-git** [iotaledger/trinity-wallet#2399]
# Description
Possibility to pay Moonpay with build in Apple Pay or Android Pay

### Motivation
During the hole process, entering the credit card information takes most time. With Apple Pay or Android Pay this process can speed up dramatically. 

### Requirements
1. iOS/Android build in payment method available for Moonpay 

### Am I planning to do it myself with a PR?
No

**Comment by cvarley100** [comment]
@GuidAnce-git Apple Pay will be available sooner or later. Android Pay likely in the future.

**Comment by GuidAnce-git** [comment]
@cvarley100 Nice to hear. Thanks for the tip.

**Comment by cvarley100** [comment]
In light of the recent attack, MoonPay will not be readded to Trinity. Apple and Android Pay may be an option with a future payment provider.
