### ISSUE TITLE
Cannot accept terms of moonpay (german UI)

### ISSUE THREAD

**Issue by SushiTee** [iotaledger/trinity-wallet#2401]
### Bug description
Cannot accept terms of moonpay (german UI). The bug is indicated by the orange lines.
In english UI it works as the text fits there.

<img width="320" alt="20191219_043925000_iOS" src="https://user-images.githubusercontent.com/293612/71146080-11bd3100-2224-11ea-91af-9aeb466abe13.png">

### Environment Specs
- Manufacturer: Apple
- Model: iPhone SE
- OS version: iOS 13.3
- Trinity version: v 1.2.0 (95)

### Steps To Reproduce
just perform the necessary steps to reach the step seen on the screenshot.

### Expected behaviour
A linebreak would be good.

### Actual behaviour
The checkbox to accept the terms is not visible.

**Comment by web2perform** [comment]
Same here with Samsung Galaxy S8+, newest version.

**Comment by cvarley100** [comment]
Hey @SushiTee & @Leibi133 please use English for now. A fix will be pushed ~later today~ tomorrow.

**Comment by web2perform** [comment]
Also note that the KYC note in red color is also visually interrupted in the German version.
