### ISSUE TITLE
Node out of sync

### ISSUE THREAD

**Issue by tguney** [iotaledger/trinity-wallet#2439]
### Bug description
When i log on to trinity i get:
Your currently selected node is out of sync. Please change node or try again.
![Screenshot_2019-12-29-12-50-33-841_com iota trinity](https://user-images.githubusercontent.com/59331512/71555162-dd265200-2a39-11ea-88ee-3db752859b6d.jpg)

### Environment Specs
Xiaomi mi max2 android 7.1.1

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v1.2.1
![Screenshot_2019-12-29-12-49-07-187_com iota trinity](https://user-images.githubusercontent.com/59331512/71555152-b36d2b00-2a39-11ea-9e75-8134e49760bf.jpg)

### Steps To Reproduce
Log on to Trinity

### Expected behaviour
Get message

**Comment by martinpaulik** [comment]
I have same problem. I uninstall Trinity wallet and installed again, but there is still problem with nodes.

OS: Windows 10 and Android

**Comment by tguney** [comment]
I installed trinity on desktop Windows 10. Same problem.

**Comment by martinpaulik** [comment]
And does not work with any node.

**Comment by retonag** [comment]
Same problem here. 
Win10 + Trinity v1.2.1

**Comment by amani1104** [comment]
Same problem on MacOS Mojave with Trinity 1.2.1 and 1.2.0

**Comment by martinpaulik** [comment]
Trinity 1.2.1 (last build)

**Comment by IoTMOD** [comment]
This is not a Trinity bug. The IOTA network is currently down.
The IOTA engineering team is on it.
https://twitter.com/iota_dev/status/1211249303517315072

**Comment by martinpaulik** [comment]
> This is not a Trinity bug. The IOTA network is currently down.
> The IOTA engineering team is on it.
> https://twitter.com/iota_dev/status/1211249303517315072

Thanks.

**Comment by martinpaulik** [comment]
It is not first issue of IOTA. They plan to do big thing with IOT, but there are still some problems.

**Comment by rajivshah3** [comment]
As @IoTMOD mentioned, this is a network issue
