### ISSUE TITLE
Error on Node Sync

### ISSUE THREAD

**Issue by Hyp3r1onX** [iotaledger/trinity-wallet#2440]
# Bug description
When trying to log into my IOTA Account i get the error that the node is out of Sync. 
I tried different nodes (manually selected some) and still getting the error.
I also completely uninstalled and reinstalled the IOTA Desktop Wallet and still same error.
I also tried to disable the System Proxy Setting same error.

### Environment Specs
What device are you running Trinity on?
- OS version: Windows 10 Professional Build 1903

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 1.2.1

Please fix this since i can't access my IOTA anymore. 

###Screenshot of Error
![iota](https://user-images.githubusercontent.com/49735625/71565195-7db55a00-2aac-11ea-81b9-a98e7ece4569.png)

**Comment by rajivshah3** [comment]
Please see https://github.com/iotaledger/trinity-wallet/issues/2439#issuecomment-569507443. The issue should be fixed soon
