### ISSUE TITLE
Message in transaction do not correspond to index in bundle

### ISSUE THREAD

**Issue by janfiedler** [iotaledger/trinity-wallet#2441]
# Bug description
If I receive transaction in bundle, where is multiple transactions to different addresses. Message in incoming transaction detail I see message from transaction index 0 and not to correspond to transaction with my address.

For example this bundle:
https://thetangle.org/bundle/OGRIIXSE9UGTIIXCZDVVEQIZTODEOVFFOELDQTRXXKX9NECUHA9HSJHO9YDXBA9AYGEQYFWAPQKWKPDBD

My address is in transaction with 8 index in bundle
9BNSLXLGABKERYBQFTHEDGYUTBWWJRERDYDRZBAGRXILIIINKGHTRABPWBXBARR9XQTPERZZJ9TXIFNN9VIEXJYCHB

![image](https://user-images.githubusercontent.com/13234075/71606938-963d7700-2b75-11ea-9b8d-4f141008097d.png)

But message in trinity is show from transaction with 0 index in bundle

![image](https://user-images.githubusercontent.com/13234075/71606893-157e7b00-2b75-11ea-910f-c35c5ac3cbc1.png)

![image](https://user-images.githubusercontent.com/13234075/71606966-c127cb00-2b75-11ea-851f-aba39e38fa0a.png)

### Environment Specs
What device are you running Trinity on?
Desktop, Win10

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v1.2.1

### Steps To Reproduce
1. Send transaction with multiple transactions in bundle to different addresses
2. And check incoming transaction for your address in trinity

### Expected behaviour
See  correct message included in transaction to my address.

### Actual behaviour
See always message from transaction with 0 index in bundle

**Comment by cvarley100** [comment]
Unfortunately there is no way to guarantee we display the relevant message from the index in a bundle. In a typical IOTA bundle the message is at index 0 so we have chosen to display this one.
