### ISSUE TITLE
App crashes on iOS during MoonPay checkout process

### ISSUE THREAD

**Issue by s-motzer** [iotaledger/trinity-wallet#2444]
### Bug description
During  the checkout process with MoonPay the app crashes when hitting "CONTINUE" after the step "billing address". Last try from me: January 2nd, 21:22 UTC time

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: iPhone 11 Pro 256 GB
- OS version: 13.3

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v 1.2.2 (98)

### Steps To Reproduce
1. Buy IOTA with MoonPay
2. Type in your address in the step "billing address"
3. Hit "Continue" on bottom right

### Expected behaviour
Next step should occur, payment/creditcard details?

### Actual behaviour
App crashes, shuts down.

### Errors
App shuts down, nothing more to see.

**Comment by rajivshah3** [comment]
This issue has been linked to an error in Bugsnag
[**Error** in **node_modules/invariant/browser.js:39**](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5dd3b3f3e7767a00196816e9?event_id=5e0f9d3d0054ce0e2f570000&i=gh&m=li)

**Comment by rajivshah3** [comment]
Likely related to https://github.com/react-native-community/react-native-webview/issues/161. Since we don’t use CocoaPods to link this library we’ll have to figure out another way to resolve this

**Comment by rajivshah3** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Error** in **node_modules/invariant/browser.js:39**](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5dd3b3f3e7767a00196816e9?event_id=5e266c470055ff7326860000&i=gh&m=fx)
