### ISSUE TITLE
wrong currency symbol shown if too high amount

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#2445]
### Bug description
When I try to buy from Moonpay an amount greater than 150USD there's a warning `KYC required for an amount greater than €150`. No matter which currency I entered it always shows the € symbol.

### Environment Specs
- Model: iPhone 11 Pro
- OS version: 13.2.2
- Trinity version: 1.2.2 (98)

### Steps To Reproduce
1. try to buy iota with moonpay
2. on `Choose the amount if MIOTA for purchase` enter an amount greater than 150 USD

### Expected behaviour
The warning should show USD or other selected currency.

### Actual behaviour
The warning always shows `€150`
![IMG_6746](https://user-images.githubusercontent.com/21984138/71741960-874e1180-2e60-11ea-9b33-f734b55fa5b7.PNG)

**Comment by rajivshah3** [comment]
@KiwiCat123 can you try to reproduce the issue again? It seems to work correctly for me on v1.2.2 (98) as well as the latest build from the `develop` branch. I wonder if the exchange rate endpoint was down when this issue occurred 🤔 

![image](https://user-images.githubusercontent.com/19519564/71794384-3e888b00-300f-11ea-97af-175c6f407adb.png)

**Comment by KiwiCat123** [comment]
@rajivshah3 I just could reproduce it. I can record a video of it if you need. I set the currency to USD, entered 151 and then this message appears again with €.
My iPhone is set to German. Maybe it has something to do with that. I’ll test it again on another iPhone.

**Comment by rajivshah3** [comment]
@KiwiCat123 ah, maybe I was entering the amount before switching the currency. I'll try switching the currency first and also try switching the device language to German
