### ISSUE TITLE
Buy IOTA with moonpay "There was a problem in your transaction. Please try again".

### ISSUE THREAD

**Issue by jairomer** [iotaledger/trinity-wallet#2473]
The issue tracker is only for reporting bugs. If you need technical assistance with the Trinity wallet, please consult the [documentation](https://docs.iota.works/trinity). For further assistance, please visit the #help channel on [Discord](https://discord.iota.org).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.iota.org).

### Bug description
There was a problem when attempting to buy some iotas with Moon Pay within the wallet. The UI will not show the root cause nor any information about the error or how to solve it. 

For mass adoption, basic usability problems like this one should provide as much information as possible, specially with something as delicate as a bank transaction. 

### Environment Specs
What device are you running Trinity on?
- OS version: Manjaro Linux

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version:  1.2.1
Using the bundle in the official web page. 

### Steps To Reproduce
1. Press "Buy IOTA" button to enter moonpay. 
2. Insert quantity, personal and card details. 
3. Press "purchase button".

### Expected behaviour
Either a buy order is made, or an informative error appears. 

### Actual behaviour
"There was a problem in your transaction. Please try again"
Credit card expiration date is "undefined/undefined", maybe is this the issue?

No informative errors, no outputs anywhere. It is impossible to know if it is a problem with the exchange or with the card details. 

### Errors
"There was a problem in your transaction. Please try again".

**Comment by cvarley100** [comment]
Hi @jairomer. Thanks for the report. Binance has suspended IOTA withdrawals while they perform maintenance. We will update the error message in Trinity to reflect this.
