### ISSUE TITLE
Can't to purchase  IOTA from Trinity Wallet by MoonPay

### ISSUE THREAD

**Issue by martinpaulik** [iotaledger/trinity-wallet#2483]
Hello guys,
last days I can't to purchase IOTA from Trinity Wallet. There is error message:

![image](https://user-images.githubusercontent.com/59334427/72510748-4388de00-384a-11ea-8d32-9ff15bb8c48f.png)

Trinity Wallet version 1.2.1
OS Windows 10 (fully patched)

Could you please help me?

**Comment by cvarley100** [comment]
Hi @martinpaulik. Please check the error log and share what you see. In your top menu, Trinity > Error Log.

**Comment by martinpaulik** [comment]
Thanks for reply. There it is:
![image](https://user-images.githubusercontent.com/59334427/72511926-c9595900-384b-11ea-8f77-ceec488e8554.png)

Node Settings:
![image](https://user-images.githubusercontent.com/59334427/72512120-db3afc00-384b-11ea-9685-67995f53c8c3.png)

Thanks.

**Comment by cvarley100** [comment]
@martinpaulik Is your device time correct?

**Comment by martinpaulik** [comment]
Yes, time on my device is correct for our Time Zone (Prague). I have same problem with next wallet on OS Android.

**Comment by cvarley100** [comment]
Okay, that's strange. Try turning off `automatic node management` and `autoselect primary node`. You can then connect to a specific node e.g. https://nodes.thetangle.org:443

**Comment by martinpaulik** [comment]
Thanks. Tried both options, but there is still timestamp error.

**Comment by martinpaulik** [comment]
I am sure that it is bug, because I did not make any changes on my devices.

**Comment by cvarley100** [comment]
@martinpaulik It seems strange that is is affecting both of your devices. Have there been any changes to your network e.g. using a VPN?

**Comment by martinpaulik** [comment]
No, I did not make any changes on my devices.

**Comment by martinpaulik** [comment]
BTW: I tried more nodes, but with same result :-(

**Comment by cvarley100** [comment]
@martinpaulik Oh. My bad. I see the issue now.

Binance has currently suspended withdrawals. MoonPay uses Binance to fulfil purchases. It will hopefully be back up and running shortly.

We will add clearer messaging to the purchase flow in Trinity so that you will be aware of these sorts of issues in future.

**Comment by martinpaulik** [comment]
OK, no problem :-) Thanks for your message.
