### ISSUE TITLE
Cannot buy via MoonPay

### ISSUE THREAD

**Issue by hardtacker** [iotaledger/trinity-wallet#2506]
Hello, i tried it serval times but I cannot buy IOTA Coins via MoonPay in the Wallet.

I run throw the process, after I fill in my Credit Card Information the next summary page shows the Credit Card Number as xxxx xxxx xxxx xxxx and expired day is shown as unkown.

For my understanding there should be the right information from the Credit Card be shown.

When I click on send, I got an Error that the request could not send out.

If I use the button back the complete Wallet crashed down.

I have to close and restart it.

What is the reason for this issues?

Thx,

Hardtacker

**Comment by rajivshah3** [comment]
Hi @hardtacker, this should be fixed in the next release
