### ISSUE TITLE
"Continue" button at the "Enter your seed" page doesn't work for additional accounts

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/trinity-wallet#2522]
### Bug description
The continue button doesn't work when adding a second seed to Trinity

### Environment Specs
- OS version: Win 10
- Trinity version:  v.1.2.1

### Steps To Reproduce
1. Create one account with a seed
2. Try to add another account

### Expected behaviour
Account should be created with the seed

### Actual behaviour
"Continue" button at the "Enter your seed" page does nothing
Reset in Trinity and reinstall didn't help

### Errors
No errors in the error log

**Comment by cvarley100** [comment]
This appears to be user-specific. Have managed to reproduce on a VM. Will continue to investigate.

**Comment by Thoralf-M** [comment]
I had the RC version installed before which overwrote the main application, uninstalled it and installed the normal Trinity version. Maybe there was something left that caused the problem

**Comment by cvarley100** [comment]
It is likely due to RC interference I suspect.

**Comment by Thoralf-M** [comment]
I manually removed the Trinity RC entries in the windows credentials and that fixed it
