### ISSUE TITLE
Currency/timeframe reset after app restart

### ISSUE THREAD

**Issue by Vid201** [iotaledger/trinity-wallet#2529]
### Bug description
After trinity gets completely closed and restarted the setting for the graph on balance page gets reset back to USD and 24h.

### Environment Specs
What device are you running Trinity on?

a)
- Manufacturer: OnePlus
- Model: OnePlus 5
- OS version: Android 9

b)
- Manufacturer: HP
- Model: Envy
- OS version: Ubuntu 19.10

What build of Trinity are you running?

a)
- Trinity version: v 1.2.3 (99)

b)
- Trinity version: v 1.2.1

### Steps To Reproduce
1. changed settings for the graph (for example to EUR 7d)
2. closing the app completely
3. reopen the app

### Expected behaviour
settings should still be EUR 7d

### Actual behaviour
setting is reset to USD 24h

**Comment by rajivshah3** [comment]
I was able to reproduce the issue on desktop. I think I found the source of the bug
