### ISSUE TITLE
Node problem

### ISSUE THREAD

**Issue by rcop89** [iotaledger/trinity-wallet#2551]
![0E03E770-03A2-420A-B519-E64C9432E6E8](https://user-images.githubusercontent.com/61000304/74406385-6bf30080-4e27-11ea-9dec-4246925a0415.png)
![9950CCD7-EFCF-4831-A22F-DD6CAA4DE08D](https://user-images.githubusercontent.com/61000304/74406393-71504b00-4e27-11ea-9b9e-f79594535734.png)

The issue tracker is only for reporting bugs. If you need technical assistance with the Trinity wallet, please consult the [documentation](https://docs.iota.works/trinity). For further assistance, please visit the #help channel on [Discord](https://discord.iota.org).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.iota.org).

### Bug description
Typed in password came up with the above pics, tried to change nodes manually, no luck. Reset app, rendered seed...still nodes not happy.

### Environment Specs
iPhone XR 

IOS 13.3.1

- Manufacturer:
- Model:
- OS version:

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: the App

### Steps To Reproduce
1.
2.
3.

### Expected behaviour
What should happen.

### Actual behaviour
What really happened.

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

**Comment by rcop89** [comment]
Can anybody help 😔

**Comment by arne-fuchs** [comment]
The coordinator is offline at the moment and you shouldn't login in trinity right now.

**Comment by rcop89** [comment]
Ok cheers

**Comment by Boomer3828** [comment]
How long is this gonna take. Download removed from the website but no message about what's going on... very disappointed.

**Comment by Antonel-hub** [comment]
Hola,,tengo el mismo problema,cuanto tiempo tardar esto, yo llevo cambiando los nodos desde ayer por la noche y nada de nada,espero que se solucione pronto.Y yo que pensaba que es una de las walet mas fiables que hay........pffff. Un saludo!!!

**Comment by Boomer3828** [comment]
https://status.iota.org/

**Comment by martinpaulik** [comment]
This thing should take IoT Market? Nope. And I say it as bigger IOTA investor. Good idea, but realisation very bad.

**Comment by martinpaulik** [comment]
And what is worst, somebody switch off all mainnet. It was second case in last 2 month. We have not access to our funds. Terrible.

**Comment by ocmone** [comment]
> This thing should take IoT Market? Nope. And I say it as bigger IOTA investor. Good idea, but realisation very bad.

1) What does a human-to-human transaction wallet have to do with IoT?
2) Mainnet is is still operating. You can still send data (which is the biggest IoT case)
3) Would you prefer to have your funds stolen? It was a wise decision to halt the coordinator in order to prevent attackers from stealing funds from Trinity users.  
4) If you didn't know all this, you are not an IOTA investor, but a speculator who has no real interest in IOTA.

**Comment by martinpaulik** [comment]
> > This thing should take IoT Market? Nope. And I say it as bigger IOTA investor. Good idea, but realisation very bad.
> 
> 1. What does a human-to-human transaction wallet have to do with IoT?
> 2. Mainnet is is still operating. You can still send data (which is the biggest IoT case)
> 3. Would you prefer to have your funds stolen? It was a wise decision to halt the coordinator in order to prevent attackers from stealing funds from Trinity users.
> 4. If you didn't know all this, you are not an IOTA investor, but a speculator who has no real interest in IOTA.

Your post is very stupid :-) I am not speculator, but you stupid man and liar. There is proof:

![image](https://user-images.githubusercontent.com/59334427/74532943-b9a76000-4f30-11ea-85a6-092878e3dcac.png)

**Comment by martinpaulik** [comment]
> > This thing should take IoT Market? Nope. And I say it as bigger IOTA investor. Good idea, but realisation very bad.
> 
> 1. What does a human-to-human transaction wallet have to do with IoT?
> 2. Mainnet is is still operating. You can still send data (which is the biggest IoT case)
> 3. Would you prefer to have your funds stolen? It was a wise decision to halt the coordinator in order to prevent attackers from stealing funds from Trinity users.
> 4. If you didn't know all this, you are not an IOTA investor, but a speculator who has no real interest in IOTA.

BTW, Critical thinking is a feature of every intelligent people. Tangle should operate 20% IoT market, but M2M will use wallets as well. But our wallets does not work. What happened if wallet in my car will not work correctly? It will be big problem, dude. You are big optimist.

**Comment by martinpaulik** [comment]
> > This thing should take IoT Market? Nope. And I say it as bigger IOTA investor. Good idea, but realisation very bad.
> 
> 1. What does a human-to-human transaction wallet have to do with IoT?
> 2. Mainnet is is still operating. You can still send data (which is the biggest IoT case)
> 3. Would you prefer to have your funds stolen? It was a wise decision to halt the coordinator in order to prevent attackers from stealing funds from Trinity users.
> 4. If you didn't know all this, you are not an IOTA investor, but a speculator who has no real interest in IOTA.

Do you understand that "speculators" as me, ensure financing IOTA development? Or are you so stupid?

**Comment by cvarley100** [comment]
As mentioned earlier. The Coordinator is currently offline. Please follow https://status.iota.org/ for status updates.

**Comment by martinpaulik** [comment]
> As mentioned earlier. The Coordinator is currently offline. Please follow https://status.iota.org/ for status updates.

You wrote this:
Mainnet is is still operating

Current status:
Mainnet:
Not operational.

OMG :-D Either you are simple BOT or blind or liar. Mainnet is down and users have not access to these funds  in wallets.

**Comment by cvarley100** [comment]
The Coordinator being down means the mainnet does not process value transactions. Please be patient while we resolve the situation, and follow https://status.iota.org/ for official updates.

**Comment by martinpaulik** [comment]
> The Coordinator being down means the mainnet does not process value transactions. Please be patient while we resolve the situation, and follow https://status.iota.org/ for official updates.

Sorry, my previous post was not for you.

**Comment by ocmone** [comment]
@martinpaulik 
Please refrain from personal insults.
The Trinity wallet has nothing to do with IoT devices. Those will have entirely different wallets with much lower base functionality.
And as I said, you can still do data transactions via the IOTA network, because they don't need the coordinator to propagate through the network. However, there are not many nodes active right now.

**Comment by martinpaulik** [comment]
> @martinpaulik
> Please refrain from personal insults.
> The Trinity wallet has nothing to do with IoT devices. Those will have entirely different wallets with much lower base functionality.
> And as I said, you can still do data transactions via the IOTA network, because they don't need the coordinator to propagate through the network. However, there are not many nodes active right now.

You are wrong. If I would like to pay for sensors data then I need Trinity Wallet for payment. What wallet could I use now for hold IOTA tokens? Trinity Wallet is recommend by IOTA Foundation. And what node are active now? Thanks.
