### ISSUE TITLE
Description mistake correction.

### ISSUE THREAD

**Issue by Alex-sandr11** [iotaledger/trinity-wallet#2554]
### Description
Desciption improvement of "Branches" part on https://github.com/iotaledger/trinity-wallet.

### Motivation
This feature is needed to avoid misunderstanding or confusion.

### Requirements
On the description page it is said that one must use prefixes but examples use another prefixes ("feature" instead of "feat" and "bugfix" instead of "bug"). Examples should be corrected according to the given list of prefixes. 

### Am I planning to do it myself with a PR?
No.

**Comment by rajivshah3** [comment]
This should be resolved in #2612
