### ISSUE TITLE
Downloadlink not working

### ISSUE THREAD

**Issue by Erlix322** [iotaledger/trinity-wallet#2555]
# Problem Description:
  - Tried to download the wallet from your website, but it doesn't start... Also the link for the download appears to be dead. During inspect it shows that the <a>Download</a> tag is missing a link
  - Also on Github it is not clear how to download and install the wallet since releases only list source code and no installer

# Expected behaviour: 
Download of Trinity is starting

**Comment by f-ben** [comment]
Thats because trinity has issues right now. The IF is working on it and will release a new version soon. You can have a look at the status here: https://status.iota.org/
