### ISSUE TITLE
readonly login: ability to use wallet without seed

### ISSUE THREAD

**Issue by c-mnd** [iotaledger/trinity-wallet#2556]
### Description
if you have a list of addresses, and unless you want to send funds, you don't need the seed.

### Motivation
protection of the seed

### Requirements
the list of addresses, created by the seed, stored seperately, protected by a 'weaker' password (or even none, if amounts are really tiny)

### Am I planning to do it myself with a PR?
No.

**Comment by c-mnd** [comment]
I've been trying (twice) to collect reactions on that issue on the #general channel of iota-discord, but there weren't any, sorry. Only fast guys without gh relations, sry.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.

**Comment by cvarley100** [comment]
Duplicate of #2006
