### ISSUE TITLE
Emergency kill switch

### ISSUE THREAD

**Issue by viossat** [iotaledger/trinity-wallet#2562]
### Description
Allow to disable Trinity on startup from a central remote server.

### Motivation
On February 12th 2020, a critical security issue has been suspected in Trinity. The mainnet Coordinator has been turned off the same day to prevent more funds to be stolen. However, that did not stop the seeds from continuing to leak.

### Requirements
Trinity should neither show password screen nor load all its dependencies if the kill switch is enabled, preventing any leak like HTTP requests.

### Open Questions (optional)
How to handle offline usage of Trinity?

### Am I planning to do it myself with a PR?
No.

Edit: To help reach consensus on my proposal, I removed controversial stuff.

**Comment by cvarley100** [comment]
This already exists, though it would not help in the case of the recent attack, as seeds had already been compromised, hence the coordinator was shut down.

See https://github.com/iotaledger/trinity-wallet/blob/50a98e0c6664655abcf24da07e3315f6e632aff8/src/desktop/src/ui/Index.js#L247
