### ISSUE TITLE
Can’t download trinity app on iPhone?!?!

### ISSUE THREAD

**Issue by rcop89** [iotaledger/trinity-wallet#2574]
The issue tracker is only for reporting bugs. If you need technical assistance with the Trinity wallet, please consult the [documentation](https://docs.iota.works/trinity). For further assistance, please visit the #help channel on [Discord](https://discord.iota.org).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.iota.org).

### Bug description

No trinity app????.

### Environment Specs
What device are you running Trinity on?

- Manufacturer:
- Model:
- OS version: 13.3.1

What build of Trinity are you running? No idea I deleted it to reinstall it now my Iota is floating around 

- Trinity version:

### Steps To Reproduce
1.
2.
3.

### Expected behaviour
What should happen. I shouldn’t lose all my IOTA...

### Actual behaviour
It’s not there 

### Errors
You can’t screenshot nothing 
![F97DED3E-22E0-4063-A4FC-4955C4034409](https://user-images.githubusercontent.com/61000304/74756376-57ba6380-526c-11ea-80ec-05b7c89c0dc2.png)

**Comment by rcop89** [comment]
Is someone having me on lol A pilots licence....

**Comment by cvarley100** [comment]
The app was taken down as a security precaution.

Please follow https://status.iota.org for ongoing updates.
