### ISSUE TITLE
App won't open on Leger

### ISSUE THREAD

**Issue by CptGrumpus** [iotaledger/trinity-wallet#2583]
Just downloaded the 1.4.2 update. When I try to restore my wallet from my ledger it gets stuck at "generating address..." and never goes through.

**Comment by honmashinsei** [comment]
Same here. It hangs at the "Loading seed for the first time." screen. The IOTA logo stops spinning, Ledger kicks back into just the IOTA app ("generating address..." message disappears) and nothing.

**Comment by cvarley100** [comment]
You have to leave it open for a while. Did you both resolve this?

**Comment by CptGrumpus** [comment]
I left it open for a long time, didn't work until I reinstalled the app
multiple times on both my ledger and on my computer.

Thanks,
Justin Smith

**Comment by rajivshah3** [comment]
@jps5482 @honmashinsei does this still happen with the latest version (1.4.5)?

**Comment by CptGrumpus** [comment]
didnt have any problems using it now with 1.4.5
