### ISSUE TITLE
Cant add seed manually, mobile Trinity Wallet busy with another action

### ISSUE THREAD

**Issue by Fumlop** [iotaledger/trinity-wallet#2585]
I tryed to enter a seed manually on a fresh created wallet...

1) Create new seed
2) Check balance shows zero --> all fine
3) add another wallet seed
4) enter manually an old seed.
5) press done

6) wallet say, busy with another action, please try again later

Cant add antoher wallet seed on latest mobile version

**Comment by cvarley100** [comment]
Fixed in #2616
