### ISSUE TITLE
Filter 0 value Data Transactions / Notifications

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/trinity-wallet#2591]
Add a feature to Trinity to filter out 0 value data transactions if the user wishes to (perhaps a setting). Additionally the user could turn off notification for new data transactions avoiding notification of spam messages.

**Comment by cvarley100** [comment]
We have this on desktop. 

<img width="175" alt="Screenshot 2020-02-23 at 11 20 13" src="https://user-images.githubusercontent.com/25092479/75111147-7b93f580-562e-11ea-85fe-6f01cf975676.png">

**Comment by Fumlop** [comment]
I leave this here, as a good proposal.

Description

As current spam on value addresses shows, we maybe need an option to ignore
a) non-value tx in trinity wallet
b) tx older as given date in options
Motivation

Prevent performance issues with massive count of tx i didnt want to see in trinity, or i cant block.
Requirements

Better UI performance
Keep tx list compact with information i want to see
Am I planning to do it myself with a PR?

No.

**Comment by cvarley100** [comment]
Duplicate.
