### ISSUE TITLE
APK at releases

### ISSUE THREAD

**Issue by MalteKiefer** [iotaledger/trinity-wallet#2595]
Hello,

is it possible to add the apk, when you release a new version?
I don't have Google Play Services, but I want to use your service.
Thanks.

**Comment by alexandre1985** [comment]
I'm in the same situation. I would also like the apk in Releases

**Comment by alexandre1985** [comment]
If not in Releases, being on F-Droid would fit the bill

**Comment by alexandre1985** [comment]
https://github.com/iotaledger/trinity-wallet/issues/2601#issuecomment-594281563

**Comment by rajivshah3** [comment]
We're currently working on F-Droid support (see https://gitlab.com/fdroid/rfp/issues/820). In the meantime I'll ask if we can post the APKs on the releases page

**Comment by nothingismagick** [comment]
From a security perspective, publicly sharing the APK in this way would make it easier to decompile and analyse - but any dedicated attacker will just instrument the app on the phone or use other tooling for grabbing the APK. Furthermore, anyone can build the APK themselves...

Nevertheless, I think that the transparency and the greater good associated with publishing the APK here outweigh the minimal increase of surface area.

I would propose however, that if the Trinity team decides to do such a thing, that it is uploaded to virustotal and we provide a link on the release page to prove that it is clean. We should also inform the user that they should always check the certificates of the signers with `apksigner verify` (which I bet 99.95% of people will not do anyway, but hey - whatever).

**Comment by rajivshah3** [comment]
> I would propose however, that if the Trinity team decides to do such a thing, that it is uploaded to virustotal and we provide a link on the release page to prove that it is clean. We should also inform the user that they should always check the certificates of the signers with `apksigner verify` (which I bet 99.95% of people will not do anyway, but hey - whatever).

Yep, good idea

**Comment by alexandre1985** [comment]
You could provide the md5sum, instead of the apksigner. Also the apk should be hosted on iota.org domain/subdomains.
This will provide, virtually, 100% security

-------- Mensagem original --------
A 8/04/2020, 20:01, Rajiv Shah escreveu:

**Comment by rajivshah3** [comment]
Hi, starting with [Trinity Mobile 1.5.0](https://github.com/iotaledger/trinity-wallet/releases/tag/mobile-1.5.0) we'll be providing APKs on GitHub for direct download. Please open an issue if you run into any problems with it

**Comment by alexandre1985** [comment]
Em Wed, 20 May 2020 14:16:44 -0700
Rajiv Shah <notifications@github.com> escreveu:

Good move.

Success.
