### ISSUE TITLE
Can`t add more than one Account

### ISSUE THREAD

**Issue by b0-ones** [iotaledger/trinity-wallet#2603]
### Bug description
In the Wallet, after I added one account by typing in my seed manually, it's not possible anymore to add another account by typing in a seed. After typing in the 81 characters seed (with showing the checksum) the pressing on the continue button does nothing. There comes no error, the account ist just not created and you can't go forward from this point only cancel the procedure. I already uninstalled the wallet and deleted %APPDATA%/Trinity. It`s reproducable on my machine, but on a friends desktop, also Windows 10 and same Trinity version it behaves as expected. Can I do antyhing to help investigate on my side? 

PS: It's still possible to add ledger accounts, i just cant create normal accounts with seedvault file or by typing in a seed manually.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Razor 
- Model: Blade Stealth
- OS version: Windows 10 Build 19536.1000

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: Trinity Desktop 1.4.3

### Steps To Reproduce
1. Install Trinity 1.4.3
2. Add one account manually by typing in a 81 character seed
3. Try to add another account by manually typing in 81 character seed. 
4. you cannot press "Continue" button, so you are not able to add another account.
5. No errors in the Log

### Expected behaviour
Add another account (Asking for the accountname after pressing continue).

### Actual behaviour
Nothing happens on the press of "continue"
![Unbenannt](https://user-images.githubusercontent.com/44143077/75614398-98ea2780-5b38-11ea-8fbb-39e8738e8695.png)
.

### Errors
No error is getting logged

**Comment by Thoralf-M** [comment]
I had the problem after I used an RC version, deleting the entries in the windows credentials fixed it for me

**Comment by b0-ones** [comment]
Indeed deleting all the entries (there were maaaanyy) in the windows credential management fixed this phenomen. Thanks Thoralf. This can be closed then.
