### ISSUE TITLE
Trinity Desktop - Can only show/print/export seed vault for the first six seeds

### ISSUE THREAD

**Issue by culnamo** [iotaledger/trinity-wallet#2609]
### Bug description
I have a total of 20 Seeds in Trinity (now after seed migration it will double). I noticed that I can only show seed, print seed and export seed vault for the first 6 seeds. For all other seeds the buttons (View seed, Print paper copy, Export SeedVault) do nothing after entring the password.

### Environment Specs

- Manufacturer: Self Build PC
- Model: Intel I5 Prozessor
- OS version: Windows 10 Pro Version 1903 Build 18362,657
- Trinity version: 1.4.3

### Steps To Reproduce
1. Goto Account Settings
2. Choose an Account which Index number is 7 or Higher 
3. Click on View Seed
4. Choose Any of the presented options (View seed, Print paper copy, Export SeedVault)
5. Enter Password
6. Click on whatever you have chosen in step 4.

### Expected behaviour
The Action on the button (View seed, Print paper copy, Export SeedVault).

### Actual behaviour
Nothing.

### Errors
No Errors

**Comment by rajivshah3** [comment]
I can't seem to reproduce this. Can you try deleting and re-adding one of the seeds to see if you can perform one of those actions?

**Comment by laumair** [comment]
I cannot seem to reproduce either.

**Comment by culnamo** [comment]
After adding the new SeedVault Files from the Migration Tool issue seem to be fixed. Before it was happening consistently. I cannot reproduce it now anymore either.
