### ISSUE TITLE
Node Error -> Transfer Error -> Transactions Won't Send (Ledger Nano)

### ISSUE THREAD

**Issue by Emily7777** [iotaledger/trinity-wallet#2626]
### Bug description
Node error that lead to transfer error.  (See screenshots attached.)
I've tried disabling the proxy.  I've tried several networks.  I can't seem to get a transfer to work.

### Environment Specs
OS = OSX, 10.14.6 on Apple Macbook Pro Hardware

- Trinity version:
1.4.3

### Steps To Reproduce
Login to wallet.
Connect Ledger Nano S with Iota app loaded
Click the account to send from on the left side bar.
Click send.
Fill in address & amount.
Click send again.

### Expected behaviour
The transaction should validate & be confirmed on the Ledger Nano S & then broadcast to the network.

### Actual behaviour
I get a node error & then send error (see screenshots).

See screenshots for error log.
![2020-03-07 10 00 30 am](https://user-images.githubusercontent.com/28765920/76137813-8bfa9600-605a-11ea-9ed7-798253a9538d.jpg)

![2020-03-07 09 50 03 am](https://user-images.githubusercontent.com/28765920/76137798-59509d80-605a-11ea-8e77-1d294777c874.jpg)

![2020-03-07 09 51 12 am](https://user-images.githubusercontent.com/28765920/76137801-62da0580-605a-11ea-9dc4-9eda9d1efd9b.jpg)

**Comment by cvarley100** [comment]
@Emily7777 The Coordinator is currently down while we resolve an attack. It will be back up tomorrow.

Please see: https://status.iota.org/
