### ISSUE TITLE
Translation not available for error message for invalid address error on QR scan

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/trinity-wallet#2633]
### Bug description
Incorrect locale on invalid address on QR scan.

### Environment Specs
What build of Trinity are you running? 

- Trinity version: 1.4.1

![IMG_1747](https://user-images.githubusercontent.com/25092479/76234152-40461900-6221-11ea-926f-c55c11db9669.PNG)

**Comment by rajivshah3** [comment]
This is probably because we now have several different strings explaining why an address is considered invalid. Which do we want to use here?

https://github.com/iotaledger/trinity-wallet/blob/d6899803039347c570da782cdbadb7cbcd53e26f/src/shared/locales/en/translation.json#L366-L370
