### ISSUE TITLE
Trinity installation stuck on Windows

### ISSUE THREAD

**Issue by Niuran78** [iotaledger/trinity-wallet#2636]
### Bug description
Stuck in the middle of Installation from File

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Desktop
- Model: 64 Bit, 32 GB, 3,6 GhZ
- OS version:Windows 10

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: Trinity 1.4.3

### Steps To Reproduce
1.Downloaded File from Github Checked SHA 256
2.Open Download
3.Download startet
4.Download stuck in the middle

### Expected behaviour
Installation should finish

### Actual behaviour
Installation from File stuck in the middle

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.
![Trinity_Stuck](https://user-images.githubusercontent.com/35644011/76368885-f0a34280-6331-11ea-952c-fed9f0ca0d0d.PNG)

**Comment by rajivshah3** [comment]
@Niuran78 how much space do you have left on your computer?

**Comment by Niuran78** [comment]
@rajivshah3 I have 200 GB space left

**Comment by KnobbyB** [comment]
I am also having the exact same problem,  have been able to update all other versions on the same pc in the past years.  Windows 10 lots of space on drive.

**Comment by KnobbyB** [comment]
In fact have the same issue on my laptop too,  also same specs

**Comment by rajivshah3** [comment]
@Niuran78 @KnobbyB could you check the following details?

- Computer manufacturer and model
- Version of Windows 10 (including edition, version, and OS build) (see [this article](https://support.microsoft.com/en-us/help/13443/windows-which-version-am-i-running))
- Antivirus programs installed (if any)
- Previous Trinity version installed (if any)

Also, does this still happen on Trinity 1.4.5?

**Comment by KnobbyB** [comment]
My pc is home built....
Ryzen 7 2700x 
32GB Ram
nvme ssd loads of room
64 bit
widows 10 home 1909
Norton antivirus but tried it with if off too with no luck
Trinity 1.4.3 currently installed and working
1.4.5 is what I am having the install issue

**Comment by Niuran78** [comment]
@rajivshah3 @KnobbyB with the new version trinity desktop 1.4.5 it works. I deleted the old version completly and downloaded trinity 1.4.5, click installation file and it worked well.

- My PC is also homebuild
- Ryzen 5 2600 Six core
- 3,4 Ghz
- 32 MB RAM
- 64bit
- windoWs 10 pro 1909
-Windows Antivirus
-Preversion was 1.4.3
no issue with 1.4.5 anymore

**Comment by KnobbyB** [comment]
Hey I did the same and all is good now,  just had to delete the 1.4.3 version?

Thanks any way

**Comment by Niuran78** [comment]
> Hey I did the same and all is good now, just had to delete the 1.4.3 version?
> 
> Thanks any way

Yeah same me
