### ISSUE TITLE
disable (show/hide) old (unsecure/unused) seeds

### ISSUE THREAD

**Issue by janviehweger** [iotaledger/trinity-wallet#2637]
It would be helpful to be able to show / hide or disable seeds in the wallet. With the latest Trinity hack, all users had to transfer their balance to a new secure seed. For keeping the transaction history in one place, many users might want keep their old seeds although not using them anymore. This leads to the problem, that one could potentially generate receiving addresses from these seeds.

**Comment by cvarley100** [comment]
As mentioned in your other issue, we are not planning minor changes like this at the moment. Users should remove their old, migrated seeds from the wallet.
