### ISSUE TITLE
Mobile: Hide Zero-Value Transactions

### ISSUE THREAD

**Issue by JA-FAR** [iotaledger/trinity-wallet#2645]
### Description
Please include the ability to hide zero-value transactions in the mobile versions of the Trinity wallet.

### Motivation
This feature is a common request from the IOTA community. Recent increases in 0i transactions with spammy messages have resulted in user frustration when using the wallet. The desktop version of Trinity is equipped with this mitigation feature. Implement this in the mobile versions to maintain feature parity across platforms.

### Requirements
When enabled, any transactions under the value threshold (0i in this case) would be hidden from view in the transaction history panel.

### Open Questions (optional)
Should this be a user-configurable threshold? 

### Am I planning to do it myself with a PR?
No

**Comment by cvarley100** [comment]
Duplicate.
