### ISSUE TITLE
All Platforms: Configure Display Units for Wallet Balance

### ISSUE THREAD

**Issue by JA-FAR** [iotaledger/trinity-wallet#2647]
### Description
Please include the ability to configure the display units for balance within all versions of the Trinity wallet. Currently, clicking or tapping the wallet balance will toggle between two display modes - abbreviated/rounded and full value. Include a feature which allows the user to configure how the balance is displayed: i, Ki, Mi, Gi, Ti, Pi.

### Motivation
The inclusion of this feature would improve the UX of the Trinity wallet.  

### Requirements
Include display options for the following units:
- i
- Ki
- Mi
- Gi
- Ti
- Pi

### Open Questions (optional)
Allow users to set a default?

### Am I planning to do it myself with a PR?
No

**Comment by cvarley100** [comment]
Minor changes like this are not currently planned for Trinity V1. We will consider them in the next version of the wallet.
