### ISSUE TITLE
🐞: "Fatal error unable to open realm at path ... " on Ubuntu

### ISSUE THREAD

**Issue by nandgator** [iotaledger/trinity-wallet#2648]
> Even though this issue seems similar to #2487 & #1594, I wish to open this as a new issue due to the following reasons:
> 1. The platform is different: #2487 is on widows but this one on Linux (Ubuntu based) - I think... it matters less, because the app is electron based, anyway.
> 2. I have some clue (about why the message is appearing which is not mentioned in #2487) which  may help in redesigning the app (https://github.com/iotaledger/trinity-wallet/issues/2487#issuecomment-579781169) / tracking the bug.

### Bug description
- The trinity wallet was set up when I had an old `$USER` (the only admin) password. I changed it recently and launched the wallet.
- The `gnome-keyring` error: `"The password you use to login in to your computer no longer matches that of your login"` came up. So I tried all the passwords but no avail. When I hit cancel, I met this:
![Screenshot from 2020-03-14 09-17-47](https://user-images.githubusercontent.com/38415384/76675023-77c71380-65db-11ea-85d0-4c1c8ebc2ddf.png)
- As you can see I installed the `libsecret-1-dev` package, but the same thing happened all over again.
- So I went according to [this - (askubuntu: How to recover / reset forgotten gnome-keyring password)](https://askubuntu.com/questions/65281/) and removed the gnome-keyring. The `gnome-keyring` asked for a new password which I gave as my current `$USER` password.
- Finally I launched trinity-wallet and was greeted with this: 
![Screenshot from 2020-03-14 10-06-54](https://user-images.githubusercontent.com/38415384/76675038-8d3c3d80-65db-11ea-927f-505b22213562.png)
> Off-topic: You can see that I cannot vertically resize the window as in #2083.

### Environment Specs
- OS & Version: elementary OS 5.1 (Hera)
- Trinity version: Stable 1.4.3 (AppImage)

### Steps To Reproduce
1. Maybe try changing your `$USER` password.
2. And see the error.

### Expected behaviour
Change in `$USER` password should not concern TrinityHotWallet (I didn't know it was linked with `gnome-keyring`). Expected a buttery smooth run.

### Errors
> ## Error launching wallet
> ### There was a fatal error launching the wallet
> Unable to open a realm at path '/home/$USER/.config/Trinity/trinity.realm': Realm file decryption failed Path:.

---

> I know you guys were in a hell of trouble after the attack, I do not wish to bother... but this is persistent...

**Comment by nandgator** [comment]
And oh... one more thing...
![Screenshot from 2020-03-14 10 36 58](https://user-images.githubusercontent.com/38415384/76675472-dc846d00-65df-11ea-9c2d-78471d841eb0.png)
Some items like `About Trinity`, `Error log`... do not respond when such errors occur. I don't know if it is expected.

**Comment by cvarley100** [comment]
@joe733 Did this resolve on wallet reset?

**Comment by nandgator** [comment]
@cvarley100 I cannot open the _Advanced Settings_ to reset the wallet. So I had to remove the configuration files form `~/.config/Trinity` after which it launched properly.

**Comment by GCiota** [comment]
@joe733 Hi Joe, thanks for sharing your knowledge. Did you fix the issue? I think I have the same problem now and I'm trying to fix it. Can I ask a few questions?

**Comment by nandgator** [comment]
@GCiota sorry for the late reply,

> Did you fix the issue?

I couldn't fix it... but as commented earlier the wallet did launch properly after I removed the `~/.config/Trinity`

**Current Status**
- Version: 1.4.3
- Account: Logged out / new / no record (cause I deleted: `~/.config/Trinity`)
- Behaviour: Asks for `gnome-keyring` on launch and if denied goes to the [first screenshot](https://user-images.githubusercontent.com/38415384/76675023-77c71380-65db-11ea-85d0-4c1c8ebc2ddf.png) on this issue.

> Can I ask a few questions?

Sure.

**Update**:
Version: 1.4.5
Account: Logged in
Behaviour: Normal (haven't tested it on `system password change` yet)

**Comment by GCiota** [comment]
1) Where can I find the ~/.config/Trinity and how can I remove? 

2) I think this happened after I changed my laptop password. Does it mean that I can fix it by re-changing my pwd back to what it was?

3) Someone recommended me to reset the wallet and re enter my seed from backup. Do you have any idea how to do it? Does it simply mean to delete the Trinity and re install?

Thank you so much.

**Comment by nandgator** [comment]
@GCiota,
> 1. Where can I find the ~/.config/Trinity and how can I remove?

Are you using `Linux` / `Windows`?
- If you are using Linux you'll find the Trinity Wallet configuration at `/home/<username>/.config/Trinity/`.
- If you are using Windows I'm not sure ... probably `AppData/Local/` the developer team can help you better and It would be effective if follow-up this issue #2487 instead.

> 2. I think this happened after I changed my laptop password. Does it mean that I can fix it by re-changing my pwd back to what it was?

I tried that but didn't seem to work, cause it opened correctly only if I provide `gnome-keyring` password.

> 3. Someone recommended me to reset the wallet and re enter my seed from backup. Do you have any idea how to do it? Does it simply mean to delete the Trinity and re install?

> @cvarley100 I cannot open the Advanced Settings to reset the wallet. So I had to remove the configuration files form ~/.config/Trinity after which it launched properly.

I couldn't reset the wallet properly, so yes in Linux removing configuration files is way of hard reset. I would recommend that your note down everything, your seeds, addresses, balance etc.
And please contact the [IOTA support](https://www.iota.org/contact-us/community-support) if you need serious help.

**Comment by GCiota** [comment]
@joe733 Thanks for your time again.

I'm using Mac OS. Catalina. Hmm.

**Comment by rajivshah3** [comment]
Sorry, I didn't see this earlier. The corresponding path to delete for macOS is `~/Library/Application Support/Trinity`

**Comment by GCiota** [comment]
Thank you so much!

**Comment by nandgator** [comment]
Closing as my environment has changed and am unable to test it. In case anybody else has the same issue, I'll be glad to re-open it.
