### ISSUE TITLE
IOTA price Restful API

### ISSUE THREAD

**Issue by alexandre1985** [iotaledger/trinity-wallet#2649]
I have notice the trinity wallet has a price chart built in.

I would like to add MIOTA as a payment coin to the services I provide, on my web page. My base coin is EUR, so I want to make the conversion from my euro price to MIOTA (in javascript, of course).

Is there an Official IOTA Restful API for that? The api that trinity wallet price chart uses to convert MIOTA to EUR would serve well.
Else I will have to write an Restful API (using an exchange market of my choice)

**Comment by alexandre1985** [comment]
I have created the api, suited for programmers, at https://iota-price.herokuapp.com

**Comment by cvarley100** [comment]
Thanks for the heads up @alexandre1985!
