### ISSUE TITLE
Making it easier to change units when sending tokens

### ISSUE THREAD

**Issue by r-c-k** [iotaledger/trinity-wallet#2653]
### Description
Allow keyboard input on Trinity Desktop to enable a quick change of the unit when sending tokens.

![trinity](https://user-images.githubusercontent.com/17240275/76774206-ece54500-67a3-11ea-8d25-4648064ac0b6.png)

### Motivation
I find it kinda unintuitive to use the dropdown to change the desired unit.

### Requirements
Press [I, K, M, G, T] after the amount to change the unit.

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
Thanks Rck, we have no plans for these sorts of "Nice to Have" changes atm. Should be considered for V2.
