### ISSUE TITLE
Using very high Ledger Indices is not ideal

### ISSUE THREAD

**Issue by vromvonbeyond** [iotaledger/trinity-wallet#2655]
### Bug description
If I want to use a very high Index with let's say 20 Numbers for my Ledger Account it is at the beginning already not so easy to delete the initial 0, because you first have to write another number and then you can delete the 0 using the arrow keys (Many people struggle already here). 
Then you only see up to 4 or 5 numbers while typing your 20 number Index into the field, so you can't really double check it before finishing the setup. 
And if you finally created your account with a 20 number index big Index and want to see it in the account settings (I think "show Seed") you only see a number that goes like this: 1.439473846 e5, so it might be useful to use more display digits, because I want exactly to know the number of my 20 digits index and not a roundet number. 

Explanation why important:
I think this feature with high indices can be used as an additional security, because if someone finds my 24 words he can steal my honeypot on index 0, but he won't find my 20digit index where all my money is and with an address notifier I will already know that there is someone aware of my Passphrase... 
Or think about your heritage. You can give all your kids a separate account on the same Ledger. And everyone gets his own 20 digits account. So you can even write your Passphrase words into the farewell letter and every kid gets a separate 20 digit Pin code maybe already at livetime... 

### Environment Specs
What device are you running Trinity on?

- Manufacturer: IOTA Foundation 
- Model: Trinity 
- OS version:

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: Latest Desktop Wallet

### Steps To Reproduce
1. Add new account with Ledger
2. Insert a 20 digit number as Index
3. See the difficulties while trying to delete the 0
4. See the difficulties when trying to see all 20 digits before creating the account 
5. Go to settings of this new created account and read the index number. 

### Expected behaviour
1. I want to delete the 0 easily with backspace and write my whole index number into the field
2. I want to see the whole index number after typing in
3.I want to see a numer like this:
12345678901234567890 and not
1.23456789e10

### Actual behaviour
1. Delete of 0 only possible if another number is added
2. Only 4 numbers can be seen inside the index field while typing
3. In the settings of the account I see a number like this:
1.23456789e10

**Comment by rajivshah3** [comment]
Summary of discussion on Discord:

- High indices should not be used as a security feature, use [advanced passphrase security](https://support.ledger.com/hc/en-us/articles/115005214529-Advanced-passphrase-security) instead
- We should restrict the index number to the range of an unsigned 31-bit integer (0 to 2147483647)
