### ISSUE TITLE
Hide 0 value transactions by default

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/trinity-wallet#2685]
## Description

0 value txes should be hidden by default.

## Motivation

Trinity addresses are getting inundated with spam and it is causing confusion.

## Requirements

Write a list of what you want this feature to do.

1. Hide by default on desktop
2. Add tx filtering on mobile and hide by default

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by SimonVillage** [comment]
I would love to see that feature. It's impossible to check my history on mobile as there is no option to filter out 0 value transactions! +1
