### ISSUE TITLE
generated seed & printed copy are different

### ISSUE THREAD

**Issue by yotardis** [iotaledger/trinity-wallet#269]
### Bug description
I installed/run trinity on my desktop, generated seed (typed 10 add. characters as advised), looked at created account settings, displayed seed, then used the print copy option on that same page ('imprimer une copie papier" in french) and ended up with a 81char string that has nothing to do with the generated/displayed seed.

### Environment Specs
Home computer

- Manufacturer: 
- Model:  MSI z77 mobo, intel quadcore i5-2500k
- OS version: Windows 7 pro SP1 64 bits

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.3.2 exe as downloaded today from your githeb

### Steps To Reproduce
1. install, run the executable
2.generate the seed & use the additional 10 characters thing
3.once generated, go to account settings and display seed
4.print the seed from the same menu

### Expected behaviour
I expected that should be the same 81char string

### Actual behaviour
trinity printed & trinity displayed string both from created account menu have absolutely nothing in common. see the first 6 characters as an exemple on line 1&2 from the printed pdf & account screenshot

![image 004](https://user-images.githubusercontent.com/42700319/44620872-3c9bad00-a89c-11e8-824d-71fdc628ec51.png)
![image 003](https://user-images.githubusercontent.com/42700319/44620874-50dfaa00-a89c-11e8-8cc1-353c3b2fa81c.png)

**Comment by yotardis** [comment]
did you get the pdf you asked for ? I Sent you the link via reddit yesterday morning…

**Comment by rihardsgravis** [comment]
> did you get the pdf you asked for ? I Sent you the link via reddit yesterday morning…

Yes, thank you - I've got the pdf. The error was that I suspected - the characters where misinterpreted while converting the raw print job to pdf (the QR code on the paper wallet contains the correct seed, but the characters are wrong). #284 fixes this issue as the seed in the paper wallet does not contains raw text (it's outlined) anymore.

**Comment by yotardis** [comment]
cool, waiting patiently for next version :)

**Comment by Drago99** [comment]
Same issue as yotardis here.
