### ISSUE TITLE
0i

### ISSUE THREAD

**Issue by marfer1977** [iotaledger/trinity-wallet#2690]
## My balance is 0i and this is wrong

My seed is < 81 characters. I entered "9" to complete 81 characters.
When accessing the account, the balance is zero. I'm sure I'm inserting the correct seed. I also used the tools (transition and sync account) and it didn't work.

## Version 1.4.5

**Comment by rajivshah3** [comment]
Have you tried going to the #help channel on [Discord](https://discord.iota.org)?
