### ISSUE TITLE
Readability of the USD value

### ISSUE THREAD

**Issue by themarkschmidt** [iotaledger/trinity-wallet#272]
### Description
Readability of the USD value should be enhanced (especially for bigger holdings).
Formatting 1500000 to 1'500'000 for example.

### Motivation
Minor UX enhancement.

### Am I planning to do it myself with a PR?
No.

**Comment by rajivshah3** [comment]
That's a good idea. We can probably use https://github.com/yahoo/react-intl/wiki/API#number-formatting-apis for this
