### ISSUE TITLE
Add ability to search transaction history by Tag

### ISSUE THREAD

**Issue by ouya99** [iotaledger/trinity-wallet#274]
### Bug description
Transactions window's search function should be able to do a TAG search

### Environment Specs
What device are you running Trinity on?
Linux

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 1.0 (desktop)

### Steps To Reproduce
1. Sent a transaction with trinity wallet (Desktop) (value 999i, messageTag: Welcome2IOTA)
2. Go to Main Screen, click on Transaction (value in iota was 999i)
3. Search in the top bar for 999 -> Transaction found! 
4. Search for "welcome...." -> Transaction not found!

### Expected behaviour
Transactions should be found by tag

### Motivation
It's needed to manage my transactions (once i have hundreds of tx)

### Am I planning to do it myself with a PR?
If you wish ... yes

**Comment by ouya99** [comment]
Maybe this search does not work at all... typing "555" also lists my transaction with value 999

**Comment by rihardsgravis** [comment]
@ouya99 The search filters transfers with equal or more value (not just equal) than you type in.

**Comment by ouya99** [comment]
@rihardsgravis Thanks for the explanation. Then it's an enhancement. For a new user it's not easy to see what fields the search is applied on, but this is even another enhancement (maybe small help icon etc..)

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
