### ISSUE TITLE
Problem mit Trinity Wallet und keine Hilfe in Sicht

### ISSUE THREAD

**Issue by SandKyler82** [iotaledger/trinity-wallet#2745]
Hallo an Alle. Ich hoffe sehr, dass mir hier jemand helfen kann. Mein Englisch ist nicht das Beste, was es nicht leichter macht. So habe ich vor ein paar Tagen versucht von meiner Trinity Wallet Iotas zu BitPanda zu senden. Aber, es geht nicht raus? Es Pendelt und wird einfach nicht bestätigt. Pitpanda sagt ich muss mich an Iota wenden. Kann mir bitte jemand helfen oder sagen, wie ich vorgehen muss, dass es funktioniert?

**Comment by Thoralf-M** [comment]
Join https://discord.iota.org/ and write in the #help channel there

**Comment by Thoralf-M** [comment]
Worked by clicking on retry, issue can be closed
