### ISSUE TITLE
Transactions window's refresh icon, does a refresh on the left sidebar only

### ISSUE THREAD

**Issue by ouya99** [iotaledger/trinity-wallet#275]
### Bug description
Transactions window's refresh icon, does a refresh on the left sidebar only

### Environment Specs
What device are you running Trinity on?
Linux

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 1.0 (desktop)

### Steps To Reproduce
1. Go to Main Screen / Transaction Panel
2. Click on its "refresh icon" (top right - right next to search text field

### Current behaviour
The Wallet's sidebar is refreshed (containing the accounts name, value, "add new account" and options and exit app)

### Expected behaviour
Transactions Window should refresh itself - or why do you have this refresh icon?

### Am I planning to do it myself with a PR?
If you wish ... yes

**Comment by ouya99** [comment]
same applies clicking on "new address" in "receive panel". Also it refreshes the left sidebar.. but in this case it also generates a new address to receive funds

**Comment by rihardsgravis** [comment]
The sidebar is not refreshed - it's disabled while the current account is updated (updating transfers, balance and spend status information) to prevent account switching while this process is happening.
