### ISSUE TITLE
Message for receiving transaction with QR code scan is limited to 37 characters

### ISSUE THREAD

**Issue by ouya99** [iotaledger/trinity-wallet#276]
### Bug description
Message for receiving transaction with QR code scan is limited to 37 characters

### Environment Specs
What device are you running Trinity on?
Linux

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v.1.0 (desktop)

### Steps To Reproduce
1. Go to "Receive Transaction"
2. Type "123456789012345678901234567" in message text field
3. Scan this QR code with Trinity mobile app (Android) -> accepted by trinity mobile
4. Repeat step 2 and 3 with "123456789012345678901234567**8**" -> not accepted

### Expected behaviour
User should be informed what is the size limit and why or the app should not allow long message text inputs

### Actual behaviour
There is a size limit for the message field - what is the limit? - will my iota transaction have a cut message text? (since only 27 TRYTES are allowed for a normal iota transaction)
If signatureMessageFragment was used a higher value would be possible, but i assume this is not intended here

### Am I planning to do it myself with a PR?
Maybe

**Comment by ouya99** [comment]
![message](https://user-images.githubusercontent.com/2676451/44623656-bea7c800-a8d4-11e8-8290-4e34618489d3.png)

**Comment by rajivshah3** [comment]
Thanks for the report @ouya99 . I can't reproduce this with iOS, maybe it's an issue with Trinity Mobile? 

>  not accepted

Could you elaborate on what happens when you scan the code? Does it fill in part of the address, none of it, cause a crash, etc?

**Comment by ouya99** [comment]
@rajivshah3 when scanning a message with 37 chars, trinity mobile fills in the correct address and correct message. When scanning a message with 38 chars, it does not take the QR code at all.. nothing happens

Tested on Linux(Desktop) in combination with Nexus5 (Android) to scan the QR code from Desktop screen

**Comment by rajivshah3** [comment]
Hi @ouya99 , is this issue still occurring?

**Comment by ouya99** [comment]
Hi @rajivshah3. Just test on macbook with Android phone. Is working now. seems fixed. Closing issue
