### ISSUE TITLE
Generated QR code for amount in Euro's is actually amount in iota

### ISSUE THREAD

**Issue by Fransooijs** [iotaledger/trinity-wallet#278]
### Bug description
When generating a QR code for Euro's in the receive tab, the QR code generated is in iotas, not €.

So a QR code to be generated for 5 euro's, actually generates a 5i QR code.

### Environment Specs
- Manufacturer:   Samsung 
- Model:              Galaxy S8
- OS version:       8.0.0

- Trinity version: v 0.4.0 (16)

### Steps To Reproduce
1. Open Trinity and go to Receive --> QR Options
2. At Amount, change the currency from i to €
3. Enter amount in Euro's and Share QR
4. scan QR code and notice the amount

### Expected behaviour
Value requested in euro's should be the same value of euro in iota

### Actual behaviour
Amount requested in euro's is the amount in iotas. I.e. 10 euro = 10 iota

**Comment by rajivshah3** [comment]
Thanks for reporting this @Fransooijs , it should be fixed in the next release

**Comment by Fransooijs** [comment]
Glad I could help. Thanks for fixing it so quickly. Amazing work y'all doing.
