### ISSUE TITLE
Trinity does not update from 1.4.5 on Ubuntu 16.04

### ISSUE THREAD

**Issue by D0LPHN** [iotaledger/trinity-wallet#2859]
## Bug description

Trinity hasn't been updating from 1.4.5 onwards on Ubuntu 16.04. When clicking "A new update is available" at the home screen, I get the following message in a pop-up window:

Download complete, Trinity will now restart to install the update.

Trinity doesn't restart but when I close the pop-up window I get this message:

Error retrieving update data
Could not retrieve update. Please check your internet connection and try again.

After closing Trinity and attempting to restart:

A JavaScript error occurred in the main process

Uncaught Exception:
Error: Object has been destroyed
    at App.module.exports.363.external_electron_.app.on (/tmp/.mount_trinitTBrFxi/resources/app.asar/dist/main.js:6104:22)
    at App.emit (events.js:182:13)

Deleting the Trinity folder in .config and downloading + freshly installing any version above 1.4.5 doesn't work - the wallet then just doesn't start.

**Comment by rajivshah3** [comment]
Does manually installing 1.5.2 not work either?

**Comment by D0LPHN** [comment]
no - then the wallet doesn't start without any message

**Comment by rajivshah3** [comment]
Can you try launching it from the command line?

**Comment by D0LPHN** [comment]
Thanks for the swift replies! 

It is going a bit over my head, but running from terminal gives me this:

Step 1: running from terminal starts AppImagelauncher and gives me this as last two lines: 
gtk-update-icon-cache: Cache file created successfully.
Directory '/home/d0lphn/.local/share/mime/packages' does not exist!

Step 2: Created /mime/packages directory +
update-mime-database  ~/local/share/mime

Step 3: new download, ~/Downloads ./trinity-desktop-1.5.2 starts AppImageLauncher, last line: 
gtk-update-icon-cache: Cache file created successfully.

Step 4: new attempt: ~/Applications$ ./trinity-desktop-1.5.2.AppImage
no response, no error, nothing

Is it something in the mime database?

**Comment by D0LPHN** [comment]
after a restart Trinity 1.4.5 also stopped working. Deleting .config/Trinity and new install solves that.

**Comment by rajivshah3** [comment]
Ok, so the issue is solved?

**Comment by cvarley100** [comment]
I believe the auto updater was disabled in 1.4.5

**Comment by D0LPHN** [comment]
Solved it by updating to Ubuntu 18.04 which was about time anyway. Works like a dream now, but didn't manage to solve the issue in 16.04
