### ISSUE TITLE
APK from Releases install error

### ISSUE THREAD

**Issue by alexandre1985** [iotaledger/trinity-wallet#2868]
## Bug description

Unable to install trinity-mobile-1.5.1-105.apk into Android 9

## Version

Which version of Trinity are you running? (Please provide the full version, you can find it in Settings > About Trinity).

- Version: trinity-mobile-1.5.1-105.apk

## Hardware specification

What hardware are you using?

- Mobile or Desktop: Mobile
- Device: Samsung Galaxy J3
- OS and version: Android 9

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Download the trinity-mobile-1.5.1-105.apk from github releases
2. Install this apk on Android

## Expected behaviour

Install Successful

## Actual behaviour

Cannot install

## What I have tried

Besides doing the install using the mobile apk AS IS in the releases (checksum is correct), I also tried to sign the apk with a self-signed certificate, and still android is giving the cannot install message

**Comment by rajivshah3** [comment]
Have you previously installed the version from Google Play?

**Comment by alexandre1985** [comment]
I have a Trinity wallet already installed using the APKPure

**Comment by rajivshah3** [comment]
That one might be signed by Google. You'll have to uninstall that one and reinstall the APK from GitHub releases since they have different certificates (the one on APKPure might be from the Play Store, which re-signs our apps with a Google key). I can also see if I can upload the latest version to APKPure

**Comment by alexandre1985** [comment]
Thank you @rajivshah3 . Wait, it seems there is the latest version on APKPure already.
On APKPure it gives an error also.
Either way, I'm gonna stop installing from APKPure and use your official releases :wink:
I'll will let you know, in a moment, how the uninstall of Trinity and install using the apk from GitHub releases went (or will go)

**Comment by alexandre1985** [comment]
Yup successful.
Congratulations in releasing Trinity Mobile outside of Play Store. Very happy.

In [Paradise](https://www.youtube.com/watch?v=1G4isv_Fylg) would be to be on FDroid too :headphones: :heart:
