### ISSUE TITLE
I have currently Trinity IOTA Light wallet 2.5.7, how do I use new version 0.3.2?

### ISSUE THREAD

**Issue by bronsin190** [iotaledger/trinity-wallet#287]
I have currently Trinity IOTA Light wallet 2.5.7? Do I need to update the version to 0.3.2? if so how can update to the latest wallet?  or do I need to download 0.3.2 version and transfer my coins. Please advise. thanks

**Comment by rajivshah3** [comment]
Hi @bronsin190 , the wallet you have is https://github.com/iotaledger/wallet. This is different from Trinity. If you'd like to test Trinity, please do not use it with amounts that you cannot afford to lose. As it's currently in beta testing, bugs may occur. You can still use the wallet you currently have for the time being, but eventually that one will no longer be supported.

**Comment by bronsin190** [comment]
Thank you so much for your reply. I'll wait for the time being.
