### ISSUE TITLE
more dependencies than listed (on RHEL 7)

### ISSUE THREAD

**Issue by cikarnd** [iotaledger/trinity-wallet#2872]
## Description

Build instructions do not account for dependencies on other GNU/Linux systems, like RHEL 7

## Version

git head

## Hardware specification

- Desktop: 
- OS and version: CentOS 7 (RHEL 7)

## Errors

The README.md file "suggests" to use gcc 4.8.
Dependencies are only listed for Fedora and Ubuntu, in RHEL libsecret-devel is also needed.
When at **_npm run deps:desktop_**, the process stops with the following first error (and a cascade after that):
```
    prebuild-install WARN install No prebuilt binaries found (target=7.3.1 runtime=electron arch=x64 libc= platform=linux)
    node-pre-gyp WARN Using request for node-pre-gyp https download 
    node-pre-gyp WARN Tried to download(404): https://static.realm.io/node-pre-gyp/5.0.5/realm-v5.0.5-electron-v7.3-linux-x64.tar.gz 
    node-pre-gyp WARN Pre-built binaries not found for realm@5.0.5 and electron@7.3.1 (electron-v7.3 ABI, glibc) (falling back to source compile with node-gyp) 
    g++: error: unrecognized command line option ‘-std=c++14’
    make: *** [Release/obj.target/object-store/src/object-store/src/binding_callback_thread_observer.o] Error 1
```
According to [this](https://stackoverflow.com/questions/36245428/c-error-unrecognized-command-line-option-std-c14), that means that a newer gcc is required there.
Though I don't know if the incorrect path to missing binaries would override this, or some other missing dependency that could be installed beforehand.

**Comment by rajivshah3** [comment]
This seems related to #2871 . I'll update the docs to fix this
