### ISSUE TITLE
Seed is unpasteable

### ISSUE THREAD

**Issue by Dimfred** [iotaledger/trinity-wallet#288]
### Seed is unpasteable
STRG+V is also grey

### Environment Specs
- Win10
- Trinity version: v0.3.2

**Comment by rajivshah3** [comment]
Hi @Dimfred , this is an intended feature for your security. Malicious websites or apps could monitor the clipboard and steal your seed.

**Comment by Dimfred** [comment]
Okay I see. Makes sense
