### ISSUE TITLE
My wallet is saying zero and i have transactions still receiving 

### ISSUE THREAD

**Issue by zureesupply** [iotaledger/trinity-wallet#2895]
## Bug description
I can’t see my balance and i have pending transactions that won’t complete. 

Briefly describe the bug.

## Version
2020
Apple version 
Which version of Trinity are you running? (Please provide the full version, you can find it in Settings > About Trinity).

- Version:
V 1.5.1 (105)
## Hardware specification

What hardware are you using?

- Mobile or Desktop: mobile 
- Device: iPhone 11
- OS and version: iOS 10

- RAM (Desktop only):
- Number of cores (Desktop only):

## Node Settings (delete if not relevant)

What are your node settings? Are you using automatic node management?

- Node settings: automatic 

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. 
2. 
3. 

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any relevant errors that you see. These could include error/crash logs or screenshots. Please ensure that these files do not contain any personal information.

**Comment by cvarley100** [comment]
Hi @zureesupply did your transactions confirm?

**Comment by zureesupply** [comment]
Yeah, they did.
