### ISSUE TITLE
installing libsecret-1-dev is not enough, needs gnome-keyring too

### ISSUE THREAD

**Issue by JoinJoin** [iotaledger/trinity-wallet#290]
In Kubuntu (18.04), when attempting to run trinity-desktop-0.3.2.AppImage, it asks you to install libsecret-1-dev but refuses to start after the installation. 

It seems, you also need gnome-keyring and it's dependencies. 

Is there a workaround for this?

**Comment by rihardsgravis** [comment]
Installing `gnome-ring` should be a required step (as it's needed to communicate to `libsecret` on some desktop environments) and it should be added to the missing linux dependencies Tutorial.
