### ISSUE TITLE
Re: Updating Trinity Wallet

### ISSUE THREAD

**Issue by jiangh77** [iotaledger/trinity-wallet#292]
When a newer Trinity Desktop Wallet come out, do I need to un-install the older version first before installing newer version or can I install newer version on top of older version without un-installing older version

Thank you

**Comment by rajivshah3** [comment]
Hi @jiangh77 , when a new version comes out you should be able to download it and install it on top of the older version. Since the app data is not stored in the same location as the application itself, your information should be preserved in the update.

**Comment by jiangh77** [comment]
Thank you
