### ISSUE TITLE
Re: Using wallet without Changing Node

### ISSUE THREAD

**Issue by jiangh77** [iotaledger/trinity-wallet#293]
When using Trinity Wallet to send a transaction, is the wallet automatically connected to node or do I need to connect to a node manually before sending

Thank you

**Comment by rajivshah3** [comment]
Hi @jiangh77 , when you first set up the wallet it is automatically connected to a node which is selected from a list. If you would like to connect to another node, you can do so in the wallet settings.

**Comment by jiangh77** [comment]
Thank you
