### ISSUE TITLE
Didnt get my Gi only a fraction of it 

### ISSUE THREAD

**Issue by Jos3H2R** [iotaledger/trinity-wallet#2950]
I didnt recieved what I was suppose to get in my wallet. I was waiting for 2.5Gi and got 2.5Ki transfered instead. The person who send the transaction gave me the detailed and everything was correct but is not reflected in my account balance

This is the bundle hash 9TZDLJ9EQLITCKDWYPHXYOIZHUGNBYHWIWIFIXWNAXSK9VVGUGFFADCZVKGTGRDTL9NSCVARFAEQHLKEW

Can you help me get my Gi?

**Comment by rajivshah3** [comment]
It looks like the sender pressed the wrong unit, as only 2.5 Ki was sent: https://thetangle.org/bundle/9TZDLJ9EQLITCKDWYPHXYOIZHUGNBYHWIWIFIXWNAXSK9VVGUGFFADCZVKGTGRDTL9NSCVARFAEQHLKEW
