### ISSUE TITLE
Re: Changin to a new PC

### ISSUE THREAD

**Issue by jiangh77** [iotaledger/trinity-wallet#296]
When I change to a new PC, would I be able to download Trinity Desktop Wallet and install again and have access to my account using the same seed I generated?  Then I can un-install Trinity Desktop Wallet on my old PC

Thank you

**Comment by rajivshah3** [comment]
Yes, as long as you have your seed safely backed up you can log in and access your funds from any wallet. Your IOTA are always associated with your seed, not your device.

For future reference, you can ask these types of questions in the #help or #trinity-discussion on [Discord](https://discord.gg/fNGZXvh). Issues on GitHub are generally used for bugs only.
