### ISSUE TITLE
Error message when checking for updates manually

### ISSUE THREAD

**Issue by octocat-mona** [iotaledger/trinity-wallet#297]
### Bug description
Error window shown when checking for updates.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Windows
- Model: 10
- OS version: 1803

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 
`0.3.2`
### Steps To Reproduce
1. Create new wallet
2. Click the hamburger settings menu -> `Trinity` -> `Check for Updates...`
3. Error screen pops up

### Expected behaviour
No updates available message should have shown.

### Actual behaviour
Error window pops up.

### Errors
![image](https://user-images.githubusercontent.com/538170/44752013-0a977e80-ab1a-11e8-9a7c-8415883cc390.png)

Hamburger settings menu -> `Trinity` -> `Error log` shows an empty screen

![image](https://user-images.githubusercontent.com/538170/44752112-59451880-ab1a-11e8-914a-d4b9425bd684.png)

**Comment by rihardsgravis** [comment]
Fixed with #282
