### ISSUE TITLE
Android app V1.5.1 requests "critical update", cannot start configuring the app.

### ISSUE THREAD

**Issue by schultz-it-solutions** [iotaledger/trinity-wallet#2976]
## Bug description

Just installed the android app from Google Play, The app opens with the initial screen to select user's language and a button "Los geht's" (let's go).
The app also shows a warning to "update, because a critical update was released".
Tapping the "Los geht's" button does not start any action.

## Version
1.5.1 android

- Version:

## Hardware specification

What hardware are you using?

Android smartphone LG Q6

## Node Settings (delete if not relevant)

What are your node settings? Are you using automatic node management?
Default probably -  don't know, as I cannot access the settings page

## Steps To reproduce the bug

Install the app
start the app

## Expected behaviour

"Los geht's" button should actually do something...

## Actual behaviour

"Los geht's" button should does nothing.

**Comment by cvarley100** [comment]
Hey @schultz-it-solutions. We are still awaiting reviews from Google and Apple on mobile. We'll announce on Discord when the new version is out.

**Comment by 212Herm** [comment]
I’m having the same issue on my iPhone 11 Pro, can’t log to my wallet

**Comment by 212Herm** [comment]
I have funds in my wallet that I can no longer access because the app won’t start.

**Comment by cvarley100** [comment]
@212Herm You will need to use the desktop version until Apple and Google finish their reviews.

**Comment by schultz-it-solutions** [comment]
I do understand that this update is critical.
However, as a "lesson-learned" you might want to consider a different provisioning-process for the future (e.g. not blocking access to the app / current version, while waiting for google and apple to accept the update). I know from personal experience, that this can take a few days.

**Comment by cvarley100** [comment]
Indeed @schultz-it-solutions. Unfortunately, however, this was unavoidable. We had to make last minute changes to address an issue, which meant a late submittal for review. The critical update alert was triggered to block use of old app versions (< 1.6.0) because they allowed connection to unsafe nodes (i.e. nodes that had not updated to Hornet 0.5.0 and the breaking protocol changes).

**Comment by cvarley100** [comment]
Play store version available as of 20/08/2020.
