### ISSUE TITLE
Trinity insists I attach ledger to refresh wallet after chrysalis update, normal?

### ISSUE THREAD

**Issue by IGit666** [iotaledger/trinity-wallet#2978]
After the chrysalis update, I logged into Trinity to see how it behaved. Wallet balance was not up to date, several transactions over the last few weeks were not there. On refresh, got error about too few nodes for quorum. On advice from discord, disabled quorum. After again attempting refresh, now trinity prompts me to attach ledger, which is fine, but I don't see why that should be necessary for transactions that have already taken place. (also trinity and ledger don't behave well together, for me at least, I have to have the ledger already turned on and appropriate wallet active before opening trinity, or trinity will not recognize my ledger). 

After initializing and attaching ledger, then reopening trinity, I could successfully refresh my wallet and the expected transactions appeared. 

Version: trinity-desktop-1.6.0

Mobile or Desktop: Desktop

OS and version: Windows 10

RAM (Desktop only): 16gb

**Comment by cvarley100** [comment]
If Trinity needs to generate an address (e.g. the latest address in the wallet's state is used) then it will ask you to connect your Ledger.
