### ISSUE TITLE
Deeplinking Autofill doesn´t work on Trinity Desktop

### ISSUE THREAD

**Issue by Cryptec** [iotaledger/trinity-wallet#2980]
## Bug description

I tested a Deeplink (=> https://tinyurl.com/ybmo7ckx ) On Trinity Mobile, and it works fine with autofill, on Windows Trinity opens, but doesn´t fill the address field. 

## Version

- Version: 1.6.0 

## Hardware specification

- Mobile or Desktop: Deskotp 
- Device: HP Workstation Z230
- OS and version: Windows 10 Pro	10.0.19041 Build 19041
- RAM (Desktop only): 16GB
- Number of cores (Desktop only) 4:

## Steps To reproduce the bug

Try to open the Deeplink in Trinity desktop ( https://tinyurl.com/ybmo7ckx ) 

in our code: ( iota://${response}/$amout=1&message=Trustify_tip )

## Expected behaviour

Trinity should fill the adress from {response} automatically, like it does on Mobile.

## Actual behaviour

Trinity opens, nothing more happen

**Comment by rajivshah3** [comment]
Weird, I thought we had fixed this 🤔

**Comment by rajivshah3** [comment]
Was Trinity already open when you clicked the deep link?

**Comment by Cryptec** [comment]
> Was Trinity already open when you clicked the deep link?

I tried both (open and closed), with same result

**Comment by rajivshah3** [comment]
I can't seem to reproduce the issue on macOS, so it seems like it might be Windows-specific 🤔

**Comment by Cryptec** [comment]
> I can't seem to reproduce the issue on macOS, so it seems like it might be Windows-specific 🤔

Yes i can confirm. I tested it now on MacOS and it works. Also on Trinity for Android. But it failed on two diferrent windows machines
