### ISSUE TITLE
IOTA/Trinity Mobile wallet - Android

### ISSUE THREAD

**Issue by hartll** [iotaledger/trinity-wallet#2984]
## Bug description

downloaded Trinity to my phone. can not create ledger account index "1i" to access ledger hardware wallet 

## Version

1.6.0

- Version:

## Hardware specification

What hardware are you using?

- Mobile  
- Device: HTC U11life
- OS and version: Android 10

## Expected behaviour

like with Trinity desktop version, create new account and choice ledger account index no problem

## Actual behaviour

when adding new acount, can't select ledger account index 

## Errors

New account is added, but always with "0i".

**Comment by rajivshah3** [comment]
Trinity Mobile does not support Ledger devices at this time

**Comment by hartll** [comment]
Thanks Raji...
