### ISSUE TITLE
Trinity Wallet can't update 26-08-2020

### ISSUE THREAD

**Issue by RubenHelder** [iotaledger/trinity-wallet#2997]
Hello everyone,

I'm having problems with my trinity desktop wallet.

After their launch of Chrysalis 1.5 I have to update my Wallet. When I press 'update' nothing happens. So I can't acces my wallet. Can anyoe help me?

**Comment by cvarley100** [comment]
Hi @RubenHelder. Auto update was disabled in a couple of versions. You can download it here: https://github.com/iotaledger/trinity-wallet/releases/tag/desktop-1.6.0
