### ISSUE TITLE
Error Launching Wallet

### ISSUE THREAD

**Issue by huggre** [iotaledger/trinity-wallet#3007]
## Bug description
Get the following error message when trying to open Trinity Desktop on my Windows 10 PC:

**Unable to open a realm at path 'C:\Users\Hugo\AppData\Roaming\Trinity\trinity.realm': Realm file decryption failed Path:Exception backtrace:
<backtrace not supported on this platform>.**

Briefly describe the bug.

I can no longer access Trinity or my Trinity accounts. 

Which version of Trinity are you running? (Please provide the full version, you can find it in Settings > About Trinity).

1.6.0

What hardware are you using?

Desktop, Windows 10

![Capture](https://user-images.githubusercontent.com/18450425/91544576-3378c700-e920-11ea-96ba-d6835f020e7a.PNG)

**Comment by cvarley100** [comment]
@huggre The best thing to do is to delete the Trinity folder in Roaming (`AppData\Roaming\Trinity`) and set up the wallet again
