### ISSUE TITLE
Trinity Log In not possible due to "error retrieving update data" with internet available on regular browser

### ISSUE THREAD

**Issue by snckills** [iotaledger/trinity-wallet#3012]
## Bug description

Briefly describe the bug.

can no login on wallet 1.5.2 due to update required but error retrieving update data. message is "error retrieving update data"
download of wallet software on trinity page wants to download version 1.4.2. exe file. github shows me version 1.6 as latest.

## Version

Which version of Trinity are you running? (Please provide the full version, you can find it in Settings > About Trinity).

- Version: 1.5.2

## Hardware specification

What hardware are you using?

- Mobile or Desktop:  amd
- Device:
- OS and version:

- RAM (Desktop only): 16gb
- Number of cores (Desktop only): 8

## Node Settings (delete if not relevant)

What are your node settings? Are you using automatic node management? automatic node management

- Node settings: 

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. doubleclick version 1.5.2 desktop link
2. get update message, click link or use menu to check 
![trinity_error](https://user-images.githubusercontent.com/36031919/91630209-c3c21500-e9cf-11ea-914d-2da4f32d02a9.JPG)
for update (internet OK on reguilar browser)
3. recieve error message "cannot retrieve update data"

## Expected behaviour

Describe what you expect to happen.

update the wallet. login to wallet

## Actual behaviour

Describe what actually happens.

recieve error message. "error retrieving update data"

## Errors

"error retrieving update data"

Paste any relevant errors that you see. These could include error/crash logs or screenshots. Please ensure that these files do not contain any personal information.

**Comment by snckills** [comment]
Issue fixed after installing: https://github.com/iotaledger/trinity-wallet/releases/tag/desktop-1.6.0

But please: Why do you provide a 1.4.2 exe on the regular "download" button on trinity homepage. This is so close to the hacked version. At first glance i thought someone is trying to trick regular users into hacked version. Also is the 1.4.2 even working?  No regular user will go to github to download the latest wallet version.

**Comment by cvarley100** [comment]
The updater is now fixed.
