### ISSUE TITLE
Missed IOTAS

### ISSUE THREAD

**Issue by RipexXx29** [iotaledger/trinity-wallet#3015]
Well i'm having the following problem if someone could give me an opinion i really thanks. Today after three months maybe i opened my trinity wallet again to see my tokens when i was trying to opened it i got a message that says another update was required so i updated the wallet to the last version 1.6.0 but after log in i notice there were not tokens, my balance showed 0i i supposed it needed a synchronization but after try for a while nothing happend i refresh the transaccions and i notice there was a send transaccion for my all balance like two months ago i don't know if this was part of the updated kind of snapshot or something but i've not been able to recover my balance i don't know where to find some information about it so if someone know how to fix this. please i really need help

**Comment by rajivshah3** [comment]
Please go to the #help channel in [Discord](https://discord.iota.org)
