### ISSUE TITLE
Can not install Trinity on Xenialpup 7.5 CE

### ISSUE THREAD

**Issue by gjeee** [iotaledger/trinity-wallet#302]
### Bug description
I can not install Trinity on a Linux Puppy distro (more specific Xenialpup 7.5 CE). Trinity says I miss a specific libsecret package:

![ss2](https://user-images.githubusercontent.com/13155183/44798683-6c0b2c00-abb2-11e8-93f0-7fdcbf154b60.png)

However I double checked and I do seem to have this particular lib. Pls see screenshot below:

![ss4](https://user-images.githubusercontent.com/13155183/44798672-66154b00-abb2-11e8-8d02-30aa1c08a99c.png)

The [packagelist](https://distrowatch.com/table.php?distribution=puppy&pkglist=true&version=7.5) also confirms this.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: N/A
- Model:  N/A
- OS version: Xenialpup 7.5 CE
- Trinity version: v0.3.2

**Comment by rajivshah3** [comment]
Hi @gjeee , have you tried installing `gnome-keyring`? According to #290 this might be necessary as well

**Comment by gjeee** [comment]
am i missing something from this list?

![ss5](https://user-images.githubusercontent.com/13155183/44802220-aa045200-abaa-11e8-8a46-23debeaa10f5.png)

**Comment by rihardsgravis** [comment]
Fixed in #300
