### ISSUE TITLE
Cant send iota 

### ISSUE THREAD

**Issue by Enflow-io** [iotaledger/trinity-wallet#3037]
## Bug description

Hi, I cant send iota to any address. Error: "Sending from the same address more than once is dangerous."
After that error I made zero transaction to refresh address. But error again: "Something went wrong while sending your transfer. Please try again"

I use ledger.

## Version

Last version   1.6.0 windows

- Version: 1.6.0 windows

## Hardware specification

What hardware are you using?

Desktop, windows 10
- RAM (Desktop only): 8gb
- Number of cores (Desktop only): 4

## Node Settings (delete if not relevant)

What are your node settings? Are you using automatic node management? automatic

- Node settings: 

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. try to send transcation with ledger nano on windows

## Expected behaviour

succesfull transaction

## Actual behaviour

error

## Errors

"Sending from the same address more than once is dangerous."
"Something went wrong while sending your transfer. Please try again"

**Comment by HBMY289** [comment]
This is not a bug, but a feature. You have funds on an address that was already spent from. Trinity protects you from signing the same address again and putting your funds at risk. Join the iota Discord server and come to the #help channel for possible solutions.
