### ISSUE TITLE
Remove react-native-webview

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#3040]
## Description

We need to remove `react-native-webview` as it's no longer used. The App Store will no longer accept apps with UIWebView starting in December:

```
ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
```

## Are you planning to do it yourself in a pull request?

Yes

**Comment by HunainHumail** [comment]
I would love to work on this issue if you would allow me @rajivshah3

**Comment by rajivshah3** [comment]
@HunainHumail Sure! Please feel free to let me know if you need help

**Comment by HunainHumail** [comment]
Sure @rajivshah3 :)

**Comment by rajivshah3** [comment]
Hi @HunainHumail , are you still working on this?
