### ISSUE TITLE
Trinity Desktop 1.6.1 renders a wrong notification

### ISSUE THREAD

**Issue by christopher-wilke** [iotaledger/trinity-wallet#3048]
## Bug description

After upgrading to 1.6.1, I see a notification to upgrade to 1.6.1

## Version

1.6.1

## Hardware specification

What hardware are you using?

- Mobile or Desktop:  Desktop
- Device: Windows
- OS and version: 10

![TrinityBug](https://user-images.githubusercontent.com/19839228/92567551-247a0900-f27e-11ea-857e-b0080790b68c.JPG)

**Comment by cvarley100** [comment]
This will be fixed now.
