### ISSUE TITLE
Mac Trinity fails to check for update

### ISSUE THREAD

**Issue by joanmarcriera** [iotaledger/trinity-wallet#306]
### Bug description
Open Trinity 0.3.2 in Mac and check for update, error appears. 

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: MacBook Air 13-inch Early 2015
- OS version: macOs High Sierra 10.13.6

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.3.2

### Steps To Reproduce
1.  Start trinity 
2. Password for wallet
3. Mac Menu, Trinity -> Check for updates

### Expected behaviour
Some check , and update available or already in last version

### Actual behaviour
Picture attached of error .
Error retrieving update data. 

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.
![image](https://user-images.githubusercontent.com/402036/44867444-b4dce680-ac7f-11e8-81e5-bc1ceb457a94.png)

![screen shot 2018-08-30 at 18 03 50](https://user-images.githubusercontent.com/402036/44867204-13559500-ac7f-11e8-8ba2-402f753c08ea.png)

**Comment by yotardis** [comment]
same "yml" error on windows (v0.3.3). seems global

**Comment by rajivshah3** [comment]
@joanmarcriera I think this was fixed in v0.3.3

**Comment by rajivshah3** [comment]
@yotardis you're still seeing this bug?

**Comment by yotardis** [comment]
ah sorry, I downloaded 0.3.3 and thought I had installed it already when I checked that update thing, but I must have done it a bit later, I don't see it right now indeed, sorry for false alarm

**Comment by rihardsgravis** [comment]
Fixed in #282

**Comment by AlphanB** [comment]
Same error is exist in v0.3.6 on Windows. No problem with v0.4.0.
I think new version's folder structure of github repo is breaking old ones' update-file-path.
May be, there will be a global constant URL for version check.

**Comment by albertolive** [comment]
I have the same version with 0.4.1 trying to download 1.0.0:

![image](https://user-images.githubusercontent.com/1182864/60680928-7ca0c880-9e8d-11e9-847a-db36b1b563f4.png)
