### ISSUE TITLE
Translate paper wallet into other languages

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#310]
### Bug description
Translation request

### Environment Specs
What device are you running Trinity on?

- Manufacturer: PC
- OS version: Windows 7 x64

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.3.3

### Request
I would like to see paper wallet translated. I can fully translate it to PL language for example.
It's just a few lines.

**Comment by cvarley100** [comment]
This would require significant changes on mobile. But it is less difficult to do on desktop.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
