### ISSUE TITLE
Node Error

### ISSUE THREAD

**Issue by Billyboola** [iotaledger/trinity-wallet#3120]
## Bug description

When trying to log into my IOTA Account i get the message: "Node Error. The node error returned an error while fetching your account information. Try changing node".
I tried different nodes (manually selected some) and still getting the error.
I also completely uninstalled and reinstalled the IOTA Desktop Wallet and still same error. Same happen in mobile version.
I also tried to disable the System Proxy Setting same error.

## Version
- Version: v1.6.1

## Hardware specification

What hardware are you using?
macOS CATALINA v10.15.7- Mobile or Desktop: 

- RAM (Desktop only): 8GB
- Number of cores (Desktop only): 3,4 GHz Quad-Core Intel Core i5

## Node Settings (delete if not relevant)

What are your node settings? Are you using automatic node management?
Automatic and manual
- Node settings: 
https://nodes.thetangle.org:443
https://durian.iotasalad.org:14265
https://potato.iotasalad.org:14265

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.
Every login. I'am not able to login.
1. 
2. 
3. 

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.
Remains in the initial screen. Nothing else.
## Errors
This is the message:
"Node Error. The node error returned an error while fetching your account information. Try changing node".

Paste any relevant errors that you see. These could include error/crash logs or screenshots. Please ensure that these files do not contain any personal information.

**Comment by rajivshah3** [comment]
Hi, the coordinator is currently down. Please follow https://status.iota.org for updates
