### ISSUE TITLE
Rounding discrepancy between balance and list item

### ISSUE THREAD

**Issue by obany** [iotaledger/trinity-wallet#314]
### Bug description
The iota total shown in the balance is rounded using a different method than the items in the transactions list.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Microsoft
- Model: Surface Book
- OS version: Win10
- Trinity version: 0.3.3

### Steps To Reproduce
1. Viewing account that has single transaction of 26666666667
2.
3.

### Expected behaviour
The balance and list item should show the same amount for the rounded iotas.

### Actual behaviour
The balance shows 26.6+ Gi and the list item shows 26.7 Gi

### Errors
![balance](https://user-images.githubusercontent.com/5030334/44909731-1f962c80-ad29-11e8-9d7c-8fb6adc05675.PNG)
![list](https://user-images.githubusercontent.com/5030334/44909736-215ff000-ad29-11e8-9910-06314507af66.PNG)

**Comment by cvarley100** [comment]
@obany The balance is not rounded. The + is a placeholder for the less significant digits.

I guess it's another argument whether that's a good idea or not.
