### ISSUE TITLE
Check for Updates Dialog reports error

### ISSUE THREAD

**Issue by DaveRL** [iotaledger/trinity-wallet#315]
### Bug description
When selecting Check for Updates from the menu before logging in Trinity checks for updates and reports that I have the latest release. The dialog has no buttons to dismiss and no title bar icons to close. Clicking back on the application causes the dialog to disappear but the menus on Trinity are blank and the application is non-functional. Also the console get's the following message

`Checking for update
Update for version 0.3.3 is not available (latest version: 0.3.3, downgrade is disallowed).
Gtk-Message: 08:44:27.166: GtkDialog mapped without a transient parent. This is discouraged.`

### Environment Specs
Dell Inspiron N5040
Linux Mint 19 Cinnamon
Trinity 0.3.3

### Steps To Reproduce
1.Open Trinity (Do not log in)
2. Select Check for Updates... from the menu (wait for the check to complete)
3. When the dialog appears, click outside of the dialog
4. Dialog disappears, the menu becomes blank and Trinity is unresponsive. 
5. if Trinity is run from the command line then error message above is visible.

### Expected behaviour
Dialog closes correctly

### Actual behaviour
Dialog disappears but most likely does not close correctly

### Errors
Gtk-Message: 08:44:27.166: GtkDialog mapped without a transient parent. This is discouraged

**Comment by DaveRL** [comment]
![screenshot from 2018-08-31 08-50-15](https://user-images.githubusercontent.com/108496/44924578-910db500-ad00-11e8-9f08-668dd945f1b5.png)

**Comment by stricki** [comment]
On windows 10 I get the message that latest.yml cannot be found. I got version 0.3.2 and wanted to update to version 0.3.3
![trinity_update_error](https://user-images.githubusercontent.com/17906700/44926146-cc37d480-ad50-11e8-851d-cbbe1a563554.png)

**Comment by PJanisio** [comment]
When trying to check update from 0.3.2, error message below (win7):

![err](https://user-images.githubusercontent.com/9625885/44949801-4cd20000-ae39-11e8-9126-5905c9328812.PNG)

**Comment by rajivshah3** [comment]
Hi @PJanisio , yours is a different issue which was fixed in version 0.3.3 (see #282). The issue here is that there doesn’t seem to be any “close” or “OK” buttons on the dialog that pops up when an update isn’t available

**Comment by rihardsgravis** [comment]
Fixed in #510
