### ISSUE TITLE
QR Sent generator is not converting from currency to IOTA

### ISSUE THREAD

**Issue by Wingman2** [iotaledger/trinity-wallet#317]
QR Sent generator is not converting from currency to IOTA

### Bug description
When asking to receive IOTA from the mobile wallet and imputing the value in a selected currency ie,(US$). The QR generated is asking for the value inputted in US$, not in the IOTA equivalent 

### Environment Specs
Android 8, One Plus 5 for asking and sending from PC windows 10

- Manufacturer: Oneplus
- Model: 5
- OS version: Android 8.1.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.4.0(16)

### Steps To Reproduce
1. Login
2. Click  Receive
3. Change unit by click on the right of the input amount field to (US$ or $)
4. Type 1,  o the right you can seed the equivalent in IOTA (1,37 Mi) but the QR code is asking for 1 IOTA

### Expected behavior
What should happen? QR generated should ask for 1,37Mi

### Actual behavior
What really happened. QR generated for 1 IOTA

### Am I planning to do it myself with a PR?
No.

**Comment by rajivshah3** [comment]
Hi @Wingman2 , this bug was fixed in https://github.com/iotaledger/trinity-wallet/pull/298. It should appear in the next release
