### ISSUE TITLE
2FA - automatic trigger of confirmation once necessary amount of numbers is typed in

### ISSUE THREAD

**Issue by SvenHildebrandt** [iotaledger/trinity-wallet#318]
Description

When I enter the 2FA-Code, the wallet should note once I typed in the necessary amount of numbers and then trigger the confirmation automatically instead of having to hit "register" to confirm the code. 

See 2FA at Binance or Bitfinex for example.

Motivation

Minor UX enhancement.

Am I planning to do it myself with a PR?

No.

**Comment by rajivshah3** [comment]
Hi @SvenHildebrandt , I think this is the expected behavior on Trinity Mobile. Are you referring to Trinity Desktop? If so, then I agree, as the goal is to have the same UI flow/behavior on both Mobile and Desktop

**Comment by SvenHildebrandt** [comment]
Yup - referring to desktop mac.

**Comment by cvarley100** [comment]
Fixed in https://github.com/iotaledger/trinity-wallet/pull/353
