### ISSUE TITLE
Password not recognized

### ISSUE THREAD

**Issue by NathanHazout** [iotaledger/trinity-wallet#3188]
I haven't looked at my wallet in a very long time.  
Today I opened trinity, it immediately asked me to install the latest version (1.6.1).  
Upon restart, it showed a single field called "password".  

I pasted my password, which I have in 1Password. It's a long string of uppercase letters. That's the only password I have as far as I know ...

Yet I get "unrecognised password".

What's the deal?

**Comment by rajivshah3** [comment]
Hi, are you sure you're not confusing your password with your seed? Your seed is 81 characters. If you forget your password, you can reset the wallet through the settings

**Comment by NathanHazout** [comment]
Thanks that worked. I guess this password feature is RELATIVELY new? Because I didn't have one before.
