### ISSUE TITLE
Order of confirmation / not confirmation (yes / no) buttons

### ISSUE THREAD

**Issue by SvenHildebrandt** [iotaledger/trinity-wallet#319]
Description

Atm, the whole wallet has a no / yes order regarding confirmation buttons for example. I believe this is (or it just feels) uncommon for me, if I am used to a yes / no order. 

Maybe this is just a personal feeling. 

Motivation

Minor UX enhancement.

Am I planning to do it myself with a PR?

No.

**Comment by rajivshah3** [comment]
I haven't used Windows in a few years so I don't really remember, but for me it's generally no/yes (I use a Mac) 
![image](https://user-images.githubusercontent.com/19519564/44958200-b2aaa000-aeaa-11e8-86e3-5bc10322535f.png)

**Comment by SvenHildebrandt** [comment]
You are correct - I obviously had the wrong "feeling" about it. 

Please nevermind and see this comment as "done".

**Comment by rajivshah3** [comment]
👍
