### ISSUE TITLE
Automatic setting of currency

### ISSUE THREAD

**Issue by SvenHildebrandt** [iotaledger/trinity-wallet#321]
Description

Maybe the trinity wallet could link the selected currency to the country chosen? At the moment most of us would probably use USD as in default, but maybe this will change at a later time. 

Motivation

Minor UX enhancement.

Am I planning to do it myself with a PR?

No.

**Comment by cvarley100** [comment]
I don't think it makes sense to link these two. One is language, one is currency. Linking them would likely cause more confusion than convenience.
