### ISSUE TITLE
wrong Balance

### ISSUE THREAD

**Issue by MarcoBreddels** [iotaledger/trinity-wallet#3217]
I installed Trinity Mobile wallet. Did twice a deposit from Binance. Now my balance is zero because the wallet send twice to another adress. I don't understand. What is wronng and pease help?
Marco

**Comment by MarcoBreddels** [comment]
![image](https://user-images.githubusercontent.com/78413126/106584849-f8ba3100-6546-11eb-8fe0-cd529a87e7e3.png)
![image](https://user-images.githubusercontent.com/78413126/106584928-0ec7f180-6547-11eb-8a71-7d9868131be2.png)

**Comment by laumair** [comment]
@MarcoBreddels Did you make both transactions (234.5 Mi & 1.1 Gi) yourself? 

Also, could you please share the current version of the wallet (application)?

**Comment by MarcoBreddels** [comment]
2 into my wallet yes but the latent 2 not
Op di 2 feb. 2021 om 16:13 schreef Umair Sarfraz <notifications@github.com>

**Comment by MarcoBreddels** [comment]
The received yes and send not

Op di 2 feb. 2021 om 16:19 schreef marco breddels <breddels35@gmail.com>

**Comment by MarcoBreddels** [comment]
Op di 2 feb. 2021 om 16:21 schreef marco breddels <breddels35@gmail.com>

**Comment by MarcoBreddels** [comment]
![image](https://user-images.githubusercontent.com/78413126/106703408-7420ee80-65ea-11eb-9f84-d51a16a8486d.png)

**Comment by MarcoBreddels** [comment]
![image](https://user-images.githubusercontent.com/78413126/106703430-7edb8380-65ea-11eb-993b-1463c3d3653f.png)

**Comment by MarcoBreddels** [comment]
![image](https://user-images.githubusercontent.com/78413126/106703449-88fd8200-65ea-11eb-83a0-c6e90594cb63.png)

**Comment by MarcoBreddels** [comment]
The 2 received I did myself and the 2 send I did not.

**Comment by MarcoBreddels** [comment]
Verstuurd vanaf mijn iPhone

**Comment by MarcoBreddels** [comment]
Tje 2 received I did myself and the 2 send not.

Verstuurd vanaf mijn iPhone

**Comment by MarcoBreddels** [comment]
So, is there an answer?

**Comment by rajivshah3** [comment]
Hi, please join our Discord for assistance (https://discord.iota.org)

**Comment by MarcoBreddels** [comment]
Hello, I did that but they can’t help me.

Listen, i downloaded a Trinity wallet en put Iota on it and have a problem.
On Discord and GitHub they don’t help me so where cannI go? I miss 1345
Iota coins.

Best regards,

Marco

Op za 13 feb. 2021 om 22:55 schreef Rajiv Shah <notifications@github.com>
