### ISSUE TITLE
Biometric Auth failed

### ISSUE THREAD

**Issue by mbeliv** [iotaledger/trinity-wallet#323]
Hi can’t use biometric finger print anymore, also the fingerprint doesn’t show anymore beside the password
![d4e372b9-0021-4e3f-b1d7-405524e730f7](https://user-images.githubusercontent.com/379873/44960527-4f7f3480-aecf-11e8-8dc8-55b164f6a1ad.png)

By resetting my wallet, they asked me for my old seed and also they permit me to create a new password.  So it means that anybody reinstalling a wallet can try any new seeds and reset any password and if lucky get into any wallets at the end.

The issue tracker is only for reporting bugs or asking for feature requests.
If you need technical assistance for using Trinity Wallet, please consult the Trinity [documentation](https://docs.iota.works/trinity) and [knowledge base](https://iotaledger.atlassian.net/wiki/spaces/trinity/overview). For further assistance, please visit the #help channel on [Discord](https://discord.gg/7Gu2mG5).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).

### Bug description
A general description of the bug.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: 
- Model: 
- OS version:

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 

### Steps To Reproduce
1.
2.
3.

### Expected behaviour
What should happen.

### Actual behaviour
What really happened.

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

**Note**
The feature request will probably be integrated faster if you do a pull request for it.
If you want to discuss the feature before you actually write the code you are welcome to do it by first submitting an issue.

### Description
Briefly describe the feature you want.

### Motivation
Explain why this feature is needed.

### Requirements
Create a list of what you want this feature request to fulfill.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
Yes/No.

**Comment by cvarley100** [comment]
Hi @mbeliv.

Please provide more details regarding your Biometric Authentication issue.

Regarding your concerns about managing to enter someone else's seed, this video may be informative: https://www.youtube.com/watch?v=p8YIdmwcubc&feature=youtu.be

**Comment by rajivshah3** [comment]
@mbeliv are you still experiencing this issue?
