### ISSUE TITLE
Create a universal linux Flatpak container for Trinity

### ISSUE THREAD

**Issue by jbingram** [iotaledger/trinity-wallet#3232]
Thx for your awesome job, much appreciated.

## Description (Briefly describe the feature that you are requesting.)

Create linux Flatpak sandboxing for Trinity and inform the general flathub.org repository. https://flathub.org/

## Motivation (Explain why this feature is needed.)

- Flatpak apps are sandboxed apps that are more secured than traditional linux packaging systems (e.g. .deb, .rpm, .tar.gz). The users can run Trinity software in isolation from the rest of the linux system. 
- Flatpak is universal, as it allows a single application build to be installed and run on virtually any Linux distribution. 
- Flatpak apps can also be used in combination with Flathub, a centralized service for distributing applications on all distributions. This makes it possible for application developers to target the entire Linux desktop market from one place. 
- Flatpak apps are natively integrated into all Linux desktops, tablets and now smartphones, so that users can easily browse, install, run and use Flatpak applications through their existing desktop environment and tools. 
-  Forward-compatibility: the same Flatpak can be run on different versions of the same distribution, including versions that haven’t been released yet. This doesn’t require any changes or management by application developers.
- Maintained platforms: called runtimes, these contain collections of dependencies, which can be used by applications, and which can take a lot of the work out of application development.
- Bundling: this allows application developers to ship almost any dependency or library as part of their application. This gives complete control over which software is used to build applications.
- Consistent application environments: because these are the same across devices, applications perform as intended. This also makes it easier to identify bugs and to do testing.
- Finally, while Flatpak does provide a centralized service for distributing applications, it also allows decentralized hosting and distribution, so that application developers or downstreams can host their own applications and application repositories.

## Requirements

Quite easy. See documentation at https://docs.flatpak.org/en/latest/

## Are you planning to do it yourself in a pull request?

No. as it is important for trust that the official flatpak of Trinity on Flathub.org  comes from an official repo and from official IF members

Thx for considering my request and keep up the good work

**Comment by rajivshah3** [comment]
Hi! We're currently working on our next wallet, Firefly (https://blog.iota.org/firefly-iota-next-generation-wallet-26bdd4d01510/), where we plan to use Snapcraft. Would that be ok? We can look at Flatpak as well but we'll focus on Snapcraft at first since our packaging tools have better support for it.

I'll close this issue since we're no longer adding new features or improvements to Trinity, but we'll keep this in mind for Firefly!

**Comment by jbingram** [comment]
Hi there, thx for your reply and thx for eventually considering Flatpak for Firefly after snapcraft. I will not judge your choice, but rather try to convince you of the well founded choice of considering Flatpak. First more linux distros actively promote Flatpak rather than snapcraft, including the most widely used distros (which is not ubuntu but linux mint). The reason is that Snapcraft is a proprietary and centralised sandboxing repository and packaging framework controlled by Canonical servers (ubuntu).  It represents a central point of control and of attack for all the other linux distros who use it. The security audit of snapcraft is also private and not made public. Furthermore many non-ubuntu linux distros don't update as regularly the snapcraft framework, which can cause security issues too by the way. On the other hand, Flatpak is GPL licenced, security audits are public (like Iota is doing for Trinity), can be decentralised on your own server, and isn't controlled by any institution, and updated regularly by most linux distros. All of this makes Flatpak more compatible with the philosophy of IOTA, isn't it? As a consequence more and more linux distros have decided to use Flatpak and decided to actively block the Snapcraft framework, including for the theoretical reasons I mentioned, but also for the practical consequences that snapcraft have caused. You can check for instance the chromium snapcraft debacle at the moment  with the most widely used linux distro (the ubuntu-based distro "linux Mint": https://hackaday.com/2020/06/24/whats-the-deal-with-snap-packages/). NB: Even some Ubuntu users are now considering flatpak rather than snapcraft.  

You guys are making your own choice, but if you could at least consider Flatpak for Firefly that would be much appreciated. The risk if you don't do it is that someone may be tempted to do it on you back (why not with some hacks included)  and try to offer a  non-official flatpak download for all the linux distros. Risky hey! So having the Firefly Flatpak app officially packaged by the IOTA foundation on at least the main flatpak servers would serve as a reference and give incentives to all the linux distros not to accept non-official Firefly flatpak app.

Thx for considering my request and keep up the good work.
