### ISSUE TITLE
Zero Balance when "moving" from Wallet 2.5.4 to Trinity Wallet

### ISSUE THREAD

**Issue by Tavvie** [iotaledger/trinity-wallet#3233]
Hi, I had to go through the reclaim process in december 2017 when updating the Iota Light Wallet 2.3.0 to 2.5.4 Finally I was able to restore my balance. Now some years later I wanted to check my balance again. As the 2.5.4 Wallet is not working anymore I downloaded the trinity wallet. After entering the new seed I got during the reclaim process the balance in Trinity was showing zero again. I think I have everything I need. The old seed (also showing zero balance), the new seed including the mnemonic words to restore it. I also have the transaction hash from the reclaim process. Can anyone help me please to get my balance back? That would be fantastic!

## Version

Which version of Trinity are you running? (Please provide the full version, you can find it in Settings > About Trinity).

- Version: Trinity 1.6.1

## Hardware specification

What hardware are you using?

- Mobile or Desktop: Desktop
- Device: IOS
- OS and version:

**Comment by rajivshah3** [comment]
Hi, please join our Discord server (https://discord.iota.org) for assistance
