### ISSUE TITLE
TRINITY WALLET V0.3.5

### ISSUE THREAD

**Issue by kriss-t** [iotaledger/trinity-wallet#3234]
Hi,
I can't login  to Trinity wallet using my password...there is no error message ... Trinity wallet ''do nothing'' after put password.
I use Trinity wallet version v 0.3.5 
Computer  with  Windows 7, 64gb.
I use trinity node ..nodes.thetangle.org:443
![trinity error](https://user-images.githubusercontent.com/42905911/107822227-090bb080-6d7e-11eb-816b-c26d7444b7ee.jpg)
![trinity node](https://user-images.githubusercontent.com/42905911/107822229-09a44700-6d7e-11eb-8909-394ae4f39d78.jpg)

![trinity node](https://user-images.githubusercontent.com/42905911/107822169-f3968680-6d7d-11eb-9687-eddcc911bb55.jpg)
![trinity error](https://user-images.githubusercontent.com/42905911/107822172-f4c7b380-6d7d-11eb-890d-0bd7df6cb93b.jpg)
![trinity error](https://user-images.githubusercontent.com/42905911/107822194-fabd9480-6d7d-11eb-8be0-33d5f09158b7.jpg)
![trinity node](https://user-images.githubusercontent.com/42905911/107822195-fb562b00-6d7d-11eb-9782-84565481a700.jpg)

Briefly describe the bug.

## Version

Which version of Trinity are you running? (Please provide the full version, you can find it in Settings > About Trinity).

- Version:

## Hardware specification

What hardware are you using?

- Mobile or Desktop: 
- Device:
- OS and version:

- RAM (Desktop only):
- Number of cores (Desktop only):

## Node Settings (delete if not relevant)

What are your node settings? Are you using automatic node management?

- Node settings: 

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. 
2. 
3. 

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

Describe what actually happens.

## Errors

Paste any relevant errors that you see. These could include error/crash logs or screenshots. Please ensure that these files do not contain any personal information.

**Comment by rajivshah3** [comment]
Your wallet version is out of date, the current version is 1.6.1. You’ll also need to update to Windows 8 or 10, as 7 is no longer supported.

**Comment by kriss-t** [comment]
Hi Rajivshah3... I didn't check my wallet I think from 2018...  so now I installed trinity wallet on antoehr PC with Windows 10..it asked me the old seed.... I found only a shortcut from my old doc seed file in the Pc folder ...do you know how to restore the original ''doc file'' if I have only shortcut?

**Comment by kriss-t** [comment]
Why I can't jsut login normally just with my password and see my wallet iota?
