### ISSUE TITLE
Make trinity desktop more userfriendly

### ISSUE THREAD

**Issue by f-ben** [iotaledger/trinity-wallet#336]
### Description
The exported seedvault file should by default be named like the account it was exported from. For example: mainaccount20180905.kdbx
### Motivation
its more userfriendly

### Description
The user should be able to order the accounts in the sidebar. Right now it´s not possible to order at all. If I have three accounts and want my third account to be on the top I have to delete and readd the other two accounts.
### Motivation
its more userfriendly

### Description
In the account details the "show seed" option shows the seed as text. There should also be a QR-Code which can be scanned in trinity mobile.
### Motivation
its more userfriendly for users who use both desktop and mobile version

### Description
Clicking a transaction in the history opens the details which is fine but the user sees a lot of information he can not work with. After clicking on a hash (also an address) a site like thetangle.org should be opened with the details of each hash.

### Motivation
its more userfriendly

### Description
Most desktop pc´s dont use webcams so the "scan address-qr-code" function is pretty useless on those devices. This feature should be improved so the user can also load a QR-Code imagefile to import the receiving address (maybe with an "open image file" option or even drag/drop an image into the qr-scan-field.

### Motivation
its more userfriendly because copy/paste is no longer needed when creating a transfer on a desktop pc

### Description
Not sure if needed, I personally would appreciate a feature like this: When sending a TX the user is not able to see the whole recipient address. Hovering the address field could show the whole address in a hovering textfield which is attached to the cursor. See screenshot for very poor example.

### Motivation
its more userfriendly because the user can directly see if he entered everything correct without the need to try to send the tx, then notice he made a mistake in the confirmation screen just to go back, try to fiddle around in the small input field and then try again.

### Am I planning to do it myself with a PR?
No because I don´t know anything about programming

**Comment by f-ben** [comment]
![address](https://user-images.githubusercontent.com/2088471/45118926-30480780-b15a-11e8-9ada-d655e6db0920.jpg)
As you may have noticed I actually copy/pasted the wrong address into paint but you get the idea ;)

**Comment by rihardsgravis** [comment]
This Issue should be split intro several issues each addressing one topic.
