### ISSUE TITLE
Unable to empty my Trinity wallet and send to Firefly

### ISSUE THREAD

**Issue by rreniers** [iotaledger/trinity-wallet#3376]
## Bug description

Unable to empty my Trinity wallet and send to Firefly
The ios app and windows app are not responsive when sending to external wallet Firefly

##

windows 10 latest
IOS 14.1

**Comment by HBMY289** [comment]
Migrating your funds to the new network is done via the new FireFly wallet. It is not possible in Trinity.
Have a look at the official blog post:
https://blog.iota.org/firefly-token-migration/
