### ISSUE TITLE
Trinity desktop beta: allow pasting seed from KeePass during initial wallet setup

### ISSUE THREAD

**Issue by b-f-** [iotaledger/trinity-wallet#341]
### Description
Functionality proposal 1: Allow pasting seed from tools like KeePass or remove copy/paste context menu option from "SEED" input.
Functionality proposal 2: Add explanatory tooltips to "camera" icon, "eye" icon, "drop seed" placeholder and warn user about potential security risks.

Safety improvement proposal 1: allow seed paste operation from a tool should be allowed and clipboard cleared directly after paste operation is completed.

Safety improvement proposal 2: require a password manager tool for creating seeds and prevent any type seed, paste seed or view seed operations. Import seeds from password-protected kdbx only.

Safety improvement proposal 3: webcams are often attack targets. Importing seeds this way seems unsafe. Same goes for scanners.

### Motivation
Assumption 1: malware on machine can access clipboard at any time.

Seed box allows user to reveal the actual seed or forces user to view the seed and retype it, therefore seed is only safe when:
Assumption 2: malware is not a keylogger and cannot take snapshots of process windows nor access web cam.

### Am I planning to do it myself with a PR?
No.

**Comment by sbaechler** [comment]
1Password immediately hides shown passwords if the app loses focus.
Currently the users just paste the seed from the PW manager into notepad and then copy it by hand from there. Which is worse.

**Comment by rajivshah3** [comment]
> Allow pasting seed from tools like KeePass or remove copy/paste context menu option from "SEED" input.

I'm not familiar with KeePass' pasting feature. Are you referring to the auto-type feature?
We're also looking into supporting other password managers so that users have more flexibility.

**Comment by b-f-** [comment]
> 
> 
> > Allow pasting seed from tools like KeePass or remove copy/paste context menu option from "SEED" input.
> 
> I'm not familiar with KeePass' pasting feature. Are you referring to the auto-type feature?
> We're also looking into supporting other password managers so that users have more flexibility.

Not the autotype feature. Just plane old paste. There is a "Paste" context menu (as described in issue description) which did not work at all.

**Comment by rajivshah3** [comment]
Users can now drag-and-drop their seeds from another application
