### ISSUE TITLE
 Following the documented instructions in the repository does not produce a working build on windows.

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#345]
Following the documented instructions in the repository does not produce a working build on windows.

If you follow the below on windows:
git clone https://github.com/iotaledger/trinity-wallet.git
Go to the trinity-wallet directory
cd trinity-wallet
Run the setup to install dependencies
yarn full-setup

You do not get a working build.

Suggested remedy:

Specify the environment that is assumed with these build instructions. or provide more specific instructions on how to get a working build on a windows environment if possible or specify if not.

**Comment by rajivshah3** [comment]
Hi @ChocoMachine , can you elaborate on what happens when you try to run these steps? This should work, assuming you have the [prerequisites](https://github.com/iotaledger/trinity-wallet#prerequisites)

**Comment by rihardsgravis** [comment]
To produce a working build on Windows, you should additionally follow the instructions on the [Trinity desktop readme](https://github.com/iotaledger/trinity-wallet/blob/develop/src/desktop/README.md) or [Trinity mobile readme](https://github.com/iotaledger/trinity-wallet/tree/develop/src/mobile). This should be clarified in the main repo Readme.

**Comment by ghost** [comment]
This is what I have done so far:
I had to run the following to get the initial install npm scripts to work:
**npm install -g concurrently**
**npm i -g cross-env** 
I started to use Bash to run the scripts.
.
I has some issues with Aragon so ended running the below:
**npm install -g node-gyp**
**CXX=g++-6 npm install argon2**
I didn't understand the last command, but the issue with Aragon went away! 
Then I ended up with "ReferenceError: Unknown plugin "transform-object-assign"... 
So... 
Got up in the morning, deleted all the node_modules folders in all the project folders and ran:
**npm run  full-setup** (in elevated prompt as I'm paranoid now and just want to get a build)

Then went to src/desktop folder and ran:
**npm run build** (got error about webpack missinig this was new!) so ran
**npm install** in src/desktop folder. (read herring this one I think)
I got:
cl : Command line error D8040: error creating or communicating with child process [c:\Repos\trinity-wallet\src\desktop\node_modules\entangled-node\build\entangled.vcxproj]
ran **yarn** in src/shared folder (just for kicks)
then went back to src/desktop and ran:
**npm run build**  (got some warnings but it built without error. :-) ).
**npm run complie:win** (no errors, all looking good.)
**npm run start**  (complied with warnings)
then nothing happens: 
So from examining scripts in packages.json I ran:
**npm run compile**
it get's stuck on "compressing and uploading to remote builder"...
Ctl-C 
**npm run compile:win**
**npm start**

I get the following error:
[1] c:\Repos\trinity-wallet\src\desktop\node_modules\electron\index.js:9
[1]   throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')

I have deleted the folder lots of times and installed again. 
I'm not an electron guy, but wanted to have a look as I know react and javascript etc and thought to pick up the rest as I go along.

Anyway that's my experience so far... there's probably something obvious I'm missing due to lack of experience on this platform, so if you see it let me know.

Cheers,

David.

**Comment by laumair** [comment]
@ChocoMachine Have you tried installing `electron` globally? 

```
npm i electron -g
```

**Comment by rajivshah3** [comment]
> I had to run the following to get the initial install npm scripts to work:
npm install -g concurrently
npm i -g cross-env

> I ended up with "ReferenceError: Unknown plugin "transform-object-assign"...

🤔 that's really weird, these should be getting installed by `npm`. What version of `npm` and `node` do you have? 

> CXX=g++-6 npm install argon2
I didn't understand the last command, but the issue with Aragon went away!

If you specify `CXX=` before a command that compiles something (we're compiling `argon2` in this case) then you're basically telling it what C++ compiler to use. It's odd that you had to specify this though

**Comment by ghost** [comment]
I had another go at work today and seem to have got it working.
I still had to add:
**npm install -g concurrently**
**npm i -g cross-env**
But then ignored the root commands in particular  **full-setup** I think that command returns too quickly, indicating the install has been completed, when probably in the background somewhere it hasn't and packages are still being downloaded. 
Then following the **full-setup.js** scrip as a guide I went to each folder (root, desktop, shared & mobile) and executed:
**yarn --verbose**
.
Then back to desktop &
**yarn build** 
Then
**yarn compile:win**
Then
**yarn start**
I get lots of 

> [10016:0910/171017.392:ERROR:CONSOLE(7574)] "Extension server error: Operation failed: : has no execution context", source: chrome-devtools://devtools/bundled/inspector.js (7574)
[1] [10016:0910/171018.392:ERROR:CONSOLE(7574)] "Extension server error: Operation failed: : has no execution context", source: chrome-devtools://devtools/bundled/inspector.js (7574)

But then it works!!! :-)

my versions are:
npm 6.2.0
node 10/9/0
yarn 1.9.4

So my tips are, **use yarn for everything**, including running the npm commands.
Don't use **full-setup** well not inside a visual studio code terminal, may be it wasn't' reporting progress back correctly, I'm not sure.

Thanks guys, o and yes I had installed **npm i electron -g**
