### ISSUE TITLE
how to build in dev env, is there a doc?

### ISSUE THREAD

**Issue by v2future** [iotaledger/trinity-wallet#365]
I have downloaded the source code, is there a guide how to build?

**Comment by rihardsgravis** [comment]
For Trinity desktop follow [Trinity desktop Readme](https://github.com/iotaledger/trinity-wallet/tree/develop/src/desktop), for Trinity Mobile follow [Trinity mobile Readme](https://github.com/iotaledger/trinity-wallet/tree/develop/src/mobile).
