### ISSUE TITLE
Trinity Android crashes during import of seedvault

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#376]
## Bug description
Trinity Android crashes during import of seedvault

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Samsung
- Model: Galaxy S8+
- OS version: Android 8.0.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v0.5.0 (22)

### Steps To Reproduce
I've created a IOTA wallet in the desktop trinity wallet and exported the seed into a seedvault. I've send the vault to my smartphone, so i can import the wallet into the trinity mobile app. I clicked on import, the android file explorer appeared and i selected the file. After that the app crashed. Everytime i try to import the vault it crashes.

### Expected behaviour
App import the seedvault file and ask for the passwort

### Actual behaviour
App crashed

### Errors
no crash log

*NOTE*
I've tried to reinstall the app. Problem is still there

**Comment by rajivshah3** [comment]
Hi @BurningPixels , thanks for the report! If it's ok with you I just updated your comment with the latest version of Trinity Mobile. Are you able to obtain the logs during the crash with Logcat (https://developer.android.com/studio/command-line/logcat)? If not I can use the Android simulator but it's best if we can get the logs from a real device.

**Comment by laumair** [comment]
@BurningPixels Thanks for reporting. This is indeed a bug on Android >= 6.0. The read permissions need to be granted during runtime. https://github.com/joltup/rn-fetch-blob/blob/master/README.md
