### ISSUE TITLE
Mobile v0.5.0 release broke Desktop auto-updates

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#384]
### Bug description
Reported by alexsporn#6593 on Discord:

> I think you broke the desktop "Check for update" with the mobile 0.5.0 release
Error: Cannot find latest-mac.yml in the latest release artifacts (https://github.com/iotaledger/trinity-wallet/releases/download/mobile-v0.5.0/latest-mac.yml): HttpError: 404 Not Found
"method: undefined url: https://github.com/iotaledger/trinity-wallet/releases/download/mobile-v0.5.0/latest-mac.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"

I'm also able to reproduce this on my computer as well.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: MacBook Pro
- OS version: macOS 10.14 Beta (18A365a)

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v0.3.3

### Steps To Reproduce
1. Check for an update by going to Trinity>Check for Updates...

### Expected behaviour
A message should be shown that says that no updates are available

### Actual behaviour
An error message is shown

### Errors
![image](https://user-images.githubusercontent.com/19519564/45661665-7727ec80-bacc-11e8-9b3d-0a0d355ff375.png)

**Comment by antalm** [comment]
I can confirm it is also broken on Linux. Also, my screen resolution is 1920x1080, however the error screen appears to be at least twice the size of my screen. I cannot scroll to see the missing parts of the error text, nor can I copy its text, so it is basically useless.
![trinity_update_error](https://user-images.githubusercontent.com/29548853/45842789-011ac400-bd1e-11e8-9e60-d0e9489a39f5.png)
