### ISSUE TITLE
Can not copy paste the seed when login !

### ISSUE THREAD

**Issue by thieuanh1995hn** [iotaledger/trinity-wallet#401]
I try but still can not copy paste the seed when login !
Please check !

**Comment by rajivshah3** [comment]
Hi, on Trinity Desktop and Trinity Mobile (Android) this is an intended feature. The clipboard is not secure and your seed could be stolen.

**Comment by thieuanh1995hn** [comment]
It’s will be dificult when identify a iot device by their address.
Vào Th 5, 20 thg 9, 2018 lúc 01:40 Rajiv Shah <notifications@github.com> đã
viết:
