### ISSUE TITLE
blank screen after typing bunch of random chars in new seed

### ISSUE THREAD

**Issue by wonkytonky** [iotaledger/trinity-wallet#404]
### Bug description
creating new account
fill in my own new seed
i keep typing chars until >81  turns into blank screen

![image](https://user-images.githubusercontent.com/19390834/45817814-2dafeb00-bce0-11e8-8c4b-d15de250f36e.png)

### Environment Specs
What device are you running Trinity on?

- Manufacturer: 
- Model: 
- OS version: win 10

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.3.4 

### Steps To Reproduce
1. add new acount
2. your own seed
3. type in random stuff until >81    turns into black screen

### Expected behaviour
some warning, 
also no warning about wrong chars that are not suppose to be used.. like 1 2 3 4 5 $ % (while typing preferably)

### Actual behaviour
blank screen no warnings

**Comment by rihardsgravis** [comment]
Fixed in #405
