### ISSUE TITLE
Cannot enter character "9" when manually entering a new seed

### ISSUE THREAD

**Issue by HBMY289** [iotaledger/trinity-wallet#406]
### Bug description
When adding a new account and entering an existing seed manually, the character "9" cannot be entered / is not accepted. Nothing appears or happens if you hit the "9" key either on normal keyboard or number pad.

### Environment Specs
Desktop version (0.3.4) on Win 7 (but issue was also reported on Mac)

### Steps To Reproduce
1. Add new Account
2. Choose "No, I have one" option to manually enter existing seed
3. Enter seed containing character "9"

### Expected behaviour
All letters including character "9" should appear when typing

### Actual behaviour
Letters can be entered, but "9"s do not appear and cannot be entered

**Comment by rajivshah3** [comment]
Fixed in #405
