### ISSUE TITLE
New addresses are not generated when pressing "new address"

### ISSUE THREAD

**Issue by Tsangares** [iotaledger/trinity-wallet#410]
### Bug description
I see that this is not exactly a bug, but it seems like a problem to me.
In the main screen, I hit receive, there is a QR code and an address. 
I am planning on giving someone one address so I copy it and hit "New Address".
I would EXPECT to see a new address and the previous one should never be shown to me again as to not get mixed up. 
But INSTEAD, I see the animation of letters changing, and it resolves on the same address as before!

### Environment Specs
I am running on a MacBook Pro with Arch Linux OS
I installed trinity from AUR: https://aur.archlinux.org/packages/iota-trinity-wallet/

- Manufacturer: Mac
- Model: Pro 2015
- OS version:  Arch Linux

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v0.3.3

### Steps To Reproduce
1. Generate new Address Button

### Expected behaviour
Make new address, never to see the old one again, except in the list of all addresses.

### Actual behaviour
The same address as before is given to me.

### Errors
I notice:  Cannot transition addresses with zero balance.

**Comment by Tsangares** [comment]
I did find as a solution: to send an empty transaction to one of my receiving addresses.

Then trininty does not use the empty transaction and it finds generates a new address on the front screen.

**Comment by cvarley100** [comment]
This is a design decision.

**Comment by sachushaji** [comment]
Hello, Can you give more info on why this design decision was made
