### ISSUE TITLE
Trinity Mobile Wallet - yarn android:dev Error

### ISSUE THREAD

**Issue by rkuo2000** [iotaledger/trinity-wallet#414]
Windows 7, git-for-windows v2.19.0, node v9.8.0, npm v4.3.0, 
$ cd src/mobile && yarn android:dev
yarn android:dev v0.22.0
$ cross-env NODE_ENV=development ./node_modules/.bin/react-native run-android
The system cannot find the path specified.
events.js:165
      throw er; // Unhandled 'error' event

**Comment by rajivshah3** [comment]
@rkuo2000 did you run `yarn` to install mobile dependencies?

**Comment by rkuo2000** [comment]
Yes, I follow the README.md under trinity-wallet & src/mobile
$cd ~/trinity-wallet
$yarn full-setup
$cd src/mobile
$yarn android:dev

**Comment by rajivshah3** [comment]
Please also double check that you have the following: https://facebook.github.io/react-native/docs/getting-started.html#installing-dependencies-3 (make sure to choose your development OS and target OS accordingly)

**Comment by rkuo2000** [comment]
Yes, react-native is installed, and Android SDK paths are added into ~/.bash_profile
$npm install -g react-native-cli 
I did not do 
$react-native init AwesomeProject
Maybe this is root-cause, let me check again.

**Comment by rajivshah3** [comment]
Ok, to isolate the issue can you go to an empty directory and do the following?

`react-native init TestApp`
`yarn`
`cross-env NODE_ENV=development ./node_modules/.bin/react-native run-android`

This will create a new app so we can see if it's an issue with the way React Native is installed or if it's just a Trinity issue

**Comment by rkuo2000** [comment]
Yes,  `react-native init TestApp`, under TestApp, `react-native run-android` works fine without Error message.

**Comment by rajivshah3** [comment]
If the command `cross-env NODE_ENV=development ./node_modules/.bin/react-native run-android` works with the TestApp then something seems to be wrong on the Trinity side of things. Can you try going to `src/mobile` and running `rm -rf node_modules && yarn`? It may take a while but you'll have to wait for all dependencies to install. I think I've heard that sometimes Yarn can install dependencies incorrectly on Windows

**Comment by rkuo2000** [comment]
It is yarn version issue, after I remove & reinstall yarn to v1.9.4. 
 `yarn android:dev` still failed (in Win7), but `cross-env NODE_ENV=development react-native run-android` works, and I found src/mobile does not support to build in windows, it needs iOS or Linux to build the Android App.
