### ISSUE TITLE
Desktop: History entries not completely shown, flickers when mouse over

### ISSUE THREAD

**Issue by HBMY289** [iotaledger/trinity-wallet#419]
### Bug description
The list of history transactions is not shown correctly. For some transactions most of the line is empty, some residual letters are visible. When moving the mouse over the items they sometimes appear and disappear again.

### Environment Specs
Trinity desktop 0.3.5 on Win 7 64 bit

### Steps To Reproduce
1. Open Trinity
2. View history
3. Move mouse over

Restart of Trinity does not solve the issue. Restart of computer cannot be done at the moment, but will be tested later.

### Expected behavior
All entries should be displayed

### Actual behavior
Some entries are not displayed correctly

![history](https://user-images.githubusercontent.com/43444790/46011413-0aad7e80-c0c6-11e8-81fd-58fbf609bc61.gif)

**Comment by rajivshah3** [comment]
Is it solved if you run Trinity with the `--disable-gpu` flag?

**Comment by HBMY289** [comment]
Yes, with that flag the issue is gone.
CPU is Intel Xeon E5-1620 v3 and the PC is equipped with an NVIDIA Quadro K2200 graphics card if that is of any interest.
