### ISSUE TITLE
IOS 12 | iPhone X | Password autofill on | keyboard covers fields

### ISSUE THREAD

**Issue by nicoschtein** [iotaledger/trinity-wallet#431]
### Bug description
When password auto fill enabled, the bar covers the last password field on the update password screen (when updating to 0.5+). 

### Environment Specs

- Manufacturer: Apple
- Model: iPhone X
- OS version: iOS 12

What build of Trinity are you running? 

- Trinity version: 0.5 (22)

### Steps To Reproduce
1. Have version < 0.5
2. Enable Password Autofill in iOS 12
3. Update to 0.5
4. You will be promoted to update your password
5. Try to select new password second field. 

### Expected behaviour
Field should not be covered. 

### Actual behaviour
it is covered by the “Password” bar above the keyboard and cannot “paste”. 

### Errors
![d7943bf8-1ad6-4a0a-9b84-d6987399a012](https://user-images.githubusercontent.com/1649257/46241803-56497c00-c395-11e8-9ac6-c0f1af13b035.png)

**Comment by rajivshah3** [comment]
Thanks for reporting this @nicoschtein ! Looking into this now, sorry for the delay
