### ISSUE TITLE
UI - Display Adress Receive Adress in a line instead of a box-pattern

### ISSUE THREAD

**Issue by SvenHildebrandt** [iotaledger/trinity-wallet#437]
### Description
Due to the fact some / most exchanges send you an e-Mail confirmation with the address to be confirmed in one line, it would enhance user experience if this would displayed in the wallet the same way. With the current style comparing the two adresses manually is a bit tricky. One step further would be a integrated "compare" field, where you could just copy and paste the address you got in the E-Mail and this is compared directy to the one displayed in the app. 

### Motivation
Enhancement of UI

### Requirements
?

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
This was a design decision - to break the address up a little bit. We will improve address displays further in the future.
