### ISSUE TITLE
Tangle Explorer Integration

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/trinity-wallet#445]
### Description
Add option for users to navigate to external (or internal) Tangle Explorer from the transaction history.

### Motivation
User convenience.

### Requirements
- If linking to an external explorer (preferably TheTangle.org), add button to navigate to a particular bundle from its transaction history modal.

### Am I planning to do it myself with a PR?
Not right now. Open for someone to pick up.

**Comment by rajivshah3** [comment]
For mobile, we should discuss whether this would simply be a link that opens the web browser (essentially taking the user out of the Trinity app) or is implemented as a WebView (in-app browser). The concern with a WebView is that it’s not completely isolated from the app and could potentially inject arbitrary JavaScript. Using a WebView securely would require React Native 0.57 (https://facebook.github.io/react-native/blog/2018/08/27/wkwebview)

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
