### ISSUE TITLE
Ensure transactions are pulled in near-instantly when polling

### ISSUE THREAD

**Issue by laumair** [iotaledger/trinity-wallet#449]
### Description
Transactions are often pulled in after a delay. This could be because of several reasons. Mainly because of Trinity's polling setup which only polls for a single service at a time. The polling setup for pulling in transactions should be improved so that new transactions are fetched instantly. 

### Motivation
User experience

### Requirements

There should be minimum delay when new transactions or reattachments are pulled in.

### Open Questions (optional)
How should we improve the process of the pulling in latest transactions? 

We could either tune our polling system or use zmq & websockets implementation for processing streams on client side

### Am I planning to do it myself with a PR?
Yes

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
