### ISSUE TITLE
Encrypted QR seed back up option

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/trinity-wallet#451]
### Description
Current seed storage options include SeedVault, paper wallet and writing it down. To improve security of the paper wallet, the seed should be encoded in a password-protected QR.

Using a combination of Argon2 password hashing and AES GCM encryption, we can store a secure copy of the seed, together with the IV in the QR (perhaps Base64). When scanned in Trinity, the encoding scheme is detected and password requested to decrypt the seed.

### Motivation
Greater protection for seed storage, particularly paper wallets

### Requirements
- Finalise encryption schema and encoding
- Integrate with QRScanner component
- Implement relevant UI/UX

### Open Questions
- Encryption scheme and encoding to be finalised

### Am I planning to do it myself with a PR?
Yes.

**Comment by vbakke** [comment]
[Charlie IF] asked for feedback for V2 on Discord.  I second encrypted QR codes. It means you can safely print, store, and scan your seed, without anyone/anything sniffing out the real seed.

I was playing with the same idea some time ago ([vbakke/tryte-encrypt](https://github.com/vbakke/tryte-encrypt/)).  I tried using scrypt, and not Argon2, for hashing the passphrase, but have no strong views on  which is better in this scenario. The important part is getting the AES bit right.

I'd be happy to help out if I can.  Preferable, more people share their views on the security of the implementation, before anything is decided.

**Comment by vbakke** [comment]
Just my five cents and my thoughts on the case: 

 - I tried converting the encrypted bytes back to trytes, mo make it more IOATAish. Charlie IF disagreed, being afraid people would confuse an encrypted seed with an actual seed (the only apparent difference was 100 vs 81 tryte characters)

- I'd still prefer to encode the bytes as readable letters, though. I'd prefer to be able to read my QR code with any scanner to be able to confirm it's content. Raw bytes won't be good for that.

 - QR codes are more compact using uppercase letters only (https://www.qrcode.com/en/about/version.html). Therefore a base32 might actually fit "lower QR versions" than base64 would.

- QR code might actually be more readable with lower error correction level, because you might get a "lower version" and thus bigger/fewer "dots" in the QR code



(Just realized that cvarley100 may be the very same person as I mention above. :-o
If so, we have already been discussing this.  ;)

**Comment by vbakke** [comment]
**Encryption** 
Correct me if I'm wrong, but how I understand AES GCM is basically AES CTR with [Authenticated_encryption](https://en.wikipedia.org/wiki/Authenticated_encryption). 

According to [this post](https://crypto.stackexchange.com/questions/1849/why-should-i-avoid-using-a-randomized-iv-for-ctr-mode), we're better off using CBC with a random IV, than a CTR with a random IV.

I'm also uncertain if we need Authenticated encryption when encrypting a seed.   We must presume that the attacker has gained the encrypted seed, and she can ignore any authentication code as she sees fit.

**Comment by vbakke** [comment]
A possible outline of an algorithm for the Encrypted QR Code.

Feel free to comment to improve our common goal. :)

### Derive key from passphrase
From the written passphrase, we need to derive a sparse cryptographic key, that is slow and difficult to calculate.

1. Passphrase Bytes = UTF-8 encoding the Passphrase
2. Passphrase Salt
		a. Using 2x SHA256 (like BIP38)
		b. Using a random IV, stored along with the final ciphertext
3. Encryption key = derive a key using the bytes and salt from 1) and 2)
		a. Using Scrypt 
		b. Using Argon2
		c. Or use PBKDF2 ?

All password derivation key functions are based on iterations. One purpose is to allow the number of iterations (and other costs parameters) to be tunes as high as possible of the specific hardware you are running on, without being too costly for the overall system og the individual user.

Regardless on which key derivation function IOTA ends up using, the protocol should allow the end user to adjust the cost. The same user might also want different costs on seeds with 10Mi versus 10Ti.


### Encrypt the seed
Encrypting the seed takes a few steps. Each step have different possible options.

**1. Convert Iota seed (81 trytes3) to bytes**
Well-proven encryptions algorithms work in bytes, not in trytes. So we need to convert. The Kerl function skips the last trit (ref: [previous Kerl on GitHub](https://github.com/iotaledger/kerl/blob/master/javascript/kerl.js#L62)).

One can fit 3^242 in 47,9 bytes.
While 3^243 requires 48,1 bytes (as a theoretical minimum).
	
If we need to be able to restore all 243 trits, the 49 bytes is the theoretical minimum. 

  1. Using trytes.values returns 48 bytes, but misses the last trit
  1. Using converter.tryte2ascii fails of trytes higher than 'LI' (or 255, as discussed in https://github.com/vbakke/trytes#why-not-just-byte2tryte-and-tryte2byte)
  1. Packing 5 trits into 8 bits (similar to vbakke/trytes) gives 50 bytes
  1. Other conversions
	 	
**2. Encrypt the seed bytes**
This question is more important than the scrypt vs argon debate.  There are many encryption schemes, and AES is a family of many variations. All with different pros and cons.   We must assume that some users will end up using the same passphrase on multiple seeds.

[Rogaway's paper](https://web.cs.ucdavis.edu/~rogaway/papers/modes.pdf) lists a few pros and cons.

Some takeways are the complete failure of GCM and CTR if the same nounce/iv is used for the same key.  (GCM is basically CTR with HMAC etc.) But as long as reuse of nounce + key is handled properly, many perfer the counter types og AES modes. CBC is prone to padding attack if not handled properly. 

Would cause any problems if we used the same IV for initializing both scrypt/argon and the AES encryption?


**3. Encode in a QR**
QR codes come is different 'sizes' called 'versions'. They can also include varying degree of error correction. Increasing the level of error correction, may often increase the version leading to "smaller dots" in the code, thus making it more error prone.

Also here we have a few options. We can store the encrypted bytes:
  1. As raw bytes
  1. Encoded as text using Base64 (adds roughly 33% in length)
  1. Encoded as text using Base32 (adds roughly 60% in length)
  1. Encoded aa tryte-characters 9 + A-Z (doubles the length)

Raw bytes as QR code is the most compressed, but some will argue that they prefer being able to see and type the text in the QR code.

QR Code can be optimized if they only contain numbers and capital letters. Base32 can fulfil this requirement, while Base64 uses both upper and lower case letters, thus needing to be encoded as if each character was any random 0-255 byte.

Base32 is actually only marginally less compressed than raw bytes. In a QR Code, that is. Not as text.


Depending on how we convert to bytes and the AES encryption, the number of encrypted bytes will vary.  If we include the IV and padding we may have 80 bytes to store, if we don't need padding we may get away with only 66 bytes.

Some examples of how different encoding influences the final "size" of the QR code, and the amount of error correction that is possible for the given QR version.


Encrypted bytes|Encoding type|Encoded chars|QR v4|QR v5|QR v6
--|---|--|-|-|-
66|Raw|66|L|M|Q
66|Base64|88|-|L|M
66|Base32|112|L|M|M
66|Trytes|132|-|L|M
80|Raw|80|-|M|M
80|Base64|108|-|-|L
80|Base32|128|-|L|M
80|Trytes|160|-|-|L

Note of Base32. There are several base32 alphabets. Seems that the RFC4648 [A-Z2-7], and Crockford 0-9, and letters minus I, L and O are commonly used. In Crockford the letter O is defines as an alias for zero, and both I and L are alias for the digit one. Crockford seems sensible.

**Metadata**
From plying around with different variants, I have found it useful to append som metadata. For example, what version of the definition is used, as well as the scrypt / argon arguments. 

One may add a QR friendly delimiter, such as $ % * + - . / : (ref [QR code alphanumeric characters](https://en.wikipedia.org/wiki/QR_code#Storage). E.g. the suffix ":2T3" for version 2 and "toughness 3". Toughness must in that case be defined as 3 notches up from a given set of scrypt / argon parameters, defined as "standard". Or possibly very specific:  ":1N14R9P10", for version 1, logN=14, r=9 and p=10.

The thing is, you cannot decryppt your seed unless your scrypt / argon matched perfectly.  In my opinion, the security should lie in the passphrase, not if you remember the number of rounds you chose fro your scrypt hashing. Therefore it should be stored together with encrypted hash. 

Worse than having you funds stolen must be to not remember the hashing parameters of your sectret seeds. ;)

**Comment by cvarley100** [comment]
Hey again @vbakke. Thanks very much for this detailed description. We will be reinvestigating Encrypted QRs in the coming weeks as part of our Trinity V2 planning. I will post an update here on the results of that.

**Comment by vbakke** [comment]
No problem.  There are of course many variants, but it is often easier improving a concrete suggestion, than something intangible. Looking forward to hear the conclusion.  :)

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
