### ISSUE TITLE
Node quorum

### ISSUE THREAD

**Issue by laumair** [iotaledger/trinity-wallet#453]
### Description
Trinity only connects to a single node for fetching transactions, latest confirmation states, address spend statuses and latest balances. Trinity does make sure that the node it connects to is [synced](https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/libs/iota/extendedApi.js#L510) but this does not guarantee whether the information it's getting from the node is correct. 

 In a distributed computing environment, a single source of information is ultimately fallible. The implication of this — when applied to a wallet — is a limit to the level of confidence we can have in the responses of a single node. This is where node quorum becomes important. Confidence increases when responses of multiple nodes are considered in tandem. With 2/3 of a pool of nodes in agreement, we can be confident that the information returned is correct. And in the case where the nodes fail to agree, we fallback to a safe result.  

### Motivation

To ensure Trinity always pulls in correct information (transactions, balances, spend statuses, confirmation states)

### Requirements

- Consider all addresses `spent` unless majority of the queried nodes say otherwise.
- Consider balance `zero` unless majority of the queried nodes say otherwise.
- Consider transaction as `unconfirmed` unless majority of the queried  nodes say otherwise. 

For new transactions, we should find unique transaction hashes from all nodes. Then compute a quorum result for valid trytes. 
### Am I planning to do it myself with a PR?
Yes

**Comment by ovanwijk** [comment]
Even though this code is also to ensure a quick response it does show an interesting way for dealing with multiple nodes. :https://github.com/ovanwijk/IotaPublicNodeSelection/blob/695d9b91056ebcc4d5aa27d50e7024823f399877/src/MultiNodeInterface.js#L594

What it does is basically select a set of nodes, query them all at the same time. If it gets the first result back all other nodes have to reply within 2 seconds (increase it to 30 seconds to negate the wait and have a quorum). In case of wereAddressesSpentFrom it treats any TRUE as more important then a set of FALSE.

**Comment by laumair** [comment]
This is indeed an interesting way. 

> In case of wereAddressesSpentFrom it treats any TRUE as more important then a set of FALSE.

One problem that I see is that a _bad_ node could block funds. However, this approach could be well suited for `findTransactions` as hashes & signatures can be validated.

**Comment by laumair** [comment]
Done in https://github.com/iotaledger/trinity-wallet/pull/631

Also related https://github.com/iotaledger/trinity-wallet/pull/884
