### ISSUE TITLE
Yubikey 2FA

### ISSUE THREAD

**Issue by cvarley100** [iotaledger/trinity-wallet#454]
### Description
2FA currently only supports TOTP. It should also support the Yubikey hardware device.

### Motivation
Additional two factor option

### Requirements
- Integrate with Yubikey API to authenticate Yubikey OTP

### Am I planning to do it myself with a PR?
No.

**Comment by georgmittendorfer** [comment]
It should support U2F in general (I think that is the same that yubikey supports).

**Comment by mgeier63** [comment]
FYI, I have some experience coding with Yubikeys, so I am currenty looking into this.
Unfortunately, after starting to work with the current 2FA code in Trinity, I do have some general concerns ( unrelated to the use of Yubikey for 2FA) and posted them to the Trinity Bug Bounty Program.

**Comment by cvarley100** [comment]
@mgeier63 Any updates on this one?

**Comment by mgeier63** [comment]
Well, I still have some concerns that have not fully been eliminated even in the latest Trinity release (for details see the conversation in bugcrowd) - for that reason I haven't continued working on this.

I have, however, started looking into the possibility of implementing the transaction signing on a JavaCard crypto chipcard.  This, if possible, would be a completely secure way of handling the seed - think of some kind of ledger-on-a-card.

Was very busy over the last months though, so didn't dig too deep.
Would this be interesting for you? Or maybe you know if anybody has already attempted this and found possible roadblocks?

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
