### ISSUE TITLE
Mobile background processes

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#455]
### Description
Trinity Mobile should support background processes such as auto-promotion and polling. 

WIP #295 
Blocked by #311 

### Motivation
The user shouldn't have to keep the app open to auto-promote. Additionally, with background polling, the app will open with up-to-date information.

### Requirements

- [ ] Comply with OS requirements on background processes
- [ ] Periodically check the confirmation status of transactions
- [ ] Create promotion/polling jobs and add them to a queue

### Am I planning to do it myself with a PR?
Yes

**Comment by rajivshah3** [comment]
This currently requires the implementation of Realm, as Redux does not allow us to access the state while the app is backgrounded

**Comment by cvarley100** [comment]
@rajivshah3 Perhaps we can revisit this one soon

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
