### ISSUE TITLE
Multisignature support

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#456]
### Description
Multisig enables accounts where multiple parties/devices are required to authorise token spends.

### Motivation
This provides increased security because an attacker must have access to multiple keys in order to sign transactions.

### Requirements
Create a list of what you want this feature request to fulfill.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
Not at the moment

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
