### ISSUE TITLE
Support for single contact address

### ISSUE THREAD

**Issue by laumair** [iotaledger/trinity-wallet#459]
### Description
There is a need for a more permanent contact address, aiming to overcome the limitations of address reuse. This would also enable donation addresses.

### Motivation

- To overcome address reuse issue
- To overcome network latency issues with multiple device usage

### Requirements

A solution that resolves

- Relying on wereAddressesSpentFrom api endpoint.
- Address reuse issues with race conditions.

and provides support for 
- Stable contact address.

### Am I planning to do it myself with a PR?
Yes

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.

Related #2009
