### ISSUE TITLE
Display QR code on View Seed page

### ISSUE THREAD

**Issue by f-ben** [iotaledger/trinity-wallet#471]
### Description
In the account details the "show seed" option shows the seed as text. There should also be a QR-Code which can be scanned in trinity mobile.

### Environment Specs
Trinity Desktop and Trinity Mobile

### Motivation
its more userfriendly for users who use both desktop and mobile version

### Am I planning to do it myself with a PR?
no

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
