### ISSUE TITLE
Add tangleexplorer to history

### ISSUE THREAD

**Issue by f-ben** [iotaledger/trinity-wallet#472]
### Description
Clicking a transaction in the history opens the details which is fine but the user sees a lot of information he can not work with. After clicking on a hash or address a site like thetangle.org should be opened with the details of each hash. Ideally with an option in the settings which service to use (eg. thetangle.org or iotasear.ch)

### Environment Specs
Trinity Desktop and Trinity Mobile

### Motivation
its more userfriendly

### Am I planning to do it myself with a PR?
no

**Comment by rajivshah3** [comment]
Duplicate of #445
