### ISSUE TITLE
Add import for addresses by QR-Code

### ISSUE THREAD

**Issue by f-ben** [iotaledger/trinity-wallet#473]
### Description
Most desktop pc´s dont use webcams so the "scan address-qr-code" function is pretty useless on those devices. This feature should be improved so the user can also load a QR-Code imagefile to import the receiving address (maybe with an "open image file" option or even drag/drop an image into the qr-scan-field.

### Environment Specs
Trinity Desktop
### Motivation
its more userfriendly because copy/paste is no longer needed when creating a transfer on a desktop pc

### Am I planning to do it myself with a PR?
No

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
