### ISSUE TITLE
Add ability so see the complete address when initiating a transfer

### ISSUE THREAD

**Issue by f-ben** [iotaledger/trinity-wallet#474]
### Description
Not sure if needed, I personally would appreciate a feature like this: When sending a TX the user is not able to see the whole recipient address. Hovering the address field could show the whole address in a hovering textfield which is attached to the cursor. See screenshot for very poor example.

### Environment Specs
Trinity Desktop

### Motivation
its more userfriendly because the user can directly see if he entered everything correct without the need to try to send the tx, then notice he made a mistake in the confirmation screen just to go back, try to fiddle around in the small input field and then try again.

### Am I planning to do it myself with a PR?
no

![45118926-30480780-b15a-11e8-9ada-d655e6db0920](https://user-images.githubusercontent.com/2088471/46548787-58996200-c8d0-11e8-8bd9-0b181858bf33.jpg)

**Comment by mfecenko** [comment]
Hi, I would like to take this issue. Is it still unassigned?

**Comment by rajivshah3** [comment]
@mfecenko Nice! I think it's still unassigned. Would you like me to assign it to you?

**Comment by mfecenko** [comment]
@rajivshah3 Yes, it would be cool.

**Comment by rajivshah3** [comment]
Great!

**Comment by rajivshah3** [comment]
Weird, it won't let me assign you 🤔  I'll mark this as assigned though so people know

**Comment by mfecenko** [comment]
Okay.

**Comment by f-ben** [comment]
Nice to see someone takes care of that :D thanks @mfecenko

**Comment by mfecenko** [comment]
Are there any special requirements on design of hovering textfield like text color, background color or shape of the hovering textfield?  .......... Should it be displayed every time when input field is not empty or just at the momemt when address input becomes longer then width of input field?

**Comment by f-ben** [comment]
Does it need a special style? I think it would be enough if just a white text appears which is attached to the cursor. The box on my screenshot was just to make it clearer what I mean because it´s a static image. If the text moves with the cursor I feel that a box is not necessary.
Personally I´d like the text to appear if it´s longer than the width of the input but I don´t know how hard it´s gonna be to code :D

**Comment by mfecenko** [comment]
Okay, I will try to make it like you said.

**Comment by rihardsgravis** [comment]
I propose to:
- show the tooltip only when the address bar is not focused and start to display with a short delay after mouse move
- use `--box-bg` for background and `--box-body` for text

**Comment by mfecenko** [comment]
PR created.
