### ISSUE TITLE
Avoid losing trytes of pending tx when doing manual sync after snapshot

### ISSUE THREAD

**Issue by HBMY289** [iotaledger/trinity-wallet#486]
### Bug description
Generally, Trinity keeps trytes of sent transactions to allow reattaching. However, if there is a pending transaction and a global snapshot happens then performing a manual sync afterward will remove those trytes. As you will not have the possibility to reattach the affected bundle from within Trinity, you will end up in a situation with funds on a spent address.

### Environment Specs
- Trinity version: Desktop 0.3.5

### Steps To Reproduce

1. Have a pending outgoing transaction
2. A global snapshot happens
3. The node you are using deleted its database
4. Perform a Manual Sync operation in Trinity

### Expected behavior
Trytes of valid pending outgoing transactions should be kept on manual sync, even if the respective transaction cannot be found on the tangle anymore due to a snapshot. Reattaching of those bundles should be possible in Trinity.

### Actual behaviour
Trytes of pending transactions are removed when performing a Manual Sync, if the respective transactions cannot be found on the tangle (due to a snapshot).

### Open Questions (optional)
It is important to check for validity of the trytes to keep (valid bundle and sufficient funds on input address(es)). Otherwise, you would not have a possibility anymore to remove invalid or incomplete bundles from Trinity by performing the Manual Sync.

### Am I planning to do it myself with a PR?
No.

**Comment by laumair** [comment]
Should be fixed in https://github.com/iotaledger/trinity-wallet/pull/375
