### ISSUE TITLE
Old seeds with a couple of hundred addresses are unusable with Trinity

### ISSUE THREAD

**Issue by Noki** [iotaledger/trinity-wallet#488]
### Bug description
Old seeds with a couple of hundred addresses are unusable with Trinity.

### Environment Specs
- OS version: Windows 10
- Trinity version: 0.3.6

### Steps To Reproduce
1. Create a new seed
2. Create a couple of hundred addresses using the see
3. Add some balance to the generated addresses and leave some addresses empty
4. Reset the trinity wallet
5. Restore the wallet using the seed

### Expected behaviour
- Short waiting time to add the seed to the wallet
- Generate and discover used addresses in the background and have a status indicator showing the progress
- Discover the full range of used addresses even though there are some addresses inbetween with a balance of 0 
- Discover and show transactions for discovered addresses once found

### Actual behaviour
![image](https://user-images.githubusercontent.com/198902/46830327-9569cb00-cda0-11e8-9fc5-646f2a5567be.png)
I look at this screen for a couple of hours now. I already tried reinstalling it and installing it on another machine. The result remains the same.

**Comment by laumair** [comment]
@Noki How many addresses have you left empty? 

> I look at this screen for a couple of hours now.

This seems odd to me. Even if there are a couple hundred addresses, it shouldn't take that long.

**Comment by Noki** [comment]
@laumair Here is the json with the balances:

```json
{
	"balances": ["0", "0", "0", "0", "0", "0", "264", "2463", "157", "105", "137", "95", "93", "120", "103", "103", "94", "106", "90", "9296", "131", "83", "20", "17", "28", "13", "11", "18", "13", "20", "11", "11", "18", "17", "11", "3", "6", "22", "10", "20", "8", "15", "25", "15", "4533", "3", "25", "33", "23", "30", "8", "16", "40", "23", "40", "0", "25", "0", "0", "0", "0", "28", "0", "0", "18", "0", "0", "38", "16", "0", "28", "22", "1151", "40", "73", "32", "0", "0", "0", "32", "0", "0", "0", "0", "30", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "32", "0", "0", "0", "34", "2699", "0", "0", "0", "5145", "0", "0", "0", "0", "0", "18", "0", "0", "0", "16", "0", "11", "0", "0", "1728", "0", "0", "0", "0", "0", "0", "21", "0", "0", "17", "0", "6883", "0", "10", "6", "0", "0", "0", "0", "0", "0", "0", "11", "0", "1398", "0", "2455", "18", "0", "20", "0", "2458", "5543", "0", "0", "0", "0", "1", "0", "0", "0", "0", "13", "41", "3", "0", "0", "0", "0", "0", "15", "0", "0", "0", "5", "0", "0", "0", "8", "0", "0", "0", "0", "0", "0", "20", "0", "0", "0", "0", "0", "0", "0", "8", "0", "0", "0", "0", "0", "0", "0", "0", "6", "0", "0", "0", "0", "0", "6", "0", "0", "8", "5", "5", "6", "0", "5", "17", "13", "3", "6", "8", "0", "0", "8", "0", "0", "0", "6", "5", "0", "0", "0", "0", "0", "0", "0", "0", "6", "0", "0", "0", "6", "11", "6", "26", "8", "3", "1", "8", "6", "10", "3", "7", "15", "3", "3", "23", "1", "0", "3", "6", "0", "0", "14", "3", "0", "13", "0", "5", "0", "5", "0", "5", "0", "13", "0", "6", "0", "9", "5", "0", "0", "0", "5", "10", "0", "0", "6", "5", "0", "0", "0", "0", "0", "0", "0", "0", "8", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "5", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "5", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "5", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "6", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "8"],
	"milestoneIndex": 834832,
	"duration": 196
}
```

* 370 addresses in total
* 224 addresses with 0 balance
* <20 empty addresses between two addresses that have a balance

> This seems odd to me. Even if there are a couple hundred addresses, it shouldn't take that long.

That's exactly why I opened this bug. ;-)

btw.: The first 6 addresses were already used to send iota

**Comment by laumair** [comment]
@Noki Thank you for providing the address information. 

Address generation should be near instant with 370 addresses.

I did some quick tests with [entangled-node](https://github.com/rihardsgravis/entangled-node) and it took ~20 seconds for generating 500 addresses. 
Trinity does make some network calls during address generation but those should be quick.

Also, as you mentioned this is an old seed so I am assuming there won't be any recent transactions/reattachments for your addresses. Even if there are it shouldn't take hours. 

/cc @rihardsgravis

**Comment by Noki** [comment]
There are some recent transactions/reattachments. If required to reproduce I could also provide the seed in a private email because so far I was only playing around with this one and the total balance is not really worth mentioning. ;-)

**Comment by rajivshah3** [comment]
@Noki is the animation freezing at all? I wonder if the address generation and the animation are running on the same thread

**Comment by Noki** [comment]
@rajivshah3 The animation keep on moving. However I've seen this during my various tries:

![image](https://user-images.githubusercontent.com/198902/46867683-29ca4100-ce26-11e8-9eab-1f0b7778ad31.png)

When I wait long enough I get to this screen at some point:

![image](https://user-images.githubusercontent.com/198902/46867905-cf7db000-ce26-11e8-9559-7c95c5890e1c.png)

If I add a name it starts all over again.

And the error log shows this:

![image](https://user-images.githubusercontent.com/198902/46867951-0358d580-ce27-11e8-9d86-9a41b202de93.png)

**Comment by rajivshah3** [comment]
Hmm, the "let's add a name" screen is odd. I'm not sure what would cause that screen to show

**Comment by Noki** [comment]
@rajivshah3 Is this your correct Mailaddress (rajivshah1@icloud.com)? I will send you the seed so you could try on your own. ;-)

**Comment by rajivshah3** [comment]
Yep, that’s correct. Is it ok if I forward it to Umair and Rihards so they can take a look as well?

**Comment by rihardsgravis** [comment]
Let's add a name is "fine" here. If adding an additional account does not success, the wallet returns to the onboarding last step ("Let's add a name").

**Comment by rihardsgravis** [comment]
Address generation should happen fine with 400 addresses. The error log indicates that there was a network request time out, so probably requesting address balances time out.

**Comment by rajivshah3** [comment]
Ah, maybe it sent too many requests to the node at once?

**Comment by Noki** [comment]
I just send you the "Seed of Death"! ;-)

Let me know once you have a solution.

**Comment by Noki** [comment]
A little follow-up:

I managed to add the seed to the mobile wallet. It seems that the mobile wallet does the requests in another way.

**Comment by rajivshah3** [comment]
@Noki interesting 🤔

**Comment by KiwiCat123** [comment]
If it helps I also have such a seed with exactly the same problem in Trinity. This problem seem to exist since the 0.3.0 alpha. Maybe I could help you with the seed.

**Comment by mgeier63** [comment]
Try this for a "public" seed with lots of used addresses ;-)

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

Impossible to use with Trinity, spinning for hours now...

**Comment by cvarley100** [comment]
@mgeier63 I just tested this seed on desktop (Mac OS) and left it running while I continued working. It loaded eventually (in under 30 minutes).

**Comment by Noki** [comment]
@mgeier63 Also worked on Windows for me...

**Comment by mgeier63** [comment]
I stand corrected. Tried it again with the release version of Trinity and it took ~ 15 minutes on an Nexus 5x to initially sync the Ax81 seed.
Probably running in development mode makes a big difference, 'cause that's when I witnessed the spinning for hours...
