### ISSUE TITLE
Tray Icon not visible in macOS Mojave dark mode

### ISSUE THREAD

**Issue by KK7NZY** [iotaledger/trinity-wallet#491]
### Environment Specs

- Manufacturer: Apple
- Model: iMac
- OS version: Mojave
- Trinity version: 0.3.6

### Description

Trinity tray icon is not visible in black tray. Would be cool of the icon color was inverted/white. At the moment it looks like there is a space where the icon should be. 

<img width="338" alt="screen shot 2018-10-12 at 9 56 29 am" src="https://user-images.githubusercontent.com/1626827/46873660-23779d00-ce05-11e8-939a-5b245c40f15c.png">

**Comment by rajivshah3** [comment]
@jdsantiagojr this will be fixed in the next release, please see #487
