### ISSUE TITLE
Unresponsive on Login-Dialog

### ISSUE THREAD

**Issue by b0-ones** [iotaledger/trinity-wallet#498]
### Bug description
If you have a diamond (#) in you password, it happens that you cant login to Trinity, it just does not login and does not give you an info about wrong password anymore.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: MacBook Pro
- OS version: Windows 10

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.3.6

### Steps To Reproduce
1. Pick a password with a diamond in it

### Expected behaviour
Login after successfull password input.

### Actual behaviour
Nothing. Not even a warning anymore, that it is a wrong password

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.

![unbenannt](https://user-images.githubusercontent.com/44143077/46920223-49f72d00-cfeb-11e8-96b2-e1c7659e8ead.png)

**Comment by rajivshah3** [comment]
Hi @b0-ones , when you say "diamond", are you referring to the 💎 emoji?

**Comment by b0-ones** [comment]
> Hi @b0-ones , when you say "diamond", are you referring to the 💎 emoji?

Hi @rajivshah3,  No i mean a Hashtag #

**Comment by rihardsgravis** [comment]
Cannot reproduce on macOS or Windows 10. The wallet accepts `#` as a valid password character.

**Comment by b0-ones** [comment]
Sorry i thought it was because of the # in the password. But that also happens to people without a # in the Password, so it must be related to something else. But it happens all of a sudden again and i have to reset the Wallet to use it again. 

See Discord Chat (German #hilfe) where this happened to another user called Lanz, who did not have a # in password:

https://discordapp.com/channels/397872799483428865/404635656426487828

**Comment by b0-ones** [comment]
![image](https://user-images.githubusercontent.com/44143077/48056742-b7dde100-e1b2-11e8-97cf-538a0300e069.png)

![image](https://user-images.githubusercontent.com/44143077/48056750-bb716800-e1b2-11e8-9d87-8dc2c2124122.png)
