### ISSUE TITLE
Ability to enter/detect proxy from environment variables 

### ISSUE THREAD

**Issue by tejasvi8874** [iotaledger/trinity-wallet#503]
- OS version: Windows 10

- Trinity version: 0.36

### Steps To Reproduce
1. Log in using seed

### Expected behaviour
Proxy settings should be auto fetched from environment variables or should be explicity solicited.

### Actual behaviour
http_proxy and https_proxy variables are completely disregarded and there's no way to enter proxy manually either.

### Errors

![image](https://user-images.githubusercontent.com/28995043/46992932-3c948c80-d12a-11e8-9de6-c678089f3fa7.png)

### Description
Proxy settings should be requested or auto retrieved. In my case only http proxy with authentication is concerned.
### Motivation
My University ethernet and Wi-fi require proxy for Internet access. Cellular connection is spotty in most places therefore for most part Uni's internet is used.
### Requirements
Option to enter proxy settings (with auth) manually.
Ability to auto retrieve proxy from environmental variable.

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
