### ISSUE TITLE
iOS - attemping to import existing seed crashes application

### ISSUE THREAD

**Issue by initharrington** [iotaledger/trinity-wallet#506]
### Bug description
Trinity wallet crashes when selecting "No, I have one" on the "Thank you for downloading Trinity Do you need to create a new seed?" page.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: iPhone XS Max 256 GB (mt602ll/a)
- OS version: 12.0.1 (16A405)

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.5.0 (22)
(Cannot get to settings -> about trinity)

### Steps To Reproduce
Restored from iCloud (Upgrading new phone, uninstalled trinity wallet after upgrade)
1. Install Trinity Wallet from Test Flight
2. Launch Trinity Wallet
3. Accept (2) ToS
4. Click "No, I have one"
5. Application crash after it briefly loads next screen.

Reinstalling app, same behavior
Restarting phone, same behavior

### Expected behaviour
I should be able to import my seed

### Actual behaviour
application crashed

mp4 video zip of issue:
[trinity_crash.mp4.zip](https://github.com/iotaledger/trinity-wallet/files/2487049/trinity_crash.mp4.zip)

button i clicked when it crashes (it loads the next screen briefly ~ milliseconds)
![trinity](https://user-images.githubusercontent.com/8240651/47082062-7cb34800-d1da-11e8-806c-e380fa45588a.png)

### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.
I don't have any but if you could tell me how to get, I can get them.

**Comment by rajivshah3** [comment]
Thanks for reporting. This was fixed in #417 which will be released soon
