### ISSUE TITLE
Can't exit ledger setup

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#509]
### Bug description
There is no way in the UI to exit setting up a Ledger Nano S device and buttons can still be pressed behind the request to set up a Ledger Nano S.

### Environment Specs

- OS version: Win10
- Trinity version: 0.4.0-alpha (Desktop)
 
### Steps To Reproduce
1. Click "add new account"
2. Connect Ledger Nano S
3. Click "Proceed with Ledger setup"
4. Click "Continue"

### Expected behavior
Users should be able to cancel the request to open the Ledger app. Users should also not be able to clock the faded "go back a step" option and continue to navigate the wallet while the "open Ledger IOTA app" is stuck on top of the screen.

### Actual behavior
Users can back out of the setup process but the request to "Open Ledger IOTA app" stays on the screen.

### Errors
https://i.imgur.com/Oz4h4Bs.png

**Comment by rihardsgravis** [comment]
This has been implemented and will be available in the next release.
