### ISSUE TITLE
java.lang.NumberFormatException during SeedVault import

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#517]
## Error in Trinity Mobile

**java.lang.NumberFormatException** in **NavigationActivity**
For input string: "raw:/storage/emulated/0/Download/SeedVault20180915-2112.kdbx"

[View on Bugsnag](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5bc50a82b839050019e235be?event_id=5bcb326700308891045d0000&i=gh&m=ci)

## Stacktrace

    Long.java:590 java.lang.Long.parseLong
    Long.java:804 java.lang.Long.valueOf
    PathResolver.java:43 com.RNFetchBlob.Utils.PathResolver.getRealPathFromURI
    RNFetchBlobFS.java:1125 com.RNFetchBlob.RNFetchBlobFS.normalizePath
    RNFetchBlobFS.java:154 com.RNFetchBlob.RNFetchBlobFS.readFile
    RNFetchBlob.java:226 com.RNFetchBlob.RNFetchBlob$6.run
    ThreadPoolExecutor.java:1162 java.util.concurrent.ThreadPoolExecutor.runWorker
    ThreadPoolExecutor.java:636 java.util.concurrent.ThreadPoolExecutor$Worker.run
    Thread.java:764 java.lang.Thread.run

[View full stacktrace](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5bc50a82b839050019e235be?event_id=5bcb326700308891045d0000&i=gh&m=ci)

*Created by Rajiv Shah via Bugsnag*

**Comment by rajivshah3** [comment]
This issue has been linked to an error in Bugsnag
[**java.lang.NumberFormatException** in **MainActivity**](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5bc669a9a9f3be00195f4367?event_id=5bc669b900308b14e1eb0000&i=gh&m=li)

**Comment by mgeier63** [comment]
FYI, this happens / is reproducible on Android >= 8, i.e. Oreo and Pie 
see [issue in `rn-fetch-blob`](https://github.com/joltup/rn-fetch-blob/issues/225)


[Pull request for `rn-fetch-blob` module](https://github.com/joltup/rn-fetch-blob/pull/226)

Please adjust dependency for `rn-fetch-blob` once accepted and a new version released.

**Comment by rajivshah3** [comment]
Nice find @mgeier63 , thanks so much! I'll keep an eye on your PR and update `rn-fetch-blob` once it's merged

**Comment by rajivshah3** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**java.lang.NumberFormatException** in **MainActivity**](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5bc50a82b839050019e235be?event_id=5be1a4a70030809950ea0000&i=gh&m=fx)

**Comment by rajivshah3** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**java.lang.NumberFormatException** in **MainActivity**](https://app.bugsnag.com/iota-foundation/trinity-mobile/errors/5bc669a9a9f3be00195f4367?event_id=5bdf12af00307eaf2dc20000&i=gh&m=fx)
