### ISSUE TITLE
Optional setting of "basic authentication" credentials for custom nodes

### ISSUE THREAD

**Issue by cyclux** [iotaledger/trinity-wallet#523]
### Description
Integration of "basic authentication" as an option for added custom nodes.

### Motivation
Some users prefer to secure their nodes from the public via setting credentials to the IRI API port.
Most used type is the "basic authentication" standard of the HTTP protocol.

### Requirements
On the node section of the settings menu, there could simply be two optional fields "user" and "password" under the "custom node" field. If both contain content, then include the credentials on each http request to the IRI API port of this node.

### Open Questions (optional)
Is it intended to include this feature, are there any drawbacks?

### Am I planning to do it myself with a PR?
Maybe

**Comment by rajivshah3** [comment]
> Is it intended to include this feature, are there any drawbacks?

We haven't really focused on it because not a lot of people seem to use it, but I don't think it would hurt to add it. Looking at https://github.com/iotaledger/iota.js/pull/221, it seems like there shouldn't be any drawbacks.

**Comment by cyclux** [comment]
Alright, I got quite some requests for tanglenodes.io so I implemented it there. Maybe the demand for this feature in Trinity is not so high (but it's also not so well documented for IRI yet though). Nevertheless, it does not seem like too much effort to implement it in Trinity. I might give it a shot for a PR if I find time.

**Comment by rajivshah3** [comment]
Sounds good! Let me know if you'd like me to assign this to you
