### ISSUE TITLE
password for the seedvault file seems to be fixed of 12 digits

### ISSUE THREAD

**Issue by gnodaij** [iotaledger/trinity-wallet#525]
i am using trinity of MAC version

the password for the seedvault file seems to be fixed of 12 digits for me... shorter or longer won't let me through. it is so for the latest several versions.

**Comment by rajivshah3** [comment]
Hi @gnodaij , please fill out the template. It provides important information to help us reproduce this

**Comment by gnodaij** [comment]
The issue tracker is only for reporting bugs or asking for feature requests.
If you need technical assistance for using Trinity Wallet, please consult the Trinity [documentation](https://docs.iota.works/trinity) and [knowledge base](https://iotaledger.atlassian.net/wiki/spaces/trinity/overview). For further assistance, please visit the #help channel on [Discord](https://discord.gg/7Gu2mG5).
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://forum.helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).



### Bug description
password for the seedvault file seems to be fixed of 12 digits

### Environment Specs
iMAC

- Manufacturer: 
- IMAC2014
- macOS Sierra

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 

### Steps To Reproduce
1. creat seedvault file
2.enter a password
3.only 12 digit is allowed

### Expected behaviour
my 13 digit pass should be ok
### Actual behaviour
only 12 digit password is allowed


### Errors
Attach crash logs or screenshots of error messages if available. Please ensure that these files do not contain any personal information.




**Note**
The feature request will probably be integrated faster if you do a pull request for it.
If you want to discuss the feature before you actually write the code you are welcome to do it by first submitting an issue.

### Description
say any pass word followed the rule larger than 8 digit should be ok

### Motivation
it is a bug right now i believe

### Requirements
Create a list of what you want this feature request to fulfill.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
Yes/No.

**Comment by rajivshah3** [comment]
What happens when you type the 13th character? Does it not show up, or does an error occur?

**Comment by gnodaij** [comment]
the create button is not clickable, same happened when less than 12 digit

**Comment by rajivshah3** [comment]
Which version of Trinity are you running?

**Comment by gnodaij** [comment]
the first version has the issue, it remains the same for the next several updates

**Comment by rajivshah3** [comment]
Does this occur when you try to export it from settings?

![image](https://user-images.githubusercontent.com/19519564/47333486-12266000-d651-11e8-826c-675888fa9ac1.png)

Or does it occur when creating a new account?
![image](https://user-images.githubusercontent.com/19519564/47333507-279b8a00-d651-11e8-86c2-9c9e626689b5.png)

**Comment by gnodaij** [comment]
no other people report this issue? is it only happened to me?

**Comment by rajivshah3** [comment]
That seems to be the case. I can't reproduce this on my MacBook Pro running macOS Mojave and haven't heard about this issue before

**Comment by gnodaij** [comment]
very wired

**Comment by rajivshah3** [comment]
Are you able to send a screen recording?

**Comment by gnodaij** [comment]
i created the seedvault file successfully only with a 12 digit password

**Comment by gnodaij** [comment]
i will try when i sit with my imac

**Comment by gnodaij** [comment]
BTW, how to record screen in mac?

**Comment by rajivshah3** [comment]
You can use QuickTime: https://support.apple.com/guide/quicktime-player/record-your-screen-qtp97b08e666/10.4/mac/10.13

**Comment by gnodaij** [comment]
i think it has something to do with the rule of the password...11 digit should be not long enough, 13 won't let through because the password contains phrase? so where can i find the rule for the seedvault file password?

**Comment by rajivshah3** [comment]
It should show suggestions to strengthen your password. These are the suggestions it should show: 
https://github.com/iotaledger/trinity-wallet/blob/b6fbb281d64bed4a9499f86348ab1cebb5afef4f/src/shared/locales/en/translation.json#L191-L206

**Comment by gnodaij** [comment]
what is the minimum length of the password?

**Comment by rajivshah3** [comment]
12 characters
