### ISSUE TITLE
Ability to disable auto node switching

### ISSUE THREAD

**Issue by georgmittendorfer** [iotaledger/trinity-wallet#544]
### Description

As a user of the wallet I would like to be able to tell the wallet what node(s) it should use so that I do not have to rely on other nodes, mainly for security and performance reasons.

If trinity wants to change to another node I would like to be asked and be able to prohibit this change.

In no case do I want to use another node without even being aware of it.

### Motivation

Currently there is an option for selecting a custom node. Unfortunately Trinity changes the node automatically sometimes. There is only an info screen that you can easily miss. The result is that you are connected to a foreign node without even knowing it.

Why do I not want Trinity to change the node:

* Security and privacy: I want to decide which node to trust.
* I spend money for my own node so I would like to be able to use it.
* I want to be able to choose a node that performs well.
* I might want to use a certain node implementation.
* I want to be connected to a node that has a view onto the tangle that is consistent with my wallets state. Not sure if that is really a problem, thinking about snapshots.

### Requirements

* I want to be able to tell trinity to use a single custom node or set of custom nodes. The current way of setting a custom node is sufficient for me.
* Trinity should not change to another node without my explicit confirmation.

### Open Questions (optional)

I am not aware of the errors why Trinity thinks it has to change the node. They seem to be false positives or related to the network (had it only on my mobile device so far) or response duration. I analysed all requests and responses to my node but there were no results with code 4xx or 5xx and the node was working properly when changing back.

I am not sure how this feature can be implemented together with the node quorum feature that asks several nodes for certain information. If this quorum feature is mandatory to use and can't be turned off it would be nice to be able to specify all the nodes it should use for that because I have several nodes and friends with nodes that I would trust.

### Am I planning to do it myself with a PR?

No, I am not familiar with the code and javascript.

**Comment by cvarley100** [comment]
Hi @georgmittendorfer. Thanks for the issue submission. I agree that this is would be worth adding. For advanced users, granular selection of which nodes are used, and how, is a useful feature.

**Comment by laumair** [comment]
> I am not aware of the errors why Trinity thinks it has to change the node. They seem to be false positives or related to the network (had it only on my mobile device so far) or response duration. I analysed all requests and responses to my node but there were no results with code 4xx or 5xx and the node was working properly when changing back.

Auto node switching doesn't check response status codes atm. So even if there's a network call timeout, a random node would be queried.

**Comment by kuhlmannmarkus** [comment]
@georgmittendorfer Thank you for this issue. I totally agree with you here. Theres one thing I want to add here: The automatic switching might still be useful, if I have the chance to set, which nodes may be chosen. As far as I can see, theres no possibility to remove nodes from the predefined list. I think this would actually be enough, since you then would be sure to use a node, which is compliant to your needs and you would still have the advantage of a quick switch, in case a node is not answering in time.

**Comment by no8ody** [comment]
I think many node operators would welcome this feature as they always want to be connected to their own node.

**Comment by rihardsgravis** [comment]
Added in #1509
