### ISSUE TITLE
The desktop portfolio does not upgrade

### ISSUE THREAD

**Issue by vincenzopalazzo** [iotaledger/trinity-wallet#550]
### Bug description
The application on linux mint 19 raises an error when I go to the section to check for any updates to the application, the application remains freezed until I close the error panel

### Environment Specs
What device are you running Trinity on?

- Manufacturer: DEL
- Model: latitude E5270
- OS version:Linux mint 18

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.3.6

### Steps To Reproduce
1. Open waller
2. Click on trinity
3. Click on Check for upgrades

### Expected behaviour
What should happen.

### Actual behaviour
What really happened.

### Errors
It does not appear in the log of the errors
#

**Comment by rajivshah3** [comment]
@vincenzopalazzo do any windows pop up when you check for updates?

**Comment by vincenzopalazzo** [comment]
Hello, an error window appeared when I checked the update but this seems to have been resolved with the update released in these last days, I would like to point out that with the latest update you no longer see the application menu.
I attach a photo
![selection_001](https://user-images.githubusercontent.com/17150045/47970275-9cc08380-e083-11e8-93f5-f70d04751735.jpg)

**Comment by rajivshah3** [comment]
@vincenzopalazzo thanks, would you mind opening a new issue for this since it seems to be a different problem?
