### ISSUE TITLE
Ledger wallet bug report

### ISSUE THREAD

**Issue by RedLQueen** [iotaledger/trinity-wallet#551]
ok at first i wanna say that im just a user who wants to report unormall things about ledger and trinity wallet when we are using ledger 👍 
all of them are on ledger , not trinity wallet:

1.First one which is not important so much is when we are opening iota app on ledger there is iota bran and an underlined IOTA txt on screen also there are two horizontal lines on top of ledger nano s' screen. what are those ?? :)) i mean in any of other apps of ledger we cant see these things

2.The other thing which i faced with that its when we are generate a receive address when we want to check it on ledger device when we push right bottom on ledger and after we go to the bottom there is some weird characters down there:))) again what are those??? 🗡 

3.The other thing which is not happen always but sometimes when u open iota's app on ledger when u push right bottom for going down , after it goes down it will jump to up , and u should push right bottom two or three times quick to stay at down:))) not jumping up to that iota brand and underlined iota weired thing :)))

4.This one is kinda question , there is no settings or something like that on iota's app on ledger so we can see seed or connect to seed with phone trinity... so there wont be ??? we cant access to seed at all with phone or something like that ??? it means our iotas will store on ledger device ??

But tnx alot for creating this kinda wallet i was waiting for this for long time, and sry for my bad english :D

**Comment by rajivshah3** [comment]
> 2.The other thing which i faced with that its when we are generate a receive address when we want to check it on ledger device when we push right bottom on ledger and after we go to the bottom there is some weird characters down there:))) again what are those??? 🗡

I think you're referring to the BIP32 path, which is a standard Ledger feature. From the Trinity Docs:

> When displaying a full input or change address, scroll to the bottom to view the BIP path used to generate that address. It will look something like “ 2c’|107a’|0’|0’ ”. The device uses this path to define which seed the address belongs to.

I think @wollac would be able to answer 1, 3, and 4

**Comment by Wollac** [comment]
> 1. When we are opening iota app on ledger there is iota bran and an underlined IOTA txt on screen also there are two horizontal lines on top of ledger nano s' screen. what are those?

This is explained in the Trinity docs:
> ... a “double button press” is prompted by two horizontal lines at the top of the Ledger screen. And in a menu, a “double button press” will either confirm the selected-menu option, or take you back to the previous menu.

In that particular situation, on the start screen, it indicates that a double button press will close the application without the need to "exit" in the menu.

Concerning 2. When you experienced this behavior, was Ledger Live open in the background trying to access the Ledger? Did it ever happen with both Ledger Live and Trinity closed?

Concerning 4. It is the fundamental security assumption of the Ledger Nano S, that the seed never leaves the device or is displayed on its screen. Trinity Mobile does not support the Ledger Nano S integration.

**Comment by rajivshah3** [comment]
> Trinity Mobile does not support the Ledger Nano S integration.

It does seem that the Ledger team has created some [React Native libraries](https://github.com/LedgerHQ/lib-ledger-core-react-native-bindings) though, so it could be a possibility in the future.

**Comment by cvarley100** [comment]
Many of your questions are answered [here](https://github.com/IOTA-Ledger/blue-app-iota) and [here](https://trinity.iota.org/hardware).
