### ISSUE TITLE
Trinity gives receiving address that already has funds.

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#562]
### Bug description
Trinity gives receiving address that already has funds on it as a newly generated receiving address. If users hit "Sync address", Trinity crashes.

### Note
This bug occurred when using the Ledger Nano S

### Environment Specs
- OS version: Win10
- IOTA Ledger App version: 0.4.1
- Ledger Nano S Firmware Version: 1.4.2

- Trinity version: 0.4.0-BETA   (Desktop)

### Steps To Reproduce
1. receive funds (unknown exact cause)
2. find that the receiving address you have generated is the address that just received funds. (Error in itself)
3. hit sync address
4. Crash

### Expected behavior
Upon hitting receive tab, a new address should be given to the user that has never received funds before.

### Actual behavior
Upon hitting receive tab, an address is given to the user that already has funds on it.

### Errors
- GUI crash after hitting "sync address":
https://i.imgur.com/bZ7LKwf.png
- Misplaced error message upon restart:
https://i.imgur.com/o5YnB64.png

**Comment by rajivshah3** [comment]
@SleepingFox88 are you able to reproduce this in the development version? Please use https://github.com/iotaledger/trinity-wallet/pull/563 as the `develop` branch may not work at this time

**Comment by laumair** [comment]
@SleepingFox88 Are you also facing this on mobile `v0.5.1`?

**Comment by laumair** [comment]
@SleepingFox88 Also, does it take a while before crashing or does it crash instantly after you press the sync button?

**Comment by sloganking** [comment]
@laumair

> @SleepingFox88 Are you also facing this on mobile `v0.5.1`?

I have not experienced any issues but may do some testing to see if there are any issues on mobile. The crashing as described above might be only when a Ledger Nano S is running the account, which would not be Ledger related.

> @SleepingFox88 Also, does it take a while before crashing or does it crash instantly after you press the sync button?

It takes a couple seconds. Video below.
https://streamable.com/kis1b 

Edit:

Take note the wallet only seems to crash when the account is managed by a Ledger Nano S, the account is receiving a pending transaction, and the sync address button is pressed.

**Comment by cvarley100** [comment]
@SleepingFox88 This should be fixed in https://github.com/iotaledger/trinity-wallet/pull/571. Please reopen this if it continues to occur.
