### ISSUE TITLE
[Feature Request] Option to rearrange account list

### ISSUE THREAD

**Issue by MickBenjamins** [iotaledger/trinity-wallet#564]
### Description
On the desktop I want to be able to rearrange the Account list on the left hand side of the UI.

### Motivation
Currently the only way to rearrange the Account list is by deleting accounts, and adding them again in a different order

**Comment by laumair** [comment]
Related issue https://github.com/iotaledger/trinity-wallet/issues/461

**Comment by rajivshah3** [comment]
Closing as duplicate
