### ISSUE TITLE
Menu bar not displayed correctly

### ISSUE THREAD

**Issue by vincenzopalazzo** [iotaledger/trinity-wallet#568]
### Bug description
The menu bar is not displayed correctly

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Del
- Model: E5270
- OS version:Linux mint 19

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.4.0

![selection_001](https://user-images.githubusercontent.com/17150045/47970502-9c75b780-e086-11e8-8bc3-73c6966f929d.jpg)

**Comment by rajivshah3** [comment]
Hi @vincenzopalazzo , has this always been the case, or was this introduced in 0.4.0?

**Comment by vincenzopalazzo** [comment]
Hi @rajivshah3 , it was introduced with the update to version 0.4.0

**Comment by rajivshah3** [comment]
Hi @vincenzopalazzo , is the behavior you're seeing similar to https://github.com/iotaledger/trinity-wallet/issues/691? It's a bit hard to tell from your screenshot

**Comment by vincenzopalazzo** [comment]
Hello @rajivshah3, no my problem is resolved.

Look this 
![selection_016](https://user-images.githubusercontent.com/17150045/50762236-aa091280-126c-11e9-8d44-09c6709aab9e.png)

**Comment by rajivshah3** [comment]
Thanks @vincenzopalazzo , I'll close this since it's resolved
