### ISSUE TITLE
[Ledger account] cannot send message

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#573]
### Bug description
It is impossible to send a message (i.e. a 0i transaction) with a Ledger account. 

### Environment Specs
OS Linux Mint 18 (but i know someone who reproduce it under Windows 7)
Ledger firmware version: 1.4.2
IOTA app version: 0.4.1
Trinity version: 0.4.0-alpha

### Steps To Reproduce
1. Plug your Ledger and open the IOTA app on your Ledger. 
2. Open a Ledger account on Trinity
3. click on "send" to display the send screen. 

### Expected behaviour
The MESSAGE field should be active and it should be possible to send 0i tx. 

### Actual behaviour
![image](https://user-images.githubusercontent.com/9414596/48001983-7db90480-e10a-11e8-9e91-4e2906026607.png)
The MESSAGE field is inactive. 
Plus it is impossible to send a 0i transaction (error message: "Transfert error: something while sending your transfert. Please try again").

**Comment by TylerHann** [comment]
0i transactions don't require a signature from the Ledger, nor are messages signed. I believe both should be compatible with Ledger (run a check for 0i before querying Ledger).

**Comment by rihardsgravis** [comment]
Fixed in #570
