### ISSUE TITLE
checksum highlighting on receiving addresses using ledger

### ISSUE THREAD

**Issue by f-ben** [iotaledger/trinity-wallet#581]
### Description
Since Ledger can only display a limited amount of characters and by default shows the first few characters and the complete checksum for a receiving address, trinity should highlight this part of the address.

### Motivation
Makes it a lot easier for ledger users to check that the address shown in ledger matches the one in trinity.

### Open Questions (optional)
Highlight only the checksum or also the first few characters which are shown on ledger? I´d prefer both highlighted.
Enable this feature only for accounts using ledger since for regular users this feature is not that relevant and may confuse the regular user?

### Am I planning to do it myself with a PR?
No

**Comment by cvarley100** [comment]
Already done 🙂 

https://github.com/iotaledger/trinity-wallet/pull/575

**Comment by f-ben** [comment]
stop being so good
