### ISSUE TITLE
Clicking "No" during snapshot transition keeps adding to the detected balance

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#599]
### Bug description
Originally reported by olaz preton#0333 on Discord

Clicking "No" repeatedly during the snapshot transition keeps adding to the detected balance, even though the detected balance is higher than the actual balance. It seems like Trinity is regenerating the same addresses, treating their balances as new, and then adding the balances to the detected balance.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: MacBook Pro
- OS version: macOS Mojave 10.14.1

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity). 

- Trinity version: Develop (as of https://github.com/iotaledger/trinity-wallet/commit/08b0b8df600f27dbe024413540744afd99df1e55)

### Steps To Reproduce
1. Add a seed with a balance to Trinity
2. Perform a snapshot transition (click the gear, go to Tools, then click Snapshot Transition)
3. Click "No" about 10 times

### Expected behaviour
Trinity should generate new addresses and check their balances.

### Actual behaviour
After the "No" button is clicked 10 or more times, Trinity will repeatedly generate the same set of addresses and add to the detected balance.

### Errors
N/A

**Comment by codehypes** [comment]
Can you please provide a screenshot of the feature you mentioned, as I find it difficult to reproduce the same scenario

Best Regards,

**Comment by rajivshah3** [comment]
Hi @coderntester , here's a screen recording of the issue: 
[Snapshot Transition Bug.mov.zip](https://github.com/iotaledger/trinity-wallet/files/2591576/Snapshot.Transition.Bug.mov.zip)

I apologize for sending it as a .zip but it seems like GitHub doesn't accept video uploads

**Comment by codehypes** [comment]
Hi @rajivshah3
 
however that does not update the real balance of my account.what is its impact?

Best Regards,

**Comment by rajivshah3** [comment]
@coderntester right, it shouldn't affect the real balance. But it makes the user think that they found more IOTA than they should have 😄
