### ISSUE TITLE
DevTools with websocket access always running by default (appimage)

### ISSUE THREAD

**Issue by CrashTD** [iotaledger/trinity-wallet#604]
Starting the .appimage via command line on linux shows 
> DevTools listening on ws://127.0.0.1:35437/devtools/browser/998eaa1d-9840-4d08-850d-449efaa073ad

This address seems to be a websocket and accept json. not tested further. however, now its possible to access http://127.0.0.1:35437/json and get more information about trinity. especially the 

> "devtoolsFrontendUrl": "/devtools/inspector.html?ws=127.0.0.1:35437/devtools/page/E6558DE92883401BA3D32963E229AB01"
> 
which rewritten like this allows opening trinity inside the browser and use the browsers own dev tools / console

http://127.0.0.1:35437/devtools/inspector.html?ws=127.0.0.1:35437/devtools/page/E6558DE92883401BA3D32963E229AB01

I don't know if that poses a potential security risk, but at least i think devtools should not running by default / there should be no open websocket that could allow access.

- OS: 4.19.2-1-MANJARO
- Trinity version: 0.4.0

**Comment by rihardsgravis** [comment]
Unsetting remote-debugging-port (#541) on runtime results in running the debug mode on random port rather disabling it. The application can only be terminated if debug mode is detected, fixed in #610
