### ISSUE TITLE
[Linux Debian based distros] Bitcoin symbol not displayed

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#605]
### Bug description
The Bitcoin symbol is not correctly displayed in the market section of an account. 

### Environment Specs
- OS version: Linux Mint 19 (some people reported the same issue on Debian based distros)
- Trinity version: 0.4.1 but already present in previous versions.

![image](https://user-images.githubusercontent.com/9414596/48707616-4bc29a80-ec00-11e8-867f-d1152943173e.png)

**Comment by ghost** [comment]
nb: €, $ and ETH symbols are correctly displayed.

**Comment by rajivshah3** [comment]
We could try using the Thai Baht symbol like we've done for Android:

https://github.com/iotaledger/trinity-wallet/blob/b3cb1e1002fe56e7d8217deec016690b3c0cf4f0/src/mobile/src/ui/components/Chart.js#L99-L101

**Comment by cvarley100** [comment]
Closing this as it's an OS issue more than anything and there's no easy way for us to detect which distro supports it and which doesn't.
