### ISSUE TITLE
Auto-promote intensity setting

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#619]
### Description
Have an option in settings where users can choose to auto-promote every few minutes or constantly until pending transactions are confirmed.

![photo_2018-11-20_18-08-54](https://user-images.githubusercontent.com/16965931/48808602-6162bd80-ecef-11e8-9c1e-b10277e456bd.jpg)

### Motivation
This will let users pick between saving power and having faster confirmations.

### Requirements
Create a list of what you want this feature request to fulfill.

### Open Questions (optional)
This feature may have similar development considerations to this one https://github.com/iotaledger/trinity-wallet/pull/295

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
