### ISSUE TITLE
When sending to self, display an icon in history (instead of two transactions)

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#620]
### Description
When sending to yourself we currently have the wallet show two transactions, one sending and one receiving of the same amount. I suggest only showing one transaction but changing the Plus or Minus Icon to an arrow that loops back around to itself to indicate you sent funds to yourself.

### Motivation
Simply transaction history screen and reduce clutter.

### Requirements

Display a transaction that is sending from and to the same account, not as two transactions like this.
![photo_2018-11-20_18-19-56](https://user-images.githubusercontent.com/16965931/48809033-f2866400-ecf0-11e8-9cb1-825d4ed9c6a8.jpg)

But one, using a symbol like this to indicate the user sent funds from and to the same account.
![clockwise-refresh-arrow_318-85995](https://user-images.githubusercontent.com/16965931/48809076-2792b680-ecf1-11e8-9173-0e8606878067.jpg)

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
