### ISSUE TITLE
App doesn't recognize installed dependencies

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/trinity-wallet#621]
### Bug description
Trinity Desktop is unable to correctly determine the installed dependencies shown by "Missing security dependencies" screen:

Screenshot from 2018-11-21 12-49-01
![image](https://user-images.githubusercontent.com/1385611/48839441-d683d080-ed8b-11e8-80fa-e9f6208990f2.png)

![image](https://user-images.githubusercontent.com/1385611/48839600-47c38380-ed8c-11e8-9687-e3f0009f0a02.png)

### Environment Specs
Ubuntu 18.10 64x

- Trinity version: 0.4.2

### Steps To Reproduce
1. install ubuntu 18.10
2. install the required dependencies
3. chmod +x the app image file
4. execute the app image file

### Expected behaviour
Trinity should start and recognize the dependencies.

### Actual behaviour
The "Missing security dependencies" screen is shown.

**Comment by IOTANGLE42** [comment]
Same problem/bug is on Ubuntu 18.04.1 LTS. All asked libraries installed but still the message with "Missing security dependencies". Additionally I Installed Trinity Wallet on a new laptop and got there a stuck after "choose your ledger account index" like #589 .
Also on Ubuntu 18.04.1 LTS.
Is there already a solution?

**Comment by rihardsgravis** [comment]
Is this still reproducable with Trinity desktop`0.4.3`? Cannot reproduce with vanilla default setup Ubuntu `18.04.1` and `18.10.1`.

**Comment by IOTANGLE42** [comment]
Hi Rihards, 

updated from 0.4.2 to 0.4.3 and still the same problem (Ubuntu 18.04.1 LTS).

**Comment by rihardsgravis** [comment]
Can finally reproduce when running the wallet as root user (`sudo`). The issue is with `node-keytar` https://github.com/atom/node-keytar/issues/132 . Will work on a fix.

**Comment by IOTANGLE42** [comment]
OK thanks mate

Am Mo., 10. Dez. 2018, 22:08 hat Rihards Gravis <notifications@github.com>
geschrieben:

**Comment by IOTANGLE42** [comment]
OK thanks :)

**Comment by rajivshah3** [comment]
Closed in #779

**Comment by sacrificium-dev** [comment]
Wanted to try Trinity Wallet on Ubuntu 18.04.1 LTS. Have the same issue. Downloaded trinity-desktop-0.4.6.AppImage. All dependencies are up to date. Someone else this problem again with Trinity Wallet 0.4.6?

**Comment by rajivshah3** [comment]
@DannyS86 is the `gnome-keyring-daemon` process running?

**Comment by IOTANGLE42** [comment]
@DannyS86 do you run App with sudo? Only work when you do NOT start with sudo

**Comment by sacrificium-dev** [comment]
@IOTANGLE42 yes, I started with sudo. Without the trinity wallet won't come up without displaying any information in the Terminal.
@rajivshah3 yes, the `gnome-keyring-daemon` is running.
Thank you guys!

**Comment by luca-moser** [comment]
I've deleted the folder `~./.config/Trinity`. Downloaded `trinity-desktop-0.4.6.AppImage`, `chmod +x`ed it and ran the app image file without sudo. Trinity then finally loaded correctly and recognized the installed dependencies, however, it doesn't register correctly as an application as one has to manually run the binary from the terminal. Opening "Home" and searching for "Trinity" doesn't give any results.

**Comment by sacrificium-dev** [comment]
@luca-moser thank you, that's it! Deleting the `~./.config/Trinity` was the solution in my case. Then I was able to start the Trinity Wallet (without sudo).
Another question by the way: is there anywhere saved a wallet-file that I can copy to my external HDD or is the SeedVault the only solution for securing the wallet outside from my computer?

**Comment by KnockKnockNe0** [comment]
I got the same issue on Debian 9.6 (stretch) and Ubuntu 16.04 (xenial)
The error message seems to depend on the locale:
```
export LC_ALL=de_DE.UTF-8
The text in Electron is: "Missing security dependencies"

export LC_ALL=C
The text in Electron is: "Cannot connect to Secret Service API"

```
gnome-keyring-daemon is running (tested with seahorse) and i'm not root.

The keytar example mentioned in https://github.com/atom/node-keytar/issues/132 actually does work here, showing my password.

**Comment by rihardsgravis** [comment]
I will close this issue as the original issue is reported to be fixed (Trinity doesn't register correctly as an application should be opened as a new issue).
