### ISSUE TITLE
Add progress bar on transaction retry

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#627]
### Description
Add a progress bar for transactions sending status when users manually hit retry on existing transactions.

### Motivation
This will help users be more aware when there are bugs and the retry button is not working as well as it could. Be that with IRI or with Trinity itself.

### Requirements
- Add a transaction sending progress indicator near the spinning "retrying" Icon in transaction details.

![toipkqh](https://user-images.githubusercontent.com/16965931/48864735-7c8b0700-ed9b-11e8-8a3f-4f1d80c9a742.png)

- It should function similar to if not the same as the progress bar on the send transaction page.

![wcfqfn5](https://user-images.githubusercontent.com/16965931/48864648-36ce3e80-ed9b-11e8-9939-cee265499078.png)

### Open Questions (optional)
- It is highly advised for this progress bar to share functionality desired in issue https://github.com/iotaledger/trinity-wallet/issues/625 when available.

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
