### ISSUE TITLE
Make checksum blue on all displayed addresses

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#632]
### Description
Make checksum blue on all displayed addresses

### Motivation
This will allow for faster user address verification, and further promote a consistent standard for how addresses are expected to be displayed.

### Requirements
Make the checksum of an address shown in blue like the address generation page already does.
https://i.imgur.com/gg33N32.png

On the:

Send page:
https://i.imgur.com/12a857z.png

Account Addresses page:
https://i.imgur.com/yv0xeTa.png

Transaction details page: (displayed when wallet is in advanced mode)
https://i.imgur.com/v9LqLCq.png

### Open Questions (optional)
- Are there any places where addresses are displayed without a blue checksum that was not listed in requirements?

### Am I planning to do it myself with a PR?
No.

**Comment by rajivshah3** [comment]
Reopening for mobile

**Comment by cvarley100** [comment]
No plans to do this on mobile
