### ISSUE TITLE
Zero balance after re-install

### ISSUE THREAD

**Issue by Trigs21** [iotaledger/trinity-wallet#640]
Bug Description

After re-installing Trinity on my phone, entering my seed (which was checked several times for accuracy), entering my account name and password, it shows my balance as zero and I get a pop up window saying "Is your balance correct?" it continues to say that i should do a snapshot transition, however I cannot continue from this screen as the "Okay" button has no reaction when i click on it,  In fact the app is unresponsive at this point and i have force it to close.  I tried this several times with the same result.

After having no luck with my phone, i downloaded and installed the desktop trinity wallet.  Entered my seed, entered my account name and password.  The balance still says zero but at least i can navigate through the menus.  I followed the steps in the help to change the node and did a manual sync.  I even tried the snapshot transition but balance still shows zero. At this point, without further solutions provided I dont know what to do.  

### Environment Specs
What device are you running Trinity on?

- Manufacturer: SAMSUNG
- Model: Galaxy S7
- OS version: 8.0.0

What build of Trinity are you running?
0.5.1
I cannot provide the full one as I cannot get passed the pop up window mentioned above. But it is the latest one available in Google Play (as of Nov.26th 2018)

- Trinity version: 0.5.1

Steps To Reproduce
1.Re-install Trinity Wallet on mobile phone
2.Enter seed, account name and password
3.Upon logging in, popup window displays "Is Your Balance Correct?" and hangs.

### Expected behaviour
1.  On Mobile Device: Pop up window show closed when pressing "Okay" allowing user to navigate to the suggested solution.
2. On Desktop App: Balance should display after changing the node and doing a manual sync.

### Actual behaviour
1. On Mobile Device: After logging in, the popup window stating "Is your balance Correct?" hangs, preventing the user from continuing.
2. On Desktop App: After logging in, balance shows zero and chaning node and doing a manual sync , and a snapshot transition still shows balance of zero.

Errors
![screenshot_20181126-074406_trinity](https://user-images.githubusercontent.com/45332663/48997914-d734b200-f151-11e8-841e-596d7f029284.jpg)

**Comment by cvarley100** [comment]
Hi @trigs21. How did you store your seed? The snapshot transition modal hang has been resolved for the next release.

**Comment by Trigs21** [comment]
Hi @cvarley100 The seed was generated through the trinity wallet option at the very beginning; I copied the seed and saved it locally.

**Comment by laumair** [comment]
@Trigs21 Do you only see a single address in `Settings > Account Management > View Addresses` ?

**Comment by Trigs21** [comment]
@laumair Yes, I believe in the Trinity Desktop I can only see one address.

**Comment by Trigs21** [comment]
@cvarley100 does this mean that I will not be able to see my balance until next release when the hang is resolved?

**Comment by cvarley100** [comment]
@trigs21 The two items should be unrelated. So you generated the seed from within Trinity on Android. How did you copy it to store it?

**Comment by Trigs21** [comment]
@cvarley100 I just followed the instructions on the screen, i wrote it down and confirmed i backed it up.  I have also saved it in my email account so its available anytime should i need it.  I dont think the issue is with the seed as i had this seed for a while now and i never had an issue with my balance before, even after a few transactions, it is just recently that the balance did not show correctly (after the reinstall) 
If you say the hang is a separate item, then there is a real problem.  what do you need from me in order to investigate further why my balance is zero.

**Comment by Trigs21** [comment]
@cvarley100 @laumair  Just wanted to let you know that after reinstalling the mobile Trinity wallet for the third time and following the steps in the help i finally managed to get the correct balance.  I wish i knew what was wrong the first two times but I'm sure glad i can sleep better at night knowing my balance is back.  Thank you for your time to help me.
