### ISSUE TITLE
Ability to use Trinity Desktop in offline mode

### ISSUE THREAD

**Issue by dreamfony** [iotaledger/trinity-wallet#647]
I would like to use Trinity Desktop in offline mode on a air gaped computer. In offline mode I would like to 

- generate a seed and a receive address 
- generate and sign payments and export them to a file which I can import and transfer to the network on a second online computer with Trinity Desktop.

**Comment by wonkytonky** [comment]
a lot of ppl are looking for this feature !

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
