### ISSUE TITLE
Allow "No fiat currency" mode

### ISSUE THREAD

**Issue by brunoamancio** [iotaledger/trinity-wallet#649]
### Bug description
I think it makes sense to allow users not to show any currency conversion in USD, EUR or anything else. Especially when I'm with somebody who doesn't know about IOTA and sees the balances. In This case I'd like to only display my balance in IOTA.

### Environment Specs
All

- Trinity version: Latest

### Expected behaviour
No balance convertion to FIAT show be displeyd in the GUI.

### Actual behaviour
There is no option to hide FIAT balance from GUI.

### Am I planning to do it myself with a PR?
No.

**Comment by brunoamancio** [comment]
?

**Comment by cvarley100** [comment]
@brunoamancio So you would like an option to remove fiat balance conversion, fiat conversion on send, and the chart & current price/MIOTA?

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
