### ISSUE TITLE
individualLetterCount & randomiseCharsToContinue on seed generation NEEDS to be precised and enhanced for more languages

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#654]
### Bug description
On seed generation screen we need to click random letters 10 times. And we have these strings to click more individual letters here.

We have 2 different forms on crowdin which are translated properly but there is a problems with it. Only individual form is used with all letters.

10 letter**s** and 1 lette**r** is never distinguished and always displaying individual form. (see screenshots and it's names)
![should be individual - it s individual](https://user-images.githubusercontent.com/35224101/49194458-83a9aa80-f383-11e8-8d8a-edf0dad75f43.png)
![should be plural - it s individual](https://user-images.githubusercontent.com/35224101/49194459-83a9aa80-f383-11e8-8a6a-8e546373fa7c.png)

**What's even more important!** In polish (and even more languages) we have two different plural forms. So it should be properly displayed like this:

10, 9, 8, 7, 6, 5 - liter _(in english it's - LETTERS)_
4, 3, 2 - litery _(in english it's still - LETTERS)_
1 - literę _(in english it's - LETTER)_

The same goes to this box:
![utgxpx8](https://user-images.githubusercontent.com/35224101/49194673-69240100-f384-11e8-8e02-5c6499d1bc42.png)

Properly it should be
10, 9, 8, 7, 6, 5 - znaków
4, 3, 2 - znaki
1 - znak

I know maybe it's really little thing but overall Trinity wallet is polished so well so would be good to have even these things great!

### Environment Specs
PC - Win7

- Trinity version: 0.4.2

**### Requirements
Please create 3 different forms for "randomiseCharsToContinue" and "individualLetterCount"
10, 9, 8, 7, 6, 5 - plural1
4,3,2 - plural2
1 - individual**

(that's how it would work in Polish language - I'm not sure about the other. It would be good if some others would comment on this submit.

### Open Questions (optional)
How these forms works in other languages?

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment]
That's odd, I think it worked for Spanish (same singular/plural as English, 1 is letra, 2 or more is letras) when I first added these strings. I'll have to investigate. This might be specific to languages that have multiple plural types

**Comment by UmbahaSpodPaha** [comment]
Steps to reproduce:
1. Reset the wallet
2. In the first setup change the language to Polish for example
3. Head to new seed generator
4. You see that "Press X more letters..." does not changing the form within the letters left (It's properly translated on github though)

**Comment by cvarley100** [comment]
@UmbahaSpodPaha I can't repro the first issue. It seems to work as expected.

I think it might get a bit too granular if we start accommodating for things like the Polish 4, 3, 2 plural form, as this may be different in multiple languages and we would have no idea.

**Comment by rajivshah3** [comment]
I think this is supposed to be handled by the `i18next` lib. I'm looking into it

**Comment by UmbahaSpodPaha** [comment]
I just received an message about typo in polish localization when in fact there is not any. :D

It's about this problem though. 

**Maybe we can change the form of this to:
"Keys left to randomize: _value_" ? or something like that.**

**Comment by UmbahaSpodPaha** [comment]
Or can I just do it by myself in PL localization maybe to not interfere with what already is done?

**Comment by UmbahaSpodPaha** [comment]
Another polish guy noticed it in and sent me message so I developed an individual workaround for PL lang (I will explain in ENG):

**_individualLetterCount_** and _**individualLetterCount_plural**_
are now both:

> You have to randomize (press) the following number of characters: <1><0>{{count}}</0></1>

and

**_randomiseCharsToContinue_** and **_randomiseCharsToContinue_plural_**
are now both:

> Characters to randomize: <1>{{count}}</1>

- - - - - - - - - - - - - - - - - - - - - - - - - - - - 

I hope it can stay like this! ;) I only changed it for lang I'm working on: PL
Every other language with that problem needs to come up with similar solution I think.

@rajivshah3 if you think the case is closed, please close this one. ;)
