### ISSUE TITLE
Add separators or tabs to differentiate standard and ledger accounts

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#655]
### Description
I came up with the idea for sorting/seperating standard and ledger accounts (when one is used). It would be either simple seperators like on the screenshot i prepared or tabs (like in Google Chrome for example)
![accounts types](https://user-images.githubusercontent.com/35224101/49195516-bbb2ec80-f387-11e8-8d66-d8862200b3af.png) 

Or tabs draft:
![accounts types-tabs](https://user-images.githubusercontent.com/35224101/49195789-c1f59880-f388-11e8-9adf-b50bf9f08014.png)

### Motivation
It's just a simple idea. it would looks better and would be useful for users with many accounts

### Requirements
Add some sort of seperating standard accounts from ledger accounts

### Open Questions (optional)
I would love to hear some feedback on this idea from other community members.

### Am I planning to do it myself with a PR?
No

**Comment by cvarley100** [comment]
@UmbahaSpodPaha @rihardsgravis We could simply add a Ledger icon for ledger accounts here.

**Comment by UmbahaSpodPaha** [comment]
@cvarley100 Oh yeah! Simple icon would be great too! Nice that you still have this one on mind. :D
