### ISSUE TITLE
Strange behavior in transactions search-bar

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#656]
### Bug description
The search-bar in transaction history acts really weirs and unintuitive. I put "13324" into search-bar and it showed me a lot of random transactions. Searching by tx messages kinda works though. Writing 30Ki or 30 Ki and still nothing.

### Environment Specs
PC - Win7

- Trinity version: 
0.4.2

### Expected behaviour
I would like to have responsive and intuitive search-bar like in banking system so we can search with dates, tx messages, od exact amounts like Mi, Ki, Gi - like 123 Mi

If it's supposed to work like that - maybe add some instruction or questionmark with little help-box to explain how it works.

### Actual behaviour
Search-bar acts really strange. Don't even know if it works properly.

### Am I planning to do it myself with a PR?
No

**Comment by UmbahaSpodPaha** [comment]
Also when we have some text typed in search box, It would be good to have a little "X" button to remove current typed-in text.

**Comment by rihardsgravis** [comment]
When inputing a number, the transactions are filtered to those which contain the same or more amount entered (e.g. entering `13324` will show all transactions that contain 13324 iota or more).

I agree – help box clarifying this and supporting Mi, Ki, Gi input would be helpful.
