### ISSUE TITLE
Feature Mobile+Desktop - Add fast-scrolldown button to the Terms and conditions & Privacy Policy

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#657]
### Description
Add quick scroll button to Terms and conditions & Privacy Policy pages on both DESKTOP and MOBILE versions. Would be great to have that fancy animation that scroll fast trough text to show us how much we "missed".
![fv8kbfy](https://user-images.githubusercontent.com/35224101/49197827-af7f5d00-f390-11e8-8587-4c738ba864a6.png)

### Motivation
Better user experience. I know it have to be there but let's be honest! ;) Let's simplify the first configuration of the wallet.

### Requirements
Add quick scroll button to Terms and conditions & Privacy Policy pages on both DESKTOP and MOBILE versions.

### Open Questions (optional)
I would like to hear some feedback from the community

### Am I planning to do it myself with a PR?
No

**Comment by UmbahaSpodPaha** [comment]
Refreshing this one! It would be so good to have this one as well. Thanks

**Comment by rajivshah3** [comment]
Hi, unfortunately we cannot implement this for legal reasons. We ask that you read the terms and conditions and privacy policy carefully, as it includes information about our liability and how we will process your data
