### ISSUE TITLE
"Corrupted" string on dropping SeedVault file + wrong string

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#659]
### Bug description
1. Weird <1></1> tags showing up when we're trying to drop seedvault file onto Trinity
2. There shouldn't be "...or click to browse" sentence in this exact string since we're already in the process of dropping file into the windows. We can't really "click to browse" on this screed. I know it's a leftover from the previous box when we're setting new seed.

![droppingseedvault](https://user-images.githubusercontent.com/35224101/49198497-a3e16580-f393-11e8-86a7-7cbbc38c9dca.png)

### Environment Specs
What device are you running Trinity on?
PC - Win7

- Trinity version: 
0.4.2

### Expected behaviour
1. The same text without these unused <1></1>
2. Text without "...click to browse" on this exact window

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment]
Ah, I keep forgetting to fix that. The reason why this happens is because when I added this the first time, the string was actually used in another area. I didn't realize it was used here as well. Thanks for reminding me 👍
