### ISSUE TITLE
disconnected ledger, still showing address when request new address

### ISSUE THREAD

**Issue by wonkytonky** [iotaledger/trinity-wallet#671]
### Bug description
when ledger is disconnected, requesting address still shows an address in background what is this address? and should it be there?
![image](https://user-images.githubusercontent.com/19390834/49250535-57dc0280-f41f-11e8-82a9-dd87e6072536.png)

### Environment Specs
desktop, win 10

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 
4.3
### Steps To Reproduce
1. open account that needs ledger
2. request new address
3.

### Expected behaviour
What should happen.
not show an address ?

### Actual behaviour
shows an address

**Comment by rihardsgravis** [comment]
It's the valid receive address you see in the background. To generate an address, a connected Ledger device is required. Once the address is generated it is cached by Trinity. When you press `Generate address`, the stored address is checked to still be a valid receive address - and if it is, it's shown on the screen. If it would not, a connected Ledger device would be required and no address would show in Trinity.

You see the `Connect your Ledger` screen to show the address also on the Ledger device screen, so you can manually check if it's a valid address you see in Trinity.

**Comment by wonkytonky** [comment]
thanks for the info

keep up the good work all
