### ISSUE TITLE
Can't resize Trinity from the top of the window

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#673]
### Bug description
We can't resize the window of Trinity from the top of the window.

### Environment Specs
What device are you running Trinity on?
Desktop - Win7 x64

- Trinity version: 
0.4.3

### Expected behaviour
Allow to resize from all sides and corners

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment]
Does an arrow show up when you hover over the edges of the window?

**Comment by UmbahaSpodPaha** [comment]
> Does an arrow show up when you hover over the edges of the window?

It does show on all edges and corners **except top edge itself**.
That's the main issue ;)
