### ISSUE TITLE
[Ledger] Account gets broken after receiving/sending

### ISSUE THREAD

**Issue by Hissi88** [iotaledger/trinity-wallet#675]
### Bug description
A newly created Ledger account shows follow behavior as soon as it has an (pending) input or an output. 
Even 0-valued Rx/Tx count.

**1.** 
The seed window changes immideatly from
![grafik](https://user-images.githubusercontent.com/45494848/49304481-bf03c080-f4cc-11e8-8656-931938259225.png)

to this

![grafik](https://user-images.githubusercontent.com/45494848/49304494-c75bfb80-f4cc-11e8-833f-7ed2313da99b.png)
Buttons dont work of cause.

**When sending from this broken account then, Trinity even starts the process although the Ledger is disconnected!!** 

Luckily the sending fails after preparing inputs with this error:
![grafik](https://user-images.githubusercontent.com/45494848/49308137-ba90d500-f4d7-11e8-8220-7dcee8ac7ab3.png)

After deletion and new creating the Ledger account number is visable again until the next input or output.

### Environment Specs
What device are you running Trinity on?

- Windows 7
- Desktop Version
- System proxy disabled (wouldnt even start otherwise)

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: trinity-desktop-0.4.3.exe (sha256: 025aa229878ec3f59e28d6f214d5710983f302d6b0f27020f9406fb24ef97df3)

### Steps To Reproduce
1. Create a Ledger Account
2. Send / receive on this account

### Errors
![grafik](https://user-images.githubusercontent.com/45494848/49304938-0dfe2580-f4ce-11e8-8913-4208cb63fbdc.png)

**Comment by rajivshah3** [comment]
Related: #560

**Comment by Hissi88** [comment]
I can reproduce it even on a virtual Windows 7 installation.

**Comment by Hissi88** [comment]
Can´t reproduce it anymore with Trinity >0.4.4. Seems to be fixed now.
I'm guessing it was somehow related to the "Error: Fetching account info". I´m not getting this error as well.

**Comment by Hissi88** [comment]
Sadly, I´ve to reopen this issue. It´s reproducable again and since 0.4.6. it has an "upgrade":

I added 4 Ledger Accounts (A, B, C, D) in alphabetical order. But as soon as one account gets an input, the order is mixed in addition. And as soon as the order is mixed, I get the issue describe above and the Ledger accounts get unusable until re-adding.

![ledger1](https://user-images.githubusercontent.com/45494848/50377210-79449e80-0619-11e9-8c59-b792e017dadd.JPG) ![ledger2](https://user-images.githubusercontent.com/45494848/50377211-7ea1e900-0619-11e9-989a-15693550f65e.JPG)

**Comment by Hissi88** [comment]
I´ve found it! It´s the "[ ]" in the accounts name for all issues above ;)
"( )" is no problem. @rajivshah3 

Btw. I did a Debug session myself and recorded some errors, but those are **not** related to the issue above. But maybe useful anyway:
![error1](https://user-images.githubusercontent.com/45494848/50387433-7c648b00-06fc-11e9-8c71-8aebf5a4e7da.JPG) 
![error2](https://user-images.githubusercontent.com/45494848/50387434-7ff81200-06fc-11e9-8917-96d6565cfab2.JPG)

**Comment by rajivshah3** [comment]
Thanks @Hissi88 ! Did these account names cause any problems in previous versions?

**Comment by Hissi88** [comment]
Yes, I have this issue since I´ve started to test with my Ledger (0.4.2) and I´ve always used the [ ] in the account name. (Except the moment when I closed this issue for a short time ;) )
That the order was mixed weirdly, is new since 0.4.6. But no [ ], then everything seems fine.

Btw. this issue is reproducable on Win 10 also and seems to affect Ledger accounts only.
