### ISSUE TITLE
Can't connect to any node

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#676]
### Bug description
Can't connect to any nodes

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Samsung
- Model: GalaxyS8+
- OS version: Android 8.0.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.5.1 (Mobile) (from android app settings, locked out of app)

### Steps To Reproduce
1. ???
2. Enter password to log in
3. Be unable to connect to any node and log in

### Expected behavior
After password is entered, node is connected to and wallet displays balance / home screen.

### Actual behavior
Node connection error after entering password.

### Errors
![photo_2018-11-30_15-01-03](https://user-images.githubusercontent.com/16965931/49309201-c9b05c80-f4b0-11e8-9f47-fdfe8624eb8f.jpg)

**Comment by rajivshah3** [comment]
Hi @SleepingFox88 , thanks for the report. I think this issue has been reported quite often by Android users. Could you give some details about your Internet connection (e.g. cellular or WiFi, on an enterprise network or VPN) so we can get to the root of this issue?

**Comment by sloganking** [comment]
Was using WiFi, no VPN. Will test other configurations and report back.

**Comment by cryptoninjarocks** [comment]
Same problem after update. App crashes.
Samsung Galaxy S7

**Comment by rajivshah3** [comment]
@cryptoninjarocks the app crash is likely a different issue

**Comment by cryptoninjarocks** [comment]
First issue: same message like sleepingFox88, after that the app crashes.

**Comment by rajivshah3** [comment]
Ah, I see. What’s your phone’s model number? I think Galaxy S9s begin with SM-G930 but there’s another letter at the end depending on your region

**Comment by cryptoninjarocks** [comment]
It is the Samsung Galaxy S7
SM-G930F
Android 8.0.0
Samsung Experience version
9.0
Android security patch level
1 October 2018

**Comment by cvarley100** [comment]
@SleepingFox88 @cryptoninjarocks Do you guys remember what you were doing in app before this happened?

**Comment by sloganking** [comment]
@cvarley100 No, it started happening right around the time I upgraded to "Trinity version: 0.5.1 (Mobile)". Not sure if that was the direct cause, it's been a while since the issue started.

I can reset the wallet and see if that fixes it.

Edit:

 I seem to be able to connect currently. Investigating now.

Edit2:

I seem to be able to connect to nodes now, and in any network configuration.

Bluetooth, Wifi, and VPN settings do not affect my ability to connect to nodes. No known updates happened to cause this change.

Edit3:

The issue is still likely a wallet bug and not a network one, as at the time of experiencing the issue, I was on the same network as another user with the same app version and device, and they were able to connect just fine to nodes that I could not connect to.

**Comment by cryptoninjarocks** [comment]
Yes, the problem occurred after the update 0.5.1

**Comment by cryptoninjarocks** [comment]
I don't know why, but the Trinity App 0.5.1 works again!

**Comment by rajivshah3** [comment]
@SleepingFox88 @cryptoninjarocks has this issue happened in the latest build? We upgraded a networking lib in v0.6.0 as part of the React Native upgrade.

**Comment by cryptoninjarocks** [comment]
Hello rajivshah3,
the Trinity App works without issues.

Thanks for the support!

best regards,
cryptoninja

**Comment by sloganking** [comment]
@rajivshah3 I have not experienced the issue since it resolved itself in v0.5.1

**Comment by rajivshah3** [comment]
Great! Thanks @cryptoninjarocks @SleepingFox88
