### ISSUE TITLE
Account name autofill from SeedVault file doesn't work cross-platform.

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#680]
### Bug description
- SeedVault exported from Desktop version doesn't autofilling account name on Trinity Mobile when you try to import
- SeedVault exported from Mobile version autofilling account name on Trinity Desktop as **Seed #1** (always)

### Expected behaviour
Account name should be imported from SeedVault always and cross-platform.

### Actual behaviour
Desktop -> Desktop - OK (autofills correctly)
Desktop -> Mobile - account name empty
Mobile -> Mobile - account name empty
Mobile -> Desktop - account name autofills with **"Seed #1"**

### Am I planning to do it myself with a PR?
No

![5bw3kap](https://user-images.githubusercontent.com/35224101/49315247-47925900-f4ed-11e8-8c70-a0c3ab76f723.png)

**Comment by rajivshah3** [comment]
I actually don't remember if we supported parsing the account name from the SeedVault file, so I think this would be an enhancement

**Comment by rihardsgravis** [comment]
Desktop supports parsing account name from SeedVault file ([see Seed.js#L194](https://github.com/iotaledger/trinity-wallet/blob/develop/src/desktop/src/ui/components/input/Seed.js#L194])) and save the correct account name ([see kdbx.js#L35](https://github.com/iotaledger/trinity-wallet/blob/develop/src/desktop/native/kdbx.js#L35))

**Comment by UmbahaSpodPaha** [comment]
Please have another look at this request devs! I'm sharing seedvaults between my PC/mobile often so It would be sick to finally have this one! :) Thanks
