### ISSUE TITLE
Notification about multiple incoming transactions when there are none

### ISSUE THREAD

**Issue by vun1** [iotaledger/trinity-wallet#684]
### Bug description
Was asked to report this issue by Rajiv on the Discord a few minutes ago.

Today at 16:40 and 17:24 UTC I received a notification about multiple incoming transaction to my 2 wallets via the Mac Trinity 0.4.3. There have actually been no incoming transactions to my wallets, therefore no notifications should have appeared. No iotas have been affected.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: MacbookPro 13" 2013
- OS version: Mojave 10.14.1

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.4.3

### Steps To Reproduce
1. Open my mac after a sleep state.
2. Trinity has been running in the background, passoword and 2FA protected, but logged in.

### Expected behaviour
Nothing

### Actual behaviour
2 notifications about incoming transactions at the time stamps mentioned above.

### Errors
None, this was a normal notification, no crashes or strange behaviour apart from the notifications that should not have appeared. No notifications showed on my iphone trinity 0.5.1 (28)

**Comment by georgmittendorfer** [comment]
Had the same issue yesterday. Linux desktop.

**Comment by rajivshah3** [comment]
I think I've seen the same issue from time to time but I've never explicitly tried to reproduce it. My guess (haven't really looked at the code yet) is that if you receive a transaction while Trinity isn't running, when it opens it will refresh the transaction history. It sees the new transaction and notifies you about it, even though it might be from multiple days ago.

**Comment by vun1** [comment]
Thanks. In my case I have not had any new incoming transactions for at least 30 days. I have had trinity open meanwhile for extended periods of time, why would it wait for 1 month to update the history?

**Comment by rajivshah3** [comment]
Were you logged in (no password prompts showing) at any time during those 30 days?

**Comment by vun1** [comment]
Yes, exactly. I have also transferred iota _from_ the wallets for which I have received "Multiple incoming Transactions" notifications (but not _to_ any of those wallets). Maybe upgrading to 0.4.3 affected the history in some way?

**Comment by rajivshah3** [comment]
> Maybe upgrading to 0.4.3 affected the history in some way?

That's possible. It seems like it's looking for changes in the wallet state (which occur when we sync the wallet with the Tangle and receive new transactions):

https://github.com/iotaledger/trinity-wallet/blob/e7b7142667c9accfab617e0aa47213573c72a47d/src/desktop/native/preload/Electron.js#L440-L475

The state migration that occurs when the wallet updates to a new version might trigger this notification, but I'm not entirely sure.

**Comment by vun1** [comment]
Thank you. This is the most likely reason. Let´s wait the official investigation results!

Regards.

**Comment by rajivshah3** [comment]
@rihardsgravis do you know what might be happening here? I can't tell if the root issue is coming from `Electron.notify` or `getAccountData` which seems to call `Electron.notify`

**Comment by rihardsgravis** [comment]
@vun1 @georgmittendorfer Can you confirm that you also did not receive any 0 value transactions (messages) to the accounts when the notifications appeared?

**Comment by georgmittendorfer** [comment]
I have never made or received any zero value transactions on these accounts.

**Comment by Hissi88** [comment]
I got this, after re-adding an already used account. The history and the balance was already there and correct, but I got a notification for old inputs.

**Comment by vun1** [comment]
I have not received any 0 value transactions in the last month before the notifications appeared.

**Comment by rajivshah3** [comment]
This is happening more often now that we've added quorum and IRI uses local snapshotting. A seed may be set up and show a limited number of transactions, but then Trinity could sync with a node that has transactions from a while ago. When these older transactions are synced, Trinity notifies the user even though these transactions may be several months old

**Comment by cyclux** [comment]
@rihardsgravis @rajivshah3 On Discord Charlie suggested to reopen this issue. I don't know if it is 100 % related though. In my case I get notified about old outgoing and confirmed transactions from the past, on every start of Trinity. It takes a while after Trinity starts, then the notifications pop off. This is a scary situation because you only expect to get notified once about outgoing TX, so if they pop off days, weeks or months later it looks like someone made a TX without knowing, while Trinity was shut down.
