### ISSUE TITLE
Ubuntu: Menu bar not visible when window is active / visible when window is not active

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#691]
### Bug description
When we have Trinity window active and on top = menu bar not visible
When we have Trinity window not active (focused on another window) = menu bar visible

![20181204_010247](https://user-images.githubusercontent.com/35224101/49410779-aa425980-f766-11e8-9e15-048b37b8b0ea.jpg)
![20181204_010302](https://user-images.githubusercontent.com/35224101/49410780-aa425980-f766-11e8-93fb-cba0ea1d9a11.jpg)

### Environment Specs
Linux Ubuntu 18.10

- Trinity version: 
0.4.3

### Expected behaviour
Menu always visible.

### Actual behaviour
What really happened.

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment]
This seems to be a bug in Electron. https://github.com/electron/electron/pull/15878 has been merged but hasn't been backported to a release. If it gets included in a release that we're able to upgrade to, this issue should be fixed.

**Comment by rajivshah3** [comment]
https://github.com/electron/electron/commit/7ba432113fcd8a8fecdc4ab57a7aed61846ad47b has been merged and will probably be released in the next `v3.0.x` version of Electron
