### ISSUE TITLE
Desktop: Context menu not translated (cut / copy / paste etc.)

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#695]
### Bug description
Context menu not translated (crowdin translations done to 100%)

![undoredocut english](https://user-images.githubusercontent.com/35224101/49482254-b1cd3580-f82e-11e8-8161-0ffca994242e.png)

### Environment Specs
Windows 7 x64 & Trinity 0.4.3

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment]
@rihardsgravis do we need to install https://github.com/sindresorhus/electron-context-menu or is this part of the Electron API?

**Comment by rihardsgravis** [comment]
> @rihardsgravis do we need to install https://github.com/sindresorhus/electron-context-menu or is this part of the Electron API?

The context menu is located at https://github.com/iotaledger/trinity-wallet/blob/2a750816b9fc6b09fc2dad316edb1ca2e7207684/src/desktop/main.js#L212

**Comment by rajivshah3** [comment]
Oh ok, I missed that. I'll make sure to localize those
