### ISSUE TITLE
Add address indexing/classification system in transaction history

### ISSUE THREAD

**Issue by Fierillo** [iotaledger/trinity-wallet#701]
I think that the history field of Trinity is a bit confusing, since only appears the ammount of iotas and if is a incoming or outcoming TX. I think that is possible assign a ID to the addresses that belong to a same seed.

**Comment by cvarley100** [comment]
@GP1992 Do you have a proposal for exactly how this might look?

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
