### ISSUE TITLE
Phone unresponsive 15-30 seconds after generating address

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#706]
### Bug description
- Generating addresses a few times can lead to being unable to press the native android home button or exit the app. I am able to flip though menus but phone is unresponsive for 15-30 seconds before registering and acting upon all the buttons I tried to press before.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Samsung
- Model: GalaxyS8+
- OS version: Android 8.0.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.5.1 (28), Mobile

### Steps To Reproduce
1. go to receiving address tab,
2. generate new address
3. re-generate same address
4. find phone becomes unresponsive and user cannot leave the application. 
5. wait 30 seconds and phone will have pressed all the buttons you previously requested.

### Expected behavior
- There should be no 30 seconds of unresponsiveness from the device.

### Actual behavior
- Device is unresponsive to user requests for 30 seconds

**Comment by rajivshah3** [comment]
Thanks for the report @SleepingFox88 . When the phone is unresponsive, is the letter scrambling during address generation still continuing?

**Comment by sloganking** [comment]
> Thanks for the report @SleepingFox88 . When the phone is unresponsive, is the letter scrambling during address generation still continuing?

@rajivshah3 No it has stopped before I try and exit the app.

The time the device is unresponsive wildly varies, almost like Trinity is doing PoW with 100% CPU usage or something similar.

**Comment by sloganking** [comment]
Upon further testing. This issue might be specific to my [third party gestures app.](https://i.imgur.com/9rFmiOe.png)

I cannot currently reproduce it if I turn gestures off and use the default GalaxyS8+ home buttons.

[Link to third party application in question](https://play.google.com/store/apps/details?id=com.xda.nobar)
