### ISSUE TITLE
Set TAG on transaction

### ISSUE THREAD

**Issue by mrbianchi** [iotaledger/trinity-wallet#713]
I was working in a project when I realized that the following example on this page:

https://docs.iota.org/trinity/information/qr#

cannot be applied with tag, the trinity wallet sets tag automatically to "TRINITY999999.."

neither you can set the tag from the wallet

**Comment by ouya99** [comment]
+1

**Comment by Isarstyle** [comment]
same issue here, when will this be fixed?

**Comment by cvarley100** [comment]
We are considering adding support for tags after full release.

**Comment by ouya99** [comment]
When is "full" release scheduled?

**Comment by cvarley100** [comment]
Getting to full release is our main priority at the moment.

**Comment by armstrys** [comment]
Having on tangle tags would be a step above many wallets!

**Comment by cvarley100** [comment]
@ouya99 @mrbianchi @Isarstyle @ryscar13 We're interested to hear what your motivation is for adding this feature. From our POV, enforcing the TRINITY tag is very useful for transaction analysis.

**Comment by ouya99** [comment]
TAG would be useful to transmit information alongside the iota transfer

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
