### ISSUE TITLE
Only a black screen when there is no internet connectivity

### ISSUE THREAD

**Issue by probonopd** [iotaledger/trinity-wallet#717]
Only a black screen when there is no internet connectivity?

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/efa393a0757e0bdd8f4e300399712f18e76be385/database/Trinity_Desktop/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/993

**Comment by rajivshah3** [comment]
Hi @probonopd , please fill out the issue template. It gives helpful system information that is necessary  for us to be able to reproduce the issue

**Comment by probonopd** [comment]
### Bug description
Black screen

### Environment Specs
Travis CI server

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: `trinity-desktop-0.4.3.AppImage`

### Steps To Reproduce
1. Download the AppImage
2. Disconnect from the internet
3. Launch the AppImage

Detailed log file at https://travis-ci.org/AppImage/appimage.github.io/builds/465483992

### Expected behaviour
A splash screen should show up or at least an error message saying internet connectivity is needed.

### Actual behaviour
See screenshot.

### Errors
See screenshot.

**Comment by rajivshah3** [comment]
@probonopd the build logs seem fine. What is the environment you're trying to run the app on? And does it work when you're connected to the internet?

**Comment by rajivshah3** [comment]
@probonopd are you still experiencing this issue?

**Comment by probonopd** [comment]
Actually it seems to be a dark blue screen. When trying this on a local machine, an animation appears. Probably the screenshot is taken as soon as the window appears, at which point the animation is not drawn yet.
