### ISSUE TITLE
Trinity Desktop is already a thing.

### ISSUE THREAD

**Issue by simoniz0r** [iotaledger/trinity-wallet#721]
https://google.com/search?q=trinity%20desktop

**Comment by rajivshah3** [comment]
@simoniz0r these are two very different things. One is an OS, the other is a cryptocurrency wallet

**Comment by simoniz0r** [comment]
Sharing namespaces is not cool.  Also, I doubt anyone will find your application when searching for it.  Trinity Desktop Environment already has google searches dominated... your app will most likely not show at all.

**Comment by rajivshah3** [comment]
That's not a bug. Please don't use GitHub to report issues of that nature.

**Comment by probonopd** [comment]
The issue is that there is already another project with the name "Trinity Desktop". Please use another name.

https://github.com/iotaledger/trinity-wallet/blob/7b52dfc9f87f27aa03f881d7599a120331e33bab/src/desktop/package.json#L2

**Comment by cvarley100** [comment]
The project is called Trinity, of which there is a desktop version. I think there is sufficient differentiation both in name and project area.
