### ISSUE TITLE
Change install directory during the installation process (or better: make Trinity portable)

### ISSUE THREAD

**Issue by Moongazer** [iotaledger/trinity-wallet#722]
On a laptop I want to protect my data as good as possible, using a protection method of MY choice. That is why I have all files and sensitive programs (like home banking applications as well as crypto wallets) on a crypted volume, which I mount manual if needed after the OS has started.

Most of Electrum wallets for example having a portable version, which is super nice and easy to put on the save/secret volume. For Trinity I had to change all the Registry values in Windows pointing to a new folder on that volume. Yes, that works but it sucks to do this manually.

**PLEASE** give an option ("Expert options" or whatever) like ANY other installation routine does, so a user can choose its install directory during installation. Or to leave even less traces in the system, make Trinity portable! I really hate it in Windows if programs just install themself on C:\ without asking! Maybe most users don't care, but I will command my computer where he should put things. Please understand that, thanks :-)

**Comment by rajivshah3** [comment]
It looks like we can do this with `app.setPath()` as shown in the [Electron docs](https://electronjs.org/docs/api/app#appsetpathname-path). It doesn't say whether we'll have to move the data from there to the new location ourselves or if `setPath` will do that for us though 🤔

**Comment by cvarley100** [comment]
Strangely, you have to choose between removing files on uninstall and choosing installation folder with Electron. We think the former is more useful to our users. Will reopen if Electron submit an update.
