### ISSUE TITLE
Paste clipboard to receiving address button on mobile

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#791]
### Description
Add a button near the receiving address text field that pastes what's in the device's clipboard to the receiving address text field.

### Motivation
This will decrease the time and amount of button presses it takes to paste addresses into the receiving address text field.

### Requirements
- Add a button [next to the camera button](https://i.imgur.com/T67Pbyi.png) that when pressed, pastes the device's clipboard into the receiving address text field.

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
