### ISSUE TITLE
blank screen after sending pow sending tx 

### ISSUE THREAD

**Issue by wonkytonky** [iotaledger/trinity-wallet#798]
### Bug description
empty screen after proof of work sending a iota transaction

### Environment Specs
What device are you running Trinity on?

- Manufacturer: 
- Model:  pc
- OS version win 10:

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 4.4

### Steps To Reproduce
1. send transactions 
2.blank screen

### Expected behaviour
not blank screen

### Actual behaviour
blank screen

### Errors

![image](https://user-images.githubusercontent.com/19390834/50032873-84cf0e80-fff6-11e8-8d23-fe2e04c78e2a.png)

**Comment by rajivshah3** [comment]
Actually, I can reproduce it as well. I think I know what the cause is

**Comment by wonkytonky** [comment]
just got it aswell into linux so it's os independant

**Comment by rajivshah3** [comment]
This issue has been linked to an error in Bugsnag
[**TypeError** in **/index.html**](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5c1428bc4b1700001a26d931?event_id=5c1430150032074609cd0000&i=gh&m=li)

**Comment by rajivshah3** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **/index.html**](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5c1428bc4b1700001a26d931?event_id=5c152ed500320ab3e3150000&i=gh&m=fx)
