### ISSUE TITLE
Continue button doesn't work when typing an existing seed

### ISSUE THREAD

**Issue by lluisin** [iotaledger/trinity-wallet#802]
### Bug description
The continue button doesn't work when adding an existing seed to Trinity after upgrading to v0.4.4

### Environment Specs
- OS version: Windows 10
- Trinity version: v0.4.4

### Steps To Reproduce
1. Upgrade Trinity to v0.4.4 from v0.4.3 in Windows 10
2. Import an existing seed by typing it or by drag&drop the seed from Notepad++
3. The "continue" button will not work

### Expected behaviour
Existing seed should import into Trinity

### Actual behaviour
Cannot get past the import seed window

**Comment by Hissi88** [comment]
Same issue when importing a SeedVault. 
The SeedVault can be imported, but then the CONTINUE button doesnt work in the view "Enter your seed".

Windows 7

**Comment by rajivshah3** [comment]
Can't reproduce on macOS Mojave 10.14.2 Beta. This might be platform-specific

**Comment by rajivshah3** [comment]
Are you adding an additional seed or is this the first account?

**Comment by Hissi88** [comment]
Only when adding an additional seed. The first import with a fresh installation works.

**Comment by rajivshah3** [comment]
I can't reproduce it that way either, but I think I know where the issue is coming from now

**Comment by rajivshah3** [comment]
This issue has been linked to an error in Bugsnag
[**TypeError** in **/index.html**](https://app.bugsnag.com/iota-foundation/trinity-desktop/errors/5c143719b4501c0019844f22?event_id=5c154115003207d9245a0000&i=gh&m=li)

**Comment by Thoralf-M** [comment]
I have the same problem now with v.1.2.1 on win 10.
I can create the first account without a problem, but if I want to add a second seed the "Continue" button does nothing, nothing in the error log
Reset in Trinity and reinstall didn't fix it
