### ISSUE TITLE
can't send iotas with enough balance

### ISSUE THREAD

**Issue by gnodaij** [iotaledger/trinity-wallet#811]
can't send iotas with enough balance

0.4.4
macos 10.13

**Comment by rajivshah3** [comment]
@gnodaij are you seeing a blue screen after trying to send?

**Comment by gnodaij** [comment]
yes only after sending, say 0 value

**Comment by gnodaij** [comment]
my question is it won't let me send the balance i have and remind of not enough balance

**Comment by rajivshah3** [comment]
Can you post a screenshot of the error?

**Comment by gnodaij** [comment]
![2018-12-16 12 28 42](https://user-images.githubusercontent.com/44387307/50050148-391f8080-012e-11e9-9090-f08cc3f6b7f8.png)

**Comment by rajivshah3** [comment]
Can you also post a screenshot of your addresses? You can view them by going to Settings > [account name] > View addresses

**Comment by gnodaij** [comment]
![2018-12-16 12 32 34](https://user-images.githubusercontent.com/44387307/50050168-af23e780-012e-11e9-9eb4-4e0fa2d88018.png)

**Comment by rajivshah3** [comment]
Sorry, last question 😄 could you post the address that begins with GEV?

**Comment by gnodaij** [comment]
GEVCWBDQW9UTEEAJYBGYSZMYAYMQNFMOOVOATMNFSNVIMIICOMDZBIELZJFEZYKFGARLZMF9RUNEZYYYXIZNQAPXID

**Comment by rajivshah3** [comment]
Hmm, that's really odd. Which node are you connected to?

**Comment by gnodaij** [comment]
![2018-12-16 12 36 27](https://user-images.githubusercontent.com/44387307/50050196-3f622c80-012f-11e9-8110-90460efba9ee.png)

**Comment by rajivshah3** [comment]
@gnodaij it looks like there's an outgoing transaction from that address now. Were you able to send the transaction this time?

**Comment by gnodaij** [comment]
it is even more strange, i am actually trying to send from another wallet, but it happened to be sending from the previous one

**Comment by gnodaij** [comment]
now with the current wallet, there is no "max" button anymore, means trinity thinks there is 0 balance from my wallet, which is not the case

**Comment by laumair** [comment]
> i am actually trying to send from another wallet, but it happened to be sending from the previous one

@gnodaij Can you please elaborate? Which other wallet are you using?

**Comment by gnodaij** [comment]
oki, somehow i can't recall how, i was able to send....

now with more balance i can't even send 1 iota out and there is no "max" button either which means trinity thinks i have a 0 balance?
![2018-12-16 1 27 05](https://user-images.githubusercontent.com/44387307/50050457-6112e200-0136-11e9-87fc-5b62854db488.png)
![2018-12-16 1 27 19](https://user-images.githubusercontent.com/44387307/50050458-62dca580-0136-11e9-8cfd-9bba6cf762d6.png)

**Comment by gnodaij** [comment]
here is where it messed up:

i have two wallets, "0" with a balance 102m, "m" with 0 balance.

i created a receiving address from "m"(but actually it is generated from "0"), and i am able to send out  balances of "0" from "m"(0 balance). the result is i am actually sending and receiving both from "0". but i can only do this from "m". i can do nothing from "0".

so weird...
![2018-12-16 3 22 11](https://user-images.githubusercontent.com/44387307/50051152-33369900-0148-11e9-9155-d0acae2f7a93.png)
![2018-12-16 3 22 44](https://user-images.githubusercontent.com/44387307/50051153-3598f300-0148-11e9-8018-1612e324f732.png)

**Comment by laumair** [comment]
@gnodaij  Thank you for providing the information. This seems like a bug to me. I will investigate.

**Comment by laumair** [comment]
@gnodaij What was the sequence in which you added accounts? Did you add account `0` first? Also, did you rename any account?

**Comment by gnodaij** [comment]
i did more experiments and i believe it has something to do with the seeds and ledger nano s

wallet "0" 's seed is in the ledger nano and wallet "m" 's seed is in the trinity.  "0" is added later through ledger nano s.

when i try to send, it seems i can only send "0"'s balance through "M" and vise versa.
![2018-12-17 11 03 01](https://user-images.githubusercontent.com/44387307/50095634-ebe7ff80-0250-11e9-876c-e24173da8452.png)
![2018-12-17 11 03 12](https://user-images.githubusercontent.com/44387307/50095642-edb1c300-0250-11e9-9ae0-ef49928aec16.png)

**Comment by laumair** [comment]
@gnodaij I can see that the order of accounts is wrong if you added the `0` account after. Did you add the `0` account after updating to v0.4.4 or before?

**Comment by gnodaij** [comment]
added it before 0.4.4, no problem

deleted "0" and added in 0.4.4 and 0.4.5, both went wrong

**Comment by laumair** [comment]
@gnodaij Thank you for reporting this bug. https://github.com/iotaledger/trinity-wallet/pull/824 should fix it. 

Till the next desktop release, I would suggest that you name your accounts with non-numeric characters to avoid this issue.

**Comment by gnodaij** [comment]
you can't prevent people from using numbers to name their wallets, so this should not be an issue.

**Comment by cvarley100** [comment]
Yeah @gnodaij, it’s a bug that has since been fixed. When the next version is released it will be resolved.
