### ISSUE TITLE
Development and production wallet accounts on one machine don't work on Windows 7

### ISSUE THREAD

**Issue by Hissi88** [iotaledger/trinity-wallet#816]
### Bug description
When adding a SeedVault as an additonal account, the Continue button doesnt work after choosing the vault.
Still not fixed in 0.4.5

![grafik](https://user-images.githubusercontent.com/45494848/50054996-13ec3b80-0149-11e9-9c32-68bfce188d6b.png)

### Environment Specs
What device are you running Trinity on?

- Windows 7

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.4.5.

### Steps To Reproduce
1. Import SeedVault as addional account
2.
3.

### Expected behaviour
Account should be added.

### Actual behaviour
Nothing.

### Errors
No error. No Log.

**Comment by rajivshah3** [comment]
@Hissi88 did you make the SeedVault inside Trinity Desktop?

**Comment by Hissi88** [comment]
Yes, The Continue Button when importing Seed Vaults worked until 0.4.4.

**Comment by Hissi88** [comment]
Same issue on my virtual Windows 7. But it´s working on Windows 10.
No problems at all with this until Trinity 0.4.4. Now I cant even create new SeedVaults in 0.4.5.

On Windows 7 the importing works, when it is the first account. Not working for additonal accounts though.

**Comment by Hissi88** [comment]
Still existing on 0.4.6.

**Comment by Hissi88** [comment]
I removed all entries in the Windows credential-manager and did a reinstall, finally it is working then again.
Maybe there was a corrupt entry. I even had dev-keys in it, because I tried to compile Trinity myself a few weeks ago...
Could then also fit, that @rajivshah3 got reports with 'Wrong password'.

What's odd, though, is that on a fresh install the import of the first vault worked, but all the additional ones didn't. 

I think that issue can be closed than. Thanks to all.

**Comment by rajivshah3** [comment]
I think @rihardsgravis was able to reproduce this on Windows 7, so there might actually be a bug.

**Comment by Hissi88** [comment]
I could succesfully reproduce and solve it again:
As soons as I have (dev) entries addionally to the normal Trinity entries in the Windows credential-manager, the Continue button doesnt work.
When I remove them, it´s working again instantly.

![grafik](https://user-images.githubusercontent.com/45494848/50387568-b84d1f80-06ff-11e9-9b1f-7f1c020c9f56.png)
![grafik](https://user-images.githubusercontent.com/45494848/50387573-f6e2da00-06ff-11e9-9484-9a5b2b277e6d.png)

**Comment by rajivshah3** [comment]
Interesting. Thanks for the extra information!

**Comment by cvarley100** [comment]
This should be fixed now.
