### ISSUE TITLE
GPU PoW

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#818]
### Description
Trinity Desktop should support using the GPU for Proof-of-Work.

### Motivation
Some users would like to use their GPUs for PoW, since GPUs tend to be faster than CPUs when performing calculations such as those involved in PoW.

### Requirements

- Create PoW implementation using OpenCL, WebGL, CUDA, etc
- Allow the user to switch the local PoW implementation between [Entangled](https://github.com/iotaledger/entangled) (default) and the GPU implementation

### Open Questions (optional)
Is there a way to do this that would provide wide cross-platform support?

### Am I planning to do it myself with a PR?
Probably not.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
