### ISSUE TITLE
Failed bundle removed from wallet state after manual sync

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#819]
### Bug description
Reported on behalf of NetWalker - TangleSheep#1169 on Discord

If the remote PoW for a transaction fails, Trinity stores the bundle and tries to resend it in order to prevent the user from attempting to re-sign the transaction. It also marks the input addresses as spent. If the user does a manual sync, the bundle will disappear from the history (possibly related to #486). However, the addresses are still marked as spent, and the balance available for sending is less than the total balance of the addresses.

### Environment Specs
What device are you running Trinity on?

- OS version: Windows 10 Professional, version 1803 (build 17134.471)

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v0.4.5

### Steps To Reproduce
1. Choose https://nodes.thetangle.org:443 as the node and select remote PoW
2. Send a large bundle (in this case 420 inputs, totaling to 841 transactions)
3. The PoW will fail because of rate-limiting from thetangle.org
4. Perform a manual sync of the wallet

### Expected behaviour
The wallet should continue attempting to send the bundle, even after the manual sync

### Actual behaviour
The bundle was removed from the wallet state but addresses were remained marked as spent, so the funds are locked

### Errors
None available

**Comment by laumair** [comment]
Related issue https://github.com/iotaledger/trinity-wallet/issues/486

This should be fixed in https://github.com/iotaledger/trinity-wallet/pull/375
