### ISSUE TITLE
Drag and drop doesn't work

### ISSUE THREAD

**Issue by 7h7** [iotaledger/trinity-wallet#820]
### Bug description
Drag and drop doesn't work
### Environment Specs
- OS version: Windows 10
- Trinity version: v0.4.5

### Steps To Reproduce
1. Add new account with existing seed
2. Mark 81 Trytes and try to drop them in Trinity

### Expected behaviour
The seed should be in the field

### Actual behaviour
Nothing happens, or if you drop it at the header the screen will stop at the "Drop SeedVault or text here" window: https://imgur.com/a/tmrFWHe but you can still use the cross at the top right to get back to the main screen

### Errors
No errors

**Comment by 7h7** [comment]
Works now with Trinity version: v0.4.6

**Comment by laumair** [comment]
@7h7 Thanks. Please feel free to reopen if you face this issue again.
