### ISSUE TITLE
Missing application icon

### ISSUE THREAD

**Issue by lukisi** [iotaledger/trinity-wallet#821]
### Bug description
The IOTA/Trinity icon is not shown for the app in the dash (of Gnome Shell)

### Environment Specs
Laptop
- Manufacturer: Dell
- Model: XPS
- OS version: Ubuntu 18.04

Trinity
- Trinity version: 0.4.5

### Steps To Reproduce
1. Open the dash, search for trinity

### Expected behaviour
The app with the correct icon should be in the results.

### Actual behaviour
The app appears with the default executable icon.

### Am I planning to do it myself with a PR?
No.

**Comment by rajivshah3** [comment]
Can you post a screenshot of what icon is shown instead of the Trinity icon?

**Comment by lukisi** [comment]
![trinity-shot](https://user-images.githubusercontent.com/17383110/50145523-14541600-02b2-11e9-98ba-51dbaf331c9f.jpg)

**Comment by rajivshah3** [comment]
@lukisi is the default icon showing in the dock as well when Trinity is running? Or does the IOTA logo appear there?

**Comment by lukisi** [comment]
When Trinity is running the default icon is showing in the dock as well.

**Comment by rajivshah3** [comment]
@rihardsgravis would this be fixed by adding the icon path to the `icon` field as shown in the [electron-builder docs](https://www.electron.build/configuration/linux)? It says it converts the macOS icon by default but I guess that's not occurring for some reason. I don't have an Ubuntu VM so I can't really test this

**Comment by KeithSSmith** [comment]
I was having this same issue where the Trinity Icon would not show up when searching through applications or in the dock (broken link).  I was able to fix these by doing the following:

Fix Default Icon while searching apps (Download trinity.png from GitHub icons):
Edit: `/home/[user]/.local/share/applications/appimagekit-trinity-desktop.desktop`
Add: `Icon=/opt/trinity/trinity.png`

Fix Broken Link in Doc while running:
Edit: `/home/[user]/.local/share/applications/appimagekit-trinity-desktop.desktop`
Add: `StartupWMClass=Trinity`

**Comment by rajivshah3** [comment]
Thanks for that info @KeithSSmith . Without those edits, does appimagekit-trinity-desktop.desktop look like [this](
https://github.com/AppImage/appimage.github.io/blob/efa393a0757e0bdd8f4e300399712f18e76be385/database/Trinity_Desktop/trinity-desktop.desktop)? If so,  it seems like an icon isn’t being included when the app is packaged

**Comment by KeithSSmith** [comment]
Just did a fresh install of Ubuntu 18.04.1 with updates and upgrades, the icons in search and in dock are still showing the default icon.  The appimagekit-trinity-desktop.desktop file looks like this (doesn't match the link you posted):

> [Desktop Entry]
> Name=Trinity
> Comment=Desktop wallet for IOTA
> Exec="/home/iota/Desktop/trinity-desktop-0.4.6.AppImage" %U
> Terminal=false
> Type=Application
> Icon=appimagekit-trinity-desktop
> StartupWMClass=Trinity
> X-AppImage-Version=0.4.6
> Categories=Office;Finance;
> MimeType=x-scheme-handler/iota;
> X-AppImage-BuildId=1EfAck1It2wrL3IZU6EUxZi1iru
> X-Desktop-File-Install-Version=0.23
> X-AppImage-Comment=Generated by /tmp/.mount_trinitRBi1DO/AppRun
> TryExec=/home/iota/Desktop/trinity-desktop-0.4.6.AppImage

**Comment by rajivshah3** [comment]
Thanks @KeithSSmith 

> Icon=appimagekit-trinity-desktop

Looks like this needs to be set during packaging. I think specifying it in the `electron-builder` config should fix it

**Comment by vincenzopalazzo** [comment]
@rajivshah3 Hello, I noticed the equal problem in gitkraken, the icon not viasualizzed in the docky, could it be an Electron problem?

**Comment by lukisi** [comment]
Trinity 0.5.0 still has same problem. I tried both an update (via the menu in app) and a fresh install on another computer.

**Comment by vincenzopalazzo** [comment]
@lukisi I have same problem but I resolved with this code

- Edit: `/home/[user]/.local/share/applications/appimagekit-trinity-desktop.desktop`

In the file edit a path for the image, I have downloaded the image for project github
