### ISSUE TITLE
Support for cookies

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/trinity-wallet#823]
### Description
Have Trinity return cookies. For example a load balancer might set a session cookie to ensure succeeding calls from Trinity always end up at the same IRI backend.

### Motivation
This feature can be helpful in case of running IRI behind a proxy/load balancer.
The load balancer will ensure session persistence of a client to a specific IRI backend node on subsequent calls. 

Example of how HAProxy sets up the session cookie (SERVERID):
https://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/#session-cookie-setup-by-the-load-balancer

Allowing cookies to be set can probably also help nginx as it has a module to set sessions cookies for upsteam server persistence. 

### Requirements
Allow cookie to be set

### Am I planning to do it myself with a PR?
No. I am afraid I lack the skills.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2. Feel free to open a PR.
