### ISSUE TITLE
Blank Screen After Computer Sleeps

### ISSUE THREAD

**Issue by yippykaiyay012** [iotaledger/trinity-wallet#830]
### Bug description
If the Trinity Wallet is open and the computer sleeps, upon waking the wallet is stuck on a blank screen and unable to recover.
The wallet must be closed from the task bar.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: HP
- Model: Touchsmart 15
- OS version: Windows 10

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version:  v0.4.5 Beta

### Steps To Reproduce
1. Open Trinity
2. Allow computer to enter sleep mode.
3. Wake computer again.

### Expected behaviour
Trinity should recover to the Lock Screen.

### Actual behaviour
Trinity is stuck on a blank screen with nothing to click on.

### Errors
Nothing useful in Error Log.

![image](https://user-images.githubusercontent.com/29374043/50239368-e3f79f00-03b9-11e9-9ec9-f5791c5fc6db.png)

**Comment by rihardsgravis** [comment]
Possibly `node-usb` dependency related issue https://github.com/tessel/node-usb/issues/220

**Comment by Thoralf-M** [comment]
Same issue with v0.5.0 and win 10, but the screen is just white

**Comment by cvarley100** [comment]
@Thoralf-M @yippykaiyay012 Still an issue in 1.0.0? Closing for now, will reopen if it persists.
