### ISSUE TITLE
Shroud not fully cover up transaction history.

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#831]
### Bug description
The blue shroud you're using to cover up the transaction history only covers up most of it but leaves the top transaction partially non covered.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Samsung 
- Model: Galaxy S8+
- OS version: Android 8.0.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: Mobile Trinity v0.6.0(31)

### Steps To Reproduce
1. Have a phone with aspect ratio significantly wider than 16:9
2. Hide your home button
3. Open a transaction from the Trinity Wallet History tab.

### Expected behavior
Part of the transaction history should not be displayed above the "You received" message

### Actual behavior
Parts of transactions are displayed when they are not suppose to be.

### Errors
https://i.imgur.com/tYudopp.png

**Comment by rajivshah3** [comment]
@cvarley100 is this an issue with the lib we're using? If so I can open an issue at that repo

**Comment by cvarley100** [comment]
Fixed in https://github.com/iotaledger/trinity-wallet/pull/916. @SleepingFox88 please reopen if the issue persists following next alpha release.
