### ISSUE TITLE
Missing French translations

### ISSUE THREAD

**Issue by viossat** [iotaledger/trinity-wallet#833]
### Bug description

Missing French translations (and in most others languages)

### Environment Specs

Trinity version: 0.5.1

### Missing translations

- `global.experimentalNodeExplanation`
- `global.youReceived`
- `global.youSent`
- `global.androidCopyPasteWarning`
- `global.confirm`
- `global.delete`
- `global.missingPermissionExplanation`
- `unitInfoModal.unitInfoExplanation`
- `unitInfoModal.unitSystem`
- `send.swipeToSend`
- `snapshotTransition.attachProgress`
- `progressSteps.transferComplete`
- `seedVault.retypeKey`
- `seedVault.seedVaultKeyExplanation`
- `paperWallet.print`
- `paperWallet.pleaseCheck`
- `paperWallet.wifiConfirmation`
- `paperWallet.printerConfirmation`
- `setPassword.anEncryptedCopy`
- `seedReentry.trinityWillNeverAskToReenter`
- `seedReentry.clipboardWarning`
- `seedReentry.clipboardWarningExplanation`
- `logoutConfirmationModal.aboutToLogOut`
- `login.whyBiometricDisabledExplanationPart1`
- `login.whyBiometricDisabledExplanationPart2`
- `transferConfirmation.fromAccount`
- `transferConfirmation.toAddress`
- `transferConfirmation.sendingAMessage`
- `transferConfirmation.sendingAnEmptyMessage`
- `history.pleaseWait`
- `saveYourSeed.whatIsAChecksum`
- `settings.account`
- `saveSeedConfirmation.iHaveBackedUp`
- `saveSeedConfirmation.reenterSeed`

**Comment by rajivshah3** [comment]
These strings are left in English because they're untranslated. Unfortunately, we cannot do anything about that
