### ISSUE TITLE
Text above circle while a tx gets promoted in Trinity Mobile

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#847]
### Bug description
The text that indicated that the transaction gets promoted is above the circle. For example in the German language this string is long enough to reach the position of the circle.

Trinity mobile 0.6.0 (36) to (39)
iPhone 8 
iOS 11.3.1

### Expected behaviour
Circle should be behind the text.

### Actual behaviour
Longer text overlaps the circle.
![img_3384](https://user-images.githubusercontent.com/21984138/50386529-c8a5d000-06e8-11e9-979c-63534329f02c.PNG)

**Comment by rajivshah3** [comment]
This might be related to the `position: 'absolute'` attribute used here:
https://github.com/iotaledger/trinity-wallet/blob/514baa937844bd1e5a42c5d84c2694f3d4576591/src/mobile/src/ui/components/TransactionRow.js#L137
