### ISSUE TITLE
'Write down your seed' section bugged on trinity mobile

### ISSUE THREAD

**Issue by f-ben** [iotaledger/trinity-wallet#848]
### Bug description
If you create a new seed and choose to write down your seed the lines of the characters can get mixed up. **This happens 1 out of 5 times on my device so its not persistent.**

### Environment Specs
- Manufacturer: OnePlus
- Model: 3T
- OS version: 8.0.0
- Trinity version: Trinity Mobile v 0.6.0 (35)

### Steps To Reproduce
1. Create a new Seed
2. Choose 'write down your seed'
3. Instead of scrolling through the list of characters simply tap a single line.

### Expected behaviour
I think tapping the lines shouldn´t do anything. And the list should f.e. look like the following:
1. G T A R D R B U L
2. L Y R O C K S T A
3. R G A M E S 9 9 9

### Actual behaviour
Sometimes the lines and characters get mixed and look f.e. like this:
1. G T A R D R B U L
1. L Y R O C K S T A
2. L Y R O C K S T A
2. L Y R O C K S T A
2. L Y R O C K S T A
1. G T A R D R B U L

### Errors
![trinity](https://user-images.githubusercontent.com/2088471/50386775-71eec500-06ed-11e9-9493-7a56e10f0561.jpeg)

**Comment by laumair** [comment]
@f-ben Thank you for reporting. I'll investigate.
