### ISSUE TITLE
Trinity Mobile freeze after fresh install (or after deleting app data)

### ISSUE THREAD

**Issue by UmbahaSpodPaha** [iotaledger/trinity-wallet#851]
### Bug description
Trinity hangs/freezes on splash screen after first open of the Trinity app (fresh install)
_I would consider this one as an important thing to fix._

### Environment Specs
Tested and reproduced on:
- Samsung Galaxy S8  (Android 8.0)
- Samsung Galaxy S9+ (Android 8.0)
- Honor Play (Android 8.1.0)

### Trinity version: 
Reproduced both on **0.5.1** and **0.6.0 (alpha)**

### Steps To Reproduce
1. Uninstall and Install Trinity Mobile (or delete data app of existing install)
2. Open Trinity (the Trinity logo will show up and app will hang on this screen forever)

**(after full app close and restart, everything is working again as supposed to)**

### Expected behaviour
Fresh install of Trinity Mobileshould work perfectly from the first try!

### Actual behaviour
Trinity hangs/freezes on splash screen after first open of the Trinity app (fresh install).

**Comment by rajivshah3** [comment]
Hi @UmbahaSpodPaha ,

> Samsung Galaxy S8 (Android 8.0)
Samsung Galaxy S9+ (Android 8.0)

What are the full model numbers (e.g. SM-XXXX) of these devices? I'll try to see if I can find related events in our crash reporting system.

**Comment by UmbahaSpodPaha** [comment]
G950F and G965F/DS but there was no actual crash ever. It just freezes and doing nothing until full restart of the app.

**Comment by laumair** [comment]
@UmbahaSpodPaha Thank you for reporting this issue. https://github.com/iotaledger/trinity-wallet/pull/854 & https://github.com/iotaledger/trinity-wallet/pull/855 should fix it.
