### ISSUE TITLE
Transactions sent to self do not appear as both sent and received transactions

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/trinity-wallet#852]
### Bug description
When sending a transaction to yourself, the transaction should appear as both "Sent" and "Received" as it does in Trinity Mobile:
![image](https://user-images.githubusercontent.com/19519564/50415473-215c9200-07e9-11e9-9769-fe201f6684e7.png)

Instead, it just shows as "Sent":
![image](https://user-images.githubusercontent.com/19519564/50415483-2faaae00-07e9-11e9-8e18-880b6bc0fd2a.png)

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Apple
- Model: MacBook Pro
- OS version: macOS Mojave 10.14.2 Beta

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v0.4.6

### Steps To Reproduce
1. Generate an address
2. Send a value transaction to that address from the same account it was generated from

### Expected behaviour
The appearance in the history should match Trinity Mobile.

### Actual behaviour
It only shows as "Sent"

### Am I planning to do it myself with a PR?
Yes.

**Comment by cvarley100** [comment]
@rajivshah3 I cannot repro this.

**Comment by rajivshah3** [comment]
Ah, looks like this was fixed. Will close
