### ISSUE TITLE
No error with invalid addresses

### ISSUE THREAD

**Issue by 7h7** [iotaledger/trinity-wallet#866]
### Bug description
No error if you want to send value to an invalid address (last trit is not 0)

### Environment Specs
- OS version: Win 10

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.4.6

### Steps To Reproduce
1. Try to send value to an address of which the last trit is not 0 (-1 or 1)

### Expected behaviour
An error should be returned stating that the address is invalid

### Actual behaviour
The bundle will be completed and an error is returned when sending to the node

### Errors
`Request error: Invalid trytes input`

**Comment by rajivshah3** [comment]
For context, IRI has a check to ensure that the last trit of the address is 0:
https://github.com/iotaledger/iri/blob/1ec6dcc007a0cd119d6a9c9878842515390ced9b/src/main/java/com/iota/iri/TransactionValidator.java#L179-L181

This check is not implemented in Trinity. As a result, a signed transaction that will not confirm is sent to a node. This should be checked before sending is initiated
