### ISSUE TITLE
Validating address on Ledger not working

### ISSUE THREAD

**Issue by calm86** [iotaledger/trinity-wallet#869]
I am trying to transfer funds to my trinity desktop wallet. I use a Ledger Nano S and when I press the "Receive" button the Trinity wallet asks to open the IOTA app on Ledger Nano S to validate the address. In the background under this message I can see a QR but when I open the IOTA app on the Ledger the screens disappears ( also the QR ) and no address is showing up on the Ledger nano to validate. 

So I am unable to validate an address, and therefore not able to transfer my funds. 

Any idea ?

**Comment by rajivshah3** [comment]
@calm86 what happens if you open the IOTA app on Ledger before trying to generate an address?

**Comment by calm86** [comment]
@rajivshah3 it is no help, still the same problem

**Comment by rihardsgravis** [comment]
Fixed in #1101
