### ISSUE TITLE
Pi/arm7 Support

### ISSUE THREAD

**Issue by Kris191** [iotaledger/trinity-wallet#870]
### Description
Support for Raspberry PI OS and Arm7 architecture.

### Motivation
Linux based system and the platform can provide a solid wallet PC

### Requirements
Ability to install on ARM linux version

### Open Questions (optional)
IS this possible? Current the AppImage file will not execute in the PI OS

### Am I planning to do it myself with a PR?
I do not have the skills to do this, mealy wondering if this is possible and something you would look to implement.

**Comment by rajivshah3** [comment]
I think we were waiting for https://github.com/AppImage/AppImageKit/pull/699 to be merged (but now it's merged 🎉). I'll look into what we need to do to support ARM builds

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet. Closing and labelling as V2.
