### ISSUE TITLE
Will not import the address that is less than 81

### ISSUE THREAD

**Issue by keenan-codes** [iotaledger/trinity-wallet#871]
### Bug description
Cannot import my wallet because it is too short. It says that it can import any address yet it will not import anything that is not exactly 81 characters.

### Environment Specs
- Manufacturer: APPLE
- Model: MacBook Pro 2016
- OS version: 10.13.6
- Trinity version: 0.4.6

### Expected behaviour
import the address into the wallet.

### Actual behaviour
denies import because address is too short

**Comment by rajivshah3** [comment]
I’m not sure what you mean by “import the address”. Do you mean the seed?

**Comment by keenan-codes** [comment]
yes.

**Comment by rajivshah3** [comment]
You can add `9`s until your seed becomes 81 characters. So if your seed is 79 characters, add `99` to the end of it to make it 81 characters. If your seed is significantly less than 81 characters, you should probably move to a new one.
