### ISSUE TITLE
Allow blacklisting of nodes to the quorum-able nodes list.

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#891]
### Description
Allow users to blacklist select nodes from the list of quorum-able nodes provided by the developers.

### Motivation
- This will let users tell their wallets to not use nodes that the user specifically does not trust.

### Requirements
- UI options will be created that will allow users to mark nodes in the existing list of nodes, as non trusted. This will cause Trinity to not use these nodes in quorums.

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
Closing to be tracked in #1799
