### ISSUE TITLE
Allow manual adding of nodes to quorum-able nodes list.

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#892]
### Description
Allow users to manually add nodes to the quorum-able nodes list.

### Motivation
- Will allow users to include their own nodes if now already in the list and they desire to do so.
- Will allow users to increase the total quorum-able nodes list size, which can increase security and network connection reliability.

### Requirements
- Add UI option in settings which takes in a specified node from the user.
- Add the given node to the quorum-able nodes list.

### Am I planning to do it myself with a PR?
No.

**Comment by laumair** [comment]
User's custom nodes would be part of the quorum nodes. Personally, I don't think there is a need to add a separate option for manually entering quorum nodes.

**Comment by rihardsgravis** [comment]
Added in #1509
