### ISSUE TITLE
Add option to manually shuffle the current selected quorum of nodes.

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#893]
### Description
A UI option will be added which will allow the user to shuffle the nodes currently selected by Trinity for quorum.

### Motivation
This will allow users to quickly change their quorum of nodes if they think the currently quorum-ed nodes are behaving strangely.

### Requirements
- Add UI that displays which nodes are currently selected for quorum
- Add shuffle button which will switch all currently quorum-ed nodes with a randomly selected node from the quorum-able nodes list.

### Am I planning to do it myself with a PR?
No.

**Comment by laumair** [comment]
> currently quorum-ed nodes are behaving strangely

Can you please elaborate on this? If a node becomes unresponsive or is not synced, it will automatically be removed from the list of quorum nodes.

**Comment by sloganking** [comment]
This feature's intention is to allow the user to get reults from new nodes if the user thinks currently quorumed nodes are behaving strangly. 

That could mean the user suspects the quorum results were incorrect.

Allowing the user to get a second opinion from different nodes may aleveate any doubts they have about the validity of the previous quorum results and make the user have greater trust in the Trinity wallet.

**Comment by rajivshah3** [comment]
@laumair are the nodes selected right before each request is made or are they selected upon login and persist for a certain amount of time? That might affect how we can do this

**Comment by cvarley100** [comment]
Closing to be tracked in #1799
