### ISSUE TITLE
Allow user to set number of nodes required in quorum.

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#894]
### Description
Allow the user to set the change the number of nodes required for quorum consensus to be greater than ~~3~~ the default amount.

### Motivation
This will allow users to require more security over speed, when it comes to confirming the state of their transactions on the IOTA network.

### Requirements
- UI option created allowing the setting of number of nodes required in each quorum
- Number of nodes inputted will be rejected unless it is ~~3~~ the default amount or higher.

### Am I planning to do it myself with a PR?
No.

**Comment by rajivshah3** [comment]
Is there any specific reason for 3? We currently have it set to 7:
https://github.com/iotaledger/trinity-wallet/blob/a1578acd0a4d404739ebbbd02e83a82983a698a9/src/shared/config.js#L52

**Comment by sloganking** [comment]
No spwcific reason to use three. My appologies I had assumed we currently default to three nodes for quorum. I will update the issue.

**Comment by rajivshah3** [comment]
No worries, I didn't know if 3 was on purpose. This is a good suggestion 👍

**Comment by rihardsgravis** [comment]
Added in #1509
