### ISSUE TITLE
Allow setting of a specific node that will always be a part of the quorum.

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#895]
### Description
Allow user to specify specific node(s) that will always be included in the wallet's quorum.

### Motivation
This will allow users to insure that nodes which they specifically trust (such as their own) will always be hosted in their wallet's quorum

### Requirements
- Add UI option to force specific node in wallet's quorum.
- The specified node will always be used in the wallet's quorum until  otherwise specified by the user.

### Am I planning to do it myself with a PR?
No.

**Comment by laumair** [comment]
@SleepingFox88 Thank you for this feature request. One important consideration is node(s) health. If the specified nodes aren't synced, this could affect the usability of the wallet. 

Perhaps, for such cases Trinity should fall back to default nodes.

**Comment by sloganking** [comment]
The Intention of this feature request is to allow users to always get results from a specified node. It would be annoying if users had to keep re-specifying this behavior to Trinity.

I propose quoruming other nodes if the specified node is not synced, and alerting the user that the specified node was not part of the quorum because it is out of sync. As opposed to removing it from the specified node list.

This would let users know they need to fix their node or stop requiring the node be part of quorum results. While not requiring the user to re-enter the node in Trinity if they decide they want to fix it.

**Comment by cvarley100** [comment]
Closing to be tracked in #1799
