### ISSUE TITLE
Re-preform getTransactionsToApprove if PoW taking too long.

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#901]
### Description
If the Proof of Work being done to send a transaction takes longer than a set period of time "say 30 seconds", Trinity will re-preform getTransactionsToApprove, and resume completing Proof of Work on top of fresh trunkTransactions and branchTransaction.

### Motivation
- It is often difficult for devices which complete PoW slower than the rest of devices on the network to broadcast a transaction at a small enough depth to be confirmed by the network. This change will ensure all transactions are placed at a high enough place on the tangle to have a high chance of being confirmed by the rest of the network, regardless of how long it took for an individual device to complete a Proof of Work cycle.
- This may increase the confirmation chance of all transactions broadcast this way and increase the health of the tangle overall, especially at high TPS.
- This may further decentralize the network by allowing devices to submit and confirm transactions, when they were previously (and currently) unable to due to processing speed restrictions.

### Requirements
- If Proof of work was started on a transaction, and is not complete within set time "say 30 seconds", Trinity will asynchronously preform getTransactionsToApprove, asking it's connected node for new trunkTransactions and branchTransactions.

- Upon receiving fresh trunkTransactions and branchTransactions from Trinity's connected node, Trinity will prepare it's desired transaction with it's new trunkTransactions and branchTransactions, stop preforming Proof of Work on the old prepared transaction, and start preforming Proof of Work on the newly prepared transaction.

- The Proof of Work timer will be reset, and this process repeated until Proof of Work is completed on a transaction, at which point it will be broadcast to the network.

### Open Questions (optional)
- This proposal would massively increase the confirmation rate of individual transactions made by devices with slow Proof of Work capabilities. We can thus, easily implement this on small message transactions. However, most value transactions reside in bundles, and bundles consist of multiple transactions layered on top of one another. The base transaction in that bundle determines the height of the rest of the bundle. This might make this proposal non implementable, unless a work around is found or adjustments to how IOTA creates bundles are made to accommodate this feature request.

### Additional notes
- Due to the pseudorandom nature of Proof of Work, changing the  trunkTransactions and branchTransactions inside of a transaction mid Proof of Work cycle, would not increase the overall time it takes the transaction's Proof of Work to be completed.

### Am I planning to do it myself with a PR?
No.

**Comment by laumair** [comment]
Related issue https://github.com/iotaledger/trinity-wallet/issues/205

**Comment by sloganking** [comment]
While #205 is a related issue, it attempts to solve the same problem in a different way. I suggest implementing the changes recommended here as well as #205

**Comment by sloganking** [comment]
This should optimally be done on all transactions. This includes, single transactions, bundled transactions and promotion transactions.

Promotion and bundled transactions will have to only have one of their approving transactions be updated, since it's important for them to be put on top of specific transactions as well.

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
