### ISSUE TITLE
IOTA installation problem in centOS 6

### ISSUE THREAD

**Issue by neethu567** [iotaledger/trinity-wallet#906]
I am using centOS6 x86_64-bit,in the installation process of  IOTA Trinity Wallet,
after completing the first 3 installation steps met with the following error.
1.Prerequisites
Node.js (8+) 
Yarn 
2.# git clone https://github.com/iotaledger/trinity-wallet.git   (Runs correctly)
3.#cd trinity-wallet  (Runs correctly)
4.#yarn && yarn deps:shared
yarn install v1.12.3
[1/4] Resolving packages...
[2/4] Fetching packages...
[######################################################################################################################################################------] 765/795P[############################################################################################################################################################] 794/795

(after this nothing is coming .if we press enter it is asking password , hit enter again asking  password, again  hit enter  and end up with following error ,i dont know what is the password )

Password: 
Password: 
error Couldn't find match for "9c009d73d44caebaf2da1cc991f0113989a83886" in "refs/heads/master,refs/tags/v0.1.1,refs/tags/v0.1.2,refs/tags/v0.1.3,refs/tags/v0.1.5,refs/tags/v0.1.6,refs/tags/v0.1.7,refs/tags/v0.2.0,refs/tags/v0.3.0" for "https://git@github.com/GoogleChrome/proxy-polyfill".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by rajivshah3** [comment]
Hi,
Just to clarify, are you trying to run the development version of Trinity or the production version?

**Comment by neethu567** [comment]
development version

**Comment by neethu567** [comment]
https://github.com/iotaledger/trinity-wallet

**Comment by rajivshah3** [comment]
@neethu567 please try some of these solutions: https://github.com/yarnpkg/yarn/issues/4468. This is likely not an issue with Trinity

**Comment by neethu567** [comment]
Thankyou
