### ISSUE TITLE
PoW is set to remote but can't turn on Auto-promotion

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#907]
### Bug description
Auto promotion cannot be turned on because the wallet thinks the connected node does not support remote proof of work, however the wallet is set to remote proof of work and successful using it to send transactions.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Samsumg
- Model: GalaxyS8+
- OS version: 8.0.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.6.0 (36)

### Steps To Reproduce
1. Connect to node with no remote PoW capabilities
2. Turn Remote Proof of Work on
3. See that Remote Proof of Work works when sending transactions
4. Find you cannot turn on auto-promotion because the selected node does not support remote Proof of Work.

### Expected behaviour
- Auto promotion should successful be enabled when the wallet previously told the user that the connected node allows remote Proof of Work.

### Actual behaviour
- Auto promotion is not able to be turned on

### Errors
https://i.imgur.com/8SmfMju.png
https://i.imgur.com/5S4Bn5q.png

**Comment by rajivshah3** [comment]
Hi @SleepingFox88 , does this occur on multiple nodes or only one node?

**Comment by sloganking** [comment]
@rajivshah3 having difficulty replicating the issue on different nodes but am unaware what the original one was.

Will update you if I come across the issue again or find the original node I had the issue with.

Edit: 

I can say that when already having PoW set to remote, and connecting to a new node that does not have Remote PoW enables, Trinity successfully turned off remote PoW in settings. 

Edit2:

Indicating the issue might only be with certain nodes

**Comment by cvarley100** [comment]
@SleepingFox88 This could be related to the changes in 1.6.0 for specifying attachToTangle support. In which case https://github.com/iotaledger/trinity-wallet/pull/913 would have fixed it.

**Comment by laumair** [comment]
@SleepingFox88 Are you still facing this issue on the latest alpha build?

**Comment by sloganking** [comment]
I have been unable to reproduce the issue so far on both v0.6.0 (36) as well as the latest alpha build.

**Comment by rajivshah3** [comment]
@laumair @SleepingFox88 can this be closed?

**Comment by sloganking** [comment]
I have not been able to reproduce the issue so I will close the issue now. If it ever happens again it can be re-opened.
