### ISSUE TITLE
Told to change node but logs in anyway

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#908]
### Bug description
When logging in, wallet gives error and tells user to connect to new node. upon ignoring the message and waiting however, the wallet logs in successfully.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Samsung
- Model: GalaxyS8+
- OS version: Android 8.0.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.6.0 (36)

### Steps To Reproduce
1. Enter password and start logging in
2. wait till error message saying "error fetching account information, try again with a different node"
3. wait a little longer and find the wallet logs in successfuly

### Expected behavior
- Wallet should have failed to log in after error, or not told the user the login attempt failed.

### Actual behavior
- wallet logs in after it said login had failed.

### Errors
https://i.imgur.com/pVFczoc.png

**Comment by rajivshah3** [comment]
This isn't supposed to be an error; it's just providing information. We should change the color accordingly though, since red is only used for errors.

**Comment by sloganking** [comment]
Great. Maybe modify the string too, since it's still possible that the wallet might successfully log in?
