### ISSUE TITLE
Text is not fully visible at Snapshot Transition

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#910]
### Bug description
The "Attaching address" text during the snapshot transition is not fully visible above the progress bar.

### Environment Specs
iPhone 8 iOS 11.3.1
Trinity mobile 0.6.0 (36)

### Expected behaviour
Text should be fully visible.

### Actual behaviour
Half of the text above the progress bar is not visible.
![img_3589](https://user-images.githubusercontent.com/21984138/51056007-ebd5e800-15e1-11e9-85d4-20599dc7a089.PNG)

**Comment by rajivshah3** [comment]
Can also reproduce on iPhone 6S. This was probably introduced by the update to RN 0.57
