### ISSUE TITLE
empty password warning is sometimes too near to status bar

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#911]
### Bug description
The empty password and unrecognized password warnings are sometimes nearer to the status bar as normal.

### Environment Specs
iPhone 8 iOS 11.3.1 and iPhone 5S iOS 12.0.1
Trinity mobile 0.6.0 (36) and (37)

### Steps To Reproduce
completely close Trinity App
next steps are visible in the video

### Expected behaviour
warnings should always have the same size and distance to the status bar

### Actual behaviour
after completely closing the app those warnings are nearer to the the status bar

video of this bug: https://www.youtube.com/watch?v=nx6SJkKdbQk

**Comment by rajivshah3** [comment]
Interesting 🤔 does this occur on v0.5.1 as well?

**Comment by KiwiCat123** [comment]
> Interesting 🤔 does this occur on v0.5.1 as well?

No, only happens on the lastest alpha.

**Comment by cvarley100** [comment]
I can't seem to reproduce this one @KiwiCat123

**Comment by KiwiCat123** [comment]
@cvarley100 I tested it again on my iPhone 8 and iPhone 5S with iOS 12.0.1 and this bug still exists in the newest version (37).
This bug only occurs after you reopen the app after you closed it completely in the app switcher.

**Comment by rajivshah3** [comment]
Hmm, maybe this is related to https://github.com/testshallpass/react-native-dropdownalert/issues/168?
