### ISSUE TITLE
UI not reset when cancel sending

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#912]
### Bug description
Upon swiping to send a transaction and entering the confirm or cancel screen, If the user hits the back button native to the android OS. The confirmation screen is exited but the swipe option for send is still on the right side of the screen.

### Environment Specs

- Manufacturer: Samsung
- Model: GalaxyS8+
- OS version: Android 8.0.0

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: 0.6.0 (36)

### Steps To Reproduce
1. swipe to send
2. hit android back button
3. see swipe option is still on the right instead of reset to the left

### Expected behaviour
Swipe option should be reset to the left upon hitting android's back button.

### Actual behaviour
Swipe option stays to the right

### Errors
https://i.imgur.com/szffG4Y.png

**Comment by cvarley100** [comment]
Fixed in https://github.com/iotaledger/trinity-wallet/pull/929
