### ISSUE TITLE
Trinity not login

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#950]
### Bug description
Trinity not login. Stuck on black screen before password request.

### Environment Specs

- Manufacturer: Samsung
- Model: GalaxyS8+
- OS version: Android 8.0.0

- Trinity version: 0.6.0 (38)

### Steps To Reproduce

(Unknown if cause)
1. Send transaction
2. transaction sending completed
3. get biometric request on send page for unknown reason
4. exit app while request was open

(Specific to this issue)
5. return to app and find it won't login, (also has blue at top of screen)
6. exit and return to app but find blue top is not black but app still won't login

### Expected behavior
Trinity should ask for password after opening the app

### Actual behavior
Trinity never asked user to input password.

### Errors

https://i.imgur.com/Qlzglbi.png
https://i.imgur.com/8ZtcVRm.png
https://i.imgur.com/oCWWveZ.png

**Comment by laumair** [comment]
@SleepingFox88 When you force exit the application, does it not open the login screen? 

/cc @cvarley100

**Comment by sloganking** [comment]
Force killing the application does fix the issue.

However simply exiting and re-opening the application does not.

**Comment by cvarley100** [comment]
Has since been fixed. See https://github.com/iotaledger/trinity-wallet/pull/959
