### ISSUE TITLE
Warn user if can't connect to enough nodes to form quorum.

### ISSUE THREAD

**Issue by sloganking** [iotaledger/trinity-wallet#958]
### Description
In the unlikely event that Trinity cannot connect to enough nodes to form a quorum, Trinity will warn and protect the user by not allowing the sending of transactions.

### Motivation
- Sending and receiving transactions without node quorum is unsafe.

### Requirements
- Warn the user if a quorum of specified number of nodes cannot be formed.
- Stop allowing sending and receiving of transactions until quorum of acceptable nodes is formed again.

### Open Questions (optional)
- Related issue: #894

### Am I planning to do it myself with a PR?
No.

**Comment by cvarley100** [comment]
@SleepingFox88 Currently if quorum fails, send would be cancelled. Do you mean something other than that?

**Comment by cvarley100** [comment]
So we have updated the error handling for failed quorum. See https://github.com/iotaledger/trinity-wallet/blob/1d7ba3a2fcb25dab32ab7a06c94404a252cdda83/src/shared/libs/errors.js#L32

We already block send/address gen if quorum fails.
