### ISSUE TITLE
[Linux Mint][Desktop] menu icon badly displayed

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#973]
### Bug description
When installing Trinity desktop under Linux Mint, the app is added in the "Office" section and the icon isn't displayed.
It would be better to create the menu entry in a more relevant section (e.g. Other or Accessories).

![image](https://user-images.githubusercontent.com/9414596/51523845-d310d200-1e2c-11e9-8e7f-fa9a4c397175.png)

### Environment Specs
- OS version: Linux Mint 19.1
- Trinity version: 0.4.6

### Steps To Reproduce
1. install desktop version by running AppImage file

### Am I planning to do it myself with a PR?
No

**Comment by ghost** [comment]
Plus: when the application is open, the icon isn't displayed in the menu bar

![capture du 2019-01-23 11-04-44](https://user-images.githubusercontent.com/9414596/51599060-13d91b80-1eff-11e9-9598-e7bdb7db6f93.png)

**Comment by rihardsgravis** [comment]
Duplicate issue #821
