### ISSUE TITLE
[Google authenticator] typo when adding 2FA

### ISSUE THREAD

**Issue by ghost** [iotaledger/trinity-wallet#975]
### Bug description
When activating 2FA on Google authenticator, the code is named ":Trinity desktop wallet". I guess the colon is a misstype. 

### Environment Specs
- OS version: Linux Mint 19.1
- Trinity version: desktop 0.4.6
- Google Authenticator 5.00 for Android

### Steps To Reproduce
1. activate 2FA with Google authenticator

### Am I planning to do it myself with a PR?
No

**Comment by rajivshah3** [comment]
![img_f27ae53ae40d-1](https://user-images.githubusercontent.com/19519564/51579339-9fff2a80-1e8e-11e9-9475-c04987ee6e65.jpeg)
![img_3ea76536cf50-1](https://user-images.githubusercontent.com/19519564/51579347-a4c3de80-1e8e-11e9-9023-fc6065d301a0.jpeg) (code redacted)

I'm unable to reproduce this with a QR code generated by Trinity Desktop v0.4.6 (macOS Mojave), scanned with Authy or Google Authenticator on iOS. Which OS and Trinity Desktop version are you running?

**Comment by ghost** [comment]
Google Authenticator 5.00 for Android. 
Trinity Desktop 0.4.6 on Linux Mint 19.1 (sorry i edited the first post)

![screenshot_20190123-071737](https://user-images.githubusercontent.com/9414596/51587058-c4372780-1edf-11e9-9949-72ccd1c68e8f.png)
