### ISSUE TITLE
empty password warning is sometimes too near to status bar

### ISSUE THREAD

**Issue by KiwiCat123** [iotaledger/trinity-wallet#984]
reopened issue #911 

### Bug description
The empty password and unrecognized password warnings are sometimes nearer to the status bar as normal.

### Environment Specs
iPhone 8 iOS 11.3.1 and iPhone 5S iOS 12.0.1
Trinity mobile 0.6.0 (39)

### Steps To Reproduce
completely close Trinity App
next steps are visible in the video

### Expected behaviour
warnings should always have the same size and distance to the status bar

### Actual behaviour
after completely closing the app those warnings are nearer to the the status bar

video of this bug: https://youtu.be/OQ_pH1IJ3ro

**Comment by rajivshah3** [comment]
@KiwiCat123 I'll close this one and reopen the old one so that the conversation isn't fragmented

**Comment by rajivshah3** [comment]
Duplicate of #911
