### ISSUE TITLE
Can't create a new account

### ISSUE THREAD

**Issue by jojoCoWorker** [iotaledger/trinity-wallet#987]
### Bug description
Can't create a new account

### Environment Specs
Android 6.0.1 on a Nexus 5

- Trinity version: v. 0.6.0(39)

### Steps To Reproduce
1. Add new account (in my case from a wallet with already several accounts created before)
2. Create a new seed (OR Use existing seed, the same happens...)
3. Back up / Import your seed
4. Write an account name
5. clic on "Done" flag

### Expected behaviour
create a new account

### Actual behaviour
application get stuck/frozen
If I clic again on "Done", I have a red warning saying "Trinity is performing another function..."

### Errors
[![Image](https://i.goopics.net/rbbbv.png)](https://goopics.net/i/rbbbv)
[![Image](https://i.goopics.net/jXXXy.png)](https://goopics.net/i/jXXXy)

**Comment by laumair** [comment]
@jojoCoWorker Does it always display this error alert when you try adding a new account? What happens if you wait a few seconds and then press `Done` ?

**Comment by cvarley100** [comment]
This is likely due to the timeout issue surrounding quorum. Wait times should be reduced now: https://github.com/iotaledger/trinity-wallet/blob/mobile-next/src/mobile/patches/react-native%2B0.57.5.patch
