### ISSUE TITLE
Add a dapp browser with secure iota.js integration

### ISSUE THREAD

**Issue by tanevanwifferen** [iotaledger/trinity-wallet#991]
### Description
A web browser window within trinity in which websites can be visited that require iota.js functionality.

### Motivation
In a fragmented world, everyone has his/her own implementation of the iota.js library on his/her website. Problems that exist are:

- a user must trust every website with their seed to login OR must have a different seed for each dapp
- even if trust is established, every website could be a potential attack vector to snoop private data

in the ethereum world, tools like metamask solve this problem by having a piece of trusted code (browser plugin, wrapper app around browser on mobile) inject the blockchain api into a website, and asks the user for confirmation for every outgoing transaction.

### Requirements
A web browser window in trinity that provides a secure iota object in websites, and protects the users' keys from malicious code.

### Am I planning to do it myself with a PR?
No, my knowledge would be insufficient

**Comment by rajivshah3** [comment]
This is a good idea. We would have to take special care to ensure that the website cannot inject malicious code into Trinity though

**Comment by cvarley100** [comment]
We will reconsider feature and enhancement suggestions for the next version of the wallet.
